/**
 * Package B, Gate 11 — bounded, read-only editorial/campaign opportunity source seam.
 *
 * Reconciliation finding: no structured editorial/campaign metadata source exists today.
 * app/lib/magazine/** models published magazine ISSUES (month/cover/PDF/flipbook) — it has no
 * per-article theme/category/audience/sponsorship-eligibility metadata that a match engine could
 * use, and adapting it would misuse issue-level data for article-level matching. Building a full
 * editorial calendar CMS inside Business Concierge is explicitly out of scope for Package B.
 *
 * This file is the smallest workable seam: a typed interface plus a small, code-reviewed starter
 * registry of category/theme-based opportunity candidates (never customer-specific names — see
 * doctrine below). If a real structured editorial/campaign data source is built later (by the
 * magazine team or a future package), only `listActiveEditorialOpportunitySources()` needs to
 * change — the match engine and everything downstream is unaffected.
 */
import type { BroadBusinessType } from "@/app/lib/business/types";
import type { CreativeFamily } from "@/app/lib/business/creativeStudio/doctrine/types";
import type { OpportunitySourceType, OpportunityType } from "./types";

export interface EditorialOpportunitySource {
  key: string;
  titleEs: string;
  titleEn: string;
  themeEs: string;
  themeEn: string;
  sourceType: OpportunitySourceType;
  opportunityType: OpportunityType;
  creativeFamily: CreativeFamily;
  /** Category-based matching only — never a specific business/customer. */
  suggestedBusinessCategories: readonly BroadBusinessType[];
  /** Optional service-area city hints. Empty means "no geography constraint". */
  suggestedCities: readonly string[];
  /** ISO date window this opportunity is active for. Null = evergreen/no fixed window. */
  activeFrom: string | null;
  activeUntil: string | null;
  /** True only for content families where a paid sponsorship relationship is a plausible outcome. */
  sponsorshipEligible: boolean;
}

/**
 * Package B, Gate 12 — canonical starter set. Category/theme based, never a real customer name.
 * Reviewed and extended in code, same convention as stewardship/recommendationRegistry.ts
 * ("hand-authored, code-resident, never generated by AI, never inferred at runtime").
 */
const EDITORIAL_OPPORTUNITY_REGISTRY: readonly EditorialOpportunitySource[] = [
  {
    key: "food_recipe_feature",
    titleEs: "Reportaje cultural de comida / receta",
    titleEn: "Cultural food / recipe feature",
    themeEs: "Comida y cultura local",
    themeEn: "Local food and culture",
    sourceType: "editorial_registry",
    opportunityType: "editorial_match",
    creativeFamily: "FOOD_RECIPES",
    suggestedBusinessCategories: ["food_hospitality", "agriculture_food_production", "retail_ecommerce"],
    suggestedCities: [],
    activeFrom: null,
    activeUntil: null,
    sponsorshipEligible: true,
  },
  {
    key: "health_wellness_feature",
    titleEs: "Reportaje de salud y bienestar",
    titleEn: "Health and wellness feature",
    themeEs: "Salud y bienestar comunitario",
    themeEn: "Community health and wellness",
    sourceType: "editorial_registry",
    opportunityType: "sponsored_feature",
    creativeFamily: "HEALTH_WELLNESS",
    suggestedBusinessCategories: ["health_beauty_wellness"],
    suggestedCities: [],
    activeFrom: null,
    activeUntil: null,
    sponsorshipEligible: true,
  },
  {
    key: "homebuyer_checklist_feature",
    titleEs: "Lista de verificación para comprar casa",
    titleEn: "Homebuyer checklist feature",
    themeEs: "Bienes raíces y vivienda",
    themeEn: "Real estate and housing",
    sourceType: "editorial_registry",
    opportunityType: "sponsored_feature",
    creativeFamily: "RESOURCES_PUBLIC_INFORMATION",
    suggestedBusinessCategories: ["real_estate_property_services", "finance_insurance"],
    suggestedCities: [],
    activeFrom: null,
    activeUntil: null,
    sponsorshipEligible: true,
  },
  {
    key: "emergency_car_kit_feature",
    titleEs: "Reportaje de kit de emergencia para el auto",
    titleEn: "Emergency car-kit feature",
    themeEs: "Seguridad automotriz",
    themeEn: "Automotive safety",
    sourceType: "editorial_registry",
    opportunityType: "sponsored_feature",
    creativeFamily: "RESOURCES_PUBLIC_INFORMATION",
    suggestedBusinessCategories: ["automotive_transportation"],
    suggestedCities: [],
    activeFrom: null,
    activeUntil: null,
    sponsorshipEligible: true,
  },
  {
    key: "wellness_challenge_campaign",
    titleEs: "Reto de bienestar de temporada",
    titleEn: "Seasonal wellness challenge",
    themeEs: "Bienestar y buenos hábitos",
    themeEn: "Wellness and healthy habits",
    sourceType: "seasonal_registry",
    opportunityType: "seasonal_campaign",
    creativeFamily: "HEALTH_WELLNESS",
    suggestedBusinessCategories: ["health_beauty_wellness"],
    suggestedCities: [],
    activeFrom: null,
    activeUntil: null,
    sponsorshipEligible: true,
  },
  {
    key: "know_your_rights_feature",
    titleEs: "Reportaje de conoce tus derechos",
    titleEn: "Know-your-rights feature",
    themeEs: "Información legal pública",
    themeEn: "Public legal information",
    sourceType: "editorial_registry",
    opportunityType: "sponsored_feature",
    creativeFamily: "RESOURCES_PUBLIC_INFORMATION",
    suggestedBusinessCategories: ["professional_services"],
    suggestedCities: [],
    activeFrom: null,
    activeUntil: null,
    sponsorshipEligible: true,
  },
  {
    key: "tax_season_feature",
    titleEs: "Reportaje de temporada de impuestos",
    titleEn: "Tax-season feature",
    themeEs: "Finanzas personales y de negocio",
    themeEn: "Personal and business finance",
    sourceType: "seasonal_registry",
    opportunityType: "seasonal_campaign",
    creativeFamily: "FINANCE_BUSINESS",
    suggestedBusinessCategories: ["professional_services", "finance_insurance"],
    suggestedCities: [],
    activeFrom: null,
    activeUntil: null,
    sponsorshipEligible: true,
  },
  {
    key: "youth_opportunity_feature",
    titleEs: "Reportaje de oportunidades juveniles",
    titleEn: "Youth opportunity feature",
    themeEs: "Juventud y comunidad",
    themeEn: "Youth and community",
    sourceType: "editorial_registry",
    opportunityType: "category_feature",
    creativeFamily: "FAMILY_YOUTH_COMMUNITY",
    suggestedBusinessCategories: ["education_training_coaching", "nonprofit_faith_community"],
    suggestedCities: [],
    activeFrom: null,
    activeUntil: null,
    sponsorshipEligible: true,
  },
];

/**
 * Read-only accessor. Filters out sources whose active window has already closed — an evergreen
 * source (activeFrom/activeUntil both null) is always considered active.
 */
export function listActiveEditorialOpportunitySources(nowIso: string = new Date().toISOString()): readonly EditorialOpportunitySource[] {
  const now = new Date(nowIso).getTime();
  return EDITORIAL_OPPORTUNITY_REGISTRY.filter((source) => {
    if (source.activeFrom && new Date(source.activeFrom).getTime() > now) return false;
    if (source.activeUntil && new Date(source.activeUntil).getTime() < now) return false;
    return true;
  });
}
