/** @deprecated Prefer `@/app/lib/language` — re-exports for LANG-G1 call sites. */
export type LeonixSiteLang = import("./language").SupportedLang;

export {
  ACTIVE_ADDITIONAL_LANGUAGES,
  ADDITIONAL_LANGUAGES,
  ALL_SUPPORTED_LANGS,
  DEFAULT_LANG,
  FUTURE_LANGUAGES,
  HELD_RTL_LANGUAGES,
  HELD_RTL_LANGUAGE_CODES,
  HIDDEN_FUTURE_LANGUAGE_CODES,
  LANGUAGE_ENGLISH_NAMES,
  LANGUAGE_LABELS as LEONIX_LANG_LABELS,
  LANGUAGE_REGISTRY,
  LANGUAGE_SHORT as LEONIX_LANG_SHORT,
  MAGAZINE_HERO_CTAS as LEONIX_MAGAZINE_HERO_CTAS,
  OFFICIAL_LAUNCH_LANGUAGES,
  OFFICIAL_LAUNCH_LANGUAGE_FALLBACK_NOTE,
  PLANNED_NON_RTL_LANGUAGES,
  PLANNED_NON_RTL_LANGUAGE_CODES,
  PRIMARY_LANGUAGES,
  PROVIDER_LANGUAGE_CODES,
  getLanguageDefinition,
  getLanguageDirection,
  getLanguageEnglishName,
  getLanguageLabel,
  getLanguageNativeLabel,
  getOfficialLaunchLanguageFallbackNote,
  getProviderLanguageCode,
  heldLanguageNote,
  isActiveLanguage,
  isAdditionalLanguageActive,
  isHeldLanguage,
  isHeldRtlLang,
  isHiddenFutureLang,
  isLanguageCode,
  isOfficialLaunchLang,
  isPlannedLanguage,
  isSupportedLang,
  languageAriaLabel as leonixLangAria,
  navCopyLang as leonixNavCopyLang,
  normalizeLang as resolveLeonixSiteLang,
  normalizeSelectableLang,
  normalizePublicLang,
  resolvePublicLangFromSearchParams,
  ACTIVE_PUBLIC_LANGS,
  withLang,
  withPublicLangAndTracking,
  type PublicTrackingParams,
  replaceLangInHref as withLeonixLang,
  staticPageCopyLang,
  type FutureLanguage,
  type FutureLanguageCode,
  type HeldRtlLang,
  type HeldRtlLanguageCode,
  type HeldRtlLanguageEntry,
  type LanguageCode,
  type LanguageDefinition,
  type LanguageDirection,
  type LanguageStatus,
  type PlannedNonRtlLanguageCode,
  type SupportedLang,
} from "./language";

export {
  LEONIX_LANGUAGES,
  LEONIX_LANGUAGE_METADATA,
  LEONIX_ACTIVE_LANGUAGE_METADATA,
  LEONIX_FUTURE_LANGUAGE_METADATA,
  LEONIX_HELD_LANGUAGE_METADATA,
  getLanguageMeta,
  getActiveLanguageMeta,
  mapRouteLangToGoogleTarget,
  mapLangToGoogleTranslateTarget,
  assertLeonixLanguageMetadataInvariants,
  type LanguageMeta,
  type LeonixLanguageStatus,
} from "./leonix/languageMetadata";

import { ADDITIONAL_LANGUAGES, PRIMARY_LANGUAGES, type SupportedLang } from "./language";

/** @deprecated Use PRIMARY_LANGUAGES + ADDITIONAL_LANGUAGES */
export const LEONIX_LANG_CODES: SupportedLang[] = [...PRIMARY_LANGUAGES, ...ADDITIONAL_LANGUAGES];
