/**
 * Global country list (Gate BCO-3R-B). Complete ISO 3166-1 alpha-2 list (249 countries and
 * dependent territories) with ES/EN display names — not a curated subset. `OTHER` is reserved for
 * territories with no stable ISO code (disputed/unrecognized territories) or a genuine exception,
 * not a stand-in for missing data. Country is deliberately not a DB CHECK constraint (would
 * require a migration every time ISO adds/renames an entry) — validated at the application layer
 * via this list instead. Array order is insertion order, not alphabetical — UI consumers
 * (SearchableSelect) sort by the active language's label at render time via `localeCompare`, so
 * the list reads alphabetically in whichever language is active without maintaining two orderings.
 */
export type CountryOption = { code: string; es: string; en: string };

export const COUNTRIES: readonly CountryOption[] = [
  { code: "AD", es: "Andorra", en: "Andorra" },
  { code: "AE", es: "Emiratos Árabes Unidos", en: "United Arab Emirates" },
  { code: "AF", es: "Afganistán", en: "Afghanistan" },
  { code: "AG", es: "Antigua y Barbuda", en: "Antigua and Barbuda" },
  { code: "AI", es: "Anguila", en: "Anguilla" },
  { code: "AL", es: "Albania", en: "Albania" },
  { code: "AM", es: "Armenia", en: "Armenia" },
  { code: "AO", es: "Angola", en: "Angola" },
  { code: "AQ", es: "Antártida", en: "Antarctica" },
  { code: "AR", es: "Argentina", en: "Argentina" },
  { code: "AS", es: "Samoa Americana", en: "American Samoa" },
  { code: "AT", es: "Austria", en: "Austria" },
  { code: "AU", es: "Australia", en: "Australia" },
  { code: "AW", es: "Aruba", en: "Aruba" },
  { code: "AX", es: "Islas Åland", en: "Åland Islands" },
  { code: "AZ", es: "Azerbaiyán", en: "Azerbaijan" },
  { code: "BA", es: "Bosnia y Herzegovina", en: "Bosnia and Herzegovina" },
  { code: "BB", es: "Barbados", en: "Barbados" },
  { code: "BD", es: "Bangladés", en: "Bangladesh" },
  { code: "BE", es: "Bélgica", en: "Belgium" },
  { code: "BF", es: "Burkina Faso", en: "Burkina Faso" },
  { code: "BG", es: "Bulgaria", en: "Bulgaria" },
  { code: "BH", es: "Baréin", en: "Bahrain" },
  { code: "BI", es: "Burundi", en: "Burundi" },
  { code: "BJ", es: "Benín", en: "Benin" },
  { code: "BL", es: "San Bartolomé", en: "Saint Barthélemy" },
  { code: "BM", es: "Bermudas", en: "Bermuda" },
  { code: "BN", es: "Brunéi", en: "Brunei" },
  { code: "BO", es: "Bolivia", en: "Bolivia" },
  { code: "BQ", es: "Bonaire, San Eustaquio y Saba", en: "Bonaire, Sint Eustatius and Saba" },
  { code: "BR", es: "Brasil", en: "Brazil" },
  { code: "BS", es: "Bahamas", en: "Bahamas" },
  { code: "BT", es: "Bután", en: "Bhutan" },
  { code: "BV", es: "Isla Bouvet", en: "Bouvet Island" },
  { code: "BW", es: "Botsuana", en: "Botswana" },
  { code: "BY", es: "Bielorrusia", en: "Belarus" },
  { code: "BZ", es: "Belice", en: "Belize" },
  { code: "CA", es: "Canadá", en: "Canada" },
  { code: "CC", es: "Islas Cocos (Keeling)", en: "Cocos (Keeling) Islands" },
  { code: "CD", es: "República Democrática del Congo", en: "DR Congo" },
  { code: "CF", es: "República Centroafricana", en: "Central African Republic" },
  { code: "CG", es: "Congo", en: "Congo" },
  { code: "CH", es: "Suiza", en: "Switzerland" },
  { code: "CI", es: "Costa de Marfil", en: "Côte d'Ivoire" },
  { code: "CK", es: "Islas Cook", en: "Cook Islands" },
  { code: "CL", es: "Chile", en: "Chile" },
  { code: "CM", es: "Camerún", en: "Cameroon" },
  { code: "CN", es: "China", en: "China" },
  { code: "CO", es: "Colombia", en: "Colombia" },
  { code: "CR", es: "Costa Rica", en: "Costa Rica" },
  { code: "CU", es: "Cuba", en: "Cuba" },
  { code: "CV", es: "Cabo Verde", en: "Cape Verde" },
  { code: "CW", es: "Curazao", en: "Curaçao" },
  { code: "CX", es: "Isla de Navidad", en: "Christmas Island" },
  { code: "CY", es: "Chipre", en: "Cyprus" },
  { code: "CZ", es: "Chequia", en: "Czechia" },
  { code: "DE", es: "Alemania", en: "Germany" },
  { code: "DJ", es: "Yibuti", en: "Djibouti" },
  { code: "DK", es: "Dinamarca", en: "Denmark" },
  { code: "DM", es: "Dominica", en: "Dominica" },
  { code: "DO", es: "República Dominicana", en: "Dominican Republic" },
  { code: "DZ", es: "Argelia", en: "Algeria" },
  { code: "EC", es: "Ecuador", en: "Ecuador" },
  { code: "EE", es: "Estonia", en: "Estonia" },
  { code: "EG", es: "Egipto", en: "Egypt" },
  { code: "EH", es: "Sahara Occidental", en: "Western Sahara" },
  { code: "ER", es: "Eritrea", en: "Eritrea" },
  { code: "ES", es: "España", en: "Spain" },
  { code: "ET", es: "Etiopía", en: "Ethiopia" },
  { code: "FI", es: "Finlandia", en: "Finland" },
  { code: "FJ", es: "Fiyi", en: "Fiji" },
  { code: "FK", es: "Islas Malvinas", en: "Falkland Islands" },
  { code: "FM", es: "Micronesia", en: "Micronesia" },
  { code: "FO", es: "Islas Feroe", en: "Faroe Islands" },
  { code: "FR", es: "Francia", en: "France" },
  { code: "GA", es: "Gabón", en: "Gabon" },
  { code: "GB", es: "Reino Unido", en: "United Kingdom" },
  { code: "GD", es: "Granada", en: "Grenada" },
  { code: "GE", es: "Georgia", en: "Georgia" },
  { code: "GF", es: "Guayana Francesa", en: "French Guiana" },
  { code: "GG", es: "Guernsey", en: "Guernsey" },
  { code: "GH", es: "Ghana", en: "Ghana" },
  { code: "GI", es: "Gibraltar", en: "Gibraltar" },
  { code: "GL", es: "Groenlandia", en: "Greenland" },
  { code: "GM", es: "Gambia", en: "Gambia" },
  { code: "GN", es: "Guinea", en: "Guinea" },
  { code: "GP", es: "Guadalupe", en: "Guadeloupe" },
  { code: "GQ", es: "Guinea Ecuatorial", en: "Equatorial Guinea" },
  { code: "GR", es: "Grecia", en: "Greece" },
  { code: "GS", es: "Islas Georgias del Sur y Sandwich del Sur", en: "South Georgia and the South Sandwich Islands" },
  { code: "GT", es: "Guatemala", en: "Guatemala" },
  { code: "GU", es: "Guam", en: "Guam" },
  { code: "GW", es: "Guinea-Bisáu", en: "Guinea-Bissau" },
  { code: "GY", es: "Guyana", en: "Guyana" },
  { code: "HK", es: "Hong Kong", en: "Hong Kong" },
  { code: "HM", es: "Islas Heard y McDonald", en: "Heard Island and McDonald Islands" },
  { code: "HN", es: "Honduras", en: "Honduras" },
  { code: "HR", es: "Croacia", en: "Croatia" },
  { code: "HT", es: "Haití", en: "Haiti" },
  { code: "HU", es: "Hungría", en: "Hungary" },
  { code: "ID", es: "Indonesia", en: "Indonesia" },
  { code: "IE", es: "Irlanda", en: "Ireland" },
  { code: "IL", es: "Israel", en: "Israel" },
  { code: "IM", es: "Isla de Man", en: "Isle of Man" },
  { code: "IN", es: "India", en: "India" },
  { code: "IO", es: "Territorio Británico del Océano Índico", en: "British Indian Ocean Territory" },
  { code: "IQ", es: "Irak", en: "Iraq" },
  { code: "IR", es: "Irán", en: "Iran" },
  { code: "IS", es: "Islandia", en: "Iceland" },
  { code: "IT", es: "Italia", en: "Italy" },
  { code: "JE", es: "Jersey", en: "Jersey" },
  { code: "JM", es: "Jamaica", en: "Jamaica" },
  { code: "JO", es: "Jordania", en: "Jordan" },
  { code: "JP", es: "Japón", en: "Japan" },
  { code: "KE", es: "Kenia", en: "Kenya" },
  { code: "KG", es: "Kirguistán", en: "Kyrgyzstan" },
  { code: "KH", es: "Camboya", en: "Cambodia" },
  { code: "KI", es: "Kiribati", en: "Kiribati" },
  { code: "KM", es: "Comoras", en: "Comoros" },
  { code: "KN", es: "San Cristóbal y Nieves", en: "Saint Kitts and Nevis" },
  { code: "KP", es: "Corea del Norte", en: "North Korea" },
  { code: "KR", es: "Corea del Sur", en: "South Korea" },
  { code: "KW", es: "Kuwait", en: "Kuwait" },
  { code: "KY", es: "Islas Caimán", en: "Cayman Islands" },
  { code: "KZ", es: "Kazajistán", en: "Kazakhstan" },
  { code: "LA", es: "Laos", en: "Laos" },
  { code: "LB", es: "Líbano", en: "Lebanon" },
  { code: "LC", es: "Santa Lucía", en: "Saint Lucia" },
  { code: "LI", es: "Liechtenstein", en: "Liechtenstein" },
  { code: "LK", es: "Sri Lanka", en: "Sri Lanka" },
  { code: "LR", es: "Liberia", en: "Liberia" },
  { code: "LS", es: "Lesoto", en: "Lesotho" },
  { code: "LT", es: "Lituania", en: "Lithuania" },
  { code: "LU", es: "Luxemburgo", en: "Luxembourg" },
  { code: "LV", es: "Letonia", en: "Latvia" },
  { code: "LY", es: "Libia", en: "Libya" },
  { code: "MA", es: "Marruecos", en: "Morocco" },
  { code: "MC", es: "Mónaco", en: "Monaco" },
  { code: "MD", es: "Moldavia", en: "Moldova" },
  { code: "ME", es: "Montenegro", en: "Montenegro" },
  { code: "MF", es: "San Martín (Francia)", en: "Saint Martin" },
  { code: "MG", es: "Madagascar", en: "Madagascar" },
  { code: "MH", es: "Islas Marshall", en: "Marshall Islands" },
  { code: "MK", es: "Macedonia del Norte", en: "North Macedonia" },
  { code: "ML", es: "Malí", en: "Mali" },
  { code: "MM", es: "Myanmar", en: "Myanmar" },
  { code: "MN", es: "Mongolia", en: "Mongolia" },
  { code: "MO", es: "Macao", en: "Macao" },
  { code: "MP", es: "Islas Marianas del Norte", en: "Northern Mariana Islands" },
  { code: "MQ", es: "Martinica", en: "Martinique" },
  { code: "MR", es: "Mauritania", en: "Mauritania" },
  { code: "MS", es: "Montserrat", en: "Montserrat" },
  { code: "MT", es: "Malta", en: "Malta" },
  { code: "MU", es: "Mauricio", en: "Mauritius" },
  { code: "MV", es: "Maldivas", en: "Maldives" },
  { code: "MW", es: "Malaui", en: "Malawi" },
  { code: "MX", es: "México", en: "Mexico" },
  { code: "MY", es: "Malasia", en: "Malaysia" },
  { code: "MZ", es: "Mozambique", en: "Mozambique" },
  { code: "NA", es: "Namibia", en: "Namibia" },
  { code: "NC", es: "Nueva Caledonia", en: "New Caledonia" },
  { code: "NE", es: "Níger", en: "Niger" },
  { code: "NF", es: "Isla Norfolk", en: "Norfolk Island" },
  { code: "NG", es: "Nigeria", en: "Nigeria" },
  { code: "NI", es: "Nicaragua", en: "Nicaragua" },
  { code: "NL", es: "Países Bajos", en: "Netherlands" },
  { code: "NO", es: "Noruega", en: "Norway" },
  { code: "NP", es: "Nepal", en: "Nepal" },
  { code: "NR", es: "Nauru", en: "Nauru" },
  { code: "NU", es: "Niue", en: "Niue" },
  { code: "NZ", es: "Nueva Zelanda", en: "New Zealand" },
  { code: "OM", es: "Omán", en: "Oman" },
  { code: "PA", es: "Panamá", en: "Panama" },
  { code: "PE", es: "Perú", en: "Peru" },
  { code: "PF", es: "Polinesia Francesa", en: "French Polynesia" },
  { code: "PG", es: "Papúa Nueva Guinea", en: "Papua New Guinea" },
  { code: "PH", es: "Filipinas", en: "Philippines" },
  { code: "PK", es: "Pakistán", en: "Pakistan" },
  { code: "PL", es: "Polonia", en: "Poland" },
  { code: "PM", es: "San Pedro y Miquelón", en: "Saint Pierre and Miquelon" },
  { code: "PN", es: "Islas Pitcairn", en: "Pitcairn Islands" },
  { code: "PR", es: "Puerto Rico", en: "Puerto Rico" },
  { code: "PS", es: "Palestina", en: "Palestine" },
  { code: "PT", es: "Portugal", en: "Portugal" },
  { code: "PW", es: "Palaos", en: "Palau" },
  { code: "PY", es: "Paraguay", en: "Paraguay" },
  { code: "QA", es: "Catar", en: "Qatar" },
  { code: "RE", es: "Reunión", en: "Réunion" },
  { code: "RO", es: "Rumania", en: "Romania" },
  { code: "RS", es: "Serbia", en: "Serbia" },
  { code: "RU", es: "Rusia", en: "Russia" },
  { code: "RW", es: "Ruanda", en: "Rwanda" },
  { code: "SA", es: "Arabia Saudita", en: "Saudi Arabia" },
  { code: "SB", es: "Islas Salomón", en: "Solomon Islands" },
  { code: "SC", es: "Seychelles", en: "Seychelles" },
  { code: "SD", es: "Sudán", en: "Sudan" },
  { code: "SE", es: "Suecia", en: "Sweden" },
  { code: "SG", es: "Singapur", en: "Singapore" },
  { code: "SH", es: "Santa Elena, Ascensión y Tristán de Acuña", en: "Saint Helena, Ascension and Tristan da Cunha" },
  { code: "SI", es: "Eslovenia", en: "Slovenia" },
  { code: "SJ", es: "Svalbard y Jan Mayen", en: "Svalbard and Jan Mayen" },
  { code: "SK", es: "Eslovaquia", en: "Slovakia" },
  { code: "SL", es: "Sierra Leona", en: "Sierra Leone" },
  { code: "SM", es: "San Marino", en: "San Marino" },
  { code: "SN", es: "Senegal", en: "Senegal" },
  { code: "SO", es: "Somalia", en: "Somalia" },
  { code: "SR", es: "Surinam", en: "Suriname" },
  { code: "SS", es: "Sudán del Sur", en: "South Sudan" },
  { code: "ST", es: "Santo Tomé y Príncipe", en: "São Tomé and Príncipe" },
  { code: "SV", es: "El Salvador", en: "El Salvador" },
  { code: "SX", es: "Sint Maarten", en: "Sint Maarten" },
  { code: "SY", es: "Siria", en: "Syria" },
  { code: "SZ", es: "Esuatini", en: "Eswatini" },
  { code: "TC", es: "Islas Turcas y Caicos", en: "Turks and Caicos Islands" },
  { code: "TD", es: "Chad", en: "Chad" },
  { code: "TF", es: "Territorios Australes Franceses", en: "French Southern Territories" },
  { code: "TG", es: "Togo", en: "Togo" },
  { code: "TH", es: "Tailandia", en: "Thailand" },
  { code: "TJ", es: "Tayikistán", en: "Tajikistan" },
  { code: "TK", es: "Tokelau", en: "Tokelau" },
  { code: "TL", es: "Timor Oriental", en: "Timor-Leste" },
  { code: "TM", es: "Turkmenistán", en: "Turkmenistan" },
  { code: "TN", es: "Túnez", en: "Tunisia" },
  { code: "TO", es: "Tonga", en: "Tonga" },
  { code: "TR", es: "Turquía", en: "Turkey" },
  { code: "TT", es: "Trinidad y Tobago", en: "Trinidad and Tobago" },
  { code: "TV", es: "Tuvalu", en: "Tuvalu" },
  { code: "TW", es: "Taiwán", en: "Taiwan" },
  { code: "TZ", es: "Tanzania", en: "Tanzania" },
  { code: "UA", es: "Ucrania", en: "Ukraine" },
  { code: "UG", es: "Uganda", en: "Uganda" },
  { code: "UM", es: "Islas Ultramarinas Menores de EE. UU.", en: "United States Minor Outlying Islands" },
  { code: "US", es: "Estados Unidos", en: "United States" },
  { code: "UY", es: "Uruguay", en: "Uruguay" },
  { code: "UZ", es: "Uzbekistán", en: "Uzbekistan" },
  { code: "VA", es: "Ciudad del Vaticano", en: "Vatican City" },
  { code: "VC", es: "San Vicente y las Granadinas", en: "Saint Vincent and the Grenadines" },
  { code: "VE", es: "Venezuela", en: "Venezuela" },
  { code: "VG", es: "Islas Vírgenes Británicas", en: "British Virgin Islands" },
  { code: "VI", es: "Islas Vírgenes de EE. UU.", en: "United States Virgin Islands" },
  { code: "VN", es: "Vietnam", en: "Vietnam" },
  { code: "VU", es: "Vanuatu", en: "Vanuatu" },
  { code: "WF", es: "Wallis y Futuna", en: "Wallis and Futuna" },
  { code: "WS", es: "Samoa", en: "Samoa" },
  { code: "YE", es: "Yemen", en: "Yemen" },
  { code: "YT", es: "Mayotte", en: "Mayotte" },
  { code: "ZA", es: "Sudáfrica", en: "South Africa" },
  { code: "ZM", es: "Zambia", en: "Zambia" },
  { code: "ZW", es: "Zimbabue", en: "Zimbabwe" },
  { code: "OTHER", es: "Otro / territorio no listado", en: "Other / unlisted territory" },
] as const;

export const COUNTRY_CODES: readonly string[] = COUNTRIES.map((c) => c.code);

export function isValidCountryCode(code: string | null | undefined): boolean {
  if (!code) return false;
  return COUNTRY_CODES.includes(code);
}

export function countryLabel(code: string, lang: "es" | "en"): string {
  const found = COUNTRIES.find((c) => c.code === code);
  return found ? found[lang] : code;
}

/** Countries sorted by the active language's label — for display in SearchableSelect, never for storage. */
export function countriesSortedByLabel(lang: "es" | "en"): readonly CountryOption[] {
  const real = COUNTRIES.filter((c) => c.code !== "OTHER");
  const other = COUNTRIES.find((c) => c.code === "OTHER");
  const sorted = [...real].sort((a, b) => a[lang].localeCompare(b[lang], lang === "es" ? "es" : "en"));
  return other ? [...sorted, other] : sorted;
}
