import type { BrNegocioListing } from "./cards/listingTypes";

export const BR_NEGOCIO_DEMO_TOTAL = 1432;

/** Synthetic publish timestamps — higher = newer for “recientes” / default sort. */
const DEMO_MS = 1_720_000_800_000;

export const brNegocioFeaturedListing: BrNegocioListing = {
  id: "feat-encino",
  imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80&auto=format&fit=crop",
  price: "$1,250,000",
  title: "Casa moderna con piscina",
  addressLine: "Encino Hills, Los Angeles, CA",
  zipCode: "91436",
  resultsPropertyKind: "casa",
  facetPool: true,
  demoPublishedAtMs: DEMO_MS + 120 * 86_400_000,
  beds: "4",
  baths: "3.5",
  sqft: "2,450",
  year: "2020",
  categoriaPropiedad: "residencial",
  badges: ["negocio", "destacada", "promocionada"],
  advertiser: {
    kind: "agente",
    name: "Angela Meakins",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80&auto=format&fit=crop",
    subtitle: "Coldwell Banker Realty",
  },
  trustChip: "Agente verificado",
  operationLabel: "Venta",
  licenseLine: "DRE #01234567",
  metaLines: ["Tour virtual disponible"],
};

export const brNegocioGridListings: BrNegocioListing[] = [
  {
    id: "gdl-1",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80&auto=format&fit=crop",
    price: "$899,000",
    title: "Casa céntrica de lujo",
    addressLine: "Zapopan, Jalisco",
    resultsPropertyKind: "casa",
    beds: "3",
    baths: "2.5",
    sqft: "2,100",
    year: "2018",
    badges: ["negocio"],
    layout: "horizontal",
    categoriaPropiedad: "residencial",
    advertiser: { kind: "agente", name: "Gabriel Soto" },
    trustChip: "Agente verificado",
    demoPublishedAtMs: DEMO_MS,
  },
  {
    id: "cdmx-1",
    imageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&q=80&auto=format&fit=crop",
    price: "$475,000",
    title: "Departamento con vista panorámica",
    addressLine: "Polanco, CDMX",
    resultsPropertyKind: "departamento",
    beds: "2",
    baths: "2",
    sqft: "1,280",
    year: "2015",
    badges: ["negocio", "reducida"],
    layout: "vertical",
    categoriaPropiedad: "residencial",
    advertiser: { kind: "constructor", name: "Alejandro Torres", subtitle: "Grupo Horizonte" },
    trustChip: "Constructor",
    metaLines: ["Precio reciente ajustado"],
  },
  {
    id: "mty-1",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80&auto=format&fit=crop",
    price: "$3,200,000",
    title: "Residencia en San Pedro",
    addressLine: "San Pedro Garza García, NL",
    resultsPropertyKind: "casa",
    beds: "5",
    baths: "4.5",
    sqft: "4,200",
    year: "2022",
    badges: ["negocio", "nuevo", "open_house"],
    layout: "vertical",
    categoriaPropiedad: "residencial",
    openHouse: "Sáb 12 abr · 11:00 – 14:00",
    advertiser: { kind: "equipo", name: "Equipo Domus", subtitle: "2 agentes" },
    trustChip: "Equipo",
    demoPublishedAtMs: DEMO_MS + 2 * 86_400_000,
  },
  {
    id: "la-2",
    imageUrl: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=900&q=80&auto=format&fit=crop",
    price: "$625,000",
    title: "Townhouse con patio privado",
    addressLine: "Pasadena, CA",
    zipCode: "91101",
    resultsPropertyKind: "casa",
    beds: "3",
    baths: "2",
    sqft: "1,760",
    year: "2019",
    badges: ["negocio", "tour_virtual", "planos"],
    layout: "horizontal",
    categoriaPropiedad: "residencial",
    advertiser: { kind: "oficina", name: "Brokerage Valle", subtitle: "Oficina central" },
    trustChip: "Oficina",
    metaLines: ["Planos y tour virtual"],
    demoPublishedAtMs: DEMO_MS + 3 * 86_400_000,
  },
  {
    id: "gdl-2",
    imageUrl: "https://images.unsplash.com/photo-1605146769289-440113cc31d0?w=900&q=80&auto=format&fit=crop",
    price: "$1,890,000",
    title: "Casa en coto con amenidades",
    addressLine: "Guadalajara, Jalisco",
    resultsPropertyKind: "casa",
    beds: "4",
    baths: "3",
    sqft: "2,890",
    year: "2021",
    badges: ["negocio"],
    layout: "vertical",
    categoriaPropiedad: "residencial",
    advertiser: { kind: "agente", name: "Mariana López" },
    trustChip: "Agente verificado",
    demoPublishedAtMs: DEMO_MS + 4 * 86_400_000,
  },
  {
    id: "mty-2",
    imageUrl: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=900&q=80&auto=format&fit=crop",
    price: "$12,500,000",
    title: "Terreno comercial en esquina",
    addressLine: "Monterrey, NL",
    resultsPropertyKind: "comercial",
    beds: "—",
    baths: "—",
    sqft: "1.2 ha",
    badges: ["negocio", "comercial"],
    layout: "horizontal",
    categoriaPropiedad: "comercial",
    advertiser: { kind: "oficina", name: "Capital Inmobiliaria" },
    trustChip: "Oficina",
    demoPublishedAtMs: DEMO_MS + 5 * 86_400_000,
  },
  {
    id: "jal-terreno-1",
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80&auto=format&fit=crop",
    price: "$2,400,000",
    title: "Lote residencial con servicios",
    addressLine: "Chapala, Jalisco",
    resultsPropertyKind: "terreno",
    beds: "—",
    baths: "—",
    sqft: "800 m²",
    year: "—",
    badges: ["negocio"],
    layout: "vertical",
    categoriaPropiedad: "terreno_lote",
    advertiser: { kind: "agente", name: "Ricardo Mena" },
    trustChip: "Agente verificado",
    metaLines: ["Esquina · servicios en banqueta"],
    demoPublishedAtMs: DEMO_MS + 6 * 86_400_000,
  },
  {
    id: "priv-spgg-1",
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80&auto=format&fit=crop",
    price: "$8,750,000",
    title: "Casa en Valle con vista al cerro",
    addressLine: "San Pedro Garza García, NL",
    resultsPropertyKind: "casa",
    beds: "4",
    baths: "3.5",
    sqft: "380 m²",
    year: "2016",
    badges: ["destacada"],
    sellerKind: "privado",
    layout: "vertical",
    categoriaPropiedad: "residencial",
    advertiser: { kind: "agente", name: "Patricia Cantú" },
    trustChip: "Particular",
    metaLines: ["Acepta ofertas razonables"],
    demoPublishedAtMs: DEMO_MS + 7 * 86_400_000,
  },
  {
    id: "priv-mty-cumbres",
    imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=900&q=80&auto=format&fit=crop",
    price: "$22,500",
    title: "Departamento iluminado en Cumbres",
    addressLine: "Cumbres Elite, Monterrey, NL",
    resultsPropertyKind: "departamento",
    facetPets: true,
    facetFurnished: true,
    beds: "2",
    baths: "2",
    sqft: "98 m²",
    year: "2019",
    badges: ["reducida"],
    sellerKind: "privado",
    layout: "horizontal",
    categoriaPropiedad: "residencial",
    advertiser: { kind: "agente", name: "Luis Garza" },
    trustChip: "Particular",
    operationLabel: "Renta",
    metaLines: ["Acepta mascotas", "Amueblado"],
    demoPublishedAtMs: DEMO_MS + 8 * 86_400_000,
  },
  {
    id: "priv-mty-centro",
    imageUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=900&q=80&auto=format&fit=crop",
    price: "$4,950,000",
    title: "Casa en zona centro con cochera",
    addressLine: "Centro, Monterrey, NL",
    resultsPropertyKind: "casa",
    beds: "3",
    baths: "2",
    sqft: "210 m²",
    year: "1998",
    badges: [],
    sellerKind: "privado",
    layout: "vertical",
    categoriaPropiedad: "residencial",
    advertiser: { kind: "agente", name: "Martha Elizondo" },
    trustChip: "Particular",
    operationLabel: "Venta",
    metaLines: ["Recién impermeabilizada"],
    demoPublishedAtMs: DEMO_MS + 9 * 86_400_000,
  },
];
