export type Lang = "es" | "en";

/** TODAY-1 — local typed COPY object for the Idea Builder, following the same convention as businessIdentityCopy.ts. */
export function ideaBuilderCopy(lang: Lang) {
  return lang === "es"
    ? {
        title: "Constructor de ideas",
        subtitle: "Organiza tu idea de negocio paso a paso. Esto es educativo -- no valida demanda de mercado ni garantiza que el negocio sera rentable.",
        unavailable: "Esta funcion aun no esta disponible.",
        loading: "Cargando...",
        pathQuestion: "Cual describe mejor tu situacion?",
        pathHaveBusiness: "Ya tengo un negocio",
        pathThinking: "Estoy pensando en empezar uno",
        ideaDescriptionLabel: "Describe tu idea de negocio",
        customerDefinitionLabel: "Quien seria tu cliente?",
        problemDefinitionLabel: "Que problema resuelves para esa persona?",
        simpleOfferLabel: "Cual seria tu oferta simple (que vendes y a quien)?",
        readinessTitle: "Preguntas de preparacion",
        readinessSubtitle: "Estas preguntas te ayudan a identificar en que areas te conviene aprender mas. No son un examen ni una evaluacion de exito.",
        yes: "Si",
        no: "No",
        notSure: "No estoy seguro",
        saveStatus: "Guardado",
        savingStatus: "Guardando...",
        completionLabel: "Progreso",
        markComplete: "Marcar como completo",
        completedBanner: "Has completado el Constructor de ideas. Puedes seguir editando cuando quieras.",
        downloadSummary: "Descargar resumen",
        nextLessonsTitle: "Lecciones sugeridas para seguir aprendiendo",
        noNextLessons: "Responde algunas preguntas de preparacion para ver sugerencias.",
        disclaimer: "Este resumen es educativo. No es una validacion de mercado, una promesa de rentabilidad ni una garantia de exito.",
        placeholderText: "Escribe aqui...",
        summaryFileTitle: "Resumen de tu idea de negocio - Leonix",
      }
    : {
        title: "Idea Builder",
        subtitle: "Organize your business idea step by step. This is educational -- it does not validate market demand or guarantee the business will be profitable.",
        unavailable: "This feature is not available yet.",
        loading: "Loading...",
        pathQuestion: "Which best describes your situation?",
        pathHaveBusiness: "I already have a business",
        pathThinking: "I am thinking about starting one",
        ideaDescriptionLabel: "Describe your business idea",
        customerDefinitionLabel: "Who would your customer be?",
        problemDefinitionLabel: "What problem do you solve for that person?",
        simpleOfferLabel: "What would your simple offer be (what you sell and to whom)?",
        readinessTitle: "Readiness questions",
        readinessSubtitle: "These questions help identify where more learning could help. They are not a test or a success evaluation.",
        yes: "Yes",
        no: "No",
        notSure: "Not sure",
        saveStatus: "Saved",
        savingStatus: "Saving...",
        completionLabel: "Progress",
        markComplete: "Mark as complete",
        completedBanner: "You have completed the Idea Builder. You can keep editing any time.",
        downloadSummary: "Download summary",
        nextLessonsTitle: "Suggested lessons to keep learning",
        noNextLessons: "Answer a few readiness questions to see suggestions.",
        disclaimer: "This summary is educational. It is not market validation, a profitability promise, or a guarantee of success.",
        placeholderText: "Write here...",
        summaryFileTitle: "Business idea summary - Leonix",
      };
}
