import type { LeonixBRNegocioForm } from "../schema/leonixBrNegocioForm";

export function createEmptyLeonixBRNegocioForm(): LeonixBRNegocioForm {
  return {
    property: {
      tipoPublicacion: { modoPublicacion: "negocio_profesional", notasInternas: "" },
      principal: {
        titulo: "",
        tipoOperacion: "",
        tipoPropiedad: "",
        subtipo: "",
        precio: "",
        moneda: "MXN",
        mostrarPrecio: true,
        estatusInmueble: "",
        tipoPublicacionInterna: "",
      },
      ubicacion: {
        direccionCompleta: "",
        ciudad: "",
        estado: "",
        codigoPostal: "",
        coloniaZona: "",
        referenciaUbicacion: "",
        ocultarDireccionExacta: false,
        puntoMapaNotas: "",
        areaAproximada: "",
      },
      caracteristicas: {
        recamaras: "",
        banosCompletos: "",
        mediosBanos: "",
        construccionPies2: "",
        terrenoPies2: "",
        niveles: "",
        estacionamientos: "",
        anioConstruccion: "",
        estadoConservacion: "",
        estiloDiseno: "",
        condicionGeneral: "",
      },
      interior: {
        cocina: "",
        comedor: "",
        sala: "",
        cuartoLavado: "",
        closets: "",
        aireAcondicionado: "",
        calefaccion: "",
        chimenea: "",
        electrodomesticosIncluidos: "",
        pisos: "",
        interiorFeatures: "",
        kitchenFeatures: "",
        diningDetails: "",
        roomDetails: "",
      },
      exterior: {
        patio: "",
        jardin: "",
        terraza: "",
        balcon: "",
        alberca: "",
        roofGarden: "",
        fachada: "",
        materialesConstruccion: "",
        techo: "",
        loteTerreno: "",
        exteriorFeatures: "",
        parkingDetails: "",
        lotDetails: "",
      },
      serviciosComunidad: {
        utilidadesServicios: "",
        energiaSolar: "",
        hoaComunidad: "",
        cuotaHoa: "",
        seguridad: "",
        accesoControlado: "",
        detallesFinancieros: "",
        detallesListing: "",
        taxParcelNotas: "",
        comunidadVecindario: "",
        escuelas: "",
      },
      medios: {
        imagenesDataUrls: [],
        videoUrl: "",
        tourVirtualUrl: "",
        planoUrl: "",
        planoNombreArchivo: "",
        thumbnailVideoUrl: "",
        ordenFotosNotas: "",
      },
      descripcionMarketing: {
        resumenCorto: "",
        descripcionCompleta: "",
        highlights: "",
        chipsDestacados: "",
        puntosFuertes: "",
        fraseMarketing: "",
        amenidadesClave: "",
        notasVecindario: "",
      },
    },
    rail: {
      negocio: {
        nombreComercial: "",
        nombreLegal: "",
        logoDataUrl: "",
        brokerageName: "",
        website: "",
        telefonoOficina: "",
        emailOficina: "",
        direccionOficina: "",
        licenciaNegocio: "",
        aniosExperiencia: "",
        descripcionNegocio: "",
        horariosAtencion: "",
        idiomas: "",
        coberturaArea: "",
      },
      agentePrincipal: {
        fotoDataUrl: "",
        nombreCompleto: "",
        cargoRol: "",
        telefonoDirecto: "",
        whatsapp: "",
        correo: "",
        licenciaIndividual: "",
        idiomas: "",
        horarios: "",
        urlPerfil: "",
        frasePresentacion: "",
        disponibilidadRespuesta: "",
      },
      equipoAdicional: {
        coAgente: "",
        brokerResponsable: "",
        contactoOficina: "",
        contactoSecundario: "",
        contactoPrestamos: "",
        masMiembrosEquipo: "",
        masAnunciosNegocioNotas: "",
      },
      redes: {
        facebook: "",
        instagram: "",
        linkedin: "",
        youtube: "",
        tiktok: "",
        whatsappLink: "",
        urlAgendarCita: "",
        urlPerfilProfesional: "",
        websitePrincipal: "",
        enlacesPersonalizados: "",
      },
      contactoCta: {
        ctaPrincipal: "",
        ctaSecundario: "",
        mostrarTelefono: true,
        permitirMensajes: true,
        permitirSolicitudVisita: true,
        tiempoRespuestaEstimado: "",
        disponibilidadGeneral: "",
      },
    },
  };
}
