/** BR-INV-B/C — pre-publish inventory drawer copy (Negocio application only). */

export type BrNegocioPrePublishInventoryLang = "es" | "en";

export function brNegocioPrePublishInventoryShellCopy(lang: BrNegocioPrePublishInventoryLang) {
  if (lang === "es") {
    return {
      cta: "Agregar propiedad al inventario",
      ctaAlt: "Agregar otra propiedad",
      hint: "Puedes preparar varias propiedades para este mismo agente o negocio antes de publicar.",
      countLabel: (n: number) => `Propiedades adicionales: ${n}`,
      emptyList: "Aún no has agregado propiedades adicionales.",
      ownerOnlyNote:
        "Solo en tu solicitud de publicación. No aparece en el anuncio público hasta que cada propiedad se publique por separado.",
      drawerTitle: "Agregar propiedad al inventario",
      drawerTitleEdit: "Editar propiedad del inventario",
      drawerExplain:
        "Esta propiedad usará la misma información del agente, contacto y negocio. Captura solo los detalles de la propiedad.",
      close: "Cerrar",
      cancel: "Cancelar",
      saveProperty: "Guardar propiedad",
      saveAndAddAnother: "Guardar y agregar otra",
      edit: "Editar",
      remove: "Eliminar",
      removeConfirm: "¿Eliminar esta propiedad del borrador de inventario?",
      sectionKicker: "Inventario de propiedades",
      fields: {
        title: "Título de la propiedad",
        propertyType: "Tipo de propiedad",
        propertySubtype: "Subtipo",
        price: "Precio",
        bedrooms: "Recámaras",
        bathrooms: "Baños",
        interiorSqft: "Tamaño interior (pies²)",
        lotSqft: "Tamaño del lote (pies²)",
        streetLine1: "Dirección",
        streetLine2: "Unidad / apt / suite / espacio",
        city: "Ciudad",
        state: "Estado",
        zip: "Código postal",
        showExactAddress: "Mostrar dirección exacta en el anuncio",
        description: "Descripción",
        mainPhotoUrl: "URL de foto principal (opcional)",
        mediaSection: "Fotos y enlaces de la propiedad",
        mediaSectionHint:
          "Solo detalles de esta propiedad. No incluyas contacto del agente, redes sociales ni financiamiento.",
        photos: "Fotos",
        addPhotos: "Agregar fotos",
        photoUrlPaste: "Agregar foto por URL",
        photoUrlPasteHint: "Pega un enlace https:// y presiona Enter o Agregar.",
        addPhotoUrl: "Agregar",
        coverPhotoNote: "La foto marcada como portada se usa en la tarjeta de vista previa.",
        listadoUrl: "Más información / listado (URL)",
        listadoUrlHint: "Enlace opcional con más detalles de la propiedad.",
        videoUrl: "Video (URL)",
        videoUrlHint: "YouTube, Vimeo u otro enlace de video.",
        tourUrl: "Tour virtual (URL)",
        tourUrlHint: "Matterport u otro tour 3D.",
        brochureUrl: "Folleto / PDF (URL)",
        brochureUrlHint: "Enlace al folleto de la propiedad.",
        mlsUrl: "MLS (URL)",
        mlsUrlHint: "Enlace preferido del MLS para esta propiedad.",
      },
      validationSummary: "Revisa los campos marcados antes de guardar.",
      previewTitle: "Vista previa del inventario",
      previewHelper:
        "Estas tarjetas son solo una vista previa para ti. Las propiedades adicionales no se publicarán hasta completar el gate de publicación.",
      previewEmptyAdditional:
        "Agrega otra propiedad para ver cómo se verá tu inventario antes de publicar.",
    };
  }
  return {
    cta: "Add property to inventory",
    ctaAlt: "Add another property",
    hint: "You can prepare multiple properties for this same agent or business before publishing.",
    countLabel: (n: number) => `Additional properties: ${n}`,
    emptyList: "You have not added additional properties yet.",
    ownerOnlyNote:
      "Owner application only. Nothing appears on the public listing until each property is published separately.",
    drawerTitle: "Add property to inventory",
    drawerTitleEdit: "Edit inventory property",
    drawerExplain:
      "This property will use the same agent, contact, and business information. Enter property details only.",
    close: "Close",
    cancel: "Cancel",
    saveProperty: "Save property",
    saveAndAddAnother: "Save and add another",
    edit: "Edit",
    remove: "Remove",
    removeConfirm: "Remove this property from the inventory draft?",
    sectionKicker: "Property inventory",
    fields: {
      title: "Property title",
      propertyType: "Property type",
      propertySubtype: "Subtype",
      price: "Price",
      bedrooms: "Bedrooms",
      bathrooms: "Bathrooms",
      interiorSqft: "Interior size (sq ft)",
      lotSqft: "Lot size (sq ft)",
      streetLine1: "Street address",
      streetLine2: "Unit / apt / suite / space",
      city: "City",
      state: "State",
      zip: "ZIP code",
      showExactAddress: "Show exact address on listing",
      description: "Description",
      mainPhotoUrl: "Main photo URL (optional)",
      mediaSection: "Property photos and links",
      mediaSectionHint:
        "Property details only. Do not include agent contact, social profiles, or financing.",
      photos: "Photos",
      addPhotos: "Add photos",
      photoUrlPaste: "Add photo by URL",
      photoUrlPasteHint: "Paste an https:// link and press Enter or Add.",
      addPhotoUrl: "Add",
      coverPhotoNote: "The cover photo is used on the inventory preview card.",
      listadoUrl: "More information / listing (URL)",
      listadoUrlHint: "Optional link with more property details.",
      videoUrl: "Video (URL)",
      videoUrlHint: "YouTube, Vimeo, or another video link.",
      tourUrl: "Virtual tour (URL)",
      tourUrlHint: "Matterport or another 3D tour.",
      brochureUrl: "Brochure / PDF (URL)",
      brochureUrlHint: "Link to the property brochure.",
      mlsUrl: "MLS (URL)",
      mlsUrlHint: "Preferred MLS link for this property.",
    },
    validationSummary: "Review the highlighted fields before saving.",
    previewTitle: "Inventory preview",
    previewHelper:
      "These cards are only a preview for you. Additional properties will not publish until the publish mapping gate is completed.",
    previewEmptyAdditional: "Add another property to see how your inventory will look before publishing.",
  };
}
