/** BR-INV-B/C — pre-publish inventory drawer copy (Negocio application only). */

export type BrNegocioPrePublishInventoryLang = "es" | "en";

export function brNegocioPrePublishInventoryShellCopy(lang: BrNegocioPrePublishInventoryLang) {
  if (lang === "es") {
    return {
      cta: "Agregar propiedad al inventario",
      ctaAlt: "Agregar otra propiedad",
      hint: "Puedes preparar varias propiedades para este mismo agente o negocio antes de publicar.",
      countLabel: (n: number) => `Propiedades adicionales: ${n}`,
      emptyList: "Aún no has agregado propiedades adicionales.",
      ownerOnlyNote:
        "Solo en tu solicitud de publicación. No aparece en el anuncio público hasta que cada propiedad se publique por separado.",
      drawerTitle: "Agregar propiedad al inventario",
      drawerTitleEdit: "Editar propiedad del inventario",
      drawerExplain:
        "Esta propiedad usará la misma información del agente, contacto y negocio. Captura solo los detalles de la propiedad.",
      fullAppExplain:
        "Completa los mismos pasos de propiedad que el anuncio principal. La información del agente y contacto se hereda automáticamente.",
      previewSaveTitle: "Vista previa de la propiedad",
      previewSaveBody:
        "Revisa la tarjeta antes de guardar. Esto no publica el anuncio; solo agrega la propiedad a tu inventario pre-publicación.",
      close: "Cerrar",
      cancel: "Cancelar",
      saveProperty: "Guardar propiedad",
      saveAndAddAnother: "Guardar y agregar otra",
      saveAndGoToParentPreview: "Guardar e ir a revisión/publicación principal",
      previewThisProperty: "Vista previa de esta propiedad",
      edit: "Editar",
      remove: "Eliminar",
      removeConfirm: "¿Eliminar esta propiedad del borrador de inventario?",
      sectionKicker: "Inventario de propiedades",
      fields: {
        title: "Título de la propiedad",
        propertyType: "Tipo de propiedad",
        propertySubtype: "Subtipo",
        price: "Precio",
        bedrooms: "Recámaras",
        bathrooms: "Baños",
        interiorSqft: "Tamaño interior (pies²)",
        lotSqft: "Tamaño del lote (pies²)",
        streetLine1: "Dirección",
        streetLine2: "Unidad / apt / suite / espacio",
        city: "Ciudad",
        state: "Estado",
        zip: "Código postal",
        showExactAddress: "Mostrar dirección exacta en el anuncio",
        description: "Descripción",
        mainPhotoUrl: "URL de foto principal (opcional)",
        mediaSection: "Fotos y enlaces de la propiedad",
        mediaSectionHint:
          "Solo detalles de esta propiedad. No incluyas contacto del agente, redes sociales ni financiamiento.",
        photos: "Fotos",
        addPhotos: "Agregar fotos",
        photoUrlPaste: "Agregar foto por URL",
        photoUrlPasteHint: "Pega un enlace https:// y presiona Enter o Agregar.",
        addPhotoUrl: "Agregar",
        coverPhotoNote: "La foto marcada como portada se usa en la tarjeta de vista previa.",
        listadoUrl: "Más información / listado (URL)",
        listadoUrlHint: "Enlace opcional con más detalles de la propiedad.",
        videoUrl: "Video (URL)",
        videoUrlHint: "YouTube, Vimeo u otro enlace de video.",
        tourUrl: "Tour virtual (URL)",
        tourUrlHint: "Matterport u otro tour 3D.",
        brochureUrl: "Folleto / PDF (URL)",
        brochureUrlHint: "Enlace al folleto de la propiedad.",
        mlsUrl: "MLS (URL)",
        mlsUrlHint: "Enlace preferido del MLS para esta propiedad.",
      },
      validationSummary: "Revisa los campos marcados antes de guardar.",
      previewTitle: "Vista previa del inventario",
      previewHelper:
        "Estas tarjetas son solo una vista previa para ti. Las propiedades adicionales no se publicarán hasta que publiques la solicitud completa.",
      previewEmptyAdditional:
        "Agrega otra propiedad para ver cómo se verá tu inventario antes de publicar.",
      inheritedNotice:
        "Esta información se hereda de la aplicación principal y se usará para esta propiedad.",
      unsavedCloseConfirm:
        "Tienes cambios sin guardar en esta propiedad. ¿Quieres cerrar sin guardar?",
      childFullPreviewKicker: "Vista previa · Borrador",
      childFullPreviewTitle: "Vista previa de la propiedad adicional",
      childFullPreviewBody:
        "Esta propiedad se publicará como una ficha propia cuando publiques la solicitud completa.",
      childFullPreviewFooter: "Vista previa de borrador — no es un anuncio publicado.",
      packagePreviewTitle: "Vista previa del inventario de propiedades",
      packagePreviewHelper:
        "Estas propiedades se publicarán junto con el anuncio principal cuando completes la solicitud.",
      inventoryIncludedTitle: "Inventario incluido en esta solicitud",
      previewCard: "Ver vista previa",
      leonixDraftNote: "ID Leonix se generará al publicar",
      photoCountLabel: (n: number) => `${n} foto${n === 1 ? "" : "s"}`,
      mainRoleLabel: "Propiedad principal",
      additionalRoleLabel: "Propiedad adicional",
      draftStatusLabel: "Borrador",
    };
  }
  return {
    cta: "Add property to inventory",
    ctaAlt: "Add another property",
    hint: "You can prepare multiple properties for this same agent or business before publishing.",
    countLabel: (n: number) => `Additional properties: ${n}`,
    emptyList: "You have not added additional properties yet.",
    ownerOnlyNote:
      "Owner application only. Nothing appears on the public listing until each property is published separately.",
    drawerTitle: "Add property to inventory",
    drawerTitleEdit: "Edit inventory property",
    drawerExplain:
      "This property will use the same agent, contact, and business information. Enter property details only.",
    fullAppExplain:
      "Complete the same property steps as the main listing. Agent and contact information is inherited automatically.",
    previewSaveTitle: "Property preview",
    previewSaveBody:
      "Review the card before saving. This does not publish the listing; it only adds the property to your pre-publish inventory.",
    close: "Close",
    cancel: "Cancel",
    saveProperty: "Save property",
    saveAndAddAnother: "Save and add another",
    saveAndGoToParentPreview: "Save and go to parent publish review",
    previewThisProperty: "Preview this property",
    edit: "Edit",
    remove: "Remove",
    removeConfirm: "Remove this property from the inventory draft?",
    sectionKicker: "Property inventory",
    fields: {
      title: "Property title",
      propertyType: "Property type",
      propertySubtype: "Subtype",
      price: "Price",
      bedrooms: "Bedrooms",
      bathrooms: "Bathrooms",
      interiorSqft: "Interior size (sq ft)",
      lotSqft: "Lot size (sq ft)",
      streetLine1: "Street address",
      streetLine2: "Unit / apt / suite / space",
      city: "City",
      state: "State",
      zip: "ZIP code",
      showExactAddress: "Show exact address on listing",
      description: "Description",
      mainPhotoUrl: "Main photo URL (optional)",
      mediaSection: "Property photos and links",
      mediaSectionHint:
        "Property details only. Do not include agent contact, social profiles, or financing.",
      photos: "Photos",
      addPhotos: "Add photos",
      photoUrlPaste: "Add photo by URL",
      photoUrlPasteHint: "Paste an https:// link and press Enter or Add.",
      addPhotoUrl: "Add",
      coverPhotoNote: "The cover photo is used on the inventory preview card.",
      listadoUrl: "More information / listing (URL)",
      listadoUrlHint: "Optional link with more property details.",
      videoUrl: "Video (URL)",
      videoUrlHint: "YouTube, Vimeo, or another video link.",
      tourUrl: "Virtual tour (URL)",
      tourUrlHint: "Matterport or another 3D tour.",
      brochureUrl: "Brochure / PDF (URL)",
      brochureUrlHint: "Link to the property brochure.",
      mlsUrl: "MLS (URL)",
      mlsUrlHint: "Preferred MLS link for this property.",
    },
    validationSummary: "Review the highlighted fields before saving.",
    previewTitle: "Inventory preview",
    previewHelper:
      "These cards are only a preview for you. Additional properties will not publish until you publish the full application.",
    previewEmptyAdditional: "Add another property to see how your inventory will look before publishing.",
    inheritedNotice:
      "This information is inherited from the main application and will be used for this property.",
    unsavedCloseConfirm:
      "You have unsaved changes in this property. Close without saving?",
    childFullPreviewKicker: "Preview · Draft",
    childFullPreviewTitle: "Additional property preview",
    childFullPreviewBody:
      "This property will publish as its own listing when you publish the full application.",
    childFullPreviewFooter: "Draft preview — not a published listing.",
    packagePreviewTitle: "Property inventory preview",
    packagePreviewHelper:
      "These properties will publish with the main listing when you complete the application.",
    inventoryIncludedTitle: "Inventory included in this application",
    previewCard: "Preview",
    leonixDraftNote: "Leonix ID generated on publish",
    photoCountLabel: (n: number) => `${n} photo${n === 1 ? "" : "s"}`,
    mainRoleLabel: "Main property",
    additionalRoleLabel: "Additional property",
    draftStatusLabel: "Draft",
  };
}
