/** English UI strings — same shape as `BR_COPY_ES` (runtime validated via `getBrAgenteResidencialCopy`). */
export const BR_COPY_EN = {
  stepLabels: [
    "Listing type",
    "Basic information",
    "Photos & media",
    "Essential details",
    "Highlighted features",
    "Description",
    "Professional profile",
    "Contact & button destinations",
    "Optional extras",
    "Preview",
  ],
  app: {
    kicker: "Leonix Classifieds · Business",
    title: "Publish Real Estate — Agent",
    subtitle:
      "Leonix is a premium showcase: the official listing stays on your MLS or website. Complete the steps and review the fixed preview before publishing.",
    navPasos: "Steps",
    cambiarCanal: "Change channel",
    verCategoria: "View RE category",
    pasoDe: "Step",
    de: "of",
    anterior: "Back",
    siguiente: "Next",
    vistaPreviaTitulo: "Preview",
    vistaPreviaBody:
      "Open the preview with your current data. You can return to edit without losing your draft in this session.",
    verVistaPrevia: "View preview",
  },
  step01: {
    title: "Listing type",
    subResidencial: "Residential on Leonix: a clear showcase for buyers. This flow is sale-only.",
    subComercial: "Commercial on Leonix: a clear showcase for business space. This flow is sale-only.",
    subTerreno: "Land and lots on Leonix: clear parcels for buyers. This flow is sale-only.",
    tipoPublicacion: "Publication type",
    tipoPublicacionHintResidencial: "Fixed for this variant: residential sale only.",
    tipoPublicacionHintComercial: "Fixed for this variant: commercial sale only.",
    tipoPublicacionHintTerreno: "Fixed for this variant: land / lot sale only.",
    ventaResidencial: "Residential sale",
    ventaComercial: "Commercial sale",
    ventaTerreno: "Land / lot sale",
    tipoPropiedad: "Property type",
    tipoComercial: "Commercial type",
    tipoTerreno: "Land / lot type",
    especificaTipo: "Specify the property type",
    especificaTipoHint: "Shown in the listing as the property type.",
    subtipo: "Subtype (optional)",
    subtipoHint: "Detail for the chosen type (e.g. penthouse or ground floor). Not required.",
    detalleAdicional: "Additional detail (optional)",
    detalleAdicionalHint: "Optional short note about the type or layout.",
  },
  step02: {
    title: "Basic information",
    sub: "What buyers see first in the preview.",
    titulo: "Listing title",
    precio: "Price",
    precioHint: "Use numbers; the preview shows USD.",
    estadoAnuncio: "Listing status",
    estadoAnuncioHint: "Available, pending, under contract, or sold.",
    ciudad: "City",
    ciudadHint: "Official NorCal list: type and pick a city; on blur we store the canonical name.",
    ciudadPlaceholder: "e.g. San Jose, Fremont…",
    area: "City area",
    areaHint: "The general area where the property is located.",
    direccion: "Address",
    direccionHint: "Street and number; you may omit unit in the public ad.",
    listado: "Listing link or file",
    listadoHint: "Lets buyers see more on your original listing without overfilling this ad.",
    pegarUrl: "Paste URL",
    subirPdf: "Upload PDF or file",
    archivo: "File:",
    adjunto: "attachment",
    quitar: "Remove",
    estados: { disponible: "Available", pendiente: "Pending", bajo_contrato: "Under contract", vendido: "Sold" },
  },
  step03: {
    title: "Photos & media",
    sub: "The main image is the cover. Video, tour, and brochure appear in the preview when the matching buttons are enabled.",
    fotos: "Photos",
    agregarFotos: "Add photos",
    portada: "Main image (cover)",
    portadaHint: "Choose which photo is the cover.",
    fotoN: (n: number) => `Photo ${n}`,
    moverIzq: "Move left",
    moverDer: "Move right",
    eliminar: "Remove",
    archivoSubido: "Uploaded",
    subirVideo: "Upload video",
    video: "Video (optional)",
    videoHint:
      "Public link (YouTube, Vimeo, etc.) or a short video file for preview. Nothing is uploaded to Mux until you publish.",
    tour: "Virtual / 3D tour (optional)",
    tourHint:
      "Matterport, 3D or 360 tour URL, or another public tour link. You may also upload a compatible file (e.g. cover image/PDF, short clip, static HTML) for local draft preview.",
    folleto: "Brochure / document (optional)",
    folletoHint:
      "PDF, Word, or brochure/plan image. Linked as “View brochure” in preview. Allowed: PDF, DOC/DOCX, JPG/PNG.",
  },
  step04: {
    title: "Essential details",
    sub: "Only what helps a buyer decide.",
    recamaras: "Bedrooms",
    banos: "Full baths",
    mediosBanos: "Half baths",
    mediosHint: "Optional.",
    tamanoInterior: "Interior size",
    tamanoInteriorHint: "Approximate square feet.",
    tamanoLote: "Lot size",
    tamanoLoteHint: "If applicable; otherwise leave blank.",
    estacionamientos: "Parking spaces",
    ano: "Year built",
    condicion: "Property condition",
    condicionHint: "General condition at listing time.",
    usoComercial: "Commercial use",
    usoComercialHint: "E.g. retail, medical office, showroom.",
    oficinasComercial: "Offices",
    oficinasComercialHint: "Approximate count if applicable.",
    nivelesComercial: "Levels / floors",
    nivelesComercialHint: "If applicable.",
    zonificacionComercial: "Zoning",
    zonificacionComercialHint: "If applicable.",
    accesoCarga: "Loading access",
    accesoCargaHint: "Check if there is a dock, ramp, or truck access.",
    usoZonificacionTerreno: "Use / zoning",
    usoZonificacionTerrenoHint: "Zone, permitted use, or notes.",
    accesoTerreno: "Access",
    accesoTerrenoHint: "Access type or roadway.",
    serviciosTerreno: "Available utilities",
    serviciosTerrenoHint: "Water, power, sewer, etc.",
    topografiaTerreno: "Topography",
    topografiaTerrenoHint: "Optional.",
    listoConstruirTerreno: "Ready to build",
    cercadoTerreno: "Fenced",
  },
  step05: {
    title: "Highlighted features",
    sub: "Check what you want shown in the preview.",
  },
  step06: {
    title: "Description",
    principal: "Main description",
    notas: "Additional notes (optional)",
    notasHint: "Short note or internal detail; not the main body.",
  },
  step07: {
    title: "Professional profile",
    sub: "This is your primary business or agent contact record; each field maps to a fixed slot in the preview.",
    agente: "Agent",
    fotoAgente: "Agent photo",
    fotoAgenteHint: "Upload an image or paste a public URL.",
    nombre: "Full name",
    titulo: "Title",
    licencia: "License or professional ID",
    licenciaHint: "If applicable in your state.",
    telefonoPersonal: "Personal phone",
    telefonoOficina: "Office phone",
    whatsapp: "WhatsApp",
    whatsappHint: "WhatsApp button only; it does not replace voice-call numbers.",
    numeroPrincipalLlamadas: "Primary number for calls",
    principalPersonal: "Personal",
    principalOficina: "Office",
    correoAgente: "Email",
    sitioWebAgente: "Website",
    sitioWebAgenteHint:
      "Your agent site (“View website” uses the contact & button destinations step first, then this, then office/brand).",
    mostrarMarca: "Show office or brand on the card",
    mostrarMarcaHint: "When off, the preview hides the brand block even if data is saved.",
    oficina: "Office or brand",
    nombreMarca: "Office or brand name",
    logo: "Office or brand logo",
    logoHint: "Image or URL; shown above your photo in the preview.",
    licenciaMarca: "Broker/office license (optional)",
    sitioMarca: "Office or brand website (optional)",
    sitioMarcaHint: "Short link under the brand name on the card.",
    redes: "Social media",
    redesSub: "One link per network; each preview icon uses only its field.",
    subirImagen: "Upload image",
    pegarUrlImagen: "Paste image URL",
    subirArchivo: "Upload file",
    pegarUrl: "Paste URL",
    instagram: "Instagram",
    facebook: "Facebook",
    youtube: "YouTube",
    tiktok: "TikTok",
    x: "X / Twitter",
    enlaceSocialAdicional: "Additional social link (optional)",
    areaServicio: "Service area (optional)",
    idiomas: "Languages (optional)",
    idiomasPh: "e.g. English and Spanish",
    segundoAgente: "Second agent",
    agente2Foto: "Second agent photo",
    agente2FotoHint: "Upload an image or paste a public URL.",
    agente2Nombre: "Full name",
    agente2Titulo: "Title",
    agente2Licencia: "License or professional ID",
    agente2Correo: "Email (optional)",
    agregarSegundoAgente: "Add second agent",
    ocultarSegundoAgente: "Hide",
    agregarBrokerAsesor: "Add broker / advisor",
    ocultarBrokerAsesor: "Hide",
    brokerSection: "Broker / advisor",
    brokerFoto: "Photo (optional)",
    brokerFotoHint: "Upload an image or paste a public URL.",
    brokerNombre: "Name",
    brokerTitulo: "Title or role",
    brokerLicencia: "License or ID",
    brokerEmail: "Email",
    brokerSitioWeb: "Website",
    brokerSitioWebHint: "Optional",
    brokerInstagram: "Instagram",
    brokerFacebook: "Facebook",
    brokerYoutube: "YouTube",
    brokerTiktok: "TikTok",
    brokerX: "X / Twitter",
    brokerEnlaceAdicional: "Additional link",
  },
  step08: {
    title: "Contact & button destinations",
    sub:
      "These fields set the preferred destination when a buyer clicks a button. If you leave a field empty, the system uses the contact information already saved in your professional profile (and other listing fallbacks where they apply). At the end of this step, toggles choose which buttons appear in the preview and when published; without a valid destination, the button stays hidden.",
    contactoBase: "Email on the card",
    contactoBaseSub:
      "Agent phones and WhatsApp were already saved in “Professional profile”; you are not re-entering them here. Adjust only the email shown on the card (also editable in that step).",
    correo: "Main email",
    correoHint:
      "Shown on the card. The “Request information” button prefers the email you set below; if that field is empty, it falls back to this main email.",
    destinos: "Preferred destination per button",
    destinosSub:
      "Optional: set a different number, email, or link than your professional card for a specific action. If you leave a field empty, the fallback described in that field’s hint applies (data from “Professional profile” or earlier listing steps).",
    numLlamadas: "Preferred number for calls",
    numLlamadasHint: "If empty: primary call number from the professional profile step.",
    numWa: "Preferred number for WhatsApp",
    numWaHint: "If empty: agent WhatsApp field from the professional step only; no button without a dedicated number.",
    correoInfo: "Preferred email for information requests",
    correoInfoHint: "If empty: uses the main email entered above in this step.",
    enlaceVisita: "Preferred link to schedule a visit",
    enlaceVisitaHint: "Https scheduling link (e.g. Calendly). No link means no button.",
    enlaceWeb: "Preferred website link",
    enlaceWebHint: "“View website” button. If empty: agent site, then office/brand site from the previous step.",
    enlaceListado: "Preferred MLS or full listing link",
    enlaceListadoHint: "If empty: listing from “Basic information”.",
    enlaceMls: "Preferred MLS link (dedicated destination)",
    enlaceMlsHint: "If empty: same as “full listing” or basic listing.",
    enlaceTour: "Preferred tour link",
    enlaceTourHint: "If empty: tour from “Photos & media”.",
    enlaceFolleto: "Preferred brochure link",
    enlaceFolletoHint: "If empty: brochure from “Photos & media”.",
    interruptores: "Toggles",
    interruptoresSub:
      "Turn on only the buttons you want in the preview and the published listing. Each button uses the preferred destination you entered above; if you did not set one for that action, the corresponding fallback applies. “Show social icons” needs at least one link in the primary agent social fields (“Professional profile”).",
    ctaSolicitar: "Request information",
    ctaVisita: "Schedule visit",
    ctaLlamar: "Call",
    ctaWa: "WhatsApp",
    ctaWeb: "View website",
    ctaRedes: "Show social icons",
    ctaListado: "View full listing",
    ctaMls: "View MLS",
    ctaTour: "View tour",
    ctaFolleto: "View brochure",
  },
  step09: {
    title: "Optional extras",
    sub: "Optional; only appears in the preview when there is data.",
    openHouse: "Open house",
    fecha: "Date",
    horaInicio: "Start time",
    horaFin: "End time",
    notasOh: "Notes",
    agregarOpenHouse: "Add open house date",
    eliminarFecha: "Remove this date",
  },
  previewUi: {
    meta: "Listing preview",
    badge: "Preview · Business",
    volverEditar: "Back to edit",
    galeria: "Gallery",
    fotoPrincipal: "Main photo",
    foto2: "Photo 2",
    foto3: "Photo 3",
    video: "Video",
    reproducirVideo: "Play video",
    tourVirtual: "Virtual tour",
    planoFolleto: "Floor plan / brochure",
    tourPlano: "Tour / plan",
    abrirTour: "Open tour",
    abrirPlano: "Open plan / brochure",
    verTodasFotos: (n: number) => `View all photos (${n})`,
    slotPrincipal: "Main photo",
    slotPrincipalSub: "Add photos in the form.",
    slot2: "Photo 2",
    opcional: "Optional",
    slotVideoTitle: "Video",
    slotVideoSub: "Paste a link or upload a file.",
    slotTour: "Tour / plan",
    slotTourSub: "Link or file (tour or brochure).",
    verMapa: "View on map",
    fotoAgente: "Agent photo",
    sitioWeb: "Website",
    area: "Area:",
    idiomas: "Languages:",
    llamar: "Call now",
    whatsapp: "WhatsApp",
    solicitarInfo: "Request information",
    programarVisita: "Schedule visit",
    verSitioWeb: "View website",
    verListado: "View full listing",
    verMls: "View MLS",
    verTour: "View tour",
    verFolleto: "View brochure",
    brokerAsesor: "Broker / advisor",
    detallesPropiedad: "Property details",
    caracteristicas: "Highlighted features",
    descripcion: "Description",
    notasAdicionales: "Additional notes",
    masInfo: "More information",
    openHouse: "Open house",
    contactoFin: "Lending contact",
    ubicacionAprox: "Approximate location",
    abrirMapa: "Open in map",
    emptySlotPdf: "file.pdf",
    licenciaAgente: "License or professional ID:",
    licenciaMarca: "Office license:",
    telPersonal: "Personal phone",
    telOficina: "Office phone",
    enlaceGenerico: "Link",
    notaVerTodasFotos: "When published, this control opens the full gallery.",
    lightboxClose: "Close",
    lightboxPrev: "Previous",
    lightboxNext: "Next",
    lightboxVideo: "Video",
    lightboxZoomHint: "Ctrl + scroll to zoom",
    lightboxResetZoom: "Reset",
    lightboxOpenVideoTab: "Open video in a new tab",
    lightboxGalleryCount: (cur: number, total: number) => `Gallery · ${cur} / ${total}`,
    footerDefault: "Leonix is a premium showcase: the official listing may be on your MLS or website.",
  },
  previewFormat: {
    opLine: "Residential sale",
    estados: {
      disponible: "Available",
      pendiente: "Pending",
      bajo_contrato: "Under contract",
      vendido: "Sold",
    },
    condicion: {
      excelente: "Excellent",
      buena: "Good",
      regular: "Fair",
      necesita_reparacion: "Needs work",
    },
    detalleTipo: "Property type",
    detalleRecamaras: "Bedrooms",
    detalleBanos: "Baths",
    detalleMedios: "Half baths",
    detalleInterior: "Interior size",
    detalleLote: "Lot size",
    detalleEstac: "Parking",
    detalleAno: "Year built",
    detalleCond: "Condition",
    qfRec: "Beds",
    qfBan: "Baths",
    qfInt: "Interior (sq ft)",
    qfEst: "Parking",
    qfAno: "Year",
    qfLote: "Lot (sq ft)",
  },
} as const;
