/** Spanish (default) strings — BR Negocio agente individual residencial publish + preview chrome. */
export const BR_COPY_ES = {
  stepLabels: [
    "Tipo de anuncio",
    "Información básica",
    "Fotos y medios",
    "Detalles esenciales",
    "Características destacadas",
    "Descripción",
    "Información profesional",
    "Contacto y destinos de botones",
    "Extras opcionales",
    "Vista previa",
  ],
  app: {
    kicker: "Leonix Clasificados · Negocio",
    title: "Publicar Bienes Raíces — Agente",
    subtitle:
      "Leonix es una vitrina premium: el listado oficial sigue en tu MLS o sitio web. Completa los pasos y revisa la vista previa fija antes de publicar.",
    navPasos: "Pasos",
    cambiarCanal: "Cambiar canal",
    verCategoria: "Ver categoría BR",
    pasoDe: "Paso",
    de: "de",
    anterior: "Anterior",
    siguiente: "Siguiente",
    vistaPreviaTitulo: "Vista previa",
    vistaPreviaBody:
      "Abre la vista previa con tus datos actuales. Puedes volver a editar sin perder el borrador en esta sesión.",
    verVistaPrevia: "Ver vista previa",
  },
  step01: {
    title: "Tipo de anuncio",
    subResidencial: "Residencial en Leonix: una vitrina clara para compradores. Esta ruta es solo venta.",
    subComercial: "Comercial en Leonix: vitrina para espacios de negocio. Esta ruta es solo venta.",
    subTerreno: "Terrenos y lotes en Leonix: parcelas claras para compradores. Esta ruta es solo venta.",
    tipoPublicacion: "Tipo de publicación",
    tipoPublicacionHintResidencial: "Fijo en esta variante: solo venta residencial.",
    tipoPublicacionHintComercial: "Fijo en esta variante: solo venta comercial.",
    tipoPublicacionHintTerreno: "Fijo en esta variante: solo venta de terreno o lote.",
    ventaResidencial: "Venta residencial",
    ventaComercial: "Venta comercial",
    ventaTerreno: "Venta terreno / lote",
    tipoPropiedad: "Tipo de propiedad",
    tipoComercial: "Tipo comercial",
    tipoTerreno: "Tipo de terreno / lote",
    especificaTipo: "Especifica el tipo de propiedad",
    especificaTipoHint: "Se muestra en el anuncio como tipo de propiedad.",
    subtipo: "Subtipo (opcional)",
    subtipoHint: "Detalle según el tipo elegido (por ejemplo penthouse o planta baja). No es obligatorio.",
    detalleAdicional: "Detalle adicional (opcional)",
    detalleAdicionalHint: "Si quieres añadir una nota corta sobre el tipo o la distribución.",
  },
  step02: {
    title: "Información básica",
    sub: "Datos que verán primero los compradores en la vista previa.",
    titulo: "Título del anuncio",
    precio: "Precio",
    precioHint: "Usa números; en la vista previa se muestra en dólares.",
    estadoAnuncio: "Estado del anuncio",
    estadoAnuncioHint: "Indica si sigue disponible, pendiente, bajo contrato o vendido.",
    ciudad: "Ciudad",
    ciudadHint: "Empieza a escribir para ver sugerencias, o ingresa cualquier ciudad manualmente.",
    ciudadPlaceholder: "Ej. San Jose, Los Ángeles, Ciudad de México…",
    area: "Zona / colonia",
    areaHint: "La zona general donde se ubica la propiedad.",
    direccion: "Calle y número",
    direccionHint: "Número y nombre de la calle (sin unidad).",
    direccionUnidad: "Unidad / apt / suite / espacio",
    direccionUnidadHint: "Opcional: Space B, Apt 2, Suite 100, Lote A, etc.",
    direccionPais: "País",
    direccionPaisHint: "Elige o escribe el país donde se ubica la propiedad.",
    direccionEstado: "Estado / provincia / región",
    direccionEstadoHint: "Para anuncios en Estados Unidos, elige el estado.",
    direccionEstadoHintIntl: "Ingresa el estado, provincia o región.",
    direccionCodigoPostal: "ZIP / código postal",
    direccionCodigoPostalHint: "ZIP de EE.UU. o código postal internacional.",
    direccionCodigoPostalHintIntl: "ZIP de EE.UU. o código postal internacional.",
    precioPreview: (formatted: string) => `Vista previa: ${formatted}`,
    mostrarDireccionExacta: "Mostrar dirección completa en vista previa y mapa",
    mostrarDireccionExactaHint:
      "Desactivado por defecto: solo ciudad/área alimentan el mapa público. Actívalo solo si quieres que la calle aparezca en la vista previa.",
    listado: "Enlace o archivo del listado",
    listadoHint:
      "Así el comprador puede ver más detalles en tu publicación original sin llenar demasiado este anuncio.",
    pegarUrl: "Pegar URL",
    subirPdf: "Subir PDF o archivo",
    archivo: "Archivo:",
    adjunto: "adjunto",
    quitar: "Quitar",
    estados: { disponible: "Disponible", pendiente: "Pendiente", bajo_contrato: "Bajo contrato", vendido: "Vendido" },
  },
  step03: {
    title: "Fotos y medios",
    sub: "La imagen principal es la portada. Video, tour y folleto se usan en la vista previa cuando activas los botones correspondientes.",
    fotos: "Fotos",
    imageUploadNoteLabel: "NOTA:",
    imageUploadNoteLine1: "La imagen 1 es la foto principal de tu anuncio.",
    imageUploadNoteLine2: "Las imágenes 2–7 son la galería para la tarjeta de resultados.",
    imageUploadNoteLine3:
      "Estas imágenes ayudan a mostrar esta propiedad en resultados de búsqueda y vistas previas.",
    agregarFotos: "Agregar fotos",
    portada: "Imagen principal (portada)",
    portadaHint: "Elige cuál foto es la portada.",
    fotoN: (n: number) => `Foto ${n}`,
    moverIzq: "Mover izquierda",
    moverDer: "Mover derecha",
    eliminar: "Eliminar",
    archivoSubido: "Archivo subido correctamente.",
    archivoListoPublicar: "Archivo listo para publicar.",
    videoListoPublicar: "Video listo para publicar.",
    usarUrl: "Usar URL",
    video: "Video (opcional)",
    videoHint:
      "Solo enlace público (YouTube, Vimeo, TikTok, Instagram, etc.). Hasta 4 URLs de video.",
    addVideo: "Añadir video",
    videoAdded: "Video añadido",
    videoUrlLabel: (n: number) => (n === 1 ? "URL de video" : `URL de video ${n}`),
    tour: "Tour virtual / 3D (opcional)",
    tourHint:
      "Enlace a Matterport, tour 360, recorrido virtual u otra URL pública de tour. Solo pega la URL — sin subir archivos del dispositivo.",
    folleto: "Folleto / documento (opcional)",
    folletoHint:
      "PDF, Word o imagen de folleto/plano. Se enlaza con «Ver folleto» en la vista previa. Tipos permitidos: PDF, DOC/DOCX, JPG/PNG.",
  },
  step04: {
    title: "Detalles esenciales",
    sub: "Sólo lo que ayuda al comprador a decidir.",
    recamaras: "Recámaras",
    banos: "Baños completos",
    mediosBanos: "Medios baños",
    mediosHint: "Opcional.",
    tamanoInterior: "Tamaño interior",
    tamanoInteriorHint: "Pies cuadrados aproximados.",
    tamanoLote: "Tamaño del lote",
    tamanoLoteHint: "Si aplica; si no, déjalo vacío.",
    estacionamientos: "Estacionamientos",
    ano: "Año de construcción",
    condicion: "Condición de la propiedad",
    condicionHint: "Estado general al momento de publicar.",
    usoComercial: "Uso comercial",
    usoComercialHint: "Ej. retail, consultorio, showroom.",
    oficinasComercial: "Oficinas",
    oficinasComercialHint: "Cantidad aproximada si aplica.",
    nivelesComercial: "Niveles / pisos",
    nivelesComercialHint: "Si aplica.",
    zonificacionComercial: "Zonificación",
    zonificacionComercialHint: "Si aplica.",
    accesoCarga: "Acceso de carga",
    accesoCargaHint: "Marca si hay muelle, rampa o acceso para carga.",
    usoZonificacionTerreno: "Uso / zonificación",
    usoZonificacionTerrenoHint: "Zona, uso permitido o referencias.",
    accesoTerreno: "Acceso",
    accesoTerrenoHint: "Tipo de acceso o vialidad.",
    serviciosTerreno: "Servicios disponibles",
    serviciosTerrenoHint: "Agua, luz, alcantarillado, etc.",
    topografiaTerreno: "Topografía",
    topografiaTerrenoHint: "Opcional.",
    listoConstruirTerreno: "Listo para construir",
    cercadoTerreno: "Cercado",
  },
  step05: {
    title: "Características destacadas",
    sub: "Marca lo que quieres mostrar en la vista previa.",
  },
  step06: {
    title: "Descripción",
    principal: "Descripción principal",
    principalHint:
      "Describe la propiedad, el espacio, las reglas importantes y lo que debe saber la persona interesada.",
    notas: "Notas adicionales (opcional)",
    notasHint: "Mensaje corto o detalle interno; no es el cuerpo principal.",
  },
  step07: {
    title: "Información profesional",
    sub: "Aquí queda el contacto principal de tu negocio o agente; cada campo corresponde a un espacio fijo en la vista previa.",
    agente: "Agente",
    fotoAgente: "Foto del agente",
    fotoAgenteHint: "Sube una imagen o pega una URL pública.",
    nombre: "Nombre completo",
    titulo: "Título",
    licencia: "Licencia o número profesional",
    licenciaHint: "Si aplica en tu estado.",
    telefonoPersonal: "Teléfono personal",
    telefonoOficina: "Teléfono de oficina",
    whatsapp: "WhatsApp",
    whatsappHint: "Solo para el botón de WhatsApp; no sustituye a los teléfonos de llamada.",
    numeroPrincipalLlamadas: "Número principal para llamadas",
    principalPersonal: "Personal",
    principalOficina: "Oficina",
    correoAgente: "Correo electrónico",
    sitioWebAgente: "Sitio web",
    sitioWebAgenteHint:
      "Tu sitio como agente (el botón «Ver sitio web» usa primero el enlace preferido de «Contacto y destinos de botones», luego este, luego el de oficina/marca).",
    mostrarMarca: "Mostrar oficina o marca en la tarjeta",
    mostrarMarcaHint: "Si está desactivado, la vista previa no muestra el bloque de marca aunque haya datos guardados.",
    oficina: "Oficina o marca",
    nombreMarca: "Nombre de oficina o marca",
    logo: "Logo de oficina o marca",
    logoHint: "Imagen o URL; se muestra arriba de tu foto en la vista previa.",
    licenciaMarca: "Licencia de broker u oficina (opcional)",
    sitioMarca: "Sitio web de oficina o marca (opcional)",
    sitioMarcaHint: "Enlace breve bajo el nombre de la marca en la tarjeta.",
    redes: "Redes sociales",
    redesSub: "Un enlace por red; cada icono en la vista previa usa solo su campo.",
    subirImagen: "Subir imagen",
    pegarUrlImagen: "Pegar URL de imagen",
    subirArchivo: "Subir archivo",
    pegarUrl: "Pegar URL",
    instagram: "Instagram",
    facebook: "Facebook",
    youtube: "YouTube",
    tiktok: "TikTok",
    x: "X / Twitter",
    linkedin: "LinkedIn",
    snapchat: "Snapchat",
    googleBusiness: "Perfil de Google Business (URL)",
    googleBusinessHint: "Opcional. Enlace público de tu perfil de negocio en Google.",
    googleReviews: "Opiniones en Google (URL)",
    googleReviewsHint: "Opcional. Enlace directo a tus reseñas en Google.",
    yelpReviews: "Opiniones en Yelp (URL)",
    yelpReviewsHint: "Opcional. Enlace a tu perfil o reseñas en Yelp.",
    enlaceSocialAdicional: "Enlace social adicional (opcional)",
    enlacesNegocio: "Enlaces adicionales del negocio",
    enlacesNegocioSub: "URLs opcionales de perfil, portafolio, reseñas o negocio. Se muestran como botones limpios solo si tienen datos.",
    addLink: "Añadir enlace",
    linkAdded: "Enlace añadido",
    businessUrlLabel: (n: number) => (n === 1 ? "URL adicional del negocio" : `URL adicional del negocio ${n}`),
    areaServicio: "Área de servicio (opcional)",
    idiomas: "Idiomas (opcional)",
    idiomasPh: "Ej. inglés y español",
    segundoAgente: "Segundo agente",
    agente2Foto: "Foto del segundo agente",
    agente2FotoHint: "Sube una imagen o pega una URL pública.",
    agente2Nombre: "Nombre completo",
    agente2Titulo: "Título",
    agente2Licencia: "Licencia o número profesional",
    agente2Correo: "Correo (opcional)",
    agregarSegundoAgente: "Agregar segundo agente",
    ocultarSegundoAgente: "Ocultar",
    agregarBrokerAsesor: "Agregar financiamiento",
    ocultarBrokerAsesor: "Ocultar",
    brokerSection: "Financiamiento",
    brokerFoto: "Logo o foto (opcional)",
    brokerFotoHint: "Solo se muestra uno: logo de la compañía o foto personal.",
    enlaceProgramarVisita: "Enlace para programar visita (opcional)",
    enlaceProgramarVisitaHint: "Calendario externo (p. ej. Calendly). Se usa en el botón «Programar visita».",
    brokerNombre: "Nombre",
    brokerTitulo: "Título o rol",
    brokerLicencia: "Licencia o número",
    brokerEmail: "Correo electrónico",
    brokerSitioWeb: "Sitio web",
    brokerSitioWebHint: "Opcional",
    brokerInstagram: "Instagram",
    brokerFacebook: "Facebook",
    brokerYoutube: "YouTube",
    brokerTiktok: "TikTok",
    brokerX: "X / Twitter",
    brokerEnlaceAdicional: "Enlace adicional",
  },
  step08: {
    title: "Acciones de contacto",
    sub:
      "Los botones del anuncio se activan solos con los datos válidos que ya capturaste en pasos anteriores. Si un dato está vacío o no es válido, el botón no aparece.",
    detectedTitle: "Acciones detectadas para compradores",
    detectedHelper:
      "Estas acciones se activan automáticamente con los datos válidos que ya capturaste. Si un dato está vacío o no es válido, el botón no aparecerá.",
    detectedEmpty: "Aún no hay acciones detectadas. Completa teléfono, correo, enlaces o redes en los pasos anteriores.",
    accionesVisibles: "Acciones visibles para compradores",
    accionesVisiblesSub:
      "Activa solo los botones que quieras mostrar en la vista previa y en la publicación. Cada botón usa los datos ya capturados; sin destino válido, el botón no aparece. «Mostrar iconos de redes» requiere al menos un enlace en las redes del agente principal.",
    contactoBase: "Correo en la tarjeta",
    contactoBaseSub:
      "Los teléfonos y el WhatsApp del agente ya se guardaron en «Información profesional»; no los vuelves a capturar aquí. Solo ajustas el correo visible en la tarjeta (también editable en ese paso).",
    correo: "Correo electrónico principal",
    correoHint:
      "Se muestra en la tarjeta. El botón «Solicitar información» usa preferentemente el correo que indiques más abajo; si ese campo queda vacío, aplica como respaldo este correo principal.",
    destinos: "Destinos preferidos para cada botón",
    destinosSub:
      "Opcional: define un número, correo o enlace distinto al de tu ficha profesional para un botón concreto. Si dejas vacío un campo, se usa el respaldo descrito en la ayuda de ese campo (datos de «Información profesional» o pasos anteriores del anuncio).",
    numLlamadas: "Número preferido para llamadas",
    numLlamadasHint: "Si vacío: número principal para llamadas del agente (paso «Información profesional»).",
    numWa: "Número preferido para WhatsApp",
    numWaHint: "Si vacío: solo el campo WhatsApp del agente (paso «Información profesional»); sin número dedicado no hay botón.",
    correoInfo: "Correo preferido para solicitar información",
    correoInfoHint: "Si vacío: se usa el correo principal indicado arriba en este paso.",
    enlaceVisita: "Enlace preferido para programar visita",
    enlaceVisitaHint: "Enlace https de calendario (p. ej. Calendly). Sin enlace, no hay botón.",
    enlaceWeb: "Enlace preferido del sitio web",
    enlaceWebHint: "Botón «Ver sitio web». Si vacío: sitio del agente y luego sitio de oficina o marca (paso anterior).",
    enlaceListado: "Enlace preferido del MLS o listado completo",
    enlaceListadoHint: "Si vacío: listado de «Fotos y medios».",
    enlaceMls: "Enlace preferido del MLS (destino dedicado)",
    enlaceMlsHint: "Si vacío: mismo destino que «listado completo» o listado básico.",
    enlaceTour: "Enlace preferido del tour",
    enlaceTourHint: "Si vacío: tour de «Fotos y medios».",
    enlaceFolleto: "Enlace preferido del folleto",
    enlaceFolletoHint: "Si vacío: folleto de «Fotos y medios».",
    interruptores: "Acciones visibles para compradores",
    interruptoresSub:
      "Activa solo los botones que quieras mostrar en la vista previa y en la publicación. Cada botón usa los datos ya capturados; sin destino válido, el botón no aparece.",
    ctaSolicitar: "Solicitar información",
    ctaVisita: "Programar visita",
    ctaLlamar: "Llamar",
    ctaWa: "WhatsApp",
    ctaWeb: "Ver sitio web",
    ctaRedes: "Mostrar iconos de redes",
    ctaListado: "Ver listado completo",
    ctaMls: "Ver MLS",
    ctaTour: "Ver tour",
    ctaFolleto: "Ver folleto",
  },
  step09: {
    title: "Extras opcionales",
    sub: "Opcional; sólo aparece en la vista previa si hay datos.",
    openHouse: "Open house",
    fecha: "Fecha",
    horaInicio: "Hora inicio",
    horaFin: "Hora fin",
    notasOh: "Notas",
    agregarOpenHouse: "Agregar fecha de open house",
    eliminarFecha: "Quitar esta fecha",
  },
  previewUi: {
    meta: "Vista previa del anuncio",
    badge: "Vista previa · Negocio",
    volverEditar: "Volver a editar",
    galeria: "Galería",
    fotoPrincipal: "Foto principal",
    foto2: "Foto 2",
    foto3: "Foto 3",
    video: "Video",
    reproducirVideo: "Reproducir video",
    tourVirtual: "Tour virtual",
    planoFolleto: "Plano / folleto",
    tourPlano: "Tour / plano",
    abrirTour: "Abrir tour",
    abrirPlano: "Abrir plano / folleto",
    verTodasFotos: (n: number) => `Ver todas las fotos (${n})`,
    slotPrincipal: "Foto principal",
    slotPrincipalSub: "Agrega fotos en el formulario.",
    slot2: "Foto 2",
    opcional: "Opcional",
    slotVideoTitle: "Video",
    slotVideoSub: "Pega un enlace público de video.",
    slotTour: "Tour / plano",
    slotTourSub: "Enlace o archivo (tour o folleto).",
    verMapa: "Ver en mapa",
    fotoAgente: "Foto del agente",
    sitioWeb: "Sitio web",
    area: "Área:",
    idiomas: "Idiomas:",
    llamar: "Llamar ahora",
    whatsapp: "WhatsApp",
    solicitarInfo: "Solicitar información",
    programarVisita: "Programar visita",
    verSitioWeb: "Ver sitio web",
    verListado: "Ver listado completo",
    verMls: "Ver MLS",
    verTour: "Ver tour",
    verFolleto: "Ver folleto",
    brokerAsesor: "Financiamiento",
    financingDisclaimer:
      "Información proporcionada por el anunciante. Leonix no garantiza aprobación, tasas ni términos.",
    masInformacion: "Más información",
    detallesPropiedad: "Detalles de la propiedad",
    caracteristicas: "Características destacadas",
    descripcion: "Descripción",
    notasAdicionales: "Notas adicionales",
    masInfo: "Más información",
    openHouse: "Open house",
    contactoFin: "Contacto de financiamiento",
    ubicacionAprox: "Ubicación aproximada",
    abrirMapa: "Abrir en mapa",
    emptySlotPdf: "archivo.pdf",
    licenciaAgente: "Licencia o número profesional:",
    licenciaMarca: "Licencia de oficina:",
    telPersonal: "Teléfono personal",
    telOficina: "Teléfono de oficina",
    enlaceGenerico: "Enlace",
    notaVerTodasFotos: "En el anuncio publicado, este control abre la galería completa.",
    lightboxClose: "Cerrar",
    lightboxPrev: "Anterior",
    lightboxNext: "Siguiente",
    lightboxVideo: "Video",
    lightboxZoomHint: "Ctrl + rueda para ampliar",
    lightboxResetZoom: "Restablecer",
    lightboxOpenVideoTab: "Abrir video en una pestaña nueva",
    lightboxGalleryCount: (cur: number, total: number) => `Galería · ${cur} / ${total}`,
    footerDefault:
      "Leonix es una vitrina premium: el listado oficial puede estar en tu MLS o sitio web.",
    officeBrokerLabel: "Oficina / Broker",
    mainAgentLabel: "Agente principal",
    secondAgentLabel: "Segundo agente",
    quickActionsLabel: "Acciones rápidas",
    googleBusiness: "Google Business",
    googleReviews: "Opiniones en Google",
    yelpReviews: "Opiniones en Yelp",
    businessHubReviews: "Opiniones",
  },
  previewFormat: {
    opLine: "Venta residencial",
    estados: {
      disponible: "Disponible",
      pendiente: "Pendiente",
      bajo_contrato: "Bajo contrato",
      vendido: "Vendido",
    },
    condicion: {
      excelente: "Excelente",
      buena: "Buena",
      regular: "Regular",
      necesita_reparacion: "Necesita reparación",
    },
    detalleTipo: "Tipo de propiedad",
    detalleRecamaras: "Recámaras",
    detalleBanos: "Baños",
    detalleMedios: "Medios baños",
    detalleInterior: "Tamaño interior",
    detalleLote: "Tamaño del lote",
    detalleEstac: "Estacionamientos",
    detalleAno: "Año de construcción",
    detalleCond: "Condición",
    qfRec: "Recámaras",
    qfBan: "Baños",
    qfInt: "Interior (ft²)",
    qfEst: "Estacionamientos",
    qfAno: "Año",
    qfLote: "Lote (ft²)",
  },
} as const;
