import type { AdminAffiliateOffer } from "./adminViajesAffiliateTypes";

export const ADMIN_VIAJES_AFFILIATE_OFFERS_MOCK: AdminAffiliateOffer[] = [
  {
    id: "aff-001",
    partnerName: "Bay Travel Co.",
    headline: "Cancún resort — todo incluido",
    destination: "Quintana Roo, MX",
    departureContext: "SFO · SJO",
    offerType: "Resort / paquete",
    priceFrom: "$589 pp",
    duration: "5d / 4n",
    affiliateLabel: "Socio comercial",
    expiryDate: "2026-08-31",
    status: "live",
    featured: true,
    featuredRank: 1,
    placements: ["top_offers_week", "homepage_featured", "results_eligible", "seasonal_campaign"],
    lastUpdated: "2026-04-02",
    publicSlug: "cancun-resort-mar",
  },
  {
    id: "aff-002",
    partnerName: "Pura Vida Escapes",
    headline: "Riviera Maya spa + snorkel",
    destination: "Playa del Carmen",
    departureContext: "SFO",
    offerType: "Paquete",
    priceFrom: "$729 pp",
    duration: "6d / 5n",
    affiliateLabel: "Temporada",
    expiryDate: "2026-09-15",
    status: "live",
    featured: true,
    featuredRank: 2,
    placements: ["top_offers_week", "destination_collections", "audience_romantic"],
    lastUpdated: "2026-04-01",
    publicSlug: "riviera-todo-incluido",
  },
  {
    id: "aff-003",
    partnerName: "Island Routes",
    headline: "Maui boutique week",
    destination: "Maui, HI",
    departureContext: "SFO",
    offerType: "Resort",
    priceFrom: "$1,120 pp",
    duration: "7d / 6n",
    affiliateLabel: "Agencia aliada",
    expiryDate: null,
    status: "draft",
    featured: false,
    featuredRank: 0,
    placements: ["homepage_featured"],
    lastUpdated: "2026-03-28",
    publicSlug: "maui-boutique",
  },
  {
    id: "aff-004",
    partnerName: "DriveAway Partners",
    headline: "SUV rental — Cancún airport",
    destination: "Cancún",
    departureContext: "CUN",
    offerType: "Renta de autos",
    priceFrom: "$42 / día",
    duration: "Flexible",
    affiliateLabel: "Socio comercial",
    expiryDate: "2026-05-01",
    status: "paused",
    featured: false,
    featuredRank: 0,
    placements: ["car_rental", "results_eligible"],
    lastUpdated: "2026-03-15",
  },
  {
    id: "aff-005",
    partnerName: "Spring Break Collective",
    headline: "Cabo long weekend",
    destination: "Los Cabos",
    departureContext: "OAK · SFO",
    offerType: "Escapada",
    priceFrom: "$499 pp",
    duration: "4d / 3n",
    affiliateLabel: "Oferta de temporada",
    expiryDate: "2026-03-20",
    status: "expired",
    featured: false,
    featuredRank: 0,
    placements: ["seasonal_campaign", "audience_group"],
    lastUpdated: "2026-03-10",
  },
];

export function getAdminAffiliateOfferById(id: string): AdminAffiliateOffer | undefined {
  return ADMIN_VIAJES_AFFILIATE_OFFERS_MOCK.find((r) => r.id === id);
}
