import type { AdminViajesBusinessOfferRow } from "./adminViajesBusinessOffersTypes";

export const ADMIN_VIAJES_BUSINESS_OFFERS_MOCK: AdminViajesBusinessOfferRow[] = [
  {
    id: "biz-offer-001",
    businessName: "Viajes del Valle",
    headline: "Guanacaste · 5 noches todo incluido",
    destination: "Guanacaste, CR",
    status: "pending",
    submittedAt: "2026-04-06",
    validThrough: "2026-06-01",
    reviewNotes: "Verify WhatsApp matches site footer.",
    trustFlags: ["first_listing", "high_value"],
    businessProfileSlug: "viajes-del-valle",
    firstTimeAdvertiser: true,
    publicOfferSlug: null,
    websiteProvided: true,
    whatsappProvided: true,
    imageModeration: "pending",
  },
  {
    id: "biz-offer-002",
    businessName: "Pura Vida Escapes",
    headline: "Arenal + Monteverde express",
    destination: "La Fortuna, CR",
    status: "needs_edits",
    submittedAt: "2026-04-02",
    validThrough: "2026-05-15",
    reviewNotes: "Ask for clearer cancellation policy on card.",
    trustFlags: ["needs_social_proof"],
    businessProfileSlug: "pura-vida-escapes",
    firstTimeAdvertiser: false,
    publicOfferSlug: null,
    websiteProvided: true,
    whatsappProvided: false,
    imageModeration: "flagged",
  },
  {
    id: "biz-offer-003",
    businessName: "Bay Travel Co.",
    headline: "Cartago highlands weekend",
    destination: "Cartago, CR",
    status: "approved",
    submittedAt: "2026-03-20",
    validThrough: "2026-12-31",
    reviewNotes: "OK — profile verified last quarter.",
    trustFlags: ["verified_profile"],
    businessProfileSlug: "bay-travel-co",
    firstTimeAdvertiser: false,
    publicOfferSlug: "roma-venecia-express",
    websiteProvided: true,
    whatsappProvided: true,
    imageModeration: "ok",
  },
  {
    id: "biz-offer-004",
    businessName: "Costa Azul Tours",
    headline: "Último minuto · Manuel Antonio",
    destination: "Quepos, CR",
    status: "rejected",
    submittedAt: "2026-03-28",
    validThrough: null,
    reviewNotes: "Pricing inconsistent with landing page.",
    trustFlags: ["policy_mismatch"],
    businessProfileSlug: null,
    firstTimeAdvertiser: true,
    publicOfferSlug: null,
    websiteProvided: false,
    whatsappProvided: true,
    imageModeration: "ok",
  },
];
