import type { AdminViajesBusinessRow } from "./adminViajesBusinessesTypes";

export const ADMIN_VIAJES_BUSINESSES_MOCK: AdminViajesBusinessRow[] = [
  {
    id: "biz-prof-001",
    businessName: "Viajes del Valle",
    profileStatus: "active",
    destinationsServed: ["Guanacaste", "Nicoya"],
    languages: ["Español", "English"],
    contactSummary: "Web + WhatsApp",
    offersCount: 3,
    trustPlaceholder: "Site matches WHOIS org",
    plan: "plus",
    publicProfileSlug: "viajes-del-valle",
  },
  {
    id: "biz-prof-002",
    businessName: "Pura Vida Escapes",
    profileStatus: "pending_review",
    destinationsServed: ["Arenal", "Monteverde"],
    languages: ["Español"],
    contactSummary: "Email + phone",
    offersCount: 1,
    trustPlaceholder: "Awaiting social verification",
    plan: "standard",
    publicProfileSlug: "pura-vida-escapes",
  },
  {
    id: "biz-prof-003",
    businessName: "Bay Travel Co.",
    profileStatus: "active",
    destinationsServed: ["Cartago", "Turrialba"],
    languages: ["Español", "English"],
    contactSummary: "WhatsApp priority",
    offersCount: 5,
    trustPlaceholder: "Verified Q1 2026",
    plan: "plus",
    publicProfileSlug: "bay-travel-co",
  },
  {
    id: "biz-prof-004",
    businessName: "Costa Azul Tours",
    profileStatus: "paused",
    destinationsServed: ["Manuel Antonio"],
    languages: ["Español"],
    contactSummary: "WhatsApp only",
    offersCount: 0,
    trustPlaceholder: "Paused — policy review",
    plan: "standard",
    publicProfileSlug: null,
  },
];
