import type { AdminLang } from "@/app/admin/_lib/adminI18nCookie";

/** Flat admin UI strings (chrome only). */
const EN: Record<string, string> = {
  "shell.leonixBrand": "Leonix",
  "shell.globalAdmin": "Global admin",
  "shell.leonixAdmin": "Leonix admin",
  "shell.signedInCookie": "Signed in via cookie",
  "shell.websiteSectionsLink": "Website sections (workspaces)",
  "shell.globalSiteSettingsLink": "Global site settings",
  "shell.viewSite": "View site →",
  "shell.searchListingsPlaceholder": "Search listings (title, city, ID)…",
  "shell.searchListingsTitle": "Open Clasificados workspace with this text as the filter",
  "shell.searchLabel": "Search",
  "shell.plusBadge": "✦ Leonix +admin",
  "shell.createClasificadosTitle": "Open the Clasificados queue (moderation and links)",
  "shell.create": "+ Create",
  "shell.tiendaTitleUnread": "Tienda (hub · inbox with alerts)",
  "shell.tiendaTitle": "Tienda — command center",
  "shell.tiendaAriaUnread": "Tienda, {n} unread",
  "shell.langAria": "Admin interface language",
  "shell.langEn": "English",
  "shell.langEs": "Spanish",
  "mobile.openMenu": "Open admin menu",
  "mobile.menuTitle": "Menu: Dashboard, users, workspaces…",
  "mobile.navDialog": "Admin navigation",
  "mobile.closeOverlay": "Close menu",
  "mobile.close": "Close",
  "mobile.globalNav": "Global administration",
  "workspaceNav.kicker": "Website sections",
  "workspaceNav.sub": "Admin-only workspaces — not the public menu.",
  "workspaceNav.overview": "Overview",
  "workspaceNav.aria": "Website section workspaces",
  "workspaceNav.link.home": "Home",
  "workspaceNav.link.clasificados": "Clasificados",
  "workspaceNav.link.packageEntitlements": "Package entitlements",
  "workspaceNav.packageEntitlements.hint": "Print-to-Digital package access generator (not public coupon CMS)",
  "workspaceNav.link.tienda": "Tienda",
  "workspaceNav.link.nosotros": "Nosotros",
  "workspaceNav.link.revista": "Revista",
  "workspaceNav.link.contacto": "Contacto",
  "workspaceNav.link.noticias": "Noticias",
  "workspaceNav.link.iglesias": "Iglesias",
  "workspaceNav.link.cupones": "Cupones",
  "workspaceNav.link.anunciate": "Advertise",
  "nav.dashboard": "Dashboard",
  "nav.categories": "Categories",
  "nav.tienda": "Tienda",
  "nav.siteSections": "Site sections",
  "nav.viajes": "Viajes",
  "nav.users": "Users",
  "nav.customerOps": "Customer ops",
  "nav.payments": "Payments",
  "nav.support": "Support",
  "nav.team": "Team",
  "nav.activityLog": "Activity Log",
  "nav.settings": "Settings",
  "nav.languageAudit": "Language audit",
  "workspaceNav.home.hint": "Public route /home (magazine) — not the root / screen",
  "workspaceNav.clasificados.hint": "Ad moderation in Supabase",
  "workspaceNav.tienda.hint": "Storefront /tienda + catalog and orders links",
  "workspaceNav.nosotros.hint": "Public page /about",
  "workspaceNav.revista.hint": "Manifest editions.json + internal notes",
  "workspaceNav.contacto.hint": "Page /contacto (global form)",
  "workspaceNav.noticias.hint": "Shell in site_section_content; RSS stays in API",
  "workspaceNav.iglesias.hint": "Copy in site_section_content; directory backlog",
  "workspaceNav.cupones.hint": "cupones_page → /cupones and /coupons",
  "workspaceNav.anunciate.hint": "Map to publish funnel (Clasificados) + admin queue; not CRM",
  "common.and": "and",
  "common.apply": "Apply",
  "common.clear": "Clear",
  "common.applyFilters": "Apply filters",
  "common.allCategories": "All categories",
  "common.allStatuses": "All statuses",
  "common.rows": "rows",
  "cta.viewAds": "View ads",
  "cta.viewAdsTitle": "Open this category’s ad queue in the admin workspace",
  "cta.viewQueue": "View queue",
  "cta.viewQueueTitle": "Open this category’s operational queue in the admin workspace",
  "cta.liveListingsPrimary": "Live listings",
  "cta.liveListingsPrimaryTitle": "Admin list of published/live rows for this category (not the public marketplace page)",
  "cta.liveListingsAltLabel": "Public listings",
  "cta.liveListingsAltTitle": "Same admin operational list — alternate label",
  "scopeNav.aria": "Switch between full queue and live-only listings",
  "scopeNav.queue": "Ad queue",
  "scopeNav.queueTitle": "Full operational queue: moderation, drafts, and published rows",
  "scopeNav.live": "Live listings",
  "scopeNav.liveTitle": "Only rows that are publicly live right now",
  "listingsCategoryOps.titleQueue": "{slug} — operational queue",
  "listingsCategoryOps.titleLive": "{slug} — live / public listings",
  "listingsCategoryOps.subQueue": "Full category table in admin (moderation + drafts + published). Use Live for what shoppers see now.",
  "listingsCategoryOps.subLive": "Only rows that are publicly live (published + active). Restore/republish rules unchanged.",
  "listingsCategoryOps.searchTitle": "Filter queue",
  "clasificados.title": "Clasificados — operations center",
  "clasificados.subtitle":
    "Above: category map (code schema + Supabase posture). Below: the global listings queue with filters — moderation, reports, and En Venta live here.",
  "clasificados.eyebrow": "Workspace · Clasificados",
  "clasificados.helper":
    "Pick a category for plans, fields, and shortcuts — or scroll to the queue. Postgres (up to {limit} rows): title, city, description, id, owner. BR/Rentas refine client-side via detail_pairs.",
  "clasificados.detailPairsMissingTitle": "Database missing listings.detail_pairs column.",
  "clasificados.detailPairsMissingBody":
    "Queue loads in reduced mode: the “En venta · vis.” column cannot show plan / renewal until you migrate. Apply migration",
  "clasificados.boostMissingTitle": "Database missing listings.republished_at column.",
  "clasificados.boostMissingBody":
    "Queue loads without republish timestamps; “En venta · vis.” shows plan and lastRenew but not last move-to-top until you migrate. Apply",
  "clasificados.homeChipsTitle": "Featured on `/home`:",
  "clasificados.homeChipsBody":
    "They are not auto-generated from this queue. In Home → content you can manually link categories or public routes (chips). Here you moderate ads in Supabase.",
  "clasificados.homeContentCta": "Home → content",
  "clasificados.brHintTitle": "Real-estate branches (BR / Rentas):",
  "clasificados.brHintBody":
    "When listings live in listings, use category and detail_pairs to distinguish sale vs rent, private vs business, and property type. Publish preview is not a public listing:",
  "clasificados.autosCta": "Autos (Leonix payments) →",
  "clasificados.autosTitle": "Table autos_classifieds_listings: payment and publish state on /clasificados/autos",
  "clasificados.serviciosCta": "Servicios (Supabase) →",
  "clasificados.serviciosTitle": "Queue Supabase: servicios_public_listings (sandbox tiers is separate)",
  "clasificados.categoriesCta": "Advanced registry →",
  "clasificados.categoriesAdvancedTitle": "Open advanced category registry (table + Supabase saves)",
  "clasificados.categoriesTitle": "Visibility, order, and operational status (site_category_config)",
  "clasificados.reportesCta": "Reports →",
  "clasificados.reportesTitle": "Listing reports queue (listing_reports)",
  "clasificados.filterHint":
    "Search q: Leonix Ad ID (if column exists), listing or owner UUID, title, city, description, slug/URL, and profile match on owner name/email/phone. Respects category. BR/Rentas refine client-side on detail_pairs. limit 50–500 (default 300).",
  "clasificados.placeholderQ": "Leonix ID, UUID, title, owner, email/phone, URL…",
  "clasificados.placeholderOwner": "Owner ID (fragment)",
  "clasificados.leonixFilters": "Leonix BR / Rentas (detail_pairs)",
  "clasificados.branchAll": "Branch (all)",
  "clasificados.operationAll": "Operation (all)",
  "clasificados.operationSale": "sale (for sale)",
  "clasificados.operationRent": "rent (for rent)",
  "clasificados.propTypeAll": "Property type (all)",
  "clasificados.limitTitle": "Maximum listings to fetch from Supabase in this view",
  "clasificados.limitAria": "Row limit",
  "clasificados.applyFiltersTitle": "Reload the queue with URL filters (read-only)",
  "clasificados.backWorkspace": "← Site sections overview",
  "clasificados.envSectionTitle": "En Venta — moderation reference",
  "clasificados.envSectionSubtitle":
    "Reference only (reason list). Does not write to the database — documentation for the team.",
  "audit.title": "Operational audit — queues by category",
  "audit.intro":
    "TRUE/FALSE values are computed when this page loads (real Supabase queries and the same helpers as the queue). If something fails, the Reason column shows the Postgres/PostgREST error or limitation.",
  "audit.th.slug": "Slug",
  "audit.th.queue": "Admin queue",
  "audit.th.source": "Source",
  "audit.th.load": "Load",
  "audit.th.search": "Search",
  "audit.th.public": "Public link",
  "audit.th.moderate": "Moderate",
  "audit.th.editAd": "Edit listing",
  "audit.th.leonixEmbedded": "Leonix ID embedded",
  "audit.th.rows": "Rows (approx.)",
  "audit.th.reason": "Reason if FALSE",
  "audit.true": "TRUE",
  "audit.false": "FALSE",
  "audit.boolTitleTrue": "Verified at page load",
  "audit.boolTitleFalse": "See reason column",
  "hub.title": "Categories — control center",
  "hub.intro":
    "Each card reflects the in-code schema key categorySchema and operational posture merged from Supabase. Open a category space for plans, fields, preview, and shortcuts to the filtered queue.",
  "hub.categoriesRegistry": "Advanced registry →",
  "hub.restLink": "Public listings table (DB)",
  "hub.editorEnVenta": "Fields & notes (DB)",
  "hub.editorOther": "Fields & notes (DB)",
  "hub.opsSpace": "Operational space",
  "hub.queueFiltered": "Ad queue",
  "hub.queueFilteredTitle": "Opens the real operational queue: dedicated vertical (Restaurantes/Servicios/Empleos/Autos) or listings queue with filter.",
  "hub.liveListingsCta": "Live listings",
  "hub.liveListingsCtaTitle": "Operational admin list of currently public/live ads for this category (scope=live)",
  "hub.standardLive": "Live standard",
  "hub.plans": "Plans",
  "hub.fields": "Fields",
  "hub.fieldGroup": "group",
  "hub.preview": "Preview",
  "hub.proPreview": "Pro preview",
  "hub.yes": "yes",
  "hub.no": "no",
  "hub.readiness": "Readiness",
  "hub.restDbLink": "Public listings table (DB)",
  "listings.col.id": "ID",
  "listings.col.leonixId": "Leonix Ad ID",
  "listings.col.title": "Title",
  "listings.col.category": "Category",
  "listings.col.city": "City",
  "listings.col.price": "Price",
  "listings.col.status": "Status",
  "listings.col.owner": "Owner",
  "listings.col.date": "Date",
  "listings.col.leonix": "Leonix",
  "listings.col.envVis": "En venta · vis.",
  "listings.col.actions": "Actions",
  "listings.actionsColumnEarlyHint":
    "Staff actions are placed before wide Leonix columns so controls stay visible without hunting horizontal scroll.",
  "listings.free": "Free",
  "listings.ownerCard": "Seller profile",
  "listings.viewPublic": "View public",
  "listings.viewRentas": "View public (Rentas)",
  "listings.inspectorRentas": "Rentas inspector",
  "listings.hidePublic": "Hide from site",
  "listings.republish": "Republish on site",
  "listings.deleteStaff": "Delete (staff)",
  "listings.emptyGlobal": "No listings match the current filters.",
  "listings.emptyCategoryTitle": "No published listings found for this category.",
  "listings.emptyCategoryBody":
    "Active filter targets public.listings.category (case-insensitive) = {slug}{rentasExtra}. Check the category dropdown for actual DB values, or open the dedicated vertical queue (Servicios, Empleos, Autos, Restaurantes) if this category stores ads outside listings.",
  "listings.emptyRentasExtra":
    ", plus merged rows with category «bienes-raices» and Leonix:operation=rent in detail_pairs when there is no text search (q).",
  "listings.col.leonixTitle": "Leonix BR/Rentas: branch, operation, category, published",
  "listings.col.envVisTitleOk": "En Venta plan and visibility (detail_pairs + republished_at)",
  "listings.col.envVisTitleNoDetailPairs":
    "detail_pairs column not available in this database — apply listings.detail_pairs migration",
  "listings.col.envVisTitleNoBoost": "republished_at column not available — apply classifieds_republish_capability migration",
  "listings.rowActionsTitle":
    "Staff actions on this row (publish/hide/delete). Text and image editing: advertiser panel with owner_id validation.",
  "listings.publicRentasTitle": "Public Rentas detail (canonical path)",
  "listings.publicGenericTitle": "Open listing on public site (new tab)",
  "listings.hidePublicTitle": "Hide from public listings (is_published=false). En Venta / results stop showing it.",
  "listings.republishTitle": "Publish again on the site (is_published=true) if status remains active.",
  "listings.deleteTitle": "Mark listing as removed in database (staff action; appears in audit)",
  "listings.deleteAria": "Mark listing as deleted in database",
  "listings.confirmDelete": "Mark this listing as removed?",
  "listings.errDelete": "Could not delete",
  "listings.confirmHide": "Hide this listing from the public site (is_published=false)? It remains visible to staff.",
  "listings.confirmShow": "Show this listing on the site again (is_published=true)?",
  "listings.errPublish": "Could not update publication",
  "listings.envLine.missingDetailPairs": "N/A · listings.detail_pairs column missing in DB",
  "listings.envLine.boostNoCol": "republish N/A (no republished_at column)",
  "listings.envLine.boostOff": "no active visibility window",
  "listings.envLine.lastRenew": "lastRenew",
  "listings.envLine.renewNd": "renew N/A",
  "listings.envLine.renewOk": "renew OK",
  "listings.envLine.renewDash": "renew —",
  "autosQueue.pageTitle": "Autos — paid listings (autos_classifieds_listings)",
  "autosQueue.pageSubtitle":
    "Leonix Autos flow (private / business lanes). “Published” means active status, visible on the public Autos API and /clasificados/autos.",
  "autosQueue.backGeneric": "← Generic listings queue",
  "autosQueue.openPublishFlow": "Open public Autos publish flow (site) ↗",
  "autosQueue.searchTitle": "Search queue",
  "autosQueue.searchHint":
    "Leonix Ad ID (if column exists), listing or user UUID, /clasificados/autos/vehiculo/… URL, vehicle text (make, model, VIN, …), title, city, and owner profile name/email/phone match.",
  "autosQueue.labelQ": "q",
  "autosQueue.placeholderQ": "UUID, URL, title, owner email…",
  "autosQueue.emptyTable":
    "No rows in autos_classifieds_listings, or the database is not configured with the service role for admin reads.",
  "autosQueue.colVia": "Lane",
  "autosQueue.colDest": "Featured",
  "autosQueue.colVis": "Visibility",
  "autosQueue.colPub": "Published at",
  "autosQueue.colImg": "Image",
  "autosQueue.colActions": "Actions",
  "autosQueue.actionsColTitle": "Operations row: public link when applicable; use staff buttons to change lifecycle status.",
  "autosQueue.viewPublic": "View public",
  "autosQueue.viewPublicTitle": "Public Autos listing. Content edits remain in the seller dashboard flow.",
  "autosQueue.yes": "yes",
  "autosQueue.no": "no",
  "autosQueue.visibilityPublic": "Public (Autos)",
  "autosQueue.visibilityPre": "Pre-publish",
  "autosQueue.visibilityInactive": "Inactive / removed",
  "autosQueue.removePublic": "Take off public",
  "autosQueue.removePublicTitle": "Set listing to removed (hidden from public Autos APIs)",
  "autosQueue.restoreActive": "Restore active",
  "autosQueue.restoreActiveTitle": "Set listing back to active with a publish timestamp",
  "dashboard.title": "Leonix Dashboard",
  "dashboard.subtitle": "Welcome back — here’s what’s happening today in operations.",
  "dashboard.helper":
    "The sidebar is global administration. To edit public sections (home, clasificados, tienda…), open Website sections below or from the menu footer.",
  "dashboard.editSectionsTitle": "Website editing (sections)",
  "dashboard.editSectionsBody":
    "Public pages are grouped under workspaces — not the same links as the live site menu. Global toggles that cross many pages live in site-wide settings.",
  "dashboard.linkWorkspaceTitle": "Public content workspaces (home, clasificados, tienda, magazine…)",
  "dashboard.linkWorkspace": "Website sections →",
  "dashboard.linkSiteSettingsTitle": "Global notices, toggles, and cross-page content",
  "dashboard.linkSiteSettings": "Global site settings →",
  "dashboard.linkOpsTitle": "Search accounts, ads, Tienda orders, and reports in one query",
  "dashboard.linkOps": "Customer ops search →",
  "dashboard.tiendaNewTitle": "Tienda — new orders",
  "dashboard.tiendaNewHint": "Self-serve print / business card submissions.",
  "dashboard.tiendaMigrateHint": "Run migrations for tienda_orders.",
  "dashboard.tiendaInbox": "Open Tienda inbox",
  "dashboard.tiendaInboxTitle": "Open the print / self-serve orders inbox (tienda_orders)",
  "dashboard.tiendaUnreadTitle": "Tienda — unread",
  "dashboard.tiendaUnreadHint": "Orders not yet marked read by staff.",
  "dashboard.tiendaUnreadInbox": "Unread inbox",
  "dashboard.tiendaUnreadTitleAttr": "Only orders marked unread by the team",
  "dashboard.tiendaReadyTitle": "Tienda — ready to fulfill",
  "dashboard.tiendaReadyHint": "Orders in ready_to_fulfill status.",
  "dashboard.tiendaViewInbox": "View inbox",
  "dashboard.tiendaReadyTitleAttr": "Orders ready for production / fulfillment",
  "dashboard.tiendaReviewTitle": "Tienda — in review",
  "dashboard.tiendaReviewHint": "Staff marked as reviewing.",
  "dashboard.tiendaFilterReview": "Filter reviewing",
  "dashboard.tiendaReviewTitleAttr": "Orders in art or spec review",
  "dashboard.tiendaTotalTitle": "Tienda — total",
  "dashboard.tiendaTotalHint": "Unread (new to staff): {n}",
  "dashboard.tiendaAllOrders": "All Tienda orders",
  "dashboard.tiendaAllTitleAttr": "Full Tienda orders inbox",
  "dashboard.recentTiendaTitle": "Recent Tienda orders",
  "dashboard.recentTiendaSub": "Newest persisted submissions — Supabase-backed inbox (not email).",
  "dashboard.tiendaEmptyUnavailable": "Tienda table unavailable or no rows yet.",
  "dashboard.tiendaEmpty": "No Tienda orders yet.",
  "dashboard.viewOrder": "View order",
  "dashboard.viewOrderTitle": "Open order detail, files, and fulfillment status",
  "dashboard.fullInbox": "Full Tienda inbox →",
  "dashboard.entitlementsHubTitle": "Package entitlements",
  "dashboard.entitlementsHubHint": "Print-to-Digital visibility contracts — not the public /cupones CMS.",
  "dashboard.entitlementsMigrateHint": "Run migration listing_package_entitlements in Supabase.",
  "dashboard.entitlementsActiveTitle": "Active entitlements",
  "dashboard.entitlementsActiveHint": "Currently within start/end window and not revoked.",
  "dashboard.entitlementsExpiringTitle": "Expiring soon",
  "dashboard.entitlementsExpiringHint": "Active entitlements ending within 14 days.",
  "dashboard.entitlementsRevokedTitle": "Revoked / expired",
  "dashboard.entitlementsRevokedHint": "Soft-revoked or past end date.",
  "dashboard.entitlementsCreate": "Create entitlement",
  "dashboard.entitlementsCreateTitle": "Open Admin Package Entitlement Generator",
  "dashboard.entitlementsViewAll": "All entitlements",
  "dashboard.entitlementsViewAllTitle": "View and manage package entitlements",
  "dashboard.recentEntitlementsTitle": "Recent package entitlements",
  "dashboard.recentEntitlementsSub": "Latest grants from listing_package_entitlements (admin manual).",
  "dashboard.entitlementsEmptyUnavailable": "Entitlements table unavailable — apply Supabase migration.",
  "dashboard.entitlementsEmpty": "No package entitlements yet.",
  "dashboard.viewEntitlement": "View",
  "dashboard.viewEntitlementTitle": "Open package entitlements workspace",
  "dashboard.pendingAdsTitle": "Pending ads review",
  "dashboard.pendingAdsHintDb": "Count may need DB status alignment.",
  "dashboard.pendingAdsHint": "Listings in pending/flagged review.",
  "dashboard.reviewAds": "Review ads",
  "dashboard.reviewAdsTitle": "Clasificados admin ad queue (moderation)",
  "dashboard.usersHelpTitle": "Users needing help (proxy)",
  "dashboard.viewUsers": "View users",
  "dashboard.viewUsersTitle": "Profile list (search and customer record)",
  "dashboard.magazineTitle": "Magazine (featured)",
  "dashboard.magazineHintUpdated": "Last manifest update: {date}",
  "dashboard.magazineHintApi": "Resolved via API (DB when issues are published; otherwise editions.json).",
  "dashboard.manageMagazines": "Manage magazines",
  "dashboard.manageMagazinesTitle": "Magazine issues, PDF/flipbook, and current cover number",
  "dashboard.reportsTitle": "Reports / complaints",
  "dashboard.reportsHint": "Pending rows in listing_reports",
  "dashboard.viewReports": "View reports",
  "dashboard.viewReportsTitle": "Listing reports queue (listing_reports)",
  "dashboard.expiringTitle": "Expiring queue (real expiration only)",
  "dashboard.expiringSub":
    "Only ads with a persisted deadline: En Venta visibility window end from listings.republished_at (plus fixed window), listings.expires_at when present, or viajes_staged_listings.expires_at. Recent listings are not used as a proxy.",
  "dashboard.expiringEmpty": "No ads with real expiration data found.",
  "dashboard.expiresLabel": "Expires:",
  "dashboard.adminQueue": "Admin / queue",
  "dashboard.adminQueueTitle": "Related admin queue or tool",
  "dashboard.viewPublic": "View public",
  "dashboard.viewPublicTitle": "Listing on the public site",
  "dashboard.noPublicUrl": "No public URL",
  "dashboard.pendingReviewTitle": "Ads pending review (real review only)",
  "dashboard.pendingReviewSub":
    "Only pending / flagged rows in listings, or real review states in dedicated tables (e.g. empleos pending_review, viajes staged in_review). No “recent listings” fallback.",
  "dashboard.pendingReviewEmpty": "No pending or flagged ads found.",
  "dashboard.updatedLabel": "Updated:",
  "dashboard.reasonLabel": "Reason:",
  "dashboard.openAdminQueueTitle": "Open admin queue / tool",
  "dashboard.sellerCard": "Seller profile",
  "dashboard.sellerCardTitle": "Seller record in Leonix admin",
  "dashboard.categoriesTitle": "Categories (registry)",
  "dashboard.categoriesSub":
    "Effective in admin (code + Supabase overlay): live {live} · staged {staged} · coming soon {comingSoon}. Public still uses code until full integration.",
  "dashboard.manageCategories": "Clasificados hub →",
  "dashboard.revistaCardTitle": "Magazine — featured issue",
  "dashboard.revistaCardSub": "The /magazine hub reads the public manifest (priority: Supabase issues; fallback editions.json).",
  "dashboard.revistaNoFeatured": "No featured issue selected",
  "dashboard.revistaUpdated": "Updated: {date}",
  "dashboard.revistaNoDate": "No date on manifest.",
  "dashboard.revistaMetricsNote": "Read metrics are not in this panel; use site analytics when applicable.",
  "dashboard.revistaManage": "Manage issues →",
  "dashboard.dataHonestyLabel": "Data honesty:",
  "dashboard.dataHonestyBody":
    "Pending counts use live Supabase where columns exist. “Users needing help” is a disabled-account proxy until a support queue exists. The expiring queue lists only rows with a real expiration timestamp in the database (no “recent listings” proxy). Verticals without an expiration field in their current public tables (restaurantes, servicios, empleos, autos) do not appear here until persistence exists. Tienda dashboard counts need the tienda_orders migration applied.",
  "categoriesPage.codeLayer": "Code",
  "categoriesPage.baseBadge": "Base: categoryConfig (code)",
  "categoriesPage.postureBadge": "Admin posture: site_category_config (merge)",
  "categoriesPage.statsBadge": "Counts: live database",
  "categoriesPage.title": "Advanced category registry",
  "categoriesPage.subtitle":
    "Primary control center: use sidebar Categories (opens the Clasificados card hub) for Live listings, ad queue, fields & notes, and operational space. This URL keeps the dense registry: live counts, pending/flagged, and the Supabase save form per slug (status, visibility, order, highlight, notes).",
  "categoriesPage.helperText":
    "No row in Supabase = code-only defaults in the advanced table. Save creates/updates the overlay per slug. There is no “simulated toggle”: the button writes to the database.",
  "categoriesPage.savedBanner": "Category overlay saved to Supabase.",
  "categoriesPage.errorBanner": "Could not save category overlay (invalid status/visibility or missing slug).",
  "categoriesPage.advancedSectionTitle": "Advanced registry — Supabase & counts",
  "categoriesPage.advancedSectionIntro":
    "Use this section for merged listing stats and per-category Supabase saves. Prefer the card hub above for queue, live listings, and category editors.",
  "categoriesPage.ctaClasificados": "Clasificados hub (cards) →",
  "categoriesPage.ctaClasificadosTitle": "Clasificados card hub (queue, live listings, category cards)",
  "categoriesPage.cardLiveLabel": "Live (admin-effective)",
  "categoriesPage.cardStagedLabel": "Staged",
  "categoriesPage.cardComingSoonLabel": "Coming soon",
  "categoriesPage.shortcutsTitle": "Operational shortcuts",
  "categoriesPage.ctaReports": "Reports queue →",
  "categoriesPage.ctaReportsTitle": "Listing reports (listing_reports)",
  "categoriesPage.ctaOps": "Customer ops →",
  "categoriesPage.ctaOpsTitle": "Search accounts, ads, orders, and reports in one query",
  "categoriesPage.ctaTienda": "Tienda orders →",
  "categoriesPage.ctaTiendaTitle": "Print / self-serve orders inbox",
  "categoriesPage.tableHintTop":
    "Counts = `listings` rows where `category` = slug. Pending/flagged = same filter + status. The second row per category saves overlay in Supabase (real action).",
  "categoriesPage.thSource": "Source",
  "categoriesPage.thViewQueue": "View queue",
  "categoriesPage.thLiveListings": "Live listings",
  "categoriesPage.thFieldsNotes": "Fields & notes",
  "categoriesPage.thOperationalSpace": "Operational space",
  "categoriesPage.thPublicLanding": "Public / landing",
  "categoriesPage.openPublicLandingTitle": "Open public or landing route (new tab)",
  "categoriesPage.pendingOnlyTitle": "Pending only",
  "categoriesPage.flaggedOnlyTitle": "Flagged only",
  "categoriesPage.operationalStatusLabel": "Operational status",
  "categoriesPage.visibilityLabel": "Visibility",
  "categoriesPage.sortOrderLabel": "Order",
  "categoriesPage.highlightLabel": "Highlight",
  "categoriesPage.notesLabel": "Notes (optional, Supabase)",
  "categoriesPage.notesPlaceholder": "Only if you want persisted notes…",
  "categoriesPage.saveButtonTitle":
    "Saves visibility, order, and status in site_category_config; updates the /clasificados/publicar hub",
  "categoriesPage.saveButton": "Save category (Supabase + publish hub)",
  "categoriesPage.footerPart1": "Order in this table follows the effective",
  "categoriesPage.footerPart2": "(overlay or code index). Add new slugs first in",
  "categoriesPage.footerPart3": "; then you can adjust posture here.",
  "opsPage.subtitle":
    "One search groups accounts, ads, Tienda orders, and reports. Links open existing screens; there is no impersonation or full CRM here.",
  "opsPage.helperText":
    "Account UUID, name, email, phone, listing id (same public UUID on /clasificados/anuncio/[id]), report id, order id, order_ref, or order email. When exactly one profile matches, a read-only context summary appears below.",
  "opsPage.searchLabel": "Unified search",
  "opsPage.searchHint":
    "Same query across profiles, ads, Tienda orders, and reports (per-section limits). Not CRM or impersonation.",
  "opsPage.searchSubmit": "Search",
  "opsPage.searchSubmitTitle": "Run search and show results on this page",
  "opsPage.clearTitle": "Clear term and return to the initial state",
  "opsPage.usersOnlyTitle": "Users list only (same admin cookie; excludes orders and reports)",
  "opsPage.usersOnlyLink": "Users only →",
  "opsPage.navJump": "Jump to results section",
  "opsPage.navOnPage": "On this page",
  "opsPage.navProfiles": "Profiles",
  "opsPage.navContext": "Context",
  "opsPage.navListings": "Ads",
  "opsPage.navTienda": "Tienda",
  "opsPage.navReports": "Reports",
  "opsPage.navTickets": "Tickets",
  "opsPage.navShortcuts": "Shortcuts",
  "opsPage.contextTitle": "Customer context (read-only)",
  "opsPage.contextSub":
    "Shown when exactly one profile matches the search. Live counts; not a “view as user” or impersonation.",
  "opsPage.contextNoProfiles": "No single profile to summarize.",
  "opsPage.contextMultiProfiles": "Multiple profiles matched — open a record or narrow the search.",
  "opsPage.contextMissing": "No context data (read error or missing profile).",
  "opsPage.fullProfile": "Full record →",
  "opsPage.adsOwner": "Ads (owner):",
  "opsPage.queueLink": "Queue →",
  "opsPage.reportsAsReporter": "Reports as reporter:",
  "opsPage.queueAsReporter": "Queue (as reporter) →",
  "opsPage.tiendaOrdersEmail": "Tienda orders (matching email):",
  "opsPage.noEmailOnProfile": " · no email on profile",
  "opsPage.internalTickets": "Internal tickets",
  "opsPage.ticketsUnavailable": "Unavailable (table or user_id column).",
  "opsPage.ticketsOpen": "open / in progress",
  "opsPage.supportFiltered": "Support (filtered) →",
  "opsPage.listingsTitle": "Clasificados listings",
  "opsPage.listingsSub": "Stable public reference today: column listings.id is the UUID used in public URLs.",
  "opsPage.openClasificadosSameQ": "Open Clasificados queue with the same search →",
  "opsPage.publicView": "Public view",
  "opsPage.adminQueue": "Admin queue",
  "opsPage.reportsTitle": "Listing reports",
  "opsPage.reportsSub":
    "Table listing_reports — match by report id, listing id, or text in the reason field.",
  "opsPage.openQueueThisSearch": "Open queue with this search →",
  "opsPage.openQueueFull": "Full queue →",
  "opsPage.openInQueue": "Open in queue →",
  "opsPage.shortcutsTitle": "Shortcuts",
  "opsPage.shortcutUsers": "Users",
  "opsPage.shortcutReports": "Reports",
  "opsPage.shortcutClasificados": "Clasificados",
  "opsPage.shortcutTiendaOrders": "Tienda orders",
  "opsPage.shortcutSupport": "Support / tickets",
  "opsPage.shortcutCategories": "Categories",
  "opsPage.anonymousName": "(no name)",
  "activityLog.badgeLive": "Supabase (admin_audit_log)",
  "activityLog.badgeEmptyTable": "Table ready · no rows",
  "activityLog.badgeUnavailable": "Table unavailable",
  "activityLog.badgeNoEvents": "No events",
  "activityLog.subtitleLive": "Latest rows from `admin_audit_log` (actions recorded by the admin server).",
  "activityLog.subtitleEmpty":
    "The table exists but there are no events yet. Enabling/disabling accounts and other actions will appear here when used.",
  "activityLog.subtitleUnavailable":
    "Apply migration `20260410120000_admin_audit_log_and_team_invites.sql` in Supabase to enable persistent logging. No sample rows are shown.",
  "activityLog.subtitleUnknown": "Unknown audit state.",
  "activityLog.helperNoSecrets":
    "Secrets and recovery links are not stored in this table. Classifieds mutations on `listings` go to `listing_audit_event` (migration 20260423180000) for seller-side traceability.",
  "activityLog.detailPrefix": "Detail:",
  "activityLog.bannerLive": "Real rows — actor stays “server” until per-row staff identity exists.",
  "activityLog.bannerOther": "No demo data: only rows persisted in Supabase.",
  "activityLog.emptyLive":
    "No auditable events yet. Actions such as enabling/disabling an account will create rows here.",
  "activityLog.unavailableP1":
    "When the table exists, staff actions recorded by the server appear here. For classifieds mutations on `listings`, check",
  "activityLog.unavailableP2": "in Supabase or the seller panel (owner read via RLS).",
  "paymentsPage.badgeUnavailable": "Tienda orders: not readable",
  "paymentsPage.badgeMeta": "Operational metadata (no PCI)",
  "paymentsPage.badgePsp": "PSP / Stripe API: not connected",
  "paymentsPage.subtitle":
    "This screen does not process or store cards. What you see are operational proxies from Tienda orders in Supabase (fulfillment state) and links to real queues.",
  "paymentsPage.helperText":
    "Card billing / processor webhooks remain outside Leonix until explicitly integrated. Do not paste PAN, CVV, or magnetic-stripe data.",
  "paymentsPage.pciBanner":
    "No PCI scope here: use the processor dashboard for chargebacks and payment methods. Leonix admin only links operational context.",
  "paymentsPage.cardTiendaRows": "Tienda orders (rows)",
  "paymentsPage.cardTiendaRowsBody":
    "Rows come from the tienda_orders table: internal checkout snapshots, not PSP revenue accounting.",
  "paymentsPage.openTiendaInbox": "Open Tienda inbox →",
  "paymentsPage.cardPipeline": "In pipeline (approx.)",
  "paymentsPage.cardPipelineBody":
    "Sum of new + reviewing + ready_to_fulfill + ordered — operational work still to close.",
  "paymentsPage.cardAttention": "Attention / failures",
  "paymentsPage.cardAttentionBody": "needs_customer_followup + failed_submission.",
  "paymentsPage.cardUnread": "Unread inbox (admin)",
  "paymentsPage.cardUnreadBody": "Column unread_admin — proxy for work pending review in Leonix.",
  "paymentsPage.cardEmailFailed": "Confirmation email failed",
  "paymentsPage.cardEmailFailedBody":
    "email_delivery_status = failed — check inbox / logs; not a PSP charge event.",
  "paymentsPage.cardApproval": "Approval incomplete",
  "paymentsPage.cardApprovalBody": "approval_complete = false — internal order checklist before fulfillment.",
  "paymentsPage.statusBreakdown": "Breakdown by status",
  "paymentsPage.futureTitle": "What this section will control in the future",
  "paymentsPage.futureLi1": "Signed links to Customer Portal / Stripe dashboard (URLs only; no secrets in admin client).",
  "paymentsPage.futureLi2": "Webhook summaries (failed charges, disputes) when a dedicated table exists.",
  "paymentsPage.futureLi3": "Search by customer ref / subscription id aligned to the real billing model.",
  "paymentsPage.futureFoot": "Today, operational order traceability lives in",
  "paymentsPage.futureFootLink": "Tienda → orders",
  "paymentsPage.processorTitle": "Processor dashboard",
  "paymentsPage.processorHintBefore": "Optional: set env var",
  "paymentsPage.processorHintAfter": "to the processor dashboard base URL only (no API keys).",
  "paymentsPage.openStripe": "Open Stripe dashboard ↗",
  "paymentsPage.noStripeUrl": "No URL configured",
  "drawPage.stub": "No function",
  "drawPage.subtitle": "This route is not an admin tool. There are no controls or preview here.",
  "drawPage.helperText": "If you landed from an old link, use the main panel or Website sections.",
  "drawPage.bodyLead": "Leonix admin lives in",
  "drawPage.bodyTail": "— not at this URL.",
  "drawPage.ctaDashboard": "Go to Dashboard →",
  "drawPage.ctaWorkspace": "Website sections →",
  "reportsPage.subtitle": "listing_reports — review or dismiss from the table (real database actions).",
  "reportsPage.helperFiltered":
    "Active filter: UUID matches report, listing, or reporter id; free text searches the reason field only.",
  "reportsPage.helperDefault": "Use ?q= in the URL to narrow results (also from Ops or a user profile).",
  "reportsPage.searchLabel": "Search",
  "reportsPage.searchPlaceholder": "UUID (report / listing / reporter) or text in reason…",
  "reportsPage.searchHint": "UUID: report, listing, or reporter. Free text: reason field only.",
  "reportsPage.applyTitle": "Filter the table with the criteria above",
  "reportsPage.apply": "Apply filter",
  "reportsPage.clearTitle": "Clear filter and show all recent reports",
  "reportsPage.clear": "Clear search",
  "reportsPage.filteredNote": "On filtered results",
  "reportsTable.empty": "No reports.",
  "reportsTable.errUpdate": "Could not update",
  "reportsTable.colDate": "Date",
  "reportsTable.colListing": "Listing",
  "reportsTable.colReporter": "Reporter",
  "reportsTable.colReason": "Reason",
  "reportsTable.colStatus": "Status",
  "reportsTable.colActions": "Actions",
  "reportsTable.openPublicTitle": "Open public listing in a new tab",
  "reportsTable.openReporterTitle": "Reporter profile in Leonix admin",
  "reportsTable.btnReviewedTitle": "Mark report as reviewed in listing_reports",
  "reportsTable.btnReviewedAria": "Mark report as reviewed",
  "reportsTable.btnReviewed": "Reviewed",
  "reportsTable.btnDismissTitle": "Dismiss report (does not delete the listing)",
  "reportsTable.btnDismissAria": "Dismiss report",
  "reportsTable.btnDismiss": "Dismiss",
  "settingsPage.stub": "Not persisted",
  "settingsPage.subtitle":
    "This page stays intentionally non-persistent: there is no generic Leonix “site settings” table. Theme and coordination notes live in code/deploy until an agreed model exists.",
  "settingsPage.helperText":
    "What persists today: site sections (`site_section_content`), categories (`site_category_config`), global settings (`/admin/site-settings`), roster (`admin_team_members`), magazine (`magazine_issues`), Tienda orders, etc.",
  "settingsPage.blockerLead": "Blocker for “save theme here”:",
  "settingsPage.blockerBody":
    "You would need a dedicated row or table (e.g. site_runtime_settings), RLS policies, and public-layout reads without breaking cache. Until then any “Save” would be fake — fields stay disabled.",
  "settingsPage.linkGlobal": "Global settings (persisted) →",
  "settingsPage.linkWorkspace": "Workspace map →",
  "settingsPage.envRosterLi":
    "Optional roster permissions: ADMIN_ENFORCE_ROSTER_PERMISSIONS + ADMIN_OPERATOR_EMAIL — see Team.",
  "globalSitePage.title": "Global site settings",
  "globalSitePage.subtitle":
    "Banners and strips that can appear on many pages (below the main menu). Does not replace the `/home` editor.",
  "globalSitePage.helperText":
    "Toggle each strip with the checkbox and edit text. Public site language still uses the ?lang= parameter (same as other public pages).",
  "globalSitePage.homeEditorCta": "Home `/home` editor",
  "globalSitePage.savedBanner": "Saved.",
  "globalSitePage.readError": "Could not read the database:",
  "globalSitePage.clasificadosLead":
    "Classifieds (En Venta, etc.): ads are published through the public publish flow and the moderation workspace at",
  "globalSitePage.clasificadosTail":
    ". This screen only saves global notices (strips under the menu); it does not create or approve ads.",
  "globalSitePage.updated": "Last updated:",
  "globalSitePage.sectionMenu": "Region under the menu",
  "globalSitePage.sectionMenuBody":
    "Turn off the entire banner block (notice + promo) without deleting copy — useful for emergencies or layout tests.",
  "globalSitePage.toggleMenuBanners": "Show strips below navigation",
  "globalSitePage.sectionNotice": "General notice (site)",
  "globalSitePage.sectionNoticeBody": "Informative line (special hours, short maintenance, etc.).",
  "globalSitePage.toggleNotice": "Show notice",
  "globalSitePage.labelNoticeEs": "Copy (ES · public)",
  "globalSitePage.labelNoticeEn": "Copy (EN · public)",
  "globalSitePage.sectionPromo": "Global promo strip",
  "globalSitePage.sectionPromoBody": "Optional second strip (promo / campaign tone). Independent from the notice.",
  "globalSitePage.togglePromo": "Show promo strip",
  "globalSitePage.labelPromoEs": "Copy (ES · public)",
  "globalSitePage.labelPromoEn": "Copy (EN · public)",
  "globalSitePage.submit": "Save global settings",
  "globalSitePage.footer":
    "Code vs content: menu, footer, and responsive structure remain in code. Only copy and on/off for these two strips are stored here.",
  "languageAudit.title": "Admin language coverage",
  "languageAudit.intro":
    "Gate checklist: each area must ship visible admin chrome through `adminMessages` / `useAdminT` (English default; Spanish when the ES cookie is set). User-generated listing text is excluded.",
  "languageAudit.th.section": "Section",
  "languageAudit.th.enDefault": "English default",
  "languageAudit.th.esToggle": "ES toggle",
  "languageAudit.th.notes": "Notes",
  "languageAudit.section.dashboard": "Dashboard",
  "languageAudit.section.categories": "Categories",
  "languageAudit.section.clasificadosWorkspace": "Clasificados workspace",
  "languageAudit.section.clasificadosQueues": "Clasificados category queues",
  "languageAudit.section.restaurantesQueue": "Restaurantes queue",
  "languageAudit.section.serviciosQueue": "Servicios queue",
  "languageAudit.section.empleosQueue": "Empleos queue",
  "languageAudit.section.autosQueue": "Autos queue",
  "languageAudit.section.tienda": "Tienda",
  "languageAudit.section.users": "Users",
  "languageAudit.section.payments": "Payments",
  "languageAudit.section.support": "Support / customer ops",
  "languageAudit.section.settings": "Settings / global site",
  "languageAudit.section.revista": "Magazine workspace",
  "languageAudit.notes.rowPass":
    "PASS — Visible chrome for this area resolves through the shared admin dictionary (EN default; ES when selected).",
};

const ES: Record<string, string> = {
  ...EN,
  "shell.globalAdmin": "Admin global",
  "shell.leonixAdmin": "Admin Leonix",
  "shell.signedInCookie": "Sesión vía cookie",
  "shell.websiteSectionsLink": "Secciones del sitio (workspaces)",
  "shell.globalSiteSettingsLink": "Ajustes globales del sitio",
  "shell.viewSite": "Ver sitio →",
  "shell.searchListingsPlaceholder": "Buscar anuncios (título, ciudad, ID)…",
  "shell.searchListingsTitle": "Abrir workspace Clasificados con este texto como filtro",
  "shell.searchLabel": "Buscar",
  "shell.createClasificadosTitle": "Ir a la cola de Clasificados (moderación y enlaces)",
  "shell.tiendaTitleUnread": "Tienda (hub · inbox con avisos)",
  "shell.tiendaTitle": "Tienda — centro de comando",
  "shell.tiendaAriaUnread": "Tienda, {n} sin leer",
  "shell.langAria": "Idioma de la interfaz admin",
  "shell.langEn": "Inglés",
  "shell.langEs": "Español",
  "mobile.openMenu": "Abrir menú admin",
  "mobile.menuTitle": "Menú: Dashboard, usuarios, workspaces…",
  "mobile.navDialog": "Navegación admin",
  "mobile.closeOverlay": "Cerrar menú",
  "mobile.close": "Cerrar",
  "mobile.globalNav": "Administración global",
  "workspaceNav.kicker": "Secciones del sitio",
  "workspaceNav.sub": "Workspaces solo admin — no el menú público.",
  "workspaceNav.overview": "Resumen",
  "workspaceNav.aria": "Workspaces por sección del sitio",
  "workspaceNav.link.home": "Home",
  "workspaceNav.link.clasificados": "Clasificados",
  "workspaceNav.link.packageEntitlements": "Paquetes / entitlements",
  "workspaceNav.packageEntitlements.hint": "Generador de acceso Print-to-Digital (no es el CMS de cupones públicos)",
  "workspaceNav.link.tienda": "Tienda",
  "workspaceNav.link.nosotros": "Nosotros",
  "workspaceNav.link.revista": "Revista",
  "workspaceNav.link.contacto": "Contacto",
  "workspaceNav.link.noticias": "Noticias",
  "workspaceNav.link.iglesias": "Iglesias",
  "workspaceNav.link.cupones": "Cupones",
  "workspaceNav.link.anunciate": "Anúnciate",
  "nav.dashboard": "Panel",
  "nav.categories": "Categorías",
  "nav.siteSections": "Secciones del sitio",
  "nav.users": "Usuarios",
  "nav.customerOps": "Operaciones cliente",
  "nav.payments": "Pagos",
  "nav.support": "Soporte",
  "nav.team": "Equipo",
  "nav.activityLog": "Registro de actividad",
  "nav.settings": "Ajustes",
  "nav.languageAudit": "Auditoría de idioma",
  "workspaceNav.home.hint": "Ruta pública /home (revista) — no la pantalla raíz /",
  "workspaceNav.clasificados.hint": "Moderación de anuncios en Supabase",
  "workspaceNav.tienda.hint": "Vitrina /tienda + enlaces al catálogo y pedidos",
  "workspaceNav.nosotros.hint": "Página pública /about",
  "workspaceNav.revista.hint": "Manifiesto editions.json + notas internas",
  "workspaceNav.contacto.hint": "Página /contacto (formulario global)",
  "workspaceNav.noticias.hint": "Shell en site_section_content; RSS sigue en API",
  "workspaceNav.iglesias.hint": "Copy en site_section_content; directorio = backlog",
  "workspaceNav.cupones.hint": "cupones_page → /cupones y /coupons",
  "workspaceNav.anunciate.hint": "Mapa al funnel publicar (Clasificados) + cola admin; sin CRM",
  "common.and": "y",
  "common.apply": "Aplicar",
  "common.clear": "Limpiar",
  "common.applyFilters": "Aplicar filtros",
  "common.allCategories": "Todas las categorías",
  "common.allStatuses": "Todos los estados",
  "common.rows": "filas",
  "cta.viewAds": "Ver anuncios",
  "cta.viewAdsTitle": "Abrir cola de anuncios de esta categoría en el workspace admin",
  "cta.viewQueue": "Ver cola",
  "cta.viewQueueTitle": "Abrir cola operativa de esta categoría en el workspace admin",
  "cta.liveListingsPrimary": "Listados activos",
  "cta.liveListingsPrimaryTitle": "Lista admin de filas publicadas/activas de esta categoría (no es el marketplace público)",
  "cta.liveListingsAltLabel": "Listados públicos",
  "cta.liveListingsAltTitle": "Misma vista operativa admin — etiqueta alternativa",
  "scopeNav.aria": "Alternar entre cola completa y solo listados en vivo",
  "scopeNav.queue": "Cola de anuncios",
  "scopeNav.queueTitle": "Cola operativa completa: moderación, borradores y publicados",
  "scopeNav.live": "Listados activos",
  "scopeNav.liveTitle": "Solo anuncios visibles al público en este momento",
  "listingsCategoryOps.titleQueue": "{slug} — cola operativa",
  "listingsCategoryOps.titleLive": "{slug} — listados públicos activos",
  "listingsCategoryOps.subQueue":
    "Tabla completa de la categoría en admin (moderación + borradores + publicados). Usa «Listados activos» para lo que el público ve ahora.",
  "listingsCategoryOps.subLive":
    "Solo filas públicas en vivo (publicado + activo). Restaurar no es republicar; republicar/subir al inicio siguen separados.",
  "listingsCategoryOps.searchTitle": "Filtrar cola",
  "clasificados.title": "Clasificados — centro de operaciones",
  "clasificados.subtitle":
    "Arriba: mapa por categoría (esquema en código + postura en Supabase). Abajo: la misma cola global de anuncios con filtros — moderación, reportes y En Venta siguen aquí.",
  "clasificados.eyebrow": "Workspace · Clasificados",
  "clasificados.helper":
    "Elige una categoría para ver planes, campos y atajos; o baja directo a la cola. Postgres (hasta {limit} filas): título, ciudad, descripción, id y owner. BR/Rentas refinan en cliente vía detail_pairs.",
  "clasificados.detailPairsMissingTitle": "Base sin columna listings.detail_pairs.",
  "clasificados.detailPairsMissingBody":
    "La cola carga en modo reducido: la columna “En venta · vis.” no puede mostrar plan / renovación hasta migrar. Aplica en Supabase la migración",
  "clasificados.boostMissingTitle": "Base sin columna listings.republished_at.",
  "clasificados.boostMissingBody":
    "La cola carga sin marcas de tiempo de republicación; la columna “En venta · vis.” muestra plan y lastRenew pero no el último “subir al tope” hasta migrar. Aplica",
  "clasificados.homeChipsTitle": "Destacados en la portada `/home`:",
  "clasificados.homeChipsBody":
    "No se generan solos desde esta cola. En Home → contenido puedes enlazar manualmente a categorías o rutas públicas (chips). Aquí moderas anuncios en Supabase.",
  "clasificados.homeContentCta": "Home → contenido",
  "clasificados.brHintTitle": "Ramas inmobiliarias (BR / Rentas):",
  "clasificados.brHintBody":
    "Cuando los listados vivan en listings, usa category y detail_pairs para distinguir venta vs renta, Privado vs Negocio y tipo de propiedad. Vista previa de publicación no es listado público:",
  "clasificados.autosCta": "Autos (pagos Leonix) →",
  "clasificados.serviciosCta": "Servicios (Supabase) →",
  "clasificados.categoriesCta": "Registro avanzado →",
  "clasificados.categoriesAdvancedTitle": "Abrir registro avanzado (tabla + guardados Supabase)",
  "clasificados.categoriesTitle": "Visibilidad, orden y estado operativo (site_category_config)",
  "clasificados.reportesCta": "Reportes →",
  "clasificados.filterHint":
    "Búsqueda q: Leonix Ad ID (si existe columna), UUID de anuncio u owner, título, ciudad, descripción, slug/URL, y coincidencia por nombre / correo / teléfono del perfil (owner). Respeta category. BR/Rentas refinan en cliente sobre detail_pairs. limit 50–500 (default 300).",
  "clasificados.placeholderQ": "Leonix ID, UUID, título, owner, email/teléfono, URL…",
  "clasificados.placeholderOwner": "Owner ID (fragmento)",
  "clasificados.leonixFilters": "Leonix BR / Rentas (detail_pairs)",
  "clasificados.branchAll": "Rama (todas)",
  "clasificados.operationAll": "Operación (todas)",
  "clasificados.operationSale": "sale (venta)",
  "clasificados.operationRent": "rent (renta)",
  "clasificados.propTypeAll": "Tipo propiedad (todas)",
  "clasificados.limitTitle": "Máximo de anuncios a traer de Supabase en esta vista",
  "clasificados.limitAria": "Límite de filas",
  "clasificados.applyFiltersTitle": "Recargar la cola con los filtros en la URL (sin mutar datos)",
  "clasificados.backWorkspace": "← Resumen de secciones del sitio",
  "clasificados.envSectionTitle": "En Venta — contrato de moderación",
  "clasificados.envSectionSubtitle":
    "Solo referencia (lista de motivos). No envía cambios a la base — documentación para el equipo.",
  "audit.title": "Auditoría operativa — colas por categoría",
  "audit.intro":
    "Valores TRUE/FALSE se calculan al cargar esta página (consultas reales a Supabase y los mismos helpers que usa la cola). Si algo falla, la columna «Motivo» indica el error de Postgres/PostgREST o la limitación exacta.",
  "audit.th.slug": "Slug",
  "audit.th.queue": "Cola admin",
  "audit.th.source": "Fuente",
  "audit.th.load": "Cargar",
  "audit.th.search": "Buscar",
  "audit.th.public": "Link público",
  "audit.th.moderate": "Moderar",
  "audit.th.editAd": "Editar anuncio",
  "audit.th.leonixEmbedded": "ID Leonix incrustado",
  "audit.th.rows": "Filas (aprox.)",
  "audit.th.reason": "Motivo si FALSE",
  "audit.true": "TRUE",
  "audit.false": "FALSE",
  "audit.boolTitleTrue": "Verificado al cargar la página",
  "audit.boolTitleFalse": "Ver columna de motivo",
  "hub.title": "Categorías — centro de control",
  "hub.intro":
    "Cada tarjeta refleja la clave de esquema categorySchema en código y la postura operativa fusionada con Supabase. Abre el espacio de una categoría para ver planes, campos, vista previa y atajos a la cola filtrada.",
  "hub.categoriesRegistry": "Registro avanzado →",
  "hub.restLink": "Tabla listados públicos (BD)",
  "hub.editorEnVenta": "Campos y notas (BD)",
  "hub.editorOther": "Campos y notas (BD)",
  "hub.opsSpace": "Espacio operativo",
  "hub.queueFiltered": "Cola de anuncios",
  "hub.queueFilteredTitle":
    "Abre la cola operativa real: vertical dedicada (Restaurantes/Servicios/Empleos/Autos) o cola listings filtrada.",
  "hub.liveListingsCta": "Listados activos",
  "hub.liveListingsCtaTitle": "Vista operativa admin de anuncios públicos/en vivo de esta categoría (scope=live)",
  "hub.standardLive": "Estándar vivo",
  "hub.plans": "Planes",
  "hub.fields": "Campos",
  "hub.fieldGroup": "grupo",
  "hub.preview": "Preview",
  "hub.proPreview": "Pro preview",
  "hub.yes": "sí",
  "hub.no": "no",
  "hub.readiness": "Readiness",
  "hub.restDbLink": "Tabla listados públicos (BD)",
  "listings.col.id": "ID",
  "listings.col.leonixId": "Leonix Ad ID",
  "listings.col.title": "Título",
  "listings.col.category": "Categoría",
  "listings.col.city": "Ciudad",
  "listings.col.price": "Precio",
  "listings.col.status": "Estado",
  "listings.col.owner": "Owner",
  "listings.col.date": "Fecha",
  "listings.col.leonix": "Leonix",
  "listings.col.envVis": "En venta · vis.",
  "listings.col.actions": "Acciones",
  "listings.actionsColumnEarlyHint":
    "Las acciones de staff están antes de las columnas anchas Leonix para que los controles se vean sin depender del scroll horizontal.",
  "listings.free": "Gratis",
  "listings.ownerCard": "Ficha vendedor",
  "listings.viewPublic": "Ver público",
  "listings.viewRentas": "Ver público (Rentas)",
  "listings.inspectorRentas": "Inspector Rentas",
  "listings.hidePublic": "Ocultar del público",
  "listings.republish": "Republicar en sitio",
  "listings.deleteStaff": "Eliminar (staff)",
  "listings.emptyGlobal": "No hay anuncios en la cola global con los filtros actuales.",
  "listings.emptyCategoryTitle": "No se encontraron anuncios publicados para esta categoría.",
  "listings.emptyCategoryBody":
    "Filtro activo: public.listings.category (sin mayúsculas) = {slug}{rentasExtra}. Revisa el menú desplegable para valores reales en BD, o abre la cola dedicada (Servicios, Empleos, Autos, Restaurantes) si esta categoría guarda anuncios fuera de listings.",
  "listings.emptyRentasExtra":
    ", más filas con categoría «bienes-raices» y Leonix:operation=rent en detail_pairs cuando no hay búsqueda de texto (q).",
  "listings.col.leonixTitle": "Leonix BR/Rentas: rama, operación, categoría, publicado",
  "listings.col.envVisTitleOk": "Plan En Venta y visibilidad (detail_pairs + republished_at)",
  "listings.col.envVisTitleNoDetailPairs":
    "Columna detail_pairs no disponible en esta base — aplica la migración listings.detail_pairs",
  "listings.col.envVisTitleNoBoost": "Columna republished_at no disponible — aplica la migración classifieds_republish_capability",
  "listings.rowActionsTitle":
    "Acciones de staff en la misma fila (publicar/ocultar/eliminar). Edición de texto e imágenes: panel del anunciante con validación owner_id.",
  "listings.publicRentasTitle": "Detalle público Rentas (ruta canónica)",
  "listings.publicGenericTitle": "Abrir anuncio en el sitio público (nueva pestaña)",
  "listings.hidePublicTitle": "Oculta del listado público (is_published=false). En Venta / resultados dejan de mostrarlo.",
  "listings.republishTitle": "Vuelve a publicar en el sitio (is_published=true) si el estado sigue activo.",
  "listings.deleteTitle": "Marca el anuncio como removed en base (acción de staff; aparece en auditoría)",
  "listings.deleteAria": "Marcar anuncio como eliminado en base de datos",
  "listings.confirmDelete": "¿Marcar este anuncio como eliminado (removed)?",
  "listings.errDelete": "Error al eliminar",
  "listings.confirmHide": "¿Ocultar este anuncio del sitio público (is_published=false)? Sigue visible para staff.",
  "listings.confirmShow": "¿Volver a mostrar este anuncio en el sitio (is_published=true)?",
  "listings.errPublish": "Error al actualizar publicación",
  "listings.envLine.missingDetailPairs": "N/D · falta columna detail_pairs en BD",
  "listings.envLine.boostNoCol": "republish N/D (sin columna republished_at)",
  "listings.envLine.boostOff": "sin ventana de visibilidad activa",
  "listings.envLine.lastRenew": "lastRenew",
  "listings.envLine.renewNd": "renew N/D",
  "listings.envLine.renewOk": "renew OK",
  "listings.envLine.renewDash": "renew —",
  "autosQueue.pageTitle": "Autos — anuncios de pago (autos_classifieds_listings)",
  "autosQueue.pageSubtitle":
    "Flujo Leonix Autos (privado / negocios). «Publicado» = estado active y visible en la API pública y en /clasificados/autos.",
  "autosQueue.backGeneric": "← Cola genérica listings",
  "autosQueue.openPublishFlow": "Flujo publicar Autos (sitio) ↗",
  "autosQueue.searchTitle": "Buscar cola",
  "autosQueue.searchHint":
    "Leonix Ad ID (si existe columna), UUID de anuncio o de usuario, URL /clasificados/autos/vehiculo/…, texto del vehículo (marca, modelo, VIN, etc.), título, ciudad, y coincidencia por nombre / correo / teléfono del perfil propietario.",
  "autosQueue.labelQ": "q",
  "autosQueue.placeholderQ": "UUID, URL, título, email del owner…",
  "autosQueue.emptyTable":
    "No hay filas en autos_classifieds_listings o la base no está configurada con service role para lecturas admin.",
  "autosQueue.colVia": "Vía",
  "autosQueue.colDest": "Dest.",
  "autosQueue.colVis": "Visibilidad",
  "autosQueue.colPub": "Publicado",
  "autosQueue.colImg": "Img",
  "autosQueue.colActions": "Acciones",
  "autosQueue.actionsColTitle":
    "Fila operativa: enlace público cuando aplica; los cambios de estado usan acciones de staff.",
  "autosQueue.viewPublic": "Ver público",
  "autosQueue.viewPublicTitle": "Listado público Autos. La edición de contenido sigue en el flujo del anunciante.",
  "autosQueue.yes": "sí",
  "autosQueue.no": "no",
  "autosQueue.visibilityPublic": "Público (Autos)",
  "autosQueue.visibilityPre": "Pre-publicación",
  "autosQueue.visibilityInactive": "Inactivo / retirado",
  "autosQueue.removePublic": "Quitar del público",
  "autosQueue.removePublicTitle": "Marcar como removed (oculto en APIs públicas de Autos)",
  "autosQueue.restoreActive": "Restaurar activo",
  "autosQueue.restoreActiveTitle": "Volver a active con marca de publicación",
  "dashboard.title": "Panel Leonix",
  "dashboard.subtitle": "Bienvenido — estado operativo del día.",
  "dashboard.helper":
    "La barra lateral es administración global. Para editar secciones del sitio (home, clasificados, tienda…), abre Secciones del sitio abajo o en el pie del menú.",
  "dashboard.editSectionsTitle": "Edición del sitio (secciones)",
  "dashboard.editSectionsBody":
    "Las páginas públicas están agrupadas en workspaces — no son los mismos enlaces que el menú en vivo. Los toggles globales viven en ajustes del sitio.",
  "dashboard.linkWorkspaceTitle": "Workspaces de contenido público (home, clasificados, tienda, revista…)",
  "dashboard.linkWorkspace": "Secciones del sitio →",
  "dashboard.linkSiteSettingsTitle": "Avisos globales, toggles y contenido transversal",
  "dashboard.linkSiteSettings": "Ajustes globales del sitio →",
  "dashboard.linkOpsTitle": "Buscar cuenta, anuncios, pedidos Tienda y reportes en una sola búsqueda",
  "dashboard.linkOps": "Búsqueda ops cliente →",
  "dashboard.tiendaNewTitle": "Tienda — pedidos nuevos",
  "dashboard.tiendaNewHint": "Envíos self-serve de impresión / tarjetas.",
  "dashboard.tiendaMigrateHint": "Ejecuta migraciones para tienda_orders.",
  "dashboard.tiendaInbox": "Abrir inbox Tienda",
  "dashboard.tiendaInboxTitle": "Abrir bandeja de pedidos impresión / self-serve (tienda_orders)",
  "dashboard.tiendaUnreadTitle": "Tienda — sin leer",
  "dashboard.tiendaUnreadHint": "Pedidos aún no marcados como leídos por staff.",
  "dashboard.tiendaUnreadInbox": "Inbox sin leer",
  "dashboard.tiendaUnreadTitleAttr": "Solo pedidos marcados no leídos por el equipo",
  "dashboard.tiendaReadyTitle": "Tienda — listos para cumplir",
  "dashboard.tiendaReadyHint": "Pedidos en estado ready_to_fulfill.",
  "dashboard.tiendaViewInbox": "Ver inbox",
  "dashboard.tiendaReadyTitleAttr": "Pedidos listos para producción / cumplimiento",
  "dashboard.tiendaReviewTitle": "Tienda — en revisión",
  "dashboard.tiendaReviewHint": "Marcados en revisión por staff.",
  "dashboard.tiendaFilterReview": "Filtrar en revisión",
  "dashboard.tiendaReviewTitleAttr": "Pedidos en revisión de arte o especificaciones",
  "dashboard.tiendaTotalTitle": "Tienda — total",
  "dashboard.tiendaTotalHint": "Sin leer (nuevos para staff): {n}",
  "dashboard.tiendaAllOrders": "Todos los pedidos Tienda",
  "dashboard.tiendaAllTitleAttr": "Bandeja completa de pedidos Tienda",
  "dashboard.recentTiendaTitle": "Pedidos Tienda recientes",
  "dashboard.recentTiendaSub": "Últimos envíos persistidos — inbox en Supabase (no email).",
  "dashboard.tiendaEmptyUnavailable": "Tabla Tienda no disponible o sin filas aún.",
  "dashboard.tiendaEmpty": "Aún no hay pedidos Tienda.",
  "dashboard.viewOrder": "Ver pedido",
  "dashboard.viewOrderTitle": "Abrir detalle del pedido, archivos y estado de cumplimiento",
  "dashboard.fullInbox": "Inbox Tienda completo →",
  "dashboard.entitlementsHubTitle": "Paquetes de visibilidad",
  "dashboard.entitlementsHubHint": "Contratos Print-to-Digital — no es el CMS público de /cupones.",
  "dashboard.entitlementsMigrateHint": "Ejecuta la migración listing_package_entitlements en Supabase.",
  "dashboard.entitlementsActiveTitle": "Entitlements activos",
  "dashboard.entitlementsActiveHint": "Dentro de ventana inicio/fin y sin revocar.",
  "dashboard.entitlementsExpiringTitle": "Por vencer pronto",
  "dashboard.entitlementsExpiringHint": "Activos que terminan en los próximos 14 días.",
  "dashboard.entitlementsRevokedTitle": "Revocados / vencidos",
  "dashboard.entitlementsRevokedHint": "Revocados suavemente o pasada la fecha fin.",
  "dashboard.entitlementsCreate": "Crear paquete",
  "dashboard.entitlementsCreateTitle": "Abrir generador Admin de package entitlements",
  "dashboard.entitlementsViewAll": "Todos los paquetes",
  "dashboard.entitlementsViewAllTitle": "Ver y administrar package entitlements",
  "dashboard.recentEntitlementsTitle": "Paquetes recientes",
  "dashboard.recentEntitlementsSub": "Últimos grants en listing_package_entitlements (admin manual).",
  "dashboard.entitlementsEmptyUnavailable": "Tabla de entitlements no disponible — aplica migración Supabase.",
  "dashboard.entitlementsEmpty": "Aún no hay package entitlements.",
  "dashboard.viewEntitlement": "Ver",
  "dashboard.viewEntitlementTitle": "Abrir workspace de package entitlements",
  "dashboard.pendingAdsTitle": "Anuncios pendientes de revisión",
  "dashboard.pendingAdsHintDb": "El conteo puede requerir alinear estados en BD.",
  "dashboard.pendingAdsHint": "Listings en pending / flagged.",
  "dashboard.reviewAds": "Revisar anuncios",
  "dashboard.reviewAdsTitle": "Cola admin de anuncios Clasificados (moderación)",
  "dashboard.usersHelpTitle": "Usuarios que necesitan ayuda (proxy)",
  "dashboard.viewUsers": "Ver usuarios",
  "dashboard.viewUsersTitle": "Lista de perfiles (búsqueda y ficha de cliente)",
  "dashboard.magazineTitle": "Revista (destacado)",
  "dashboard.magazineHintUpdated": "Última actualización en manifiesto: {date}",
  "dashboard.magazineHintApi": "Resuelto vía API (BD si hay números publicados; si no, editions.json).",
  "dashboard.manageMagazines": "Gestionar números",
  "dashboard.manageMagazinesTitle": "Números de revista, PDF/flipbook y número actual en portada",
  "dashboard.reportsTitle": "Reportes / quejas",
  "dashboard.reportsHint": "Filas pendientes en listing_reports",
  "dashboard.viewReports": "Ver reportes",
  "dashboard.viewReportsTitle": "Cola de reportes de anuncios (listing_reports)",
  "dashboard.expiringTitle": "Cola por expiración (solo fechas reales)",
  "dashboard.expiringSub":
    "Solo anuncios con fecha límite persistida: fin de ventana de visibilidad desde listings.republished_at (más ventana fija), listings.expires_at si existe, o viajes_staged_listings.expires_at. No se usan anuncios recientes como sustituto.",
  "dashboard.expiringEmpty": "No hay anuncios con datos de expiración reales.",
  "dashboard.expiresLabel": "Expira:",
  "dashboard.adminQueue": "Admin / cola",
  "dashboard.adminQueueTitle": "Cola o herramienta admin relacionada",
  "dashboard.viewPublic": "Ver público",
  "dashboard.viewPublicTitle": "Anuncio en el sitio público",
  "dashboard.noPublicUrl": "Sin URL pública",
  "dashboard.pendingReviewTitle": "Anuncios en revisión (solo revisión real)",
  "dashboard.pendingReviewSub":
    "Solo filas pending / flagged en listings, o estados reales en tablas dedicadas (p. ej. empleos pending_review, viajes staged in_review). Sin fallback de anuncios recientes.",
  "dashboard.pendingReviewEmpty": "No hay anuncios pending o flagged.",
  "dashboard.updatedLabel": "Actualizado:",
  "dashboard.reasonLabel": "Motivo:",
  "dashboard.openAdminQueueTitle": "Abrir cola / herramienta admin",
  "dashboard.sellerCard": "Ficha vendedor",
  "dashboard.sellerCardTitle": "Ficha del vendedor en Leonix admin",
  "dashboard.categoriesTitle": "Categorías (registro)",
  "dashboard.categoriesSub":
    "Efectivo en admin (código + overlay Supabase): live {live} · staged {staged} · coming soon {comingSoon}. Público aún usa código hasta integración.",
  "dashboard.manageCategories": "Hub Clasificados →",
  "dashboard.revistaCardTitle": "Revista — número destacado",
  "dashboard.revistaCardSub": "El hub /magazine lee el manifiesto público (prioridad: Supabase; respaldo editions.json).",
  "dashboard.revistaNoFeatured": "Sin número destacado",
  "dashboard.revistaUpdated": "Actualizado: {date}",
  "dashboard.revistaNoDate": "Sin fecha en manifiesto.",
  "dashboard.revistaMetricsNote": "Métricas de lectura no están en este panel; usa analítica del sitio cuando aplique.",
  "dashboard.revistaManage": "Gestionar números →",
  "dashboard.dataHonestyLabel": "Transparencia de datos:",
  "dashboard.dataHonestyBody":
    "Los conteos pending usan Supabase en vivo donde existan columnas. «Usuarios que necesitan ayuda» es un proxy de cuenta deshabilitada hasta existir cola de soporte. La cola por expiración solo lista filas con marca de expiración real en base (sin proxy de anuncios recientes). Verticales sin campo de expiración en sus tablas públicas actuales (restaurantes, servicios, empleos, autos) no aparecen aquí hasta que exista persistencia. Los conteos de Tienda requieren la migración tienda_orders.",
  "categoriesPage.codeLayer": "Código",
  "categoriesPage.baseBadge": "Base: categoryConfig (código)",
  "categoriesPage.postureBadge": "Postura admin: site_category_config (merge)",
  "categoriesPage.statsBadge": "Conteos: DB en vivo",
  "categoriesPage.title": "Registro avanzado de categorías",
  "categoriesPage.subtitle":
    "Centro principal: usa Categorías en la barra lateral (abre el hub en tarjetas) para listados activos, cola, campos y notas y espacio operativo. Esta URL conserva la tabla densa: conteos en vivo, pending/flagged y el formulario Supabase por slug (estado, visibilidad, orden, destacado, notas).",
  "categoriesPage.helperText":
    "Sin fila en Supabase = solo defaults de código en la tabla avanzada. Guardar crea/actualiza overlay por slug. No hay «toggle simulado»: el botón escribe en base de datos.",
  "categoriesPage.savedBanner": "Overlay de categoría guardado en Supabase.",
  "categoriesPage.errorBanner": "No se pudo guardar el overlay (estado/visibilidad inválidos o slug faltante).",
  "categoriesPage.advancedSectionTitle": "Registro avanzado — Supabase y conteos",
  "categoriesPage.advancedSectionIntro":
    "Usa esta sección para conteos fusionados y guardados Supabase por categoría. Prefiere el hub en tarjetas arriba para cola, listados activos y editores.",
  "categoriesPage.ctaClasificados": "Hub Clasificados (tarjetas) →",
  "categoriesPage.ctaClasificadosTitle": "Hub Clasificados en tarjetas (cola, listados, categorías)",
  "categoriesPage.cardLiveLabel": "Live (efectivo admin)",
  "categoriesPage.cardStagedLabel": "Staged",
  "categoriesPage.cardComingSoonLabel": "Coming soon",
  "categoriesPage.shortcutsTitle": "Atajos operativos",
  "categoriesPage.ctaReports": "Cola de reportes →",
  "categoriesPage.ctaReportsTitle": "Reportes de anuncios (listing_reports)",
  "categoriesPage.ctaOps": "Ops cliente →",
  "categoriesPage.ctaOpsTitle": "Buscar cuenta, anuncios, pedidos y reportes en una sola búsqueda",
  "categoriesPage.ctaTienda": "Pedidos Tienda →",
  "categoriesPage.ctaTiendaTitle": "Bandeja de pedidos de impresión / self-serve",
  "categoriesPage.tableHintTop":
    "Conteos = filas `listings` con `category` = slug. Pending/flagged = mismo filtro + estado. La segunda fila por categoría guarda overlay en Supabase (acción real).",
  "categoriesPage.thSource": "Fuente",
  "categoriesPage.thViewQueue": "Ver cola",
  "categoriesPage.thLiveListings": "Listados activos / públicos",
  "categoriesPage.thFieldsNotes": "Campos y notas",
  "categoriesPage.thOperationalSpace": "Espacio operativo",
  "categoriesPage.thPublicLanding": "Público / landing",
  "categoriesPage.openPublicLandingTitle": "Abrir ruta pública o landing (nueva pestaña)",
  "categoriesPage.pendingOnlyTitle": "Solo pending",
  "categoriesPage.flaggedOnlyTitle": "Solo flagged",
  "categoriesPage.operationalStatusLabel": "Estado operativo",
  "categoriesPage.visibilityLabel": "Visibilidad",
  "categoriesPage.sortOrderLabel": "Orden",
  "categoriesPage.highlightLabel": "Destacar",
  "categoriesPage.notesLabel": "Notas (opcional, Supabase)",
  "categoriesPage.notesPlaceholder": "Solo si quieres anotación persistida…",
  "categoriesPage.saveButtonTitle":
    "Guarda visibilidad, orden y estado en site_category_config; actualiza el hub /clasificados/publicar",
  "categoriesPage.saveButton": "Guardar categoría (Supabase + publicar)",
  "categoriesPage.footerPart1": "El orden en esta tabla sigue el",
  "categoriesPage.footerPart2": "efectivo (overlay o índice de código). Añade slugs nuevos primero en",
  "categoriesPage.footerPart3": "; luego podrás ajustar postura aquí.",
  "opsPage.subtitle":
    "Una sola búsqueda agrupa cuenta, anuncios, pedidos Tienda y reportes. Los enlaces abren las pantallas ya existentes; aquí no hay suplantación ni CRM completo.",
  "opsPage.helperText":
    "UUID de cuenta, nombre, correo, teléfono, listing id (misma UUID pública en /clasificados/anuncio/[id]), id de reporte, order id, order_ref o email de pedido. Si solo cae un perfil, verás un resumen de contexto (conteos) debajo.",
  "opsPage.searchLabel": "Búsqueda unificada",
  "opsPage.searchHint":
    "Misma búsqueda en perfiles, anuncios, pedidos Tienda y reportes (límite por sección). No es CRM ni suplantación.",
  "opsPage.searchSubmit": "Buscar",
  "opsPage.searchSubmitTitle": "Ejecutar búsqueda y mostrar resultados en esta página",
  "opsPage.clearTitle": "Quitar término y volver al estado inicial",
  "opsPage.usersOnlyTitle": "Solo la lista de usuarios (misma cookie admin; no incluye pedidos ni reportes)",
  "opsPage.usersOnlyLink": "Solo usuarios →",
  "opsPage.navJump": "Saltar a sección de resultados",
  "opsPage.navOnPage": "En esta página",
  "opsPage.navProfiles": "Perfiles",
  "opsPage.navContext": "Contexto",
  "opsPage.navListings": "Anuncios",
  "opsPage.navTienda": "Tienda",
  "opsPage.navReports": "Reportes",
  "opsPage.navTickets": "Tickets",
  "opsPage.navShortcuts": "Atajos",
  "opsPage.contextTitle": "Contexto de cliente (solo lectura)",
  "opsPage.contextSub":
    "Aparece cuando hay exactamente un perfil en la búsqueda. Conteos en vivo; no es vista «como el usuario» ni impersonación.",
  "opsPage.contextNoProfiles": "Sin perfil único para resumir.",
  "opsPage.contextMultiProfiles": "Varios perfiles coinciden — abre el detalle o acota la búsqueda.",
  "opsPage.contextMissing": "Sin datos de contexto (error de lectura o perfil ausente).",
  "opsPage.fullProfile": "Ficha completa →",
  "opsPage.adsOwner": "Anuncios (owner):",
  "opsPage.queueLink": "Cola →",
  "opsPage.reportsAsReporter": "Reportes como reporter:",
  "opsPage.queueAsReporter": "Cola (como reporter) →",
  "opsPage.tiendaOrdersEmail": "Pedidos Tienda (email coincidente):",
  "opsPage.noEmailOnProfile": " · sin email en perfil",
  "opsPage.internalTickets": "Tickets internos",
  "opsPage.ticketsUnavailable": "No disponible (tabla o columna user_id).",
  "opsPage.ticketsOpen": "abiertos / en curso",
  "opsPage.supportFiltered": "Soporte (filtrado) →",
  "opsPage.listingsTitle": "Listados Clasificados",
  "opsPage.listingsSub": "Referencia pública estable hoy: la columna listings.id es la UUID que ves en URLs públicas.",
  "opsPage.openClasificadosSameQ": "Abrir cola Clasificados con la misma búsqueda →",
  "opsPage.publicView": "Vista pública",
  "opsPage.adminQueue": "Cola admin",
  "opsPage.reportsTitle": "Reportes de anuncios",
  "opsPage.reportsSub":
    "Tabla listing_reports. Coincidencias por id de reporte, listing id o texto en el motivo.",
  "opsPage.openQueueThisSearch": "Abrir cola con esta búsqueda →",
  "opsPage.openQueueFull": "Cola completa →",
  "opsPage.openInQueue": "Abrir en cola →",
  "opsPage.shortcutsTitle": "Atajos",
  "opsPage.shortcutUsers": "Usuarios",
  "opsPage.shortcutReports": "Reportes",
  "opsPage.shortcutClasificados": "Clasificados",
  "opsPage.shortcutTiendaOrders": "Pedidos Tienda",
  "opsPage.shortcutSupport": "Soporte / tickets",
  "opsPage.shortcutCategories": "Categorías",
  "opsPage.anonymousName": "(sin nombre)",
  "activityLog.badgeLive": "Supabase (admin_audit_log)",
  "activityLog.badgeEmptyTable": "Tabla lista · sin filas",
  "activityLog.badgeUnavailable": "Tabla no disponible",
  "activityLog.badgeNoEvents": "Sin eventos",
  "activityLog.subtitleLive": "Últimas filas desde `admin_audit_log` (acciones registradas por el servidor admin).",
  "activityLog.subtitleEmpty":
    "La tabla existe pero aún no hay eventos. Habilitar/deshabilitar usuarios y otras acciones empezarán a aparecer cuando se usen.",
  "activityLog.subtitleUnavailable":
    "Aplica la migración `20260410120000_admin_audit_log_and_team_invites.sql` en Supabase para habilitar el registro persistente. No se muestran filas de ejemplo.",
  "activityLog.subtitleUnknown": "Estado de auditoría desconocido.",
  "activityLog.helperNoSecrets":
    "No se guardan secretos ni enlaces de recuperación en esta tabla. Las mutaciones de anuncios en `listings` quedan en `listing_audit_event` (migración 20260423180000) para trazabilidad del vendedor.",
  "activityLog.detailPrefix": "Detalle:",
  "activityLog.bannerLive": "Filas reales — actor siempre «server» hasta que exista identidad de staff por fila.",
  "activityLog.bannerOther": "Sin datos de demostración: solo filas persistidas en Supabase.",
  "activityLog.emptyLive":
    "Aún no hay eventos auditables. Las acciones como habilitar/deshabilitar cuenta generarán filas aquí.",
  "activityLog.unavailableP1":
    "Cuando la tabla exista, verás aquí las acciones de staff registradas por el servidor. Mutaciones de clasificados en tabla `listings`: revisa",
  "activityLog.unavailableP2": "en Supabase o el panel del vendedor (lectura propia vía RLS).",
  "paymentsPage.badgeUnavailable": "Pedidos Tienda: no legible",
  "paymentsPage.badgeMeta": "Metadatos operativos (sin PCI)",
  "paymentsPage.badgePsp": "PSP / Stripe API: no conectado",
  "paymentsPage.subtitle":
    "Esta pantalla no procesa ni almacena tarjetas. Lo que ves aquí son proxies operativos desde pedidos Tienda en Supabase (estado de fulfillment) y enlaces a colas reales.",
  "paymentsPage.helperText":
    "Facturación con tarjeta / webhooks del procesador siguen fuera de Leonix hasta integración explícita. No pegues PAN, CVV ni datos magnéticos.",
  "paymentsPage.pciBanner":
    "Sin alcance PCI aquí: usa el dashboard del procesador para contracargos y métodos de pago. Leonix admin solo enlaza contexto operativo.",
  "paymentsPage.cardTiendaRows": "Pedidos Tienda (filas)",
  "paymentsPage.cardTiendaRowsBody":
    "Filas desde tienda_orders: checkout interno, no contabilidad de ingresos del PSP.",
  "paymentsPage.openTiendaInbox": "Abrir inbox Tienda →",
  "paymentsPage.cardPipeline": "En pipeline (aprox.)",
  "paymentsPage.cardPipelineBody":
    "Suma de new + reviewing + ready_to_fulfill + ordered — trabajo operativo pendiente de cerrar.",
  "paymentsPage.cardAttention": "Atención / fallos",
  "paymentsPage.cardAttentionBody": "needs_customer_followup + failed_submission.",
  "paymentsPage.cardUnread": "Inbox sin leer (admin)",
  "paymentsPage.cardUnreadBody": "Columna unread_admin — proxy de trabajo pendiente de revisar en Leonix.",
  "paymentsPage.cardEmailFailed": "Email de confirmación fallido",
  "paymentsPage.cardEmailFailedBody":
    "email_delivery_status = failed — revisar bandeja / logs, no es cobro PSP.",
  "paymentsPage.cardApproval": "Aprobación incompleta",
  "paymentsPage.cardApprovalBody":
    "approval_complete = false — checklist interno del pedido antes de fulfillment.",
  "paymentsPage.statusBreakdown": "Desglose por estado",
  "paymentsPage.futureTitle": "Qué controlará esta sección en el futuro",
  "paymentsPage.futureLi1": "Enlaces firmados al Customer Portal / dashboard Stripe (solo URLs; sin secretos en el cliente admin).",
  "paymentsPage.futureLi2": "Resúmenes de webhooks (fallos de cobro, disputas) cuando exista tabla dedicada.",
  "paymentsPage.futureLi3": "Búsqueda por customer ref / subscription id alineada al modelo de facturación real.",
  "paymentsPage.futureFoot": "Hoy, la trazabilidad operativa de pedidos está en",
  "paymentsPage.futureFootLink": "Tienda → pedidos",
  "paymentsPage.processorTitle": "Panel del procesador",
  "paymentsPage.processorHintBefore": "Opcional: define la variable de entorno",
  "paymentsPage.processorHintAfter": "con solo la URL base del dashboard (sin claves API).",
  "paymentsPage.openStripe": "Abrir dashboard Stripe ↗",
  "paymentsPage.noStripeUrl": "Sin URL configurada",
  "drawPage.stub": "Sin función",
  "drawPage.subtitle": "Esta ruta no es una herramienta de administración. No hay controles ni vista previa aquí.",
  "drawPage.helperText": "Si llegaste por un enlace antiguo, usa el panel principal o Secciones del sitio.",
  "drawPage.bodyLead": "El admin Leonix vive en",
  "drawPage.bodyTail": "— no en esta URL.",
  "drawPage.ctaDashboard": "Ir al Dashboard →",
  "drawPage.ctaWorkspace": "Secciones del sitio →",
  "reportsPage.subtitle": "listing_reports — revisar o descartar desde la tabla (acciones reales en base).",
  "reportsPage.helperFiltered":
    "Filtro activo: UUID busca por id de reporte, listing o reporter; texto busca en el motivo.",
  "reportsPage.helperDefault": "Usa ?q= en la URL para acotar (también desde Ops o ficha de usuario).",
  "reportsPage.searchLabel": "Buscar",
  "reportsPage.searchPlaceholder": "UUID (reporte / listing / reporter) o texto en motivo…",
  "reportsPage.searchHint": "UUID: reporte, anuncio o reporter. Texto libre: solo en el motivo.",
  "reportsPage.applyTitle": "Filtrar la tabla con el criterio indicado",
  "reportsPage.apply": "Aplicar filtro",
  "reportsPage.clearTitle": "Quitar filtro y ver todos los reportes recientes",
  "reportsPage.clear": "Limpiar búsqueda",
  "reportsPage.filteredNote": "Sobre resultados filtrados",
  "reportsTable.empty": "No hay reportes.",
  "reportsTable.errUpdate": "Error al actualizar",
  "reportsTable.colDate": "Fecha",
  "reportsTable.colListing": "Anuncio",
  "reportsTable.colReporter": "Reporter",
  "reportsTable.colReason": "Motivo",
  "reportsTable.colStatus": "Estado",
  "reportsTable.colActions": "Acciones",
  "reportsTable.openPublicTitle": "Abrir anuncio público en nueva pestaña",
  "reportsTable.openReporterTitle": "Ficha del usuario que reportó (Leonix admin)",
  "reportsTable.btnReviewedTitle": "Marca el reporte como revisado en listing_reports",
  "reportsTable.btnReviewedAria": "Marcar reporte como revisado",
  "reportsTable.btnReviewed": "Revisado",
  "reportsTable.btnDismissTitle": "Descarta el reporte (no implica borrar el anuncio)",
  "reportsTable.btnDismissAria": "Descartar reporte",
  "reportsTable.btnDismiss": "Descartar",
  "settingsPage.stub": "No persistido",
  "settingsPage.subtitle":
    "Esta página sigue siendo intencionalmente no persistente: no hay tabla Leonix de «site settings» genéricos. El tema y notas de coordinación viven en código / despliegue hasta que exista un modelo acordado.",
  "settingsPage.helperText":
    "Lo que sí persiste hoy: secciones del sitio (`site_section_content`), categorías (`site_category_config`), ajustes globales (`/admin/site-settings`), roster (`admin_team_members`), revista (`magazine_issues`), pedidos Tienda, etc.",
  "settingsPage.blockerLead": "Bloqueador para «guardar tema aquí»:",
  "settingsPage.blockerBody":
    "Haría falta una fila o tabla dedicada (p. ej. site_runtime_settings), políticas RLS, y lectura en el layout público sin romper caché. Hasta entonces, cualquier botón «Save» sería falso — por eso los campos siguen deshabilitados.",
  "settingsPage.linkGlobal": "Ajustes globales (persistidos) →",
  "settingsPage.linkWorkspace": "Mapa de workspaces →",
  "settingsPage.envRosterLi":
    "Permisos de roster opcionales: ADMIN_ENFORCE_ROSTER_PERMISSIONS + ADMIN_OPERATOR_EMAIL — ver Team.",
  "globalSitePage.title": "Ajustes globales del sitio",
  "globalSitePage.subtitle":
    "Avisos y franjas que pueden mostrarse en muchas páginas (debajo del menú principal). No sustituye al editor de la portada `/home`.",
  "globalSitePage.helperText":
    "Activa cada franja con la casilla y escribe texto. Idioma en el sitio: parámetro ?lang= (como el resto de páginas públicas).",
  "globalSitePage.homeEditorCta": "Editor Home `/home`",
  "globalSitePage.savedBanner": "Guardado.",
  "globalSitePage.readError": "No se pudo leer la base:",
  "globalSitePage.clasificadosLead":
    "Clasificados (En Venta, etc.): la publicación de anuncios ocurre en el flujo público de publicar y en el espacio de moderación",
  "globalSitePage.clasificadosTail":
    ". Esta pantalla solo guarda avisos globales del sitio (franjas bajo el menú), no crea ni aprueba anuncios.",
  "globalSitePage.updated": "Última actualización:",
  "globalSitePage.sectionMenu": "Región bajo el menú",
  "globalSitePage.sectionMenuBody":
    "Apaga todo el bloque de franjas (aviso + promo) sin borrar textos — útil en emergencias o pruebas de diseño.",
  "globalSitePage.toggleMenuBanners": "Mostrar franjas bajo la navegación",
  "globalSitePage.sectionNotice": "Aviso general (sitio)",
  "globalSitePage.sectionNoticeBody": "Línea informativa (horarios especiales, mantenimiento corto, etc.).",
  "globalSitePage.toggleNotice": "Mostrar aviso",
  "globalSitePage.labelNoticeEs": "Texto ES",
  "globalSitePage.labelNoticeEn": "Texto EN",
  "globalSitePage.sectionPromo": "Franja promocional global",
  "globalSitePage.sectionPromoBody": "Segunda franja opcional (tono promo / campaña). Independiente del aviso.",
  "globalSitePage.togglePromo": "Mostrar franja promo",
  "globalSitePage.labelPromoEs": "Texto ES",
  "globalSitePage.labelPromoEn": "Texto EN",
  "globalSitePage.submit": "Guardar ajustes globales",
  "globalSitePage.footer":
    "Código vs contenido: el menú, pie y estructura responsive siguen en código. Aquí solo se guardan textos y encendido/apagado de estas dos franjas.",
  "languageAudit.title": "Cobertura de idioma del admin",
  "languageAudit.intro":
    "Lista de verificación: cada área debe mostrar el chrome admin vía `adminMessages` / `useAdminT` (inglés por defecto; español con cookie ES). Se excluye texto de anuncios de usuarios.",
  "languageAudit.th.section": "Sección",
  "languageAudit.th.enDefault": "Inglés por defecto",
  "languageAudit.th.esToggle": "Toggle ES",
  "languageAudit.th.notes": "Notas",
  "languageAudit.section.dashboard": "Panel",
  "languageAudit.section.categories": "Categorías",
  "languageAudit.section.clasificadosWorkspace": "Workspace Clasificados",
  "languageAudit.section.clasificadosQueues": "Colas por categoría (Clasificados)",
  "languageAudit.section.restaurantesQueue": "Cola Restaurantes",
  "languageAudit.section.serviciosQueue": "Cola Servicios",
  "languageAudit.section.empleosQueue": "Cola Empleos",
  "languageAudit.section.autosQueue": "Cola Autos",
  "languageAudit.section.tienda": "Tienda",
  "languageAudit.section.users": "Usuarios",
  "languageAudit.section.payments": "Pagos",
  "languageAudit.section.support": "Soporte / ops cliente",
  "languageAudit.section.settings": "Ajustes / sitio global",
  "languageAudit.section.revista": "Workspace Revista",
  "languageAudit.notes.rowPass":
    "PASS — El chrome visible de esta área se resuelve con el diccionario admin compartido (EN por defecto; ES al elegirlo).",
};

export function adminTr(lang: AdminLang, key: string, vars?: Record<string, string | number>): string {
  const raw = (lang === "es" ? ES[key] : undefined) ?? EN[key] ?? key;
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}

export function adminMessages(lang: AdminLang) {
  return (key: string, vars?: Record<string, string | number>) => adminTr(lang, key, vars);
}
