import type { AdminLang } from "@/app/admin/_lib/adminI18nCookie";

/** Flat admin UI strings (chrome only). */
const EN: Record<string, string> = {
  "shell.leonixBrand": "Leonix",
  "shell.globalAdmin": "Global admin",
  "shell.leonixAdmin": "Leonix admin",
  "shell.signedInCookie": "Signed in via cookie",
  "shell.websiteSectionsLink": "Website sections (workspaces)",
  "shell.globalSiteSettingsLink": "Global site settings",
  "shell.viewSite": "View site →",
  "shell.searchListingsPlaceholder": "Search listings (title, city, ID)…",
  "shell.searchListingsTitle": "Open Clasificados workspace with this text as the filter",
  "shell.searchLabel": "Search",
  "shell.plusBadge": "✦ Leonix +admin",
  "shell.createClasificadosTitle": "Open the Clasificados queue (moderation and links)",
  "shell.create": "+ Create",
  "shell.tiendaTitleUnread": "Tienda (hub · inbox with alerts)",
  "shell.tiendaTitle": "Tienda — command center",
  "shell.tiendaAriaUnread": "Tienda, {n} unread",
  "shell.langAria": "Admin interface language",
  "shell.langEn": "English",
  "shell.langEs": "Spanish",
  "mobile.openMenu": "Open admin menu",
  "mobile.menuTitle": "Menu: Dashboard, users, workspaces…",
  "mobile.navDialog": "Admin navigation",
  "mobile.closeOverlay": "Close menu",
  "mobile.close": "Close",
  "mobile.globalNav": "Global administration",
  "workspaceNav.kicker": "Website sections",
  "workspaceNav.sub": "Admin-only workspaces — not the public menu.",
  "workspaceNav.overview": "Overview",
  "workspaceNav.aria": "Website section workspaces",
  "workspaceNav.link.home": "Home",
  "workspaceNav.link.clasificados": "Clasificados",
  "workspaceNav.link.tienda": "Tienda",
  "workspaceNav.link.nosotros": "Nosotros",
  "workspaceNav.link.revista": "Revista",
  "workspaceNav.link.contacto": "Contacto",
  "workspaceNav.link.noticias": "Noticias",
  "workspaceNav.link.iglesias": "Iglesias",
  "workspaceNav.link.cupones": "Cupones",
  "workspaceNav.link.anunciate": "Advertise",
  "nav.dashboard": "Dashboard",
  "nav.categories": "Categories",
  "nav.tienda": "Tienda",
  "nav.siteSections": "Site sections",
  "nav.viajes": "Viajes",
  "nav.users": "Users",
  "nav.customerOps": "Customer ops",
  "nav.payments": "Payments",
  "nav.support": "Support",
  "nav.team": "Team",
  "nav.activityLog": "Activity Log",
  "nav.settings": "Settings",
  "nav.languageAudit": "Language audit",
  "workspaceNav.home.hint": "Public route /home (magazine) — not the root / screen",
  "workspaceNav.clasificados.hint": "Ad moderation in Supabase",
  "workspaceNav.tienda.hint": "Storefront /tienda + catalog and orders links",
  "workspaceNav.nosotros.hint": "Public page /about",
  "workspaceNav.revista.hint": "Manifest editions.json + internal notes",
  "workspaceNav.contacto.hint": "Page /contacto (global form)",
  "workspaceNav.noticias.hint": "Shell in site_section_content; RSS stays in API",
  "workspaceNav.iglesias.hint": "Copy in site_section_content; directory backlog",
  "workspaceNav.cupones.hint": "cupones_page → /cupones and /coupons",
  "workspaceNav.anunciate.hint": "Map to publish funnel (Clasificados) + admin queue; not CRM",
  "common.apply": "Apply",
  "common.clear": "Clear",
  "common.applyFilters": "Apply filters",
  "common.allCategories": "All categories",
  "common.allStatuses": "All statuses",
  "common.rows": "rows",
  "cta.viewAds": "View ads",
  "cta.viewAdsTitle": "Open this category’s ad queue in the admin workspace",
  "cta.viewQueue": "View queue",
  "cta.viewQueueTitle": "Open this category’s operational queue in the admin workspace",
  "clasificados.title": "Clasificados — operations center",
  "clasificados.subtitle":
    "Above: category map (code schema + Supabase posture). Below: the global listings queue with filters — moderation, reports, and En Venta live here.",
  "clasificados.eyebrow": "Workspace · Clasificados",
  "clasificados.helper":
    "Pick a category for plans, fields, and shortcuts — or scroll to the queue. Postgres (up to {limit} rows): title, city, description, id, owner. BR/Rentas refine client-side via detail_pairs.",
  "clasificados.detailPairsMissingTitle": "Database missing listings.detail_pairs column.",
  "clasificados.detailPairsMissingBody":
    "Queue loads in reduced mode: the “En venta · vis.” column cannot show plan / renewal until you migrate. Apply migration",
  "clasificados.boostMissingTitle": "Database missing listings.boost_expires column.",
  "clasificados.boostMissingBody":
    "Queue loads without boost dates; “En venta · vis.” shows plan and lastRenew but not exact boost/renew until you migrate. Apply",
  "clasificados.homeChipsTitle": "Featured on `/home`:",
  "clasificados.homeChipsBody":
    "They are not auto-generated from this queue. In Home → content you can manually link categories or public routes (chips). Here you moderate ads in Supabase.",
  "clasificados.homeContentCta": "Home → content",
  "clasificados.brHintTitle": "Real-estate branches (BR / Rentas):",
  "clasificados.brHintBody":
    "When listings live in listings, use category and detail_pairs to distinguish sale vs rent, private vs business, and property type. Publish preview is not a public listing:",
  "clasificados.autosCta": "Autos (Leonix payments) →",
  "clasificados.autosTitle": "Table autos_classifieds_listings: payment and publish state on /clasificados/autos",
  "clasificados.serviciosCta": "Servicios (Supabase) →",
  "clasificados.serviciosTitle": "Queue Supabase: servicios_public_listings (sandbox tiers is separate)",
  "clasificados.categoriesCta": "Category registry →",
  "clasificados.categoriesTitle": "Visibility, order, and operational status (site_category_config)",
  "clasificados.reportesCta": "Reports →",
  "clasificados.reportesTitle": "Listing reports queue (listing_reports)",
  "clasificados.filterHint":
    "Search q: Leonix Ad ID (if column exists), listing or owner UUID, title, city, description, slug/URL, and profile match on owner name/email/phone. Respects category. BR/Rentas refine client-side on detail_pairs. limit 50–500 (default 300).",
  "clasificados.placeholderQ": "Leonix ID, UUID, title, owner, email/phone, URL…",
  "clasificados.placeholderOwner": "Owner ID (fragment)",
  "clasificados.leonixFilters": "Leonix BR / Rentas (detail_pairs)",
  "clasificados.branchAll": "Branch (all)",
  "clasificados.operationAll": "Operation (all)",
  "clasificados.operationSale": "sale (for sale)",
  "clasificados.operationRent": "rent (for rent)",
  "clasificados.propTypeAll": "Property type (all)",
  "clasificados.limitTitle": "Maximum listings to fetch from Supabase in this view",
  "clasificados.limitAria": "Row limit",
  "clasificados.applyFiltersTitle": "Reload the queue with URL filters (read-only)",
  "clasificados.backWorkspace": "← Site sections overview",
  "clasificados.envSectionTitle": "En Venta — moderation reference",
  "clasificados.envSectionSubtitle":
    "Reference only (reason list). Does not write to the database — documentation for the team.",
  "audit.title": "Operational audit — queues by category",
  "audit.intro":
    "TRUE/FALSE values are computed when this page loads (real Supabase queries and the same helpers as the queue). If something fails, the Reason column shows the Postgres/PostgREST error or limitation.",
  "audit.th.slug": "Slug",
  "audit.th.queue": "Admin queue",
  "audit.th.source": "Source",
  "audit.th.load": "Load",
  "audit.th.search": "Search",
  "audit.th.public": "Public link",
  "audit.th.moderate": "Moderate",
  "audit.th.rows": "Rows (approx.)",
  "audit.th.reason": "Reason if FALSE",
  "audit.true": "TRUE",
  "audit.false": "FALSE",
  "audit.boolTitleTrue": "Verified at page load",
  "audit.boolTitleFalse": "See reason column",
  "hub.title": "Categories — control center",
  "hub.intro":
    "Each card reflects the in-code schema key categorySchema and operational posture merged from Supabase. Open a category space for plans, fields, preview, and shortcuts to the filtered queue.",
  "hub.categoriesRegistry": "Category registry (order / visibility) →",
  "hub.restLink": "Public listings table (DB) →",
  "hub.editorEnVenta": "Content editor →",
  "hub.editorOther": "Fields & notes (DB) →",
  "hub.opsSpace": "Operational space →",
  "hub.queueFiltered": "Ad queue (filtered)",
  "hub.queueFilteredTitle": "Opens the real operational queue: dedicated vertical (Restaurantes/Servicios/Empleos/Autos) or listings queue with filter.",
  "hub.standardLive": "Live standard",
  "hub.plans": "Plans",
  "hub.fields": "Fields",
  "hub.fieldGroup": "group",
  "hub.preview": "Preview",
  "hub.proPreview": "Pro preview",
  "hub.yes": "yes",
  "hub.no": "no",
  "hub.readiness": "Readiness",
  "hub.restDbLink": "Public listings table (DB) →",
  "listings.col.id": "ID",
  "listings.col.leonixId": "Leonix Ad ID",
  "listings.col.title": "Title",
  "listings.col.category": "Category",
  "listings.col.city": "City",
  "listings.col.price": "Price",
  "listings.col.status": "Status",
  "listings.col.owner": "Owner",
  "listings.col.date": "Date",
  "listings.col.leonix": "Leonix",
  "listings.col.envVis": "En venta · vis.",
  "listings.col.actions": "Actions",
  "listings.free": "Free",
  "listings.ownerCard": "Seller profile",
  "listings.viewPublic": "View public",
  "listings.viewRentas": "View public (Rentas)",
  "listings.inspectorRentas": "Rentas inspector",
  "listings.hidePublic": "Hide from site",
  "listings.republish": "Republish on site",
  "listings.deleteStaff": "Delete (staff)",
  "listings.emptyGlobal": "No listings match the current filters.",
  "listings.emptyCategoryTitle": "No published listings found for this category.",
  "listings.emptyCategoryBody":
    "Active filter targets public.listings.category (case-insensitive) = {slug}{rentasExtra}. Check the category dropdown for actual DB values, or open the dedicated vertical queue (Servicios, Empleos, Autos, Restaurantes) if this category stores ads outside listings.",
  "listings.emptyRentasExtra":
    ", plus merged rows with category «bienes-raices» and Leonix:operation=rent in detail_pairs when there is no text search (q).",
  "listings.col.leonixTitle": "Leonix BR/Rentas: branch, operation, category, published",
  "listings.col.envVisTitleOk": "En Venta plan and visibility (detail_pairs + boost_expires)",
  "listings.col.envVisTitleNoDetailPairs":
    "detail_pairs column not available in this database — apply listings.detail_pairs migration",
  "listings.col.envVisTitleNoBoost": "boost_expires column not available — apply listings_engagement_boost migration",
  "listings.rowActionsTitle":
    "Staff actions on this row (publish/hide/delete). Text and image editing: advertiser panel with owner_id validation.",
  "listings.publicRentasTitle": "Public Rentas detail (canonical path)",
  "listings.publicGenericTitle": "Open listing on public site (new tab)",
  "listings.hidePublicTitle": "Hide from public listings (is_published=false). En Venta / results stop showing it.",
  "listings.republishTitle": "Publish again on the site (is_published=true) if status remains active.",
  "listings.deleteTitle": "Mark listing as removed in database (staff action; appears in audit)",
  "listings.deleteAria": "Mark listing as deleted in database",
  "listings.confirmDelete": "Mark this listing as removed?",
  "listings.errDelete": "Could not delete",
  "listings.confirmHide": "Hide this listing from the public site (is_published=false)? It remains visible to staff.",
  "listings.confirmShow": "Show this listing on the site again (is_published=true)?",
  "listings.errPublish": "Could not update publication",
  "listings.envLine.missingDetailPairs": "N/A · listings.detail_pairs column missing in DB",
  "listings.envLine.boostNoCol": "boost N/A (no boost_expires column)",
  "listings.envLine.boostOff": "boost off",
  "listings.envLine.lastRenew": "lastRenew",
  "listings.envLine.renewNd": "renew N/A",
  "listings.envLine.renewOk": "renew OK",
  "listings.envLine.renewDash": "renew —",
  "languageAudit.title": "Admin language coverage",
  "languageAudit.intro":
    "Honest checklist for interface copy (not user-generated listing text). “English default” means first paint with cookie unset is English. “ES toggle” means cookie + refresh switches chrome to Spanish where keys exist.",
  "languageAudit.th.section": "Section",
  "languageAudit.th.enDefault": "English default",
  "languageAudit.th.esToggle": "ES toggle",
  "languageAudit.th.notes": "Notes",
  "languageAudit.section.dashboard": "Dashboard",
  "languageAudit.section.categories": "Categories",
  "languageAudit.section.clasificadosWorkspace": "Clasificados workspace",
  "languageAudit.section.clasificadosQueues": "Clasificados category queues",
  "languageAudit.section.restaurantesQueue": "Restaurantes queue",
  "languageAudit.section.serviciosQueue": "Servicios queue",
  "languageAudit.section.empleosQueue": "Empleos queue",
  "languageAudit.section.autosQueue": "Autos queue",
  "languageAudit.section.tienda": "Tienda",
  "languageAudit.section.users": "Users",
  "languageAudit.section.payments": "Payments",
  "languageAudit.section.support": "Support / customer ops",
  "languageAudit.section.settings": "Settings / global site",
  "languageAudit.notes.dashboard":
    "Shell, sidebar, top bar, and language toggle use the shared dictionary. The home dashboard body (category cards, Tienda preview, Revista block, data-honesty footer) still contains Spanish or mixed hardcoded strings in `page.tsx`.",
  "languageAudit.notes.categories":
    "Page chrome, badges, table headers, and shortcuts are still largely Spanish in `categories/page.tsx` (only queue CTA labels use the shared helper).",
  "languageAudit.notes.clasificadosWorkspace":
    "Main workspace page, category hub, operational audit table, filters, and listings table use `adminMessages` / `useAdminT` after the latest pass.",
  "languageAudit.notes.clasificadosQueues":
    "Generic `?category=` queue shares the listings table i18n. Dedicated vertical pages (servicios, empleos, autos, restaurantes, rentas sub-routes) still have local Spanish UI in their own TSX files.",
  "languageAudit.notes.restaurantesQueue":
    "Row actions and table copy on the Restaurantes admin route are not fully migrated to `adminStrings` yet.",
  "languageAudit.notes.serviciosQueue":
    "Workspace servicios queue page still ships Spanish labels and actions.",
  "languageAudit.notes.empleosQueue":
    "Empleos queue page still ships Spanish labels and actions.",
  "languageAudit.notes.autosQueue":
    "Autos admin workspace pages still ship Spanish or mixed copy outside shared chrome.",
  "languageAudit.notes.tienda":
    "Tienda orders UI uses some localized components; workspace hub `workspace/tienda/page.tsx` is still Spanish-first.",
  "languageAudit.notes.users":
    "User list and profile pages still contain Spanish labels and helper strings.",
  "languageAudit.notes.payments":
    "Payments admin routes were not exhaustively migrated in this pass; verify with a repo search for Spanish literals.",
  "languageAudit.notes.support":
    "Ops, reportes, and related customer-ops pages still contain extensive Spanish copy.",
  "languageAudit.notes.settings":
    "Per-section content editors (home, cupones, nosotros, etc.) still mix Spanish field labels and helper text.",
};

const ES: Record<string, string> = {
  ...EN,
  "shell.globalAdmin": "Admin global",
  "shell.leonixAdmin": "Admin Leonix",
  "shell.signedInCookie": "Sesión vía cookie",
  "shell.websiteSectionsLink": "Secciones del sitio (workspaces)",
  "shell.globalSiteSettingsLink": "Ajustes globales del sitio",
  "shell.viewSite": "Ver sitio →",
  "shell.searchListingsPlaceholder": "Buscar anuncios (título, ciudad, ID)…",
  "shell.searchListingsTitle": "Abrir workspace Clasificados con este texto como filtro",
  "shell.searchLabel": "Buscar",
  "shell.createClasificadosTitle": "Ir a la cola de Clasificados (moderación y enlaces)",
  "shell.tiendaTitleUnread": "Tienda (hub · inbox con avisos)",
  "shell.tiendaTitle": "Tienda — centro de comando",
  "shell.tiendaAriaUnread": "Tienda, {n} sin leer",
  "shell.langAria": "Idioma de la interfaz admin",
  "shell.langEn": "Inglés",
  "shell.langEs": "Español",
  "mobile.openMenu": "Abrir menú admin",
  "mobile.menuTitle": "Menú: Dashboard, usuarios, workspaces…",
  "mobile.navDialog": "Navegación admin",
  "mobile.closeOverlay": "Cerrar menú",
  "mobile.close": "Cerrar",
  "mobile.globalNav": "Administración global",
  "workspaceNav.kicker": "Secciones del sitio",
  "workspaceNav.sub": "Workspaces solo admin — no el menú público.",
  "workspaceNav.overview": "Resumen",
  "workspaceNav.aria": "Workspaces por sección del sitio",
  "workspaceNav.link.home": "Home",
  "workspaceNav.link.clasificados": "Clasificados",
  "workspaceNav.link.tienda": "Tienda",
  "workspaceNav.link.nosotros": "Nosotros",
  "workspaceNav.link.revista": "Revista",
  "workspaceNav.link.contacto": "Contacto",
  "workspaceNav.link.noticias": "Noticias",
  "workspaceNav.link.iglesias": "Iglesias",
  "workspaceNav.link.cupones": "Cupones",
  "workspaceNav.link.anunciate": "Anúnciate",
  "nav.dashboard": "Panel",
  "nav.categories": "Categorías",
  "nav.siteSections": "Secciones del sitio",
  "nav.users": "Usuarios",
  "nav.customerOps": "Operaciones cliente",
  "nav.payments": "Pagos",
  "nav.support": "Soporte",
  "nav.team": "Equipo",
  "nav.activityLog": "Registro de actividad",
  "nav.settings": "Ajustes",
  "nav.languageAudit": "Auditoría de idioma",
  "workspaceNav.home.hint": "Ruta pública /home (revista) — no la pantalla raíz /",
  "workspaceNav.clasificados.hint": "Moderación de anuncios en Supabase",
  "workspaceNav.tienda.hint": "Vitrina /tienda + enlaces al catálogo y pedidos",
  "workspaceNav.nosotros.hint": "Página pública /about",
  "workspaceNav.revista.hint": "Manifiesto editions.json + notas internas",
  "workspaceNav.contacto.hint": "Página /contacto (formulario global)",
  "workspaceNav.noticias.hint": "Shell en site_section_content; RSS sigue en API",
  "workspaceNav.iglesias.hint": "Copy en site_section_content; directorio = backlog",
  "workspaceNav.cupones.hint": "cupones_page → /cupones y /coupons",
  "workspaceNav.anunciate.hint": "Mapa al funnel publicar (Clasificados) + cola admin; sin CRM",
  "common.apply": "Aplicar",
  "common.clear": "Limpiar",
  "common.applyFilters": "Aplicar filtros",
  "common.allCategories": "Todas las categorías",
  "common.allStatuses": "Todos los estados",
  "common.rows": "filas",
  "cta.viewAds": "Ver anuncios",
  "cta.viewAdsTitle": "Abrir cola de anuncios de esta categoría en el workspace admin",
  "cta.viewQueue": "Ver cola",
  "cta.viewQueueTitle": "Abrir cola operativa de esta categoría en el workspace admin",
  "clasificados.title": "Clasificados — centro de operaciones",
  "clasificados.subtitle":
    "Arriba: mapa por categoría (esquema en código + postura en Supabase). Abajo: la misma cola global de anuncios con filtros — moderación, reportes y En Venta siguen aquí.",
  "clasificados.eyebrow": "Workspace · Clasificados",
  "clasificados.helper":
    "Elige una categoría para ver planes, campos y atajos; o baja directo a la cola. Postgres (hasta {limit} filas): título, ciudad, descripción, id y owner. BR/Rentas refinan en cliente vía detail_pairs.",
  "clasificados.detailPairsMissingTitle": "Base sin columna listings.detail_pairs.",
  "clasificados.detailPairsMissingBody":
    "La cola carga en modo reducido: la columna “En venta · vis.” no puede mostrar plan / renovación hasta migrar. Aplica en Supabase la migración",
  "clasificados.boostMissingTitle": "Base sin columna listings.boost_expires.",
  "clasificados.boostMissingBody":
    "La cola carga sin fechas de boost; la columna “En venta · vis.” muestra plan y lastRenew pero no el estado exacto de boost/renew hasta migrar. Aplica",
  "clasificados.homeChipsTitle": "Destacados en la portada `/home`:",
  "clasificados.homeChipsBody":
    "No se generan solos desde esta cola. En Home → contenido puedes enlazar manualmente a categorías o rutas públicas (chips). Aquí moderas anuncios en Supabase.",
  "clasificados.homeContentCta": "Home → contenido",
  "clasificados.brHintTitle": "Ramas inmobiliarias (BR / Rentas):",
  "clasificados.brHintBody":
    "Cuando los listados vivan en listings, usa category y detail_pairs para distinguir venta vs renta, Privado vs Negocio y tipo de propiedad. Vista previa de publicación no es listado público:",
  "clasificados.autosCta": "Autos (pagos Leonix) →",
  "clasificados.serviciosCta": "Servicios (Supabase) →",
  "clasificados.categoriesCta": "Registro de categorías →",
  "clasificados.reportesCta": "Reportes →",
  "clasificados.filterHint":
    "Búsqueda q: Leonix Ad ID (si existe columna), UUID de anuncio u owner, título, ciudad, descripción, slug/URL, y coincidencia por nombre / correo / teléfono del perfil (owner). Respeta category. BR/Rentas refinan en cliente sobre detail_pairs. limit 50–500 (default 300).",
  "clasificados.placeholderQ": "Leonix ID, UUID, título, owner, email/teléfono, URL…",
  "clasificados.placeholderOwner": "Owner ID (fragmento)",
  "clasificados.leonixFilters": "Leonix BR / Rentas (detail_pairs)",
  "clasificados.branchAll": "Rama (todas)",
  "clasificados.operationAll": "Operación (todas)",
  "clasificados.operationSale": "sale (venta)",
  "clasificados.operationRent": "rent (renta)",
  "clasificados.propTypeAll": "Tipo propiedad (todas)",
  "clasificados.limitTitle": "Máximo de anuncios a traer de Supabase en esta vista",
  "clasificados.limitAria": "Límite de filas",
  "clasificados.applyFiltersTitle": "Recargar la cola con los filtros en la URL (sin mutar datos)",
  "clasificados.backWorkspace": "← Resumen de secciones del sitio",
  "clasificados.envSectionTitle": "En Venta — contrato de moderación",
  "clasificados.envSectionSubtitle":
    "Solo referencia (lista de motivos). No envía cambios a la base — documentación para el equipo.",
  "audit.title": "Auditoría operativa — colas por categoría",
  "audit.intro":
    "Valores TRUE/FALSE se calculan al cargar esta página (consultas reales a Supabase y los mismos helpers que usa la cola). Si algo falla, la columna «Motivo» indica el error de Postgres/PostgREST o la limitación exacta.",
  "audit.th.slug": "Slug",
  "audit.th.queue": "Cola admin",
  "audit.th.source": "Fuente",
  "audit.th.load": "Cargar",
  "audit.th.search": "Buscar",
  "audit.th.public": "Link público",
  "audit.th.moderate": "Moderar",
  "audit.th.rows": "Filas (aprox.)",
  "audit.th.reason": "Motivo si FALSE",
  "audit.true": "TRUE",
  "audit.false": "FALSE",
  "audit.boolTitleTrue": "Verificado al cargar la página",
  "audit.boolTitleFalse": "Ver columna de motivo",
  "hub.title": "Categorías — centro de control",
  "hub.intro":
    "Cada tarjeta refleja la clave de esquema categorySchema en código y la postura operativa fusionada con Supabase. Abre el espacio de una categoría para ver planes, campos, vista previa y atajos a la cola filtrada.",
  "hub.categoriesRegistry": "Registro de categorías (orden / visibilidad) →",
  "hub.restLink": "Tabla listados públicos (DB) →",
  "hub.editorEnVenta": "Editor de contenido →",
  "hub.editorOther": "Campos & notas (BD) →",
  "hub.opsSpace": "Espacio operativo →",
  "hub.queueFiltered": "Cola de anuncios (filtrada)",
  "hub.queueFilteredTitle":
    "Abre la cola operativa real: vertical dedicada (Restaurantes/Servicios/Empleos/Autos) o cola listings filtrada.",
  "hub.standardLive": "Estándar vivo",
  "hub.plans": "Planes",
  "hub.fields": "Campos",
  "hub.fieldGroup": "grupo",
  "hub.preview": "Preview",
  "hub.proPreview": "Pro preview",
  "hub.yes": "sí",
  "hub.no": "no",
  "hub.readiness": "Readiness",
  "hub.restDbLink": "Tabla listados públicos (DB) →",
  "listings.col.id": "ID",
  "listings.col.leonixId": "Leonix Ad ID",
  "listings.col.title": "Título",
  "listings.col.category": "Categoría",
  "listings.col.city": "Ciudad",
  "listings.col.price": "Precio",
  "listings.col.status": "Estado",
  "listings.col.owner": "Owner",
  "listings.col.date": "Fecha",
  "listings.col.leonix": "Leonix",
  "listings.col.envVis": "En venta · vis.",
  "listings.col.actions": "Acciones",
  "listings.free": "Gratis",
  "listings.ownerCard": "Ficha vendedor",
  "listings.viewPublic": "Ver público",
  "listings.viewRentas": "Ver público (Rentas)",
  "listings.inspectorRentas": "Inspector Rentas",
  "listings.hidePublic": "Ocultar del público",
  "listings.republish": "Republicar en sitio",
  "listings.deleteStaff": "Eliminar (staff)",
  "listings.emptyGlobal": "No hay anuncios en la cola global con los filtros actuales.",
  "listings.emptyCategoryTitle": "No se encontraron anuncios publicados para esta categoría.",
  "listings.emptyCategoryBody":
    "Filtro activo: public.listings.category (sin mayúsculas) = {slug}{rentasExtra}. Revisa el menú desplegable para valores reales en BD, o abre la cola dedicada (Servicios, Empleos, Autos, Restaurantes) si esta categoría guarda anuncios fuera de listings.",
  "listings.emptyRentasExtra":
    ", más filas con categoría «bienes-raices» y Leonix:operation=rent en detail_pairs cuando no hay búsqueda de texto (q).",
  "listings.col.leonixTitle": "Leonix BR/Rentas: rama, operación, categoría, publicado",
  "listings.col.envVisTitleOk": "Plan En Venta y visibilidad (detail_pairs + boost_expires)",
  "listings.col.envVisTitleNoDetailPairs":
    "Columna detail_pairs no disponible en esta base — aplica la migración listings.detail_pairs",
  "listings.col.envVisTitleNoBoost": "Columna boost_expires no disponible — aplica la migración listings_engagement_boost",
  "listings.rowActionsTitle":
    "Acciones de staff en la misma fila (publicar/ocultar/eliminar). Edición de texto e imágenes: panel del anunciante con validación owner_id.",
  "listings.publicRentasTitle": "Detalle público Rentas (ruta canónica)",
  "listings.publicGenericTitle": "Abrir anuncio en el sitio público (nueva pestaña)",
  "listings.hidePublicTitle": "Oculta del listado público (is_published=false). En Venta / resultados dejan de mostrarlo.",
  "listings.republishTitle": "Vuelve a publicar en el sitio (is_published=true) si el estado sigue activo.",
  "listings.deleteTitle": "Marca el anuncio como removed en base (acción de staff; aparece en auditoría)",
  "listings.deleteAria": "Marcar anuncio como eliminado en base de datos",
  "listings.confirmDelete": "¿Marcar este anuncio como eliminado (removed)?",
  "listings.errDelete": "Error al eliminar",
  "listings.confirmHide": "¿Ocultar este anuncio del sitio público (is_published=false)? Sigue visible para staff.",
  "listings.confirmShow": "¿Volver a mostrar este anuncio en el sitio (is_published=true)?",
  "listings.errPublish": "Error al actualizar publicación",
  "listings.envLine.missingDetailPairs": "N/D · falta columna detail_pairs en BD",
  "listings.envLine.boostNoCol": "boost N/D (sin columna boost_expires)",
  "listings.envLine.boostOff": "boost off",
  "listings.envLine.lastRenew": "lastRenew",
  "listings.envLine.renewNd": "renew N/D",
  "listings.envLine.renewOk": "renew OK",
  "listings.envLine.renewDash": "renew —",
  "languageAudit.title": "Cobertura de idioma del admin",
  "languageAudit.intro":
    "Lista honesta del copy de interfaz (no el texto de anuncios de usuarios). “Inglés por defecto” = primera carga sin cookie en inglés. “Toggle ES” = cookie + refresh cambia el chrome al español donde existan claves.",
  "languageAudit.th.section": "Sección",
  "languageAudit.th.enDefault": "Inglés por defecto",
  "languageAudit.th.esToggle": "Toggle ES",
  "languageAudit.th.notes": "Notas",
  "languageAudit.section.dashboard": "Panel",
  "languageAudit.section.categories": "Categorías",
  "languageAudit.section.clasificadosWorkspace": "Workspace Clasificados",
  "languageAudit.section.clasificadosQueues": "Colas por categoría (Clasificados)",
  "languageAudit.section.restaurantesQueue": "Cola Restaurantes",
  "languageAudit.section.serviciosQueue": "Cola Servicios",
  "languageAudit.section.empleosQueue": "Cola Empleos",
  "languageAudit.section.autosQueue": "Cola Autos",
  "languageAudit.section.tienda": "Tienda",
  "languageAudit.section.users": "Usuarios",
  "languageAudit.section.payments": "Pagos",
  "languageAudit.section.support": "Soporte / ops cliente",
  "languageAudit.section.settings": "Ajustes / sitio global",
  "languageAudit.notes.dashboard":
    "Chrome compartido (nav, shell, toggle) usa diccionario. El cuerpo del panel principal (tarjetas de categorías, Tienda, Revista, pie de «data honesty») sigue con cadenas fijas en español o mixtas en `page.tsx`.",
  "languageAudit.notes.categories":
    "Badges, encabezados de tabla y atajos siguen mayormente en español en `categories/page.tsx` (solo los CTAs de cola usan el helper compartido).",
  "languageAudit.notes.clasificadosWorkspace":
    "Página principal del workspace, hub de categorías, tabla de auditoría operativa, filtros y tabla de anuncios pasan por `adminMessages` / `useAdminT` en el último bloque de trabajo.",
  "languageAudit.notes.clasificadosQueues":
    "La cola genérica `?category=` comparte la tabla i18n. Rutas verticales dedicadas (servicios, empleos, autos, restaurantes, rentas…) aún tienen UI local en español en sus TSX.",
  "languageAudit.notes.restaurantesQueue":
    "Acciones por fila y textos de la cola Restaurantes aún no están totalmente en `adminStrings`.",
  "languageAudit.notes.serviciosQueue":
    "La cola Servicios en workspace sigue con etiquetas y acciones en español.",
  "languageAudit.notes.empleosQueue":
    "La cola Empleos sigue con etiquetas y acciones en español.",
  "languageAudit.notes.autosQueue":
    "Páginas admin de Autos siguen con copy en español o mixto fuera del chrome compartido.",
  "languageAudit.notes.tienda":
    "Pedidos Tienda mezcla componentes; el hub `workspace/tienda/page.tsx` sigue orientado a español.",
  "languageAudit.notes.users":
    "Listado y ficha de usuario conservan muchas cadenas en español.",
  "languageAudit.notes.payments":
    "Rutas de pagos no revisadas exhaustivamente en este paso; buscar literales en español en el repo.",
  "languageAudit.notes.support":
    "Ops, reportes y flujos relacionados conservan mucho copy en español.",
  "languageAudit.notes.settings":
    "Editores por sección (home, cupones, etc.) mezclan etiquetas de formulario y ayudas en español.",
};

export function adminTr(lang: AdminLang, key: string, vars?: Record<string, string | number>): string {
  const raw = (lang === "es" ? ES[key] : undefined) ?? EN[key] ?? key;
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}

export function adminMessages(lang: AdminLang) {
  return (key: string, vars?: Record<string, string | number>) => adminTr(lang, key, vars);
}
