import type { AdminDashboardCtaVariant } from "../_components/AdminDashboardCta";
import type { AdminTruthStatus } from "../_components/AdminPagePurposeCard";

export type AdminActionRiskLevel = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";

export type AdminActionKey =
  | "viewPublic"
  | "editListing"
  | "manageListing"
  | "viewResults"
  | "suspend"
  | "restore"
  | "archive"
  | "republish"
  | "feature"
  | "verifyLeonix"
  | "runAiReview"
  | "markReviewed"
  | "clearFlag"
  | "delete"
  | "permanentDelete"
  | "publishIssue"
  | "archiveIssue"
  | "saveDraft"
  | "exportCsv"
  | "sendPasswordReset"
  | "assignStaff";

export type AdminActionContract = {
  key: AdminActionKey;
  label: string;
  title: string;
  description: string;
  whatItDoes: string;
  dataTouched: string;
  status: AdminTruthStatus;
  riskLevel: AdminActionRiskLevel;
  dangerous: boolean;
  confirmationRecommended: boolean;
  auditRecommended: boolean;
  variant: AdminDashboardCtaVariant;
  helperCopy: string;
  nextGate: string;
};

export const ADMIN_OS_ACTION_REGISTRY: Record<AdminActionKey, AdminActionContract> = {
  viewPublic: {
    key: "viewPublic",
    label: "View public",
    title: "View public listing",
    description: "Open the customer-facing listing or page for visual inspection.",
    whatItDoes: "Navigates to the public URL. It does not change data.",
    dataTouched: "No write. Reads public route state.",
    status: "real",
    riskLevel: "LOW",
    dangerous: false,
    confirmationRecommended: false,
    auditRecommended: false,
    variant: "view",
    helperCopy: "Use this to confirm the public page renders after edits or lifecycle changes.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  editListing: {
    key: "editListing",
    label: "Edit listing",
    title: "Edit listing",
    description: "Open a staff or owner edit flow for a listing when that category supports it.",
    whatItDoes: "Loads editable listing fields. It should preserve listing identity and Leonix Ad ID.",
    dataTouched: "Writes only after the edit form is saved.",
    status: "partial",
    riskLevel: "MEDIUM",
    dangerous: false,
    confirmationRecommended: false,
    auditRecommended: true,
    variant: "primary",
    helperCopy: "Category edit fidelity varies; use preview/public view after saving.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  manageListing: {
    key: "manageListing",
    label: "Manage listing",
    title: "Manage listing",
    description: "Open the operator tools for one listing.",
    whatItDoes: "Groups safe inspect/edit/lifecycle tools without changing data by itself.",
    dataTouched: "No write until an inner action is submitted.",
    status: "partial",
    riskLevel: "LOW",
    dangerous: false,
    confirmationRecommended: false,
    auditRecommended: false,
    variant: "primary",
    helperCopy: "Use this when you need the listing toolbox, not a public preview.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  viewResults: {
    key: "viewResults",
    label: "View in results",
    title: "View in results",
    description: "Open the category results page to check discoverability.",
    whatItDoes: "Navigates to a search/results page. It does not change listing data.",
    dataTouched: "No write. Reads public results route state.",
    status: "partial",
    riskLevel: "LOW",
    dangerous: false,
    confirmationRecommended: false,
    auditRecommended: false,
    variant: "view",
    helperCopy: "Visibility still needs a dedicated Listing Visibility Checker gate.",
    nextGate: "ADMIN-LISTING-VISIBILITY-CHECKER-01",
  },
  suspend: {
    key: "suspend",
    label: "Suspend",
    title: "Suspend listing",
    description: "Temporarily remove or reduce public visibility for a listing.",
    whatItDoes: "Updates lifecycle/status fields through the existing category admin API.",
    dataTouched: "Source listing table status fields.",
    status: "partial",
    riskLevel: "HIGH",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "warning",
    helperCopy: "Use when a listing should stop showing while preserving history.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  restore: {
    key: "restore",
    label: "Restore",
    title: "Restore listing",
    description: "Undo a suspension or inactive state when the listing is safe to show again.",
    whatItDoes: "Restores visibility state. It is not the same as Republish or Move to top.",
    dataTouched: "Source listing table status fields.",
    status: "partial",
    riskLevel: "MEDIUM",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "active",
    helperCopy: "Use Restore for visibility recovery, not ranking boost.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  archive: {
    key: "archive",
    label: "Archive",
    title: "Archive listing",
    description: "Soft-remove an item from active operations while preserving history.",
    whatItDoes: "Moves the row out of the active workflow without permanently deleting proof.",
    dataTouched: "Source row lifecycle/status/archive fields.",
    status: "partial",
    riskLevel: "HIGH",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "neutral",
    helperCopy: "Archive is the preferred safe removal action for most ops work.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  republish: {
    key: "republish",
    label: "Republish",
    title: "Republish / move to top",
    description: "Refresh listing placement when the category supports a republish window.",
    whatItDoes: "Updates republish timestamp/count fields; it should not rewrite listing content.",
    dataTouched: "republished_at, republish_count, and category-specific republish fields.",
    status: "needs live proof",
    riskLevel: "MEDIUM",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "neutral",
    helperCopy: "Requires live proof for every source table before being treated as fully ready.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  feature: {
    key: "feature",
    label: "Feature",
    title: "Feature listing",
    description: "Control premium placement or spotlight treatment where supported.",
    whatItDoes: "Toggles promote/featured fields. It should not change public listing content.",
    dataTouched: "promoted/admin_promoted columns and package entitlement context.",
    status: "needs live proof",
    riskLevel: "HIGH",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "premium",
    helperCopy: "Feature needs live schema proof and package/payment alignment before launch confidence.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  verifyLeonix: {
    key: "verifyLeonix",
    label: "Verify Leonix",
    title: "Verify Leonix",
    description: "Apply a staff trust signal. Clients cannot self-verify.",
    whatItDoes: "Toggles Leonix verification fields after staff review.",
    dataTouched: "leonix_verified columns and related audit context.",
    status: "needs live proof",
    riskLevel: "HIGH",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "active",
    helperCopy: "Use only after the business/listing has been reviewed by staff.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  runAiReview: {
    key: "runAiReview",
    label: "Run AI review",
    title: "Run AI review",
    description: "Review listing content for policy risk using the existing AI moderation flow.",
    whatItDoes: "Writes review output when provider and listing_moderation_reviews are ready. It does not auto-delete.",
    dataTouched: "listing_moderation_reviews and source listing context.",
    status: "needs live proof",
    riskLevel: "HIGH",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "warning",
    helperCopy: "AI review is advisory until live provider/schema proof is complete.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  markReviewed: {
    key: "markReviewed",
    label: "Mark reviewed",
    title: "Mark reviewed",
    description: "Record that staff reviewed a report, flag, or moderation item.",
    whatItDoes: "Should update review/resolution status without hiding history.",
    dataTouched: "listing_reports, listing_moderation_reviews, or category status fields.",
    status: "partial",
    riskLevel: "MEDIUM",
    dangerous: false,
    confirmationRecommended: false,
    auditRecommended: true,
    variant: "warning",
    helperCopy: "Some report resolution actions still need a complete proof pass.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  clearFlag: {
    key: "clearFlag",
    label: "Clear flag",
    title: "Clear flag",
    description: "Clear a review flag only after staff confirms the listing is safe.",
    whatItDoes: "Should update report/flag state while retaining the audit trail.",
    dataTouched: "listing_reports or source listing moderation fields.",
    status: "partial",
    riskLevel: "HIGH",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "warning",
    helperCopy: "Do not clear flags just to silence a queue; document the reason.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  delete: {
    key: "delete",
    label: "Delete",
    title: "Delete / remove",
    description: "Soft-delete or remove an item from normal display when the action is category-supported.",
    whatItDoes: "Usually marks deleted/removed instead of wiping the record.",
    dataTouched: "deleted_at/status fields on the source table.",
    status: "partial",
    riskLevel: "HIGH",
    dangerous: true,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "danger",
    helperCopy: "Prefer Archive unless deletion is required by policy or cleanup.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  permanentDelete: {
    key: "permanentDelete",
    label: "Permanent delete",
    title: "Permanent delete",
    description: "Irreversibly remove data. This must stay visually separated and protected.",
    whatItDoes: "Deletes records instead of marking them inactive.",
    dataTouched: "Source table rows and related assets where implemented.",
    status: "partial",
    riskLevel: "CRITICAL",
    dangerous: true,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "danger",
    helperCopy: "Use only for protected cleanup cases after QA confirms safeguards.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  publishIssue: {
    key: "publishIssue",
    label: "Publish issue",
    title: "Publish magazine issue",
    description: "Move a magazine issue from draft to public manifest eligibility.",
    whatItDoes: "Updates magazine issue status and revalidates manifest paths.",
    dataTouched: "magazine_issues and magazine manifest cache.",
    status: "partial",
    riskLevel: "MEDIUM",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "primary",
    helperCopy: "Always check public preview/manifest after publishing.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  archiveIssue: {
    key: "archiveIssue",
    label: "Archive issue",
    title: "Archive magazine issue",
    description: "Remove an issue from current cover flow while keeping it in archive history.",
    whatItDoes: "Updates magazine issue status and cover selection state.",
    dataTouched: "magazine_issues.",
    status: "partial",
    riskLevel: "MEDIUM",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "warning",
    helperCopy: "Archive should preserve issue metadata and assets.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  saveDraft: {
    key: "saveDraft",
    label: "Save draft",
    title: "Save draft",
    description: "Persist draft metadata without publishing publicly.",
    whatItDoes: "Saves internal or draft fields.",
    dataTouched: "Feature-specific draft or metadata rows.",
    status: "partial",
    riskLevel: "LOW",
    dangerous: false,
    confirmationRecommended: false,
    auditRecommended: true,
    variant: "primary",
    helperCopy: "Saving is not publishing; verify public state separately.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  exportCsv: {
    key: "exportCsv",
    label: "Export CSV",
    title: "Export CSV",
    description: "Download operational rows for offline follow-up.",
    whatItDoes: "Reads data and generates a CSV response.",
    dataTouched: "No write. Reads the relevant lead/report/table rows.",
    status: "real",
    riskLevel: "LOW",
    dangerous: false,
    confirmationRecommended: false,
    auditRecommended: true,
    variant: "neutral",
    helperCopy: "Exports may include customer contact info; handle files carefully.",
    nextGate: "ADMIN-ACTION-QA-AND-LIVE-SCHEMA-PROOF-01",
  },
  sendPasswordReset: {
    key: "sendPasswordReset",
    label: "Send password reset",
    title: "Send password reset",
    description: "Support action for account recovery.",
    whatItDoes: "Should send a reset link through a controlled server action.",
    dataTouched: "Supabase Auth plus support audit context.",
    status: "planned",
    riskLevel: "HIGH",
    dangerous: false,
    confirmationRecommended: true,
    auditRecommended: true,
    variant: "warning",
    helperCopy: "Not ready until safe support sessions and audit proof exist.",
    nextGate: "ADMIN-USER-SUPPORT-VIEW-01",
  },
  assignStaff: {
    key: "assignStaff",
    label: "Assign staff",
    title: "Assign staff",
    description: "Assign an owner or staff member to a queue item.",
    whatItDoes: "Should write assignment metadata for team accountability.",
    dataTouched: "Future assignment fields/tables.",
    status: "planned",
    riskLevel: "MEDIUM",
    dangerous: false,
    confirmationRecommended: false,
    auditRecommended: true,
    variant: "neutral",
    helperCopy: "Needs staff assignment schema/workflow before it is real.",
    nextGate: "ADMIN-TEAM-PERMISSIONS-TRUTH-01",
  },
};

export function getAdminActionContract(key: AdminActionKey): AdminActionContract {
  return ADMIN_OS_ACTION_REGISTRY[key];
}
