import type { SupportedLang } from "@/app/lib/language";
import type { PublicNavCopyBundle, PublicNavCopyRegistry, PublicNavItemLabels } from "./types";

const CHROME_ES = {
  brandName: "Leonix Media",
  navAria: "Navegación principal",
  recursosMenu: "Recursos Comunitarios",
  langAria: "Idioma",
  signIn: "Iniciar sesión",
  createAccount: "Crear cuenta",
  myAccount: "Mi cuenta",
  myListings: "Mis anuncios",
  signOut: "Cerrar sesión",
  account: "Cuenta",
  manageAccount: "Administrar mi cuenta",
  signedOutToast: "Sesión cerrada correctamente",
  openMenu: "Abrir menú",
  closeMenu: "Cerrar menú",
  menu: "Menú",
} as const;

const CHROME_EN = {
  brandName: "Leonix Media",
  navAria: "Main navigation",
  recursosMenu: "Community Resources",
  langAria: "Language",
  signIn: "Sign in",
  createAccount: "Create account",
  myAccount: "My account",
  myListings: "My listings",
  signOut: "Sign out",
  account: "Account",
  manageAccount: "Manage account",
  signedOutToast: "Signed out successfully",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  menu: "Menu",
} as const;

const ITEMS_ES: PublicNavItemLabels = {
  inicio: "Inicio",
  revista: "La Revista",
  clasificados: "Clasificados",
  "negocios-locales": "Negocios Locales",
  "recursos-comunitarios": "Recursos Comunitarios",
  "recursos-all": "Ver todos los recursos",
  "comunidad-eventos": "Comunidad y Eventos",
  clases: "Clases",
  iglesias: "Iglesias",
  "ayuda-comunitaria": "Ayuda comunitaria",
  viajes: "Viajes",
  "productos-promocionales": "Productos Promocionales",
  "productos-promocionalesShort": "Productos Promo",
  "compact-overflow": "Viajes y promo",
  anunciate: "Anúnciate",
  "about-us": "Sobre nosotros",
  "contact-us": "Contacto",
};

const ITEMS_EN: PublicNavItemLabels = {
  inicio: "Home",
  revista: "The Magazine",
  clasificados: "Classifieds",
  "negocios-locales": "Local Businesses",
  "recursos-comunitarios": "Community Resources",
  "recursos-all": "View all resources",
  "comunidad-eventos": "Community & Events",
  clases: "Classes",
  iglesias: "Churches",
  "ayuda-comunitaria": "Community Help",
  viajes: "Travel",
  "productos-promocionales": "Promotional Products",
  "productos-promocionalesShort": "Promo Products",
  "compact-overflow": "Travel & promo",
  anunciate: "Advertise",
  "about-us": "About us",
  "contact-us": "Contact us",
};

function bundle(items: PublicNavItemLabels, chrome: PublicNavCopyBundle["chrome"]): PublicNavCopyBundle {
  return { items, chrome };
}

function fromEnItems(partial: Partial<PublicNavItemLabels>): PublicNavItemLabels {
  return { ...ITEMS_EN, ...partial };
}

function fromEnChrome(partial: Partial<PublicNavCopyBundle["chrome"]>): PublicNavCopyBundle["chrome"] {
  return { ...CHROME_EN, ...partial };
}

export const PUBLIC_NAV_COPY: PublicNavCopyRegistry = {
  es: bundle(ITEMS_ES, CHROME_ES),
  en: bundle(ITEMS_EN, CHROME_EN),
  vi: bundle(
    fromEnItems({
      inicio: "Trang chủ",
      revista: "Tạp chí",
      clasificados: "Rao vặt",
      "negocios-locales": "Doanh nghiệp địa phương",
      "recursos-comunitarios": "Tài nguyên cộng đồng",
      "recursos-all": "Xem tất cả tài nguyên",
      "comunidad-eventos": "Cộng đồng & Sự kiện",
      clases: "Lớp học",
      iglesias: "Nhà thờ",
      "ayuda-comunitaria": "Hỗ trợ cộng đồng",
      viajes: "Du lịch",
      "productos-promocionales": "Sản phẩm khuyến mãi",
      "productos-promocionalesShort": "Sản phẩm promo",
      "compact-overflow": "Du lịch & promo",
      anunciate: "Quảng cáo",
      "about-us": "Giới thiệu",
      "contact-us": "Liên hệ",
    }),
    fromEnChrome({
      navAria: "Điều hướng chính",
      recursosMenu: "Tài nguyên cộng đồng",
      langAria: "Ngôn ngữ",
      signIn: "Đăng nhập",
      createAccount: "Tạo tài khoản",
      myAccount: "Tài khoản của tôi",
      myListings: "Tin đăng của tôi",
      signOut: "Đăng xuất",
      account: "Tài khoản",
      manageAccount: "Quản lý tài khoản",
      signedOutToast: "Đã đăng xuất thành công",
      openMenu: "Mở menu",
      closeMenu: "Đóng menu",
      menu: "Menu",
    }),
  ),
  pt: bundle(
    fromEnItems({
      inicio: "Início",
      revista: "Revista",
      clasificados: "Classificados",
      "negocios-locales": "Negócios locais",
      "recursos-comunitarios": "Recursos comunitários",
      "recursos-all": "Ver todos os recursos",
      "comunidad-eventos": "Comunidade e eventos",
      clases: "Aulas",
      iglesias: "Igrejas",
      "ayuda-comunitaria": "Ajuda comunitária",
      viajes: "Viagens",
      "productos-promocionales": "Produtos promocionais",
      "productos-promocionalesShort": "Produtos promo",
      "compact-overflow": "Viagens e promo",
      anunciate: "Anuncie",
      "about-us": "Sobre nós",
      "contact-us": "Contato",
    }),
    fromEnChrome({
      navAria: "Navegação principal",
      recursosMenu: "Recursos comunitários",
      langAria: "Idioma",
      signIn: "Entrar",
      createAccount: "Criar conta",
      myAccount: "Minha conta",
      myListings: "Meus anúncios",
      signOut: "Sair",
      account: "Conta",
      manageAccount: "Gerenciar conta",
      signedOutToast: "Sessão encerrada com sucesso",
      openMenu: "Abrir menu",
      closeMenu: "Fechar menu",
      menu: "Menu",
    }),
  ),
  tl: bundle(
    fromEnItems({
      inicio: "Home",
      revista: "Ang Magasin",
      clasificados: "Classifieds",
      "recursos-comunitarios": "Mga mapagkukunan ng komunidad",
      "recursos-all": "Tingnan lahat ng mapagkukunan",
      "comunidad-eventos": "Komunidad at mga event",
      clases: "Mga klase",
      iglesias: "Mga simbahan",
      "ayuda-comunitaria": "Tulong sa komunidad",
      viajes: "Travel",
      "productos-promocionales": "Promotional products",
      "productos-promocionalesShort": "Promo products",
      "compact-overflow": "Travel at promo",
      anunciate: "Mag-advertise",
    }),
    fromEnChrome({
      navAria: "Pangunahing navigation",
      recursosMenu: "Mga mapagkukunan ng komunidad",
      langAria: "Wika",
      signIn: "Mag-sign in",
      createAccount: "Gumawa ng account",
      myAccount: "Aking account",
      myListings: "Aking mga listing",
      signOut: "Mag-sign out",
      account: "Account",
      manageAccount: "Pamahalaan ang account",
      signedOutToast: "Matagumpay na nag-sign out",
      openMenu: "Buksan ang menu",
      closeMenu: "Isara ang menu",
      menu: "Menu",
    }),
  ),
  km: bundle(
    fromEnItems({
      inicio: "ទំព័រដើម",
      revista: "ទស្សនាវដ្តី",
      clasificados: "ការផ្សាយពាណិជ្ជកម្ម",
      "negocios-locales": "អាជីវកម្មក្នុងតំបន់",
      "recursos-comunitarios": "ធនធានសហគមន៍",
      "recursos-all": "មើលធនធានទាំងអស់",
      "comunidad-eventos": "សហគមន៍ និងព្រឹត្តិការណ៍",
      clases: "ថ្នាក់",
      iglesias: "ព្រះវិហារ",
      "ayuda-comunitaria": "ជំនួយសហគមន៍",
      viajes: "ការធ្វើដំណើរ",
      "productos-promocionales": "ផលិតផលផ្សព្វផ្សាយ",
      "compact-overflow": "ដំណើរ និង promo",
      anunciate: "ផ្សាយពាណិជ្ជកម្ម",
      "about-us": "About us",
      "contact-us": "Contact us",
    }),
    fromEnChrome({
      navAria: "ការរុករកចម្បង",
      recursosMenu: "ធនធានសហគមន៍",
      langAria: "ភាសា",
      signIn: "ចូល",
      createAccount: "បង្កើតគណនី",
      myAccount: "គណនីរបស់ខ្ញុំ",
      myListings: "ការផ្សាយរបស់ខ្ញុំ",
      signOut: "ចាកចេញ",
      account: "គណនី",
      manageAccount: "គ្រប់គ្រងគណនី",
      signedOutToast: "ចាកចេញបានដោយជោគជ័យ",
      openMenu: "បើកម៉ឺនុយ",
      closeMenu: "បិទម៉ឺនុយ",
      menu: "ម៉ឺនុយ",
    }),
  ),
  zh: bundle(
    fromEnItems({
      inicio: "首页",
      revista: "杂志",
      clasificados: "分类信息",
      "recursos-comunitarios": "社区资源",
      "recursos-all": "查看全部资源",
      "comunidad-eventos": "社区与活动",
      clases: "课程",
      iglesias: "教堂",
      "ayuda-comunitaria": "社区帮助",
      viajes: "旅行",
      "productos-promocionales": "促销产品",
      "productos-promocionalesShort": "促销产品",
      "compact-overflow": "旅行与促销",
      anunciate: "投放广告",
    }),
    fromEnChrome({
      navAria: "主导航",
      recursosMenu: "社区资源",
      langAria: "语言",
      signIn: "登录",
      createAccount: "创建账户",
      myAccount: "我的账户",
      myListings: "我的 listings",
      signOut: "退出",
      account: "账户",
      manageAccount: "管理账户",
      signedOutToast: "已成功退出",
      openMenu: "打开菜单",
      closeMenu: "关闭菜单",
      menu: "菜单",
    }),
  ),
  ja: bundle(
    fromEnItems({
      inicio: "ホーム",
      revista: "マガジン",
      clasificados: "クラシファイド",
      "recursos-comunitarios": "コミュニティリソース",
      "recursos-all": "すべてのリソースを見る",
      "comunidad-eventos": "コミュニティとイベント",
      clases: "クラス",
      iglesias: "教会",
      "ayuda-comunitaria": "コミュニティ支援",
      viajes: "旅行",
      "productos-promocionales": "プロモーション商品",
      "productos-promocionalesShort": "プロモ商品",
      "compact-overflow": "旅行とプロモ",
      anunciate: "広告掲載",
    }),
    fromEnChrome({
      navAria: "メインナビゲーション",
      recursosMenu: "コミュニティリソース",
      langAria: "言語",
      signIn: "ログイン",
      createAccount: "アカウント作成",
      myAccount: "マイアカウント",
      myListings: "マイリスティング",
      signOut: "ログアウト",
      account: "アカウント",
      manageAccount: "アカウント管理",
      signedOutToast: "ログアウトしました",
      openMenu: "メニューを開く",
      closeMenu: "メニューを閉じる",
      menu: "メニュー",
    }),
  ),
  ko: bundle(
    fromEnItems({
      inicio: "홈",
      revista: "매거진",
      clasificados: "분류 광고",
      "recursos-comunitarios": "커뮤니티 리소스",
      "recursos-all": "모든 리소스 보기",
      "comunidad-eventos": "커뮤니티 및 이벤트",
      clases: "수업",
      iglesias: "교회",
      "ayuda-comunitaria": "커뮤니티 도움",
      viajes: "여행",
      "productos-promocionales": "프로모션 제품",
      "compact-overflow": "여행 및 프로모",
      anunciate: "광고하기",
    }),
    fromEnChrome({
      navAria: "주요 탐색",
      recursosMenu: "커뮤니티 리소스",
      langAria: "언어",
      signIn: "로그인",
      createAccount: "계정 만들기",
      myAccount: "내 계정",
      myListings: "내 listings",
      signOut: "로그아웃",
      account: "계정",
      manageAccount: "계정 관리",
      signedOutToast: "로그아웃되었습니다",
      openMenu: "메뉴 열기",
      closeMenu: "메뉴 닫기",
      menu: "메뉴",
    }),
  ),
  hi: bundle(
    fromEnItems({
      inicio: "होम",
      revista: "पत्रिका",
      clasificados: "क्लासिफ़ाइड",
      "recursos-comunitarios": "सामुदायिक संसाधन",
      "recursos-all": "सभी संसाधन देखें",
      "comunidad-eventos": "समुदाय और कार्यक्रम",
      clases: "कक्षाएँ",
      iglesias: "चर्च",
      "ayuda-comunitaria": "सामुदायिक सहायता",
      viajes: "यात्रा",
      "productos-promocionales": "प्रचार उत्पाद",
      "compact-overflow": "यात्रा और प्रोमो",
      anunciate: "विज्ञापन दें",
    }),
    fromEnChrome({
      navAria: "मुख्य नेविगेशन",
      recursosMenu: "सामुदायिक संसाधन",
      langAria: "भाषा",
      signIn: "साइन इन",
      createAccount: "खाता बनाएँ",
      myAccount: "मेरा खाता",
      myListings: "मेरी listings",
      signOut: "साइन आउट",
      account: "खाता",
      manageAccount: "खाता प्रबंधित करें",
      signedOutToast: "सफलतापूर्वक साइन आउट",
      openMenu: "मेनू खोलें",
      closeMenu: "मेनू बंद करें",
      menu: "मेनू",
    }),
  ),
  hy: bundle(
    fromEnItems({
      inicio: "Գլխավոր",
      revista: "Ամսագիր",
      clasificados: "Դասակարգված",
      "recursos-comunitarios": "Համայնքային ռեսուրսներ",
      "recursos-all": "Դիտել բոլոր ռեսուրսները",
      "comunidad-eventos": "Համայնք և միջոցառումներ",
      clases: "Դասեր",
      iglesias: "Եկեղեցիներ",
      "ayuda-comunitaria": "Համայնքային օգնություն",
      viajes: "Ճանապարհորդություն",
      "productos-promocionales": "Գովազդային ապրանքներ",
      "compact-overflow": "Ճանապարհորդություն և promo",
      anunciate: "Գովազդել",
    }),
    fromEnChrome({
      navAria: "Հիմնական նավigation",
      recursosMenu: "Համայնքային ռեսուրսներ",
      langAria: "Լեզու",
      signIn: "Մուտք",
      createAccount: "Ստեղծել հաշիվ",
      myAccount: "Իմ հաշիվը",
      myListings: "Իմ հայտարարությունները",
      signOut: "Դուրս գալ",
      account: "Հաշիվ",
      manageAccount: "Կառավարել հաշիվը",
      signedOutToast: "Հաջողությամբ դուրս եկաք",
      openMenu: "Բացել մենյուն",
      closeMenu: "Փակել մենյուն",
      menu: "Մենյու",
    }),
  ),
  ru: bundle(
    fromEnItems({
      inicio: "Главная",
      revista: "Журнал",
      clasificados: "Объявления",
      "recursos-comunitarios": "Ресурсы сообщества",
      "recursos-all": "Все ресурсы",
      "comunidad-eventos": "Сообщество и события",
      clases: "Курсы",
      iglesias: "Церкви",
      "ayuda-comunitaria": "Помощь сообществу",
      viajes: "Путешествия",
      "productos-promocionales": "Рекламная продукция",
      "compact-overflow": "Путешествия и promo",
      anunciate: "Рекламировать",
    }),
    fromEnChrome({
      navAria: "Основная навигация",
      recursosMenu: "Ресурсы сообщества",
      langAria: "Язык",
      signIn: "Войти",
      createAccount: "Создать аккаунт",
      myAccount: "Мой аккаунт",
      myListings: "Мои объявления",
      signOut: "Выйти",
      account: "Аккаунт",
      manageAccount: "Управление аккаунтом",
      signedOutToast: "Вы успешно вышли",
      openMenu: "Открыть меню",
      closeMenu: "Закрыть меню",
      menu: "Меню",
    }),
  ),
  pa: bundle(
    fromEnItems({
      inicio: "ਹੋਮ",
      revista: "ਰਸਾਲਾ",
      clasificados: "Classifieds",
      "recursos-comunitarios": "ਕਮਿਊਨਿਟੀ ਸਰੋਤ",
      "recursos-all": "ਸਾਰੇ ਸਰੋਤ ਵੇਖੋ",
      "comunidad-eventos": "ਕਮਿਊਨਿਟੀ ਅਤੇ ਇਵੈਂਟ",
      clases: "ਕਲਾਸਾਂ",
      iglesias: "ਗਿਰਜਾਘਰ",
      "ayuda-comunitaria": "ਕਮਿਊਨਿਟੀ ਮਦਦ",
      viajes: "ਯਾਤਰਾ",
      "productos-promocionales": "ਪ੍ਰਚਾਰ ਉਤਪਾਦ",
      "compact-overflow": "ਯਾਤਰਾ ਅਤੇ promo",
      anunciate: "ਇਸ਼ਤਿਹਾਰ ਦਿਓ",
    }),
    fromEnChrome({
      navAria: "ਮੁੱਖ ਨੈਵੀਗੇਸ਼ਨ",
      recursosMenu: "ਕਮਿਊਨਿਟੀ ਸਰੋਤ",
      langAria: "ਭਾਸ਼ਾ",
      signIn: "ਸਾਈਨ ਇਨ",
      createAccount: "ਖਾਤਾ ਬਣਾਓ",
      myAccount: "ਮੇਰਾ ਖਾਤਾ",
      myListings: "ਮੇਰੀਆਂ listings",
      signOut: "ਸਾਈਨ ਆਉਟ",
      account: "ਖਾਤਾ",
      manageAccount: "ਖਾਤਾ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
      signedOutToast: "ਸਫਲਤਾਪੂਰਵਕ ਸਾਈਨ ਆਉਟ",
      openMenu: "ਮੀਨੂ ਖੋਲ੍ਹੋ",
      closeMenu: "ਮੀਨੂ ਬੰਦ ਕਰੋ",
      menu: "ਮੀਨੂ",
    }),
  ),
};

export function getPublicNavCopy(lang: SupportedLang): PublicNavCopyBundle {
  return PUBLIC_NAV_COPY[lang] ?? PUBLIC_NAV_COPY.en;
}

export function getPublicNavItemLabel(
  itemId: string,
  lang: SupportedLang,
  opts?: { short?: boolean },
): string {
  const copy = getPublicNavCopy(lang);
  const items = copy.items;
  if (opts?.short && itemId === "productos-promocionales" && items["productos-promocionalesShort"]) {
    return items["productos-promocionalesShort"];
  }
  const key = itemId as keyof PublicNavItemLabels;
  if (key in items && typeof items[key] === "string") return items[key] as string;
  return lang === "es" ? ITEMS_ES.inicio : ITEMS_EN.inicio;
}

export function getNavbarChromeCopy(lang: SupportedLang): PublicNavCopyBundle["chrome"] {
  return getPublicNavCopy(lang).chrome;
}

export type { PublicNavCopyBundle, PublicNavItemLabels, NavbarChromeCopy } from "./types";
