import type { BusinessTypePreset, ChipDef, ServiciosInternalGroup } from "./clasificadosServiciosApplicationTypes";

function C(id: string, es: string, en: string): ChipDef {
  return { id, es, en };
}

function preset(
  id: string,
  group: ServiciosInternalGroup,
  labelEs: string,
  labelEn: string,
  suggestedServices: ChipDef[],
  reasonsToChoose: ChipDef[],
  quickFacts: ChipDef[],
  primaryCtaOptions: ChipDef[],
  secondaryCtaOptions: ChipDef[],
): BusinessTypePreset {
  return {
    id,
    internalGroup: group,
    labelEs,
    labelEn,
    suggestedServices,
    reasonsToChoose,
    quickFacts,
    primaryCtaOptions,
    secondaryCtaOptions,
  };
}

/** All supported business types — one universal app, many presets */
export const BUSINESS_TYPE_PRESETS: BusinessTypePreset[] = [
  // Hogar y Oficios
  preset(
    "plomeria",
    "home_trade",
    "Plomería",
    "Plumbing",
    [
      C("plom_fugas", "Reparación de fugas", "Leak repair"),
      C("plom_destape", "Destape de drenaje", "Drain cleaning"),
      C("plom_calentador", "Calentador de agua", "Water heater"),
      C("plom_griferia", "Instalación de grifería", "Fixture installation"),
      C("plom_emergencia", "Plomería de emergencia", "Emergency plumbing"),
    ],
    [
      C("plom_r1", "Licenciado", "Licensed"),
      C("plom_r2", "Asegurado", "Insured"),
      C("plom_r3", "Servicio el mismo día", "Same-day service"),
      C("plom_r4", "Estimados gratis", "Free estimates"),
    ],
    [C("plom_q1", "Disponible 24/7", "Available 24/7")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote"), C("cta_llamar", "Llamar ahora", "Call now")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "electricista",
    "home_trade",
    "Electricista",
    "Electrician",
    [
      C("elec_instalacion", "Instalación eléctrica", "Electrical installation"),
      C("elec_reparacion", "Reparación eléctrica", "Electrical repair"),
      C("elec_emergencia", "Emergencias eléctricas", "Electrical emergencies"),
      C("elec_iluminacion", "Instalación de iluminación", "Lighting installation"),
    ],
    [
      C("elec_r1", "Certificado", "Certified"),
      C("elec_r2", "Seguro", "Insured"),
      C("elec_r3", "Servicio de emergencia", "Emergency service"),
    ],
    [C("elec_q1", "Trabajo garantizado", "Guaranteed work")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote"), C("cta_emergencia", "Emergencia", "Emergency")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "carpinteria",
    "home_trade",
    "Carpintería",
    "Carpentry",
    [
      C("carp_muebles", "Fabricación de muebles", "Furniture making"),
      C("carp_reparacion", "Reparación de muebles", "Furniture repair"),
      C("carp_instalacion", "Instalación de carpintería", "Carpentry installation"),
      C("carp_cocina", "Cocinas a medida", "Custom kitchens"),
    ],
    [
      C("carp_r1", "Madera de calidad", "Quality wood"),
      C("carp_r2", "Diseño personalizado", "Custom design"),
      C("carp_r3", "Garantía de trabajo", "Work guarantee"),
    ],
    [C("carp_q1", "Más de 10 años de experiencia", "10+ years experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "pintura",
    "home_trade",
    "Pintura",
    "Painting",
    [
      C("pint_interior", "Pintura interior", "Interior painting"),
      C("pint_exterior", "Pintura exterior", "Exterior painting"),
      C("pint_residencial", "Pintura residencial", "Residential painting"),
      C("pint_comercial", "Pintura comercial", "Commercial painting"),
    ],
    [
      C("pint_r1", "Pintura de calidad", "Quality paint"),
      C("pint_r2", "Preparación profesional", "Professional preparation"),
      C("pint_r3", "Limpieza incluida", "Cleanup included"),
    ],
    [C("pint_q1", "Trabajo garantizado", "Guaranteed work")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "hvac_aire_acondicionado",
    "home_trade",
    "HVAC / Aire Acondicionado",
    "HVAC / Air Conditioning",
    [
      C("hvac_instalacion", "Instalación de AC", "AC installation"),
      C("hvac_mantenimiento", "Mantenimiento de AC", "AC maintenance"),
      C("hvac_reparacion", "Reparación de AC", "AC repair"),
      C("hvac_ventilacion", "Sistemas de ventilación", "Ventilation systems"),
    ],
    [
      C("hvac_r1", "Técnicos certificados", "Certified technicians"),
      C("hvac_r2", "Servicio 24/7", "24/7 service"),
      C("hvac_r3", "Garantía de equipo", "Equipment warranty"),
    ],
    [C("hvac_q1", "Respuesta rápida", "Fast response")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote"), C("cta_emergencia", "Emergencia", "Emergency")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "fumigacion_control_plagas",
    "home_trade",
    "Fumigación / Control de Plagas",
    "Pest Control",
    [
      C("fumi_insectos", "Control de insectos", "Insect control"),
      C("fumi_roedores", "Control de roedores", "Rodent control"),
      C("fumi_terminas", "Control de termitas", "Termite control"),
      C("fumi_preventivo", "Tratamiento preventivo", "Preventive treatment"),
    ],
    [
      C("fumi_r1", "Productos seguros", "Safe products"),
      C("fumi_r2", "Garantía de servicio", "Service guarantee"),
      C("fumi_r3", "Servicio profesional", "Professional service"),
    ],
    [C("fumi_q1", "Certificado y licenciado", "Certified and licensed")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "jardineria_paisajismo",
    "home_trade",
    "Jardinería / Paisajismo",
    "Gardening / Landscaping",
    [
      C("jard_diseño", "Diseño de jardines", "Garden design"),
      C("jard_mantenimiento", "Mantenimiento de jardines", "Garden maintenance"),
      C("jard_cesped", "Instalación de césped", "Sod installation"),
      C("jard_riego", "Sistemas de riego", "Irrigation systems"),
    ],
    [
      C("jard_r1", "Diseñadores profesionales", "Professional designers"),
      C("jard_r2", "Plantas de calidad", "Quality plants"),
      C("jard_r3", "Mantenimiento garantizado", "Maintenance guarantee"),
    ],
    [C("jard_q1", "Experiencia en diseño", "Design experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "limpieza_hogares",
    "home_trade",
    "Limpieza de Hogares",
    "Home Cleaning",
    [
      C("limp_regular", "Limpieza regular", "Regular cleaning"),
      C("limp_profunda", "Limpieza profunda", "Deep cleaning"),
      C("limp_post_construccion", "Limpieza post-construcción", "Post-construction cleaning"),
      C("limp_ventanas", "Limpieza de ventanas", "Window cleaning"),
    ],
    [
      C("limp_r1", "Personal confiable", "Trusted staff"),
      C("limp_r2", "Productos ecológicos", "Eco-friendly products"),
      C("limp_r3", "Servicio asegurado", "Insured service"),
    ],
    [C("limp_q1", "Flexibilidad de horarios", "Flexible scheduling")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "reparaciones_generales",
    "home_trade",
    "Reparaciones Generales",
    "General Repairs",
    [
      C("repar_hogar", "Reparaciones del hogar", "Home repairs"),
      C("repar_mantenimiento", "Mantenimiento general", "General maintenance"),
      C("repar_pequeños", "Pequeños arreglos", "Small repairs"),
      C("repar_emergencias", "Reparaciones de emergencia", "Emergency repairs"),
    ],
    [
      C("repar_r1", "Mano de obra calificada", "Skilled labor"),
      C("repar_r2", "Respuesta rápida", "Fast response"),
      C("repar_r3", "Precios justos", "Fair prices"),
    ],
    [C("repar_q1", "Experiencia múltiple", "Multi-trade experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "remodelacion_construccion",
    "home_trade",
    "Remodelación / Construcción",
    "Remodeling / Construction",
    [
      C("remo_cocinas", "Remodelación de cocinas", "Kitchen remodeling"),
      C("remo_banos", "Remodelación de baños", "Bathroom remodeling"),
      C("remo_construccion", "Construcción nueva", "New construction"),
      C("remo_adiciones", "Adiciones a casa", "Home additions"),
    ],
    [
      C("remo_r1", "Contratista licenciado", "Licensed contractor"),
      C("remo_r2", "Permitos incluidos", "Permits included"),
      C("remo_r3", "Calidad garantizada", "Quality guaranteed"),
    ],
    [C("remo_q1", "Más de 15 años de experiencia", "15+ years experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "techos_canales",
    "home_trade",
    "Techos y Canales",
    "Roofing & Gutters",
    [
      C("tech_instalacion", "Instalación de techos", "Roof installation"),
      C("tech_reparacion", "Reparación de techos", "Roof repair"),
      C("tech_canales", "Instalación de canales", "Gutter installation"),
      C("tech_limpieza", "Limpieza de canales", "Gutter cleaning"),
    ],
    [
      C("tech_r1", "Materiales de calidad", "Quality materials"),
      C("tech_r2", "Garantía extendida", "Extended warranty"),
      C("tech_r3", "Inspección gratuita", "Free inspection"),
    ],
    [C("tech_q1", "Técnicos experimentados", "Experienced technicians")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),

  // Automotriz
  preset(
    "mecanica_general",
    "automotive",
    "Mecánica General",
    "General Mechanics",
    [
      C("mec_diagnostico", "Diagnóstico", "Diagnostics"),
      C("mec_reparacion", "Reparación general", "General repair"),
      C("mec_mantenimiento", "Mantenimiento", "Maintenance"),
      C("mec_inspeccion", "Inspección", "Inspection"),
    ],
    [
      C("mec_r1", "Técnicos certificados", "Certified technicians"),
      C("mec_r2", "Diagnóstico preciso", "Accurate diagnosis"),
      C("mec_r3", "Garantía de trabajo", "Work guarantee"),
    ],
    [C("mec_q1", "Equipos modernos", "Modern equipment")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "smog_inspeccion",
    "automotive",
    "Smog / Inspección",
    "Smog / Inspection",
    [
      C("smog_certificacion", "Certificación Smog", "Smog certification"),
      C("smog_inspeccion", "Inspección vehicular", "Vehicle inspection"),
      C("smog_diagnostico", "Diagnóstico de emisiones", "Emissions diagnostics"),
    ],
    [
      C("smog_r1", "Estación certificada", "Certified station"),
      C("smog_r2", "Resultados rápidos", "Fast results"),
      C("smog_r3", "Precios competitivos", "Competitive prices"),
    ],
    [C("smog_q1", "Servicio rápido", "Fast service")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "grua_remolque",
    "automotive",
    "Grúa / Remolque",
    "Towing",
    [
      C("grua_emergencia", "Remolque de emergencia", "Emergency towing"),
      C("grua_larga_distancia", "Remolque larga distancia", "Long distance towing"),
      C("grua_carga", "Transporte de carga", "Cargo transport"),
    ],
    [
      C("grua_r1", "Servicio 24/7", "24/7 service"),
      C("grua_r2", "Respuesta rápida", "Fast response"),
      C("grua_r3", "Cobertura amplia", "Wide coverage"),
    ],
    [C("grua_q1", "Equipos modernos", "Modern equipment")],
    [C("cta_emergencia", "Emergencia", "Emergency")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "llantas_neumaticos",
    "automotive",
    "Llantas y Neumáticos",
    "Tires",
    [
      C("llan_venta", "Venta de llantas", "Tire sales"),
      C("llan_instalacion", "Instalación", "Installation"),
      C("llan_balanceo", "Balanceo", "Balancing"),
      C("llan_alineacion", "Alineación", "Alignment"),
    ],
    [
      C("llan_r1", "Marcas reconocidas", "Recognized brands"),
      C("llan_r2", "Instalación profesional", "Professional installation"),
      C("llan_r3", "Precios competitivos", "Competitive prices"),
    ],
    [C("llan_q1", "Servicio rápido", "Fast service")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "cambio_aceite",
    "automotive",
    "Cambio de Aceite",
    "Oil Change",
    [
      C("aceite_cambio", "Cambio de aceite", "Oil change"),
      C("aceite_filtro", "Cambio de filtro", "Filter change"),
      C("aceite_revisión", "Revisión general", "General checkup"),
    ],
    [
      C("aceite_r1", "Aceite de calidad", "Quality oil"),
      C("aceite_r2", "Servicio rápido", "Fast service"),
      C("aceite_r3", "Precios justos", "Fair prices"),
    ],
    [C("aceite_q1", "Sin cita necesaria", "No appointment needed")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "lavado_detallado",
    "automotive",
    "Lavado y Detallado",
    "Car Wash & Detailing",
    [
      C("lav_lavado", "Lavado completo", "Full wash"),
      C("lav_detallado", "Detallado completo", "Full detailing"),
      C("lav_ceramica", "Protección cerámica", "Ceramic protection"),
      C("lav_interior", "Limpieza interior", "Interior cleaning"),
    ],
    [
      C("lav_r1", "Productos premium", "Premium products"),
      C("lav_r2", "Detalle profesional", "Professional detail"),
      C("lav_r3", "Resultados garantizados", "Guaranteed results"),
    ],
    [C("lav_q1", "Experiencia en detailing", "Detailing experience")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "carroceria_pintura",
    "automotive",
    "Carrocería y Pintura",
    "Body Work & Paint",
    [
      C("carp_reparacion", "Reparación de carrocería", "Body repair"),
      C("carp_pintura", "Pintura automotriz", "Auto painting"),
      C("carp_abolladuras", "Eliminación de abolladuras", "Dent removal"),
      C("carp_personalizacion", "Personalización", "Customization"),
    ],
    [
      C("carp_r1", "Calidad de pintura", "Paint quality"),
      C("carp_r2", "Garantía de trabajo", "Work guarantee"),
      C("carp_r3", "Técnicos expertos", "Expert technicians"),
    ],
    [C("carp_q1", "Equipos modernos", "Modern equipment")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "vidrios_parabrisas",
    "automotive",
    "Vidrios y Parabrisas",
    "Glass & Windshield",
    [
      C("vid_parabrisas", "Reemplazo de parabrisas", "Windshield replacement"),
      C("vid_ventanillas", "Reemplazo de ventanillas", "Window replacement"),
      C("vid_reparacion", "Reparación de grietas", "Crack repair"),
      C("vid_tintado", "Tintado de vidrios", "Window tinting"),
    ],
    [
      C("vid_r1", "Vidrio de calidad", "Quality glass"),
      C("vid_r2", "Instalación profesional", "Professional installation"),
      C("vid_r3", "Garantía de servicio", "Service warranty"),
    ],
    [C("vid_q1", "Servicio móvil", "Mobile service")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "baterias_electrico",
    "automotive",
    "Baterías y Eléctrico",
    "Batteries & Electrical",
    [
      C("bat_baterias", "Venta de baterías", "Battery sales"),
      C("bat_instalacion", "Instalación eléctrica", "Electrical installation"),
      C("bat_diagnostico", "Diagnóstico eléctrico", "Electrical diagnostics"),
      C("bat_alternador", "Reparación de alternador", "Alternator repair"),
    ],
    [
      C("bat_r1", "Baterías garantizadas", "Warranted batteries"),
      C("bat_r2", "Diagnóstico preciso", "Accurate diagnosis"),
      C("bat_r3", "Servicio rápido", "Fast service"),
    ],
    [C("bat_q1", "Técnicos certificados", "Certified technicians")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "alineacion_balanceo",
    "automotive",
    "Alineación y Balanceo",
    "Alignment & Balancing",
    [
      C("alin_alineacion", "Alineación", "Alignment"),
      C("alin_balanceo", "Balanceo", "Balancing"),
      C("alin_suspension", "Revisión de suspensión", "Suspension check"),
    ],
    [
      C("alin_r1", "Equipos precisos", "Precision equipment"),
      C("alin_r2", "Técnicos expertos", "Expert technicians"),
      C("alin_r3", "Servicio rápido", "Fast service"),
    ],
    [C("alin_q1", "Conducción segura", "Safe driving")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "transmisiones",
    "automotive",
    "Transmisiones",
    "Transmissions",
    [
      C("trans_reparacion", "Reparación de transmisión", "Transmission repair"),
      C("trans_mantenimiento", "Mantenimiento", "Maintenance"),
      C("trans_diagnostico", "Diagnóstico", "Diagnostics"),
    ],
    [
      C("trans_r1", "Especialistas en transmisiones", "Transmission specialists"),
      C("trans_r2", "Garantía extendida", "Extended warranty"),
      C("trans_r3", "Diagnóstico preciso", "Accurate diagnosis"),
    ],
    [C("trans_q1", "Años de experiencia", "Years of experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),

  // Salud y Belleza
  preset(
    "peluqueria_barberia",
    "health_beauty",
    "Peluquería / Barbería",
    "Hair Salon / Barber",
    [
      C("pel_corte", "Corte de cabello", "Haircut"),
      C("pel_tinte", "Tinte", "Hair coloring"),
      C("pel_barberia", "Barbería", "Barber services"),
      C("pel_estilo", "Estilismo", "Styling"),
    ],
    [
      C("pel_r1", "Estilistas profesionales", "Professional stylists"),
      C("pel_r2", "Productos de calidad", "Quality products"),
      C("pel_r3", "Ambiente agradable", "Pleasant atmosphere"),
    ],
    [C("pel_q1", "Últimas tendencias", "Latest trends")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "spa_masajes",
    "health_beauty",
    "Spa / Masajes",
    "Spa / Massage",
    [
      C("spa_masaje", "Masajes terapéuticos", "Therapeutic massage"),
      C("spa_relajacion", "Tratamientos de relajación", "Relaxation treatments"),
      C("spa_facial", "Tratamientos faciales", "Facial treatments"),
      C("spa_cuerpo", "Tratamientos corporales", "Body treatments"),
    ],
    [
      C("spa_r1", "Terapeutas certificados", "Certified therapists"),
      C("spa_r2", "Ambiente tranquilo", "Peaceful environment"),
      C("spa_r3", "Productos naturales", "Natural products"),
    ],
    [C("spa_q1", "Experiencia relajante", "Relaxing experience")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "unas_manicure",
    "health_beauty",
    "Uñas / Manicure",
    "Nails / Manicure",
    [
      C("unas_manicure", "Manicure", "Manicure"),
      C("unas_pedicure", "Pedicure", "Pedicure"),
      C("unas_acrilicas", "Uñas acrílicas", "Acrylic nails"),
      C("unas_diseño", "Diseño de uñas", "Nail art"),
    ],
    [
      C("unas_r1", "Técnicas expertas", "Expert technicians"),
      C("unas_r2", "Productos seguros", "Safe products"),
      C("unas_r3", "Higiene garantizada", "Guaranteed hygiene"),
    ],
    [C("unas_q1", "Diseños modernos", "Modern designs")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "estética_belleza",
    "health_beauty",
    "Estética y Belleza",
    "Beauty & Aesthetics",
    [
      C("est_cuidado_facial", "Cuidado facial", "Facial care"),
      C("est_depilacion", "Depilación", "Hair removal"),
      C("est_tratamientos", "Tratamientos estéticos", "Aesthetic treatments"),
      C("est_maquillaje", "Maquillaje profesional", "Professional makeup"),
    ],
    [
      C("est_r1", "Esteticistas certificados", "Certified aestheticians"),
      C("est_r2", "Equipos modernos", "Modern equipment"),
      C("est_r3", "Productos premium", "Premium products"),
    ],
    [C("est_q1", "Resultados visibles", "Visible results")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "entrenamiento_personal",
    "health_beauty",
    "Entrenamiento Personal",
    "Personal Training",
    [
      C("entren_plan", "Planes de entrenamiento", "Training plans"),
      C("entren_nutricion", "Asesoría nutricional", "Nutrition advice"),
      C("entren_grupal", "Entrenamiento grupal", "Group training"),
      C("entren_online", "Entrenamiento online", "Online training"),
    ],
    [
      C("entren_r1", "Entrenadores certificados", "Certified trainers"),
      C("entren_r2", "Planes personalizados", "Customized plans"),
      C("entren_r3", "Resultados garantizados", "Guaranteed results"),
    ],
    [C("entren_q1", "Experiencia comprobada", "Proven experience")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "nutricion_dietas",
    "health_beauty",
    "Nutrición / Dietas",
    "Nutrition / Diets",
    [
      C("nutr_consultoria", "Consultoría nutricional", "Nutrition consulting"),
      C("nutr_planes", "Planes de dieta", "Diet plans"),
      C("nutr_suplementos", "Asesoría de suplementos", "Supplement advice"),
      C("nutr_seguimiento", "Seguimiento personalizado", "Personalized follow-up"),
    ],
    [
      C("nutr_r1", "Nutricionistas certificados", "Certified nutritionists"),
      C("nutr_r2", "Planes personalizados", "Customized plans"),
      C("nutr_r3", "Enfoque científico", "Scientific approach"),
    ],
    [C("nutr_q1", "Resultados saludables", "Healthy results")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "terapia_fisica",
    "health_beauty",
    "Terapia Física",
    "Physical Therapy",
    [
      C("terapia_rehabilitacion", "Rehabilitación", "Rehabilitation"),
      C("terapia_dolor", "Manejo del dolor", "Pain management"),
      C("terapia_movilidad", "Mejora de movilidad", "Mobility improvement"),
      C("terapia_deportiva", "Terapia deportiva", "Sports therapy"),
    ],
    [
      C("terapia_r1", "Terapeutas licenciados", "Licensed therapists"),
      C("terapia_r2", "Tratamiento personalizado", "Personalized treatment"),
      C("terapia_r3", "Equipos modernos", "Modern equipment"),
    ],
    [C("terapia_q1", "Recuperación efectiva", "Effective recovery")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "yoga_pilates",
    "health_beauty",
    "Yoga / Pilates",
    "Yoga / Pilates",
    [
      C("yoga_clases", "Clases de yoga", "Yoga classes"),
      C("yoga_privadas", "Clases privadas", "Private classes"),
      C("yoga_grupos", "Clases grupales", "Group classes"),
      C("yoga_online", "Clases online", "Online classes"),
    ],
    [
      C("yoga_r1", "Instructores certificados", "Certified instructors"),
      C("yoga_r2", "Todos los niveles", "All levels"),
      C("yoga_r3", "Ambiente tranquilo", "Peaceful environment"),
    ],
    [C("yoga_q1", "Bienestar integral", "Holistic wellness")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "acupuntura",
    "health_beauty",
    "Acupuntura",
    "Acupuncture",
    [
      C("acup_tratamiento", "Tratamiento de acupuntura", "Acupuncture treatment"),
      C("acup_dolor", "Manejo del dolor", "Pain management"),
      C("acup_estrés", "Reducción de estrés", "Stress reduction"),
      C("acup_energía", "Balance de energía", "Energy balance"),
    ],
    [
      C("acup_r1", "Practicantes certificados", "Certified practitioners"),
      C("acup_r2", "Técnicas tradicionales", "Traditional techniques"),
      C("acup_r3", "Ambiente seguro", "Safe environment"),
    ],
    [C("acup_q1", "Medicina tradicional", "Traditional medicine")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "salud_mental_psicologia",
    "health_beauty",
    "Salud Mental / Psicología",
    "Mental Health / Psychology",
    [
      C("salud_terapia", "Terapia individual", "Individual therapy"),
      C("salud_consejo", "Consejería", "Counseling"),
      C("salud_grupo", "Terapia de grupo", "Group therapy"),
      C("salud_crisis", "Intervención en crisis", "Crisis intervention"),
    ],
    [
      C("salud_r1", "Psicólogos licenciados", "Licensed psychologists"),
      C("salud_r2", "Confidencialidad garantizada", "Guaranteed confidentiality"),
      C("salud_r3", "Enfoque profesional", "Professional approach"),
    ],
    [C("salud_q1", "Apoyo compasivo", "Compassionate support")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),

  // Legal y Profesional
  preset(
    "abogado_asesoria_legal",
    "legal_professional",
    "Abogado / Asesoría Legal",
    "Lawyer / Legal Advice",
    [
      C("abog_consulta", "Consulta legal", "Legal consultation"),
      C("abog_contratos", "Revisión de contratos", "Contract review"),
      C("abog_familia", "Derecho familiar", "Family law"),
      C("abog_negocios", "Derecho comercial", "Business law"),
    ],
    [
      C("abog_r1", "Abogado licenciado", "Licensed attorney"),
      C("abog_r2", "Experiencia comprobada", "Proven experience"),
      C("abog_r3", "Confidencialidad", "Confidentiality"),
    ],
    [C("abog_q1", "Asesoramiento experto", "Expert advice")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "contador_impuestos",
    "legal_professional",
    "Contador / Impuestos",
    "Accountant / Taxes",
    [
      C("cont_impuestos", "Preparación de impuestos", "Tax preparation"),
      C("cont_contabilidad", "Contabilidad", "Accounting"),
      C("cont_asesoria", "Asesoría fiscal", "Tax advice"),
      C("cont_nominas", "Nóminas", "Payroll"),
    ],
    [
      C("cont_r1", "Contador certificado", "Certified accountant"),
      C("cont_r2", "Precios competitivos", "Competitive prices"),
      C("cont_r3", "Servicio confiable", "Reliable service"),
    ],
    [C("cont_q1", "Años de experiencia", "Years of experience")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "notaria",
    "legal_professional",
    "Notaría",
    "Notary Services",
    [
      C("not_firmas", "Firmas notariales", "Notarized signatures"),
      C("not_documentos", "Autenticación de documentos", "Document authentication"),
      C("not_testimonios", "Testimonios", "Testimonies"),
      C("not_poderes", "Poderes", "Powers of attorney"),
    ],
    [
      C("not_r1", "Notario público", "Public notary"),
      C("not_r2", "Servicio rápido", "Fast service"),
      C("not_r3", "Documentos legales", "Legal documents"),
    ],
    [C("not_q1", "Atención profesional", "Professional attention")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "traduccion_interpretacion",
    "legal_professional",
    "Traducción / Interpretación",
    "Translation / Interpretation",
    [
      C("trad_documentos", "Traducción de documentos", "Document translation"),
      C("trad_interpretacion", "Interpretación", "Interpretation"),
      C("trad_certificada", "Traducción certificada", "Certified translation"),
      C("trad_consecutiva", "Traducción consecutiva", "Consecutive translation"),
    ],
    [
      C("trad_r1", "Traductores certificados", "Certified translators"),
      C("trad_r2", "Precisión garantizada", "Guaranteed accuracy"),
      C("trad_r3", "Múltiples idiomas", "Multiple languages"),
    ],
    [C("trad_q1", "Experiencia internacional", "International experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "consultoria_negocios",
    "legal_professional",
    "Consultoría de Negocios",
    "Business Consulting",
    [
      C("cons_estrategia", "Consultoría estratégica", "Strategic consulting"),
      C("cons_finanzas", "Consultoría financiera", "Financial consulting"),
      C("cons_operaciones", "Optimización de operaciones", "Operations optimization"),
      C("cons_crecimiento", "Planificación de crecimiento", "Growth planning"),
    ],
    [
      C("cons_r1", "Consultores expertos", "Expert consultants"),
      C("cons_r2", "Resultados medibles", "Measurable results"),
      C("cons_r3", "Enfoque práctico", "Practical approach"),
    ],
    [C("cons_q1", "Experiencia empresarial", "Business experience")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "marketing_publicidad",
    "legal_professional",
    "Marketing / Publicidad",
    "Marketing / Advertising",
    [
      C("mark_estrategia", "Estrategia de marketing", "Marketing strategy"),
      C("mark_digital", "Marketing digital", "Digital marketing"),
      C("mark_social", "Gestión de redes sociales", "Social media management"),
      C("mark_contenido", "Creación de contenido", "Content creation"),
    ],
    [
      C("mark_r1", "Especialistas en marketing", "Marketing specialists"),
      C("mark_r2", "Resultados comprobados", "Proven results"),
      C("mark_r3", "Creatividad innovadora", "Innovative creativity"),
    ],
    [C("mark_q1", "Tendencias actuales", "Current trends")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "diseno_grafico",
    "legal_professional",
    "Diseño Gráfico",
    "Graphic Design",
    [
      C("dis_logo", "Diseño de logo", "Logo design"),
      C("dis_marca", "Identidad de marca", "Brand identity"),
      C("dis_impresion", "Diseño para impresión", "Print design"),
      C("dis_digital", "Diseño digital", "Digital design"),
    ],
    [
      C("dis_r1", "Diseñadores creativos", "Creative designers"),
      C("dis_r2", "Portafolio profesional", "Professional portfolio"),
      C("dis_r3", "Entrega a tiempo", "On-time delivery"),
    ],
    [C("dis_q1", "Diseño moderno", "Modern design")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "fotografia_video",
    "legal_professional",
    "Fotografía / Video",
    "Photography / Video",
    [
      C("foto_eventos", "Fotografía de eventos", "Event photography"),
      C("foto_comercial", "Fotografía comercial", "Commercial photography"),
      C("foto_video", "Producción de video", "Video production"),
      C("foto_edicion", "Edición profesional", "Professional editing"),
    ],
    [
      C("foto_r1", "Equipos profesionales", "Professional equipment"),
      C("foto_r2", "Calidad garantizada", "Quality guaranteed"),
      C("foto_r3", "Entrega rápida", "Fast delivery"),
    ],
    [C("foto_q1", "Visión artística", "Artistic vision")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "desarrollo_web",
    "legal_professional",
    "Desarrollo Web",
    "Web Development",
    [
      C("web_sitios", "Desarrollo de sitios web", "Website development"),
      C("web_comercio", "Comercio electrónico", "E-commerce"),
      C("web_mantenimiento", "Mantenimiento web", "Web maintenance"),
      C("web_optimizacion", "Optimización SEO", "SEO optimization"),
    ],
    [
      C("web_r1", "Desarrolladores expertos", "Expert developers"),
      C("web_r2", "Diseño responsivo", "Responsive design"),
      C("web_r3", "Soporte técnico", "Technical support"),
    ],
    [C("web_q1", "Tecnología moderna", "Modern technology")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "recursos_humanos",
    "legal_professional",
    "Recursos Humanos",
    "Human Resources",
    [
      C("rh_reclutamiento", "Reclutamiento", "Recruitment"),
      C("rh_capacitacion", "Capacitación", "Training"),
      C("rh_politicas", "Políticas de RRHH", "HR policies"),
      C("rh_consultoria", "Consultoría de RRHH", "HR consulting"),
    ],
    [
      C("rh_r1", "Especialistas en RRHH", "HR specialists"),
      C("rh_r2", "Servicio integral", "Comprehensive service"),
      C("rh_r3", "Confidencialidad", "Confidentiality"),
    ],
    [C("rh_q1", "Experiencia empresarial", "Business experience")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "arquitectura",
    "legal_professional",
    "Arquitectura",
    "Architecture",
    [
      C("arq_diseño", "Diseño arquitectónico", "Architectural design"),
      C("arq_planos", "Planos de construcción", "Construction plans"),
      C("arq_supervision", "Supervisión de obra", "Construction supervision"),
      C("arq_remodelacion", "Diseño de remodelación", "Remodeling design"),
    ],
    [
      C("arq_r1", "Arquitecto licenciado", "Licensed architect"),
      C("arq_r2", "Diseño innovador", "Innovative design"),
      C("arq_r3", "Proyectos completados", "Completed projects"),
    ],
    [C("arq_q1", "Visión creativa", "Creative vision")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),

  // Educación y Tutoría
  preset(
    "tutoria_clases_particulares",
    "education_tutoring",
    "Tutoría / Clases Particulares",
    "Tutoring / Private Lessons",
    [
      C("tut_mates", "Tutoría de matemáticas", "Math tutoring"),
      C("tut_idiomas", "Tutoría de idiomas", "Language tutoring"),
      C("tut_ciencias", "Tutoría de ciencias", "Science tutoring"),
      C("tut_online", "Clases online", "Online classes"),
    ],
    [
      C("tut_r1", "Tutores calificados", "Qualified tutors"),
      C("tut_r2", "Métodos personalizados", "Personalized methods"),
      C("tut_r3", "Resultados comprobados", "Proven results"),
    ],
    [C("tut_q1", "Experiencia educativa", "Educational experience")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "musica_clases_instrumento",
    "education_tutoring",
    "Música / Clases de Instrumento",
    "Music / Instrument Lessons",
    [
      C("mus_guitarra", "Clases de guitarra", "Guitar lessons"),
      C("mus_piano", "Clases de piano", "Piano lessons"),
      C("mus_violin", "Clases de violín", "Violin lessons"),
      C("mus_canto", "Clases de canto", "Singing lessons"),
    ],
    [
      C("mus_r1", "Maestros de música", "Music teachers"),
      C("mus_r2", "Todos los niveles", "All levels"),
      C("mus_r3", "Método efectivo", "Effective method"),
    ],
    [C("mus_q1", "Pasión por la música", "Passion for music")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "arte_manualidades",
    "education_tutoring",
    "Arte / Manualidades",
    "Art / Crafts",
    [
      C("arte_pintura", "Clases de pintura", "Painting classes"),
      C("arte_escultura", "Clases de escultura", "Sculpture classes"),
      C("arte_manualidades", "Talleres de manualidades", "Craft workshops"),
      C("arte_dibujo", "Clases de dibujo", "Drawing classes"),
    ],
    [
      C("arte_r1", "Artistas profesionales", "Professional artists"),
      C("arte_r2", "Materiales de calidad", "Quality materials"),
      C("arte_r3", "Ambiente creativo", "Creative environment"),
    ],
    [C("arte_q1", "Expresión artística", "Artistic expression")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "idiomas_conversacion",
    "education_tutoring",
    "Idiomas / Conversación",
    "Languages / Conversation",
    [
      C("idi_ingles", "Clases de inglés", "English classes"),
      C("idi_frances", "Clases de francés", "French classes"),
      C("idi_conversacion", "Práctica de conversación", "Conversation practice"),
      C("idi_negocios", "Idiomas para negocios", "Business languages"),
    ],
    [
      C("idi_r1", "Profesores nativos", "Native teachers"),
      C("idi_r2", "Métodos comunicativos", "Communicative methods"),
      C("idi_r3", "Grupos pequeños", "Small groups"),
    ],
    [C("idi_q1", "Inmersión lingüística", "Language immersion")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "preparacion_examenes",
    "education_tutoring",
    "Preparación de Exámenes",
    "Test Preparation",
    [
      C("exam_universidad", "Preparación universitaria", "College prep"),
      C("exam_estandarizados", "Exámenes estandarizados", "Standardized tests"),
      C("exam_idiomas", "Exámenes de idiomas", "Language tests"),
      C("exam_certificacion", "Certificaciones profesionales", "Professional certifications"),
    ],
    [
      C("exam_r1", "Instructores especializados", "Specialized instructors"),
      C("exam_r2", "Material actualizado", "Updated materials"),
      C("exam_r3", "Tasas de éxito", "Success rates"),
    ],
    [C("exam_q1", "Estrategias efectivas", "Effective strategies")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "educacion_adultos",
    "education_tutoring",
    "Educación para Adultos",
    "Adult Education",
    [
      C("edu_alfabetizacion", "Alfabetización", "Literacy"),
      C("edu_computacion", "Clases de computación", "Computer classes"),
      C("edu_desarrollo", "Desarrollo personal", "Personal development"),
      C("edu_comunitaria", "Educación comunitaria", "Community education"),
    ],
    [
      C("edu_r1", "Educadores pacientes", "Patient educators"),
      C("edu_r2", "Ambiente respetuoso", "Respectful environment"),
      C("edu_r3", "Aprendizaje práctico", "Practical learning"),
    ],
    [C("edu_q1", "Educación para todos", "Education for all")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "entrenamiento_deportivo",
    "education_tutoring",
    "Entrenamiento Deportivo",
    "Sports Training",
    [
      C("deport_futbol", "Entrenamiento de fútbol", "Soccer training"),
      C("deport_basketball", "Entrenamiento de basketball", "Basketball training"),
      C("deport_tenis", "Clases de tenis", "Tennis lessons"),
      C("deport_personalizado", "Entrenamiento personalizado", "Personalized training"),
    ],
    [
      C("deport_r1", "Entrenadores certificados", "Certified coaches"),
      C("deport_r2", "Equipos profesionales", "Professional equipment"),
      C("deport_r3", "Métodos probados", "Proven methods"),
    ],
    [C("deport_q1", "Pasión deportiva", "Sports passion")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),

  // Eventos y Entretenimiento
  preset(
    "planificacion_eventos",
    "events_entertainment",
    "Planificación de Eventos",
    "Event Planning",
    [
      C("event_bodas", "Planificación de bodas", "Wedding planning"),
      C("event_corporativos", "Eventos corporativos", "Corporate events"),
      C("event_fiestas", "Fiestas privadas", "Private parties"),
      C("event_conferencias", "Conferencias", "Conferences"),
    ],
    [
      C("event_r1", "Planificadores expertos", "Expert planners"),
      C("event_r2", "Atención al detalle", "Attention to detail"),
      C("event_r3", "Presupuesto ajustado", "Budget-friendly"),
    ],
    [C("event_q1", "Eventos memorables", "Memorable events")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "fotografia_eventos",
    "events_entertainment",
    "Fotografía de Eventos",
    "Event Photography",
    [
      C("foto_event_bodas", "Fotografía de bodas", "Wedding photography"),
      C("foto_event_corporativos", "Eventos corporativos", "Corporate events"),
      C("foto_event_fiestas", "Fiestas y celebraciones", "Parties and celebrations"),
      C("foto_event_grados", "Ceremonias de graduación", "Graduation ceremonies"),
    ],
    [
      C("foto_event_r1", "Fotógrafos profesionales", "Professional photographers"),
      C("foto_event_r2", "Equipos de alta calidad", "High-quality equipment"),
      C("foto_event_r3", "Entrega rápida", "Fast delivery"),
    ],
    [C("foto_event_q1", "Captura de momentos", "Moment capturing")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "catering_comida_eventos",
    "events_entertainment",
    "Catering / Comida para Eventos",
    "Event Catering",
    [
      C("cat_bodas", "Catering para bodas", "Wedding catering"),
      C("cat_corporativo", "Catering corporativo", "Corporate catering"),
      C("cat_social", "Eventos sociales", "Social events"),
      C("cat_personalizado", "Menús personalizados", "Custom menus"),
    ],
    [
      C("cat_r1", "Chefs profesionales", "Professional chefs"),
      C("cat_r2", "Ingredientes frescos", "Fresh ingredients"),
      C("cat_r3", "Servicio impecable", "Impeccable service"),
    ],
    [C("cat_q1", "Experiencia culinaria", "Culinary experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "entretenimiento_show",
    "events_entertainment",
    "Entretenimiento / Show",
    "Entertainment / Shows",
    [
      C("entre_musica", "Música en vivo", "Live music"),
      C("entre_magia", "Espectáculos de magia", "Magic shows"),
      C("entre_comedia", "Shows de comedia", "Comedy shows"),
      C("entre_danza", "Presentaciones de danza", "Dance performances"),
    ],
    [
      C("entre_r1", "Artistas profesionales", "Professional artists"),
      C("entre_r2", "Espectáculos únicos", "Unique shows"),
      C("entre_r3", "Entretenimiento garantizado", "Guaranteed entertainment"),
    ],
    [C("entre_q1", "Talento excepcional", "Exceptional talent")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "dj_musica_eventos",
    "events_entertainment",
    "DJ / Música para Eventos",
    "DJ / Event Music",
    [
      C("dj_fiestas", "DJ para fiestas", "Party DJ"),
      C("dj_bodas", "DJ para bodas", "Wedding DJ"),
      C("dj_corporativo", "DJ para eventos corporativos", "Corporate event DJ"),
      C("dj_playlist", "Playlist personalizada", "Custom playlist"),
    ],
    [
      C("dj_r1", "Equipo profesional", "Professional equipment"),
      C("dj_r2", "Música variada", "Varied music"),
      C("dj_r3", "Animación", "Entertainment"),
    ],
    [C("dj_q1", "Experiencia en eventos", "Event experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "decoracion_eventos",
    "events_entertainment",
    "Decoración de Eventos",
    "Event Decoration",
    [
      C("decor_bodas", "Decoración de bodas", "Wedding decoration"),
      C("decor_fiestas", "Decoración de fiestas", "Party decoration"),
      C("decor_corporativo", "Decoración corporativa", "Corporate decoration"),
      C("decor_temas", "Decoración temática", "Themed decoration"),
    ],
    [
      C("decor_r1", "Decoradores creativos", "Creative decorators"),
      C("decor_r2", "Detalles únicos", "Unique details"),
      C("decor_r3", "Presupuesto flexible", "Flexible budget"),
    ],
    [C("decor_q1", "Ambientes mágicos", "Magical atmospheres")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "alquiler_equipo_eventos",
    "events_entertainment",
    "Alquiler de Equipo para Eventos",
    "Event Equipment Rental",
    [
      C("alq_sillas", "Alquiler de sillas", "Chair rental"),
      C("alq_mesas", "Alquiler de mesas", "Table rental"),
      C("alq_carpas", "Alquiler de carpas", "Tent rental"),
      C("alq_sonido", "Equipo de sonido", "Sound equipment"),
    ],
    [
      C("alq_r1", "Equipo de calidad", "Quality equipment"),
      C("alq_r2", "Entrega y montaje", "Delivery and setup"),
      C("alq_r3", "Precios competitivos", "Competitive prices"),
    ],
    [C("alq_q1", "Servicio confiable", "Reliable service")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),

  // Tecnología y Soporte
  preset(
    "soporte_tecnico_ti",
    "technology_support",
    "Soporte Técnico / TI",
    "IT / Technical Support",
    [
      C("ti_soporte", "Soporte técnico", "Technical support"),
      C("ti_redes", "Soporte de redes", "Network support"),
      C("ti_servidores", "Administración de servidores", "Server administration"),
      C("ti_seguridad", "Seguridad informática", "IT security"),
    ],
    [
      C("ti_r1", "Técnicos certificados", "Certified technicians"),
      C("ti_r2", "Respuesta rápida", "Fast response"),
      C("ti_r3", "Soluciones efectivas", "Effective solutions"),
    ],
    [C("ti_q1", "Experiencia técnica", "Technical experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "reparacion_electronicos",
    "technology_support",
    "Reparación de Electrónicos",
    "Electronics Repair",
    [
      C("elec_celulares", "Reparación de celulares", "Cell phone repair"),
      C("elec_computadoras", "Reparación de computadoras", "Computer repair"),
      C("elec_tablets", "Reparación de tablets", "Tablet repair"),
      C("elec_consolas", "Reparación de consolas", "Game console repair"),
    ],
    [
      C("elec_r1", "Técnicos especializados", "Specialized technicians"),
      C("elec_r2", "Repuestos de calidad", "Quality parts"),
      C("elec_r3", "Garantía de servicio", "Service warranty"),
    ],
    [C("elec_q1", "Diagnóstico preciso", "Accurate diagnosis")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "desarrollo_web_apps",
    "technology_support",
    "Desarrollo Web / Apps",
    "Web / App Development",
    [
      C("dev_apps", "Desarrollo de apps", "App development"),
      C("dev_web", "Desarrollo web", "Web development"),
      C("dev_mantenimiento", "Mantenimiento", "Maintenance"),
      C("dev_actualizacion", "Actualizaciones", "Updates"),
    ],
    [
      C("dev_r1", "Desarrolladores expertos", "Expert developers"),
      C("dev_r2", "Tecnología moderna", "Modern technology"),
      C("dev_r3", "Soporte continuo", "Ongoing support"),
    ],
    [C("dev_q1", "Innovación constante", "Constant innovation")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "diseno_web_ux",
    "technology_support",
    "Diseño Web / UX",
    "Web Design / UX",
    [
      C("ux_diseno", "Diseño UX/UI", "UX/UI design"),
      C("ux_prototipos", "Prototipado", "Prototyping"),
      C("ux_testing", "Pruebas de usabilidad", "Usability testing"),
      C("ux_optimizacion", "Optimización de experiencia", "Experience optimization"),
    ],
    [
      C("ux_r1", "Diseñadores expertos", "Expert designers"),
      C("ux_r2", "Enfoque usuario", "User-focused"),
      C("ux_r3", "Resultados medibles", "Measurable results"),
    ],
    [C("ux_q1", "Diseño centrado en usuario", "User-centered design")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "instalacion_software",
    "technology_support",
    "Instalación de Software",
    "Software Installation",
    [
      C("soft_instalacion", "Instalación de programas", "Program installation"),
      C("soft_configuracion", "Configuración", "Configuration"),
      C("soft_actualizacion", "Actualización de software", "Software updates"),
      C("soft_soporte", "Soporte técnico", "Technical support"),
    ],
    [
      C("soft_r1", "Técnicos certificados", "Certified technicians"),
      C("soft_r2", "Instalación profesional", "Professional installation"),
      C("soft_r3", "Capacitación incluida", "Training included"),
    ],
    [C("soft_q1", "Software legítimo", "Legitimate software")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "redes_conectividad",
    "technology_support",
    "Redes y Conectividad",
    "Networks & Connectivity",
    [
      C("red_instalacion", "Instalación de redes", "Network installation"),
      C("red_configuracion", "Configuración de red", "Network configuration"),
      C("red_mantenimiento", "Mantenimiento de red", "Network maintenance"),
      C("red_seguridad", "Seguridad de red", "Network security"),
    ],
    [
      C("red_r1", "Ingenieros de red", "Network engineers"),
      C("red_r2", "Equipos profesionales", "Professional equipment"),
      C("red_r3", "Soporte 24/7", "24/7 support"),
    ],
    [C("red_q1", "Conectividad confiable", "Reliable connectivity")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "recuperacion_datos",
    "technology_support",
    "Recuperación de Datos",
    "Data Recovery",
    [
      C("datos_recuperacion", "Recuperación de datos", "Data recovery"),
      C("datos_duros", "Recuperación de discos duros", "Hard drive recovery"),
      C("datos_copias", "Recuperación de copias", "Backup recovery"),
      C("datos_emergencia", "Recuperación de emergencia", "Emergency recovery"),
    ],
    [
      C("datos_r1", "Especialistas en recuperación", "Recovery specialists"),
      C("datos_r2", "Equipos avanzados", "Advanced equipment"),
      C("datos_r3", "Confidencialidad", "Confidentiality"),
    ],
    [C("datos_q1", "Tasa de éxito alta", "High success rate")],
    [C("cta_emergencia", "Emergencia", "Emergency")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),

  // Servicios Generales
  preset(
    "mensajeria_delivery",
    "miscellaneous",
    "Mensajería / Delivery",
    "Messenger / Delivery",
    [
      C("mens_paquetes", "Entrega de paquetes", "Package delivery"),
      C("mens_documentos", "Mensajería de documentos", "Document messenger"),
      C("mens_moto", "Delivery en moto", "Motorcycle delivery"),
      C("mens_urgente", "Entrega urgente", "Urgent delivery"),
    ],
    [
      C("mens_r1", "Entrega rápida", "Fast delivery"),
      C("mens_r2", "Servicio confiable", "Reliable service"),
      C("mens_r3", "Seguro de carga", "Cargo insurance"),
    ],
    [C("mens_q1", "Cobertura amplia", "Wide coverage")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "tramites_gestoria",
    "miscellaneous",
    "Trámites / Gestoría",
    "Paperwork / Processing",
    [
      C("tram_gubernamentales", "Trámites gubernamentales", "Government paperwork"),
      C("tram_legales", "Trámites legales", "Legal paperwork"),
      C("tram_permisos", "Gestión de permisos", "Permit processing"),
      C("tram_licencias", "Trámites de licencias", "License processing"),
    ],
    [
      C("tram_r1", "Gestores expertos", "Expert processors"),
      C("tram_r2", "Trámite rápido", "Fast processing"),
      C("tram_r3", "Documentación completa", "Complete documentation"),
    ],
    [C("tram_q1", "Conocimiento legal", "Legal knowledge")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "mudanzas_transporte",
    "miscellaneous",
    "Mudanzas / Transporte",
    "Moving / Transport",
    [
      C("mud_residencial", "Mudanzas residenciales", "Residential moving"),
      C("mud_comercial", "Mudanzas comerciales", "Commercial moving"),
      C("mud_empaque", "Servicios de empaque", "Packing services"),
      C("mud_almacenaje", "Almacenaje temporal", "Temporary storage"),
    ],
    [
      C("mud_r1", "Personal capacitado", "Trained staff"),
      C("mud_r2", "Equipo adecuado", "Proper equipment"),
      C("mud_r3", "Servicio seguro", "Secure service"),
    ],
    [C("mud_q1", "Experiencia en mudanzas", "Moving experience")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "almacenamiento",
    "miscellaneous",
    "Almacenamiento",
    "Storage",
    [
      C("alm_corto", "Almacenamiento corto plazo", "Short-term storage"),
      C("alm_largo", "Almacenamiento largo plazo", "Long-term storage"),
      C("alm_cajas", "Alquiler de cajas", "Box rental"),
      C("alm_seguro", "Almacenamiento seguro", "Secure storage"),
    ],
    [
      C("alm_r1", "Instalaciones seguras", "Secure facilities"),
      C("alm_r2", "Acceso 24/7", "24/7 access"),
      C("alm_r3", "Precios competitivos", "Competitive prices"),
    ],
    [C("alm_q1", "Flexibilidad de espacio", "Space flexibility")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "consultoria_variada",
    "miscellaneous",
    "Consultoría Variada",
    "General Consulting",
    [
      C("cons_negocios", "Consultoría de negocios", "Business consulting"),
      C("cons_financiera", "Consultoría financiera", "Financial consulting"),
      C("cons_estrategica", "Consultoría estratégica", "Strategic consulting"),
      C("cons_personal", "Consultoría personal", "Personal consulting"),
    ],
    [
      C("cons_r1", "Consultores expertos", "Expert consultants"),
      C("cons_r2", "Análisis profundo", "In-depth analysis"),
      C("cons_r3", "Soluciones prácticas", "Practical solutions"),
    ],
    [C("cons_q1", "Experiencia diversificada", "Diversified experience")],
    [C("cta_cita", "Agendar cita", "Schedule appointment")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "servicios_impresion",
    "miscellaneous",
    "Servicios de Impresión",
    "Printing Services",
    [
      C("imp_digital", "Impresión digital", "Digital printing"),
      C("imp_offset", "Impresión offset", "Offset printing"),
      C("imp_gran_formato", "Impresión gran formato", "Large format printing"),
      C("imp_personalizada", "Impresión personalizada", "Custom printing"),
    ],
    [
      C("imp_r1", "Calidad de impresión", "Print quality"),
      C("imp_r2", "Entrega rápida", "Fast delivery"),
      C("imp_r3", "Precios competitivos", "Competitive prices"),
    ],
    [C("imp_q1", "Equipos modernos", "Modern equipment")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "traduccion_documentos",
    "miscellaneous",
    "Traducción de Documentos",
    "Document Translation",
    [
      C("trad_legal", "Traducción legal", "Legal translation"),
      C("trad_medica", "Traducción médica", "Medical translation"),
      C("trad_tecnica", "Traducción técnica", "Technical translation"),
      C("trad_certificada", "Traducción certificada", "Certified translation"),
    ],
    [
      C("trad_r1", "Traductores profesionales", "Professional translators"),
      C("trad_r2", "Precisión garantizada", "Guaranteed accuracy"),
      C("trad_r3", "Entrega a tiempo", "On-time delivery"),
    ],
    [C("trad_q1", "Especialización múltiple", "Multiple specializations")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
  preset(
    "servicio_otro_generico",
    "other",
    "Otro servicio",
    "Other service",
    [
      C("otro_svc", "Servicio a medida", "Custom service"),
      C("otro_consulta", "Consultoría / asesoría", "Consulting"),
      C("otro_urgente", "Atención con cita", "By appointment"),
    ],
    [
      C("otro_r1", "Servicio local", "Local service"),
      C("otro_r2", "Referencias previas", "References on request"),
    ],
    [C("otro_q1", "Horario flexible", "Flexible hours")],
    [C("cta_cotiz", "Solicitar cotización", "Request quote"), C("cta_llamar", "Llamar ahora", "Call now")],
    [C("sec_whatsapp", "WhatsApp", "WhatsApp")],
  ),
];

export function getBusinessTypePreset(id: string): BusinessTypePreset | undefined {
  return BUSINESS_TYPE_PRESETS.find((p) => p.id === id);
}

export function chipLabel(chip: ChipDef, lang: "es" | "en"): string {
  return lang === "en" ? chip.en : chip.es;
}
