export type AutosPublicLang = "es" | "en";

export const AUTOS_PUBLIC_BLUEPRINT_COPY = {
  es: {
    breadcrumb: "Clasificados",
    title: "Leonix Autos",
    tagline: "Encuentra tu próximo vehículo en NorCal — concesionarios y particulares en un solo lugar.",
    searchPlaceholder: "Buscar por marca, modelo, año…",
    cityLabel: "Ciudad",
    cityPlaceholder: "Ej. San Jose",
    zipLabel: "ZIP",
    zipPlaceholder: "5 dígitos",
    nearLabel: "Cerca de",
    searchCta: "Buscar autos",
    quickDiscovery: "Explorar por estilo",
    chips: {
      sedan: "Sedán",
      suv: "SUV",
      truck: "Camioneta",
      coupe: "Coupé",
      luxury: "Lujo",
      ev: "Eléctrico / Híbrido",
    },
    featuredZoneTitle: "Destacado cerca de San Jose, CA",
    featuredBadge: "Destacado",
    freshTitle: "Inventario reciente",
    browseAll: "Explorar todos los autos",
    resultsTitle: "Autos en venta",
    resultsNear: "cerca de {city}, {state}",
    resultCount: "{n} resultados",
    sortLabel: "Ordenar",
    sortNewest: "Más reciente",
    sortPriceLow: "Precio: menor",
    sortPriceHigh: "Precio: mayor",
    sortMileage: "Menor millaje",
    filtersOpen: "Filtros",
    filtersTitle: "Filtros",
    filterApply: "Aplicar",
    filterReset: "Restablecer",
    filterPrice: "Precio (USD)",
    priceMin: "Mín.",
    priceMax: "Máx.",
    filterMake: "Marca",
    filterModel: "Modelo",
    filterYear: "Año",
    yearFrom: "Desde",
    yearTo: "Hasta",
    filterAny: "Cualquiera",
    conditionNew: "Nuevo",
    conditionUsed: "Usado",
    conditionCertified: "Certificado",
    filterCondition: "Condición",
    filterSeller: "Vendedor",
    sellerAll: "Todos",
    sellerDealer: "Concesionario",
    sellerPrivate: "Particular",
    filterBody: "Carrocería",
    filterTransmission: "Transmisión",
    filterDrivetrain: "Tracción",
    filterFuel: "Combustible",
    filterMileage: "Millaje máx.",
    filterTitle: "Estado del título",
    paginationPrev: "Anterior",
    paginationNext: "Siguiente",
    loadMore: "Cargar más",
    pageOf: "Página {page}",
    cardMonthly: "desde {amount}/mes est.",
    cardMi: "mi",
    sellerDealerFooter: "Concesionario",
    sellerPrivateFooter: "Particular",
    alertCta: "Establecer alerta",
    postAd: "Publicar anuncio",
    viewListings: "Ver anuncios",
    hubNote: "También en Leonix",
  },
  en: {
    breadcrumb: "Classifieds",
    title: "Leonix Autos",
    tagline: "Find your next vehicle in NorCal — dealerships and private sellers in one premium destination.",
    searchPlaceholder: "Search by make, model, year…",
    cityLabel: "City",
    cityPlaceholder: "e.g. San Jose",
    zipLabel: "ZIP",
    zipPlaceholder: "5 digits",
    nearLabel: "Near",
    searchCta: "Search inventory",
    quickDiscovery: "Browse by style",
    chips: {
      sedan: "Sedan",
      suv: "SUV",
      truck: "Truck",
      coupe: "Coupe",
      luxury: "Luxury",
      ev: "Electric / Hybrid",
    },
    featuredZoneTitle: "Featured near San Jose, CA",
    featuredBadge: "Featured",
    freshTitle: "Fresh inventory",
    browseAll: "Explore all vehicles",
    resultsTitle: "Vehicles for sale",
    resultsNear: "near {city}, {state}",
    resultCount: "{n} results",
    sortLabel: "Sort",
    sortNewest: "Newest",
    sortPriceLow: "Price: low to high",
    sortPriceHigh: "Price: high to low",
    sortMileage: "Lowest mileage",
    filtersOpen: "Filters",
    filtersTitle: "Filters",
    filterApply: "Apply",
    filterReset: "Reset",
    filterPrice: "Price (USD)",
    priceMin: "Min",
    priceMax: "Max",
    filterMake: "Make",
    filterModel: "Model",
    filterYear: "Year",
    yearFrom: "From",
    yearTo: "To",
    filterAny: "Any",
    conditionNew: "New",
    conditionUsed: "Used",
    conditionCertified: "Certified",
    filterCondition: "Condition",
    filterSeller: "Seller",
    sellerAll: "All",
    sellerDealer: "Dealership",
    sellerPrivate: "Private",
    filterBody: "Body style",
    filterTransmission: "Transmission",
    filterDrivetrain: "Drivetrain",
    filterFuel: "Fuel",
    filterMileage: "Max mileage",
    filterTitle: "Title status",
    paginationPrev: "Previous",
    paginationNext: "Next",
    loadMore: "Load more",
    pageOf: "Page {page}",
    cardMonthly: "from {amount}/mo est.",
    cardMi: "mi",
    sellerDealerFooter: "Dealership",
    sellerPrivateFooter: "Private",
    alertCta: "Set alert",
    postAd: "Post a listing",
    viewListings: "View listings",
    hubNote: "Also on Leonix",
  },
} as const;

export type AutosPublicBlueprintCopy = (typeof AUTOS_PUBLIC_BLUEPRINT_COPY)[AutosPublicLang];
