import type { SupportedLang } from "@/app/lib/language";
import type { PublicChromeCopy } from "./types";

const ES: PublicChromeCopy = {
  followUs: "Síguenos",
  contact: "Contacto",
  advertise: "Anúnciate",
  promoProducts: "Productos para Promoción",
  cookiePrefs: "Preferencias de cookies",
  learnMore: "Más información",
  email: "Correo",
  phone: "Teléfono",
  advertiseBody:
    "conecta negocios, clasificados y comunidad en un solo ecosistema bilingüe para el Área de la Bahía y el norte de California.",
  socialNote: "Próximamente en redes.",
  companyNote: "Una empresa bajo",
  legal: "Legal",
  privacy: "Privacidad",
  terms: "Términos",
  dataDeletion: "Eliminación de datos",
  legalNavAria: "Enlaces legales",
};

const EN: PublicChromeCopy = {
  followUs: "Follow us",
  contact: "Contact",
  advertise: "Advertise",
  promoProducts: "Promotional Products",
  cookiePrefs: "Cookie preferences",
  learnMore: "Learn more",
  email: "Email",
  phone: "Phone",
  advertiseBody:
    "connects businesses, classifieds, and community in one bilingual ecosystem for the Bay Area and Northern California.",
  socialNote: "Social channels coming soon.",
  companyNote: "A company under",
  legal: "Legal",
  privacy: "Privacy",
  terms: "Terms",
  dataDeletion: "Data deletion",
  legalNavAria: "Legal links",
};

function fromEn(partial: Partial<PublicChromeCopy>): PublicChromeCopy {
  return { ...EN, ...partial };
}

export const PUBLIC_CHROME_COPY: Record<SupportedLang, PublicChromeCopy> = {
  es: ES,
  en: EN,
  vi: {
    followUs: "Theo dõi chúng tôi",
    contact: "Liên hệ",
    advertise: "Quảng cáo",
    promoProducts: "Sản phẩm khuyến mãi",
    cookiePrefs: "Tùy chọn cookie",
    learnMore: "Tìm hiểu thêm",
    email: "Email",
    phone: "Điện thoại",
    advertiseBody:
      "kết nối doanh nghiệp, rao vặt và cộng đồng trong một hệ sinh thái song ngữ cho Bay Area và Bắc California.",
    socialNote: "Kênh mạng xã hội sắp ra mắt.",
    companyNote: "Một công ty thuộc",
    legal: "Pháp lý",
    privacy: "Quyền riêng tư",
    terms: "Điều khoản",
    dataDeletion: "Xóa dữ liệu",
    legalNavAria: "Liên kết pháp lý",
  },
  pt: {
    followUs: "Siga-nos",
    contact: "Contato",
    advertise: "Anuncie",
    promoProducts: "Produtos promocionais",
    cookiePrefs: "Preferências de cookies",
    learnMore: "Saiba mais",
    email: "E-mail",
    phone: "Telefone",
    advertiseBody:
      "conecta negócios, classificados e comunidade em um ecossistema bilíngue para a Bay Area e o norte da Califórnia.",
    socialNote: "Redes sociais em breve.",
    companyNote: "Uma empresa sob",
    legal: "Legal",
    privacy: "Privacidade",
    terms: "Termos",
    dataDeletion: "Exclusão de dados",
    legalNavAria: "Links legais",
  },
  tl: fromEn({
    followUs: "Sundan kami",
    contact: "Contact",
    advertise: "Mag-advertise",
    promoProducts: "Promotional products",
    cookiePrefs: "Mga preference ng cookie",
    learnMore: "Alamin pa",
    email: "Email",
    phone: "Telepono",
    advertiseBody:
      "nag-uugnay ng negosyo, classifieds, at komunidad sa isang bilingual ecosystem para sa Bay Area at Northern California.",
    socialNote: "Malapit na ang social channels.",
    companyNote: "Isang kumpanya sa ilalim ng",
    privacy: "Privacy",
    terms: "Terms",
    dataDeletion: "Pagbura ng data",
    legalNavAria: "Mga legal na link",
  }),
  km: fromEn({
    followUs: "តាមដានយើង",
    contact: "ទំនាក់ទំនង",
    advertise: "ផ្សាយពាណិជ្ជកម្ម",
    promoProducts: "ផលិតផលផ្សព្វផ្សាយ",
    cookiePrefs: "ការកំណត់ cookie",
    learnMore: "ស្វែងយល់បន្ថែម",
    email: "អ៊ីមែល",
    phone: "ទូរស័ព្ទ",
    advertiseBody:
      "ភ្ជាប់អាជីវកម្ម ការផ្សាយពាណិជ្ជកម្ម និងសហគមន៍ក្នុងប្រព័ន្ធបរិស្ថានពីរភាសាសម្រាប់ Bay Area និងភាគខាងជើង California។",
    socialNote: "បណ្តាញសocial នឹងមកដល់ឆាប់ៗនេះ។",
    companyNote: "ក្រុមហ៊ុនក sob",
    legal: "ផ្លូវច្បាប់",
    privacy: "ភាពឯកជន",
    terms: "លក្ខខណ្ឌ",
    dataDeletion: "លុបទិន្នន័យ",
    legalNavAria: "តំណផ្លូវច្បាប់",
  }),
  zh: fromEn({
    followUs: "关注我们",
    contact: "联系",
    advertise: "投放广告",
    promoProducts: "促销产品",
    cookiePrefs: "Cookie 偏好",
    learnMore: "了解更多",
    email: "电子邮件",
    phone: "电话",
    advertiseBody: "将企业、分类信息和社区连接在一个双语生态系统中，服务湾区和北加州。",
    socialNote: "社交媒体频道即将上线。",
    companyNote: "隶属于",
    legal: "法律",
    privacy: "隐私",
    terms: "条款",
    dataDeletion: "数据删除",
    legalNavAria: "法律链接",
  }),
  ja: {
    followUs: "フォローする",
    contact: "お問い合わせ",
    advertise: "広告掲載",
    promoProducts: "プロモーション商品",
    cookiePrefs: "Cookie設定",
    learnMore: "詳しく見る",
    email: "メール",
    phone: "電話",
    advertiseBody:
      "は、Bay Areaと北カリフォルニア向けに、ビジネス、クラシファイド、コミュニティをつなぐバイリンガルエコシステムです。",
    socialNote: "ソーシャルチャンネルは近日公開予定です。",
    companyNote: "傘下企業：",
    legal: "法的情報",
    privacy: "プライバシー",
    terms: "利用規約",
    dataDeletion: "データ削除",
    legalNavAria: "法的リンク",
  },
  ko: fromEn({
    followUs: "팔로우",
    contact: "문의",
    advertise: "광고하기",
    promoProducts: "프로모션 제품",
    cookiePrefs: "쿠키 설정",
    learnMore: "자세히 보기",
    email: "이메일",
    phone: "전화",
    advertiseBody: "Bay Area와 북부 캘리포니아를 위한 이중 언어 생태계에서 비즈니스, 분류 광고, 커뮤니티를 연결합니다.",
    socialNote: "소셜 채널 곧 공개 예정.",
    companyNote: "소속 회사:",
    legal: "법적 고지",
    privacy: "개인정보",
    terms: "약관",
    dataDeletion: "데이터 삭제",
    legalNavAria: "법적 링크",
  }),
  hi: fromEn({
    followUs: "हमें फ़ॉलो करें",
    contact: "संपर्क",
    advertise: "विज्ञापन दें",
    promoProducts: "प्रचार उत्पाद",
    cookiePrefs: "कुकी प्राथमिकताएँ",
    learnMore: "और जानें",
    email: "ईमेल",
    phone: "फ़ोन",
    advertiseBody:
      "Bay Area और उत्तरी California के लिए व्यवसाय, classifieds और समुदाय को एक द्विभाषी पारिस्थितिकी तंत्र में जोड़ता है।",
    socialNote: "सोशल चैनल जल्द आ रहे हैं।",
    companyNote: "एक कंपनी अंतर्गत",
    legal: "कानूनी",
    privacy: "गोपनीयता",
    terms: "शर्तें",
    dataDeletion: "डेटा हटाना",
    legalNavAria: "कानूनी लिंक",
  }),
  hy: fromEn({
    followUs: "Հետևեք մեզ",
    contact: "Կապ",
    advertise: "Գովազդ",
    promoProducts: "Խթանման ապրանքներ",
    cookiePrefs: "Cookie-ի կարգավորումներ",
    learnMore: "Իմանալ ավելին",
    email: "Էլ. փոստ",
    phone: "Հեռախոս",
    advertiseBody:
      "միավորում է բիզնեսը, հայտարարությունները և համայնքը երկլեզու էկոհամակարգում Bay Area-ի և Հյուսիսային California-ի համար։",
    socialNote: "Սոցիալական ալիքները շուտով կլինեն։",
    companyNote: "Ընկերություն՝",
    legal: "Իրավական",
    privacy: "Անձնականություն",
    terms: "Պայմաններ",
    dataDeletion: "Տվյalneri jnjum",
    legalNavAria: "Իրավական հղումներ",
  }),
  ru: fromEn({
    followUs: "Подписаться",
    contact: "Контакты",
    advertise: "Реклама",
    promoProducts: "Рекламная продукция",
    cookiePrefs: "Настройки cookie",
    learnMore: "Подробнее",
    email: "Email",
    phone: "Телефон",
    advertiseBody:
      "объединяет бизнес, объявления и сообщество в двуязычной экосистеме для Bay Area и Северной Калифорнии.",
    socialNote: "Соцсети скоро появятся.",
    companyNote: "Компания под управлением",
    legal: "Правовая информация",
    privacy: "Конфиденциальность",
    terms: "Условия",
    dataDeletion: "Удаление данных",
    legalNavAria: "Правовые ссылки",
  }),
  pa: fromEn({
    followUs: "ਸਾਨੂੰ ਫਾਲੋ ਕਰੋ",
    contact: "ਸੰਪਰਕ",
    advertise: "ਇਸ਼ਤਿਹਾਰ ਦਿਓ",
    promoProducts: "ਪ੍ਰਚਾਰ ਉਤਪਾਦ",
    cookiePrefs: "ਕੁਕੀ ਪਸੰਦਾਂ",
    learnMore: "ਹੋਰ ਜਾਣੋ",
    email: "ਈਮੇਲ",
    phone: "ਫੋਨ",
    advertiseBody:
      "Bay Area ਅਤੇ ਉੱਤਰੀ California ਲਈ ਕਾਰੋਬਾਰ, classifieds ਅਤੇ ਕਮਿਊਨਿਟੀ ਨੂੰ ਇੱਕ ਦੋ-ਭਾਸ਼ੀ ecosystem ਵਿੱਚ ਜੋੜਦਾ ਹੈ।",
    socialNote: "ਸੋਸ਼ਲ ਚੈਨਲ ਜਲਦੀ ਆ ਰਹੇ ਹਨ।",
    companyNote: "ਇੱਕ ਕੰਪਨੀ ਅਧੀਨ",
    legal: "ਕਾਨੂੰਨੀ",
    privacy: "ਗੋਪਨੀਯਤਾ",
    terms: "ਸ਼ਰਤਾਂ",
    dataDeletion: "ਡਾਟਾ ਮਿਟਾਉਣਾ",
    legalNavAria: "ਕਾਨੂੰਨੀ ਲਿੰਕ",
  }),
};

/** Footer and shared public chrome copy — native for all active non-RTL languages. */
export function getPublicChromeCopy(lang: SupportedLang): PublicChromeCopy {
  return PUBLIC_CHROME_COPY[lang];
}

export type { PublicChromeCopy } from "./types";
