import {
  createEmptyBienesRaicesMuxVideoSlot,
  mergePartialBienesRaicesNegocioState,
  type BienesRaicesNegocioFormState,
} from "../schema/bienesRaicesNegocioFormState";
import { mapBienesRaicesNegocioStateToPreviewVm } from "./mapBienesRaicesNegocioStateToPreviewVm";
import type { BienesRaicesNegocioPreviewVm } from "./bienesRaicesNegocioPreviewVm";

/** Representative state for static designer mock route only (`/negocio/preview-mockup`). */
export function buildBrNegocioDesignerDemoState(): BienesRaicesNegocioFormState {
  return mergePartialBienesRaicesNegocioState({
    advertiserType: "agente_individual",
    publicationType: "residencial_venta",
    titulo: "Casa moderna con piscina en zona residencial exclusiva",
    precio: "1250000",
    tipoOperacion: "Venta",
    direccion: "Encino Hills",
    ciudad: "Los Ángeles",
    estado: "CA",
    codigoPostal: "91316",
    colonia: "Encino Hills",
    listingStatus: "en_venta",
    tipoPropiedad: "Casa unifamiliar",
    recamaras: "4",
    banosCompletos: "3",
    mediosBanos: "1",
    piesCuadrados: "2450",
    tamanoLote: "7,200 pies²",
    estacionamientos: "2",
    anioConstruccion: "2020",
    media: {
      photoUrls: [
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80&auto=format&fit=crop",
      ],
      primaryImageIndex: 0,
      listingVideoSlots: [
        {
          ...createEmptyBienesRaicesMuxVideoSlot(0),
          fallbackUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80&auto=format&fit=crop",
        },
        {
          ...createEmptyBienesRaicesMuxVideoSlot(1),
          fallbackUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80&auto=format&fit=crop",
        },
      ],
      virtualTourUrl: "https://example.com/tour",
      floorPlanUrls: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80&auto=format&fit=crop"],
      sitePlanUrl: "",
      photoCaptions: [],
    },
    highlightPresets: {
      piscina: true,
      cocinaRemodelada: true,
      electrodomesticosLujo: true,
      vista: true,
      comunidadCerrada: false,
      techosAltos: true,
      walkInCloset: true,
      smartHome: false,
      chimenea: false,
      lavanderia: true,
      terraza: false,
      gimnasio: false,
      patio: true,
      balcon: false,
      cuartoPrincipalGrande: true,
      oficinaEnCasa: false,
      panelesSolares: false,
      estacionamientoTechado: true,
      accesoControlado: false,
      elevador: false,
      amenidadesDesarrollo: false,
    },
    descripcionLarga:
      "Residencia contemporánea con líneas limpias, amplios ventanales y transición fluida entre espacios interiores y exteriores.",
    identityAgente: {
      nombre: "Angela Meakins",
      fotoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80&auto=format&fit=crop",
      rol: "Agente de listado",
      brokerage: "Coldwell Banker Realty",
      logoBrokerageUrl: "",
      licencia: "DRE #01234567",
      telDirecto: "(818) 555-0100",
      telOficina: "",
      email: "angela@example.com",
      sitioWeb: "https://example.com",
      redes: ["Web", "IG", "FB", "YT", "in"],
      idiomas: "Inglés, español",
      areasServicio: "San Fernando Valley",
      bio: "",
      segundoAgenteActivo: true,
    },
    asesorFinancieroActivo: true,
    segundoAgente: {
      nombre: "Nicole Anderson",
      fotoUrl: "",
      rol: "Segundo agente",
      telefono: "(818) 555-0142",
      email: "",
      bio: "",
    },
    asesorFinanciero: {
      nombre: "David Ramírez",
      fotoUrl: "",
      rol: "Asesor de préstamos",
      compania: "Leonix Home Loans",
      telefono: "(818) 555-0199",
      email: "",
      sitioWeb: "",
      nmls: "NMLS #998877",
      textoApoyo: "Preaprobación y opciones de financiamiento.",
    },
    cta: {
      permitirSolicitarInfo: true,
      permitirProgramarVisita: true,
      permitirLlamar: true,
      permitirWhatsapp: true,
      mensajePrellenado: "",
      instruccionesContacto: "",
      horarioPreferido: "",
      openHouseActivo: true,
      openHouseFecha: "2026-04-12",
      openHouseInicio: "11:00",
      openHouseFin: "14:00",
      openHouseNotas: "Open house el sábado.",
    },
  });
}

export function buildBrNegocioDesignerDemoVm(): BienesRaicesNegocioPreviewVm {
  return mapBienesRaicesNegocioStateToPreviewVm(buildBrNegocioDesignerDemoState());
}
