export type Lang = "es" | "en";

/**
 * Feature-local ES/EN copy for the Business Identity experience (Package BCO-3). Follows the
 * repository's existing convention (dashboardShellCopy-style function returning a per-lang
 * object literal), not a new i18n framework. Spanish-first, plain, encouraging — no corporate
 * or manipulative language.
 */
export function businessIdentityCopy(lang: Lang) {
  if (lang === "es") {
    return {
      preview: {
        heroEyebrow: "Leonix Business Concierge",
        heroTitle: "Construyendo mejores negocios. Creando mejores vidas.",
        heroLead:
          "Business Concierge te ayudará a organizar la identidad de tu negocio en Leonix y a entender con claridad qué hacer después — sin presión de venta y sin promesas vacías.",
        helpTitle: "En qué te va a ayudar",
        helpItems: [
          "Aclarar la identidad de tu negocio: quién eres, qué ofreces y dónde.",
          "Organizar tu información verificada en un solo lugar.",
          "Identificar los próximos pasos importantes, uno a la vez.",
          "Enseñarte habilidades prácticas, no crear dependencia.",
          "Preparar apoyo de marketing para cuando estés listo.",
          "Medir tu progreso con honestidad, sin inventar cifras.",
        ],
        promiseTitle: "Nuestra promesa",
        promiseItems: [
          "Proteger antes que vender.",
          "Enseñar antes que ofrecer más.",
          "La intervención más pequeña que realmente ayude.",
          "Nunca inventamos evidencia ni resultados.",
          "Tú siempre tienes el control final.",
        ],
        journeyTitle: "El camino, paso a paso",
        journeySteps: ["Entender", "Organizar", "Priorizar", "Actuar", "Aprender", "Mejorar"],
        eligibilityTitle: "Cómo desbloquear la configuración",
        eligibilityLead:
          "Los anunciantes Negocio verificados en Leonix pueden desbloquear la configuración completa de Business Identity. Si ya anuncias como negocio, es posible que ya tengas acceso.",
        eligibilityCta: "Ver opciones para anunciar como negocio",
        ideaTitle: "¿Tienes una idea de negocio?",
        ideaLead:
          "Estamos construyendo herramientas para quienes todavía están en la etapa de idea. Todavía no existen — te avisaremos cuando estén listas.",
        ideaBadge: "Próximamente",
      },
      access: {
        loading: "Cargando tu estado de acceso…",
        unavailableTitle: "Estamos preparando Business Concierge",
        unavailableBody: "Esta función todavía se está preparando para tu cuenta. Vuelve a intentarlo más tarde.",
        ineligibleTitle: "Todavía no encontramos evidencia de tu negocio",
        ineligibleBody:
          "No es un rechazo definitivo — simplemente todavía no podemos confirmar automáticamente que administras un negocio en Leonix.",
        ambiguousTitle: "Necesitamos verificar el acceso a tu negocio",
        ambiguousBody:
          "Encontramos información relacionada con un negocio, pero no pudimos confirmarla automáticamente. Nuestro equipo puede revisarlo manualmente.",
        ambiguousCta: "Solicitar revisión manual",
        eligibleTitle: "Puedes comenzar la configuración de tu negocio",
        eligibleBody: "Toma unos 5-10 minutos. Tu progreso se guarda automáticamente en cada paso.",
        eligibleCta: "Comenzar configuración",
        signInRequired: "Inicia sesión para continuar.",
      },
      drafts: {
        resumeTitle: "Continúa donde te quedaste",
        multipleTitle: "Tienes varios negocios en progreso",
        step: "Paso",
        of: "de",
        lastUpdated: "Última actualización",
        resume: "Continuar",
        delete: "Eliminar",
        deleteConfirmTitle: "¿Eliminar este borrador?",
        deleteConfirmBody: "Esta acción no se puede deshacer.",
        deleteConfirmYes: "Sí, eliminar",
        deleteConfirmNo: "Cancelar",
        startAnother: "Comenzar otro negocio",
        untitled: "Negocio sin nombre",
        expiresNote: "Los borradores sin actividad se eliminan automáticamente después de un tiempo.",
      },
      wizard: {
        stepLabels: [
          "Datos básicos",
          "Tipo y etapa",
          "Ubicación",
          "Contacto",
          "Confirmación",
          "Anuncio existente",
          "Revisión",
        ],
        back: "Atrás",
        next: "Siguiente",
        saveState: { saving: "Guardando…", saved: "Guardado", failed: "No se pudo guardar — reintentar" },
        step1: {
          title: "Datos básicos del negocio",
          displayNameLabel: "Nombre del negocio",
          displayNameHint: "El nombre que usarás en Leonix.",
          legalNameLabel: "Nombre legal (opcional)",
          publicNameLabel: "Nombre público, si es diferente (opcional)",
          publicNameHint:
            "El nombre legal es el registrado oficialmente; el nombre público es como lo conocen tus clientes, si es distinto.",
          languageLabel: "Idioma principal",
        },
        step2: {
          title: "Tipo y etapa del negocio",
          typeLabel: "Tipo de negocio",
          typeOptions: [
            { value: "retail", label: "Tienda / venta al público" },
            { value: "food", label: "Comida y bebida" },
            { value: "services", label: "Servicios" },
            { value: "real_estate", label: "Bienes raíces" },
            { value: "automotive", label: "Automotriz" },
            { value: "other", label: "Otro" },
          ],
          stageLabel: "Etapa del negocio",
          stageOptions: [
            { value: "idea", label: "Idea" },
            { value: "starting", label: "Comenzando" },
            { value: "active", label: "Activo" },
            { value: "paused", label: "En pausa" },
          ],
        },
        step3: {
          title: "Ubicación o zona de servicio",
          kindLabel: "¿Cómo describes tu ubicación?",
          kindPhysical: "Dirección física",
          kindServiceArea: "Zona de servicio (texto)",
          textLabel: "Descripción",
          textHintPhysical: "Ejemplo: 123 Calle Principal, Ciudad",
          textHintServiceArea: "Ejemplo: Área metropolitana de Leonix",
        },
        step4: {
          title: "Contacto y canal preferido",
          typeLabel: "Tipo de contacto",
          typePhone: "Teléfono",
          typeEmail: "Correo electrónico",
          typeWebsite: "Sitio web",
          valueLabel: "Valor",
          preferredLabel: "¿Es tu canal de comunicación preferido?",
          channelLabel: "Canal preferido",
          channelWhatsapp: "WhatsApp",
          channelCall: "Llamada",
          channelEmail: "Correo electrónico",
          primaryLabel: "Contacto principal",
          addAnother: "Agregar otro contacto",
          removeLabel: "Eliminar contacto",
          atLeastOne: "Agrega al menos un contacto para continuar.",
        },
        step5: {
          title: "Confirmación de autorización",
          confirmLabel:
            "Confirmo que soy dueño(a) o estoy autorizado(a) para representar este negocio, y que la información es correcta según mi conocimiento.",
          disclosure:
            "Leonix usará esta información para crear tu Identidad de Negocio. Esto no transfiere la propiedad legal del negocio.",
          settingUpForSomeoneElse: "Estoy configurando esto para alguien más",
        },
        step6: {
          title: "¿Ya tienes un anuncio en Leonix?",
          skipLabel: "Omitir por ahora",
          selectLabel: "Selecciona un anuncio",
          sourceLabel: "Tipo de anuncio",
          idLabel: "ID o slug del anuncio",
          verifying: "Verificando propiedad…",
          verifiedOk: "Anuncio verificado correctamente.",
          verifiedPending: "No pudimos verificar este anuncio todavía — quedará pendiente de revisión.",
          unsupportedSource: "Ese tipo de anuncio todavía no se puede vincular.",
        },
        step7: {
          title: "Revisión y creación",
          sectionBasics: "Datos básicos",
          sectionTypeStage: "Tipo y etapa",
          sectionContact: "Contacto",
          sectionServiceArea: "Ubicación",
          sectionOwnership: "Confirmación",
          sectionListing: "Anuncio vinculado",
          edit: "Editar",
          confirmedYes: "Confirmado",
          noListing: "Ninguno",
          submit: "Crear Identidad de Negocio",
          submitting: "Creando…",
          duplicateAcknowledge: "Entiendo y quiero continuar de todos modos",
        },
        errors: {
          generic: "Ocurrió un error. Intenta de nuevo.",
          validation: "Revisa los campos marcados.",
          network: "No pudimos conectar con el servidor. Intenta de nuevo.",
        },
      },
      duplicate: {
        exactTitle: "Es posible que este negocio ya exista",
        probableTitle: "Encontramos información similar",
        possibleTitle: "Encontramos información parecida",
        exactBody: "Un negocio con información muy similar ya está registrado en Leonix.",
        probableBody: "Un negocio con datos parecidos ya está registrado en Leonix.",
        possibleBody: "Un negocio con un nombre parecido ya está registrado en Leonix.",
        ownBusinessBody: "Ya tienes acceso a este negocio.",
        continueAnyway: "Continuar de todos modos",
        openExisting: "Abrir mi negocio existente",
        requestReview: "Solicitar revisión manual",
        goBack: "Volver y corregir",
      },
      completed: {
        sectionIdentity: "Identidad del negocio",
        sectionContact: "Contacto",
        sectionServiceArea: "Zona de servicio",
        sectionListing: "Anuncio conectado",
        sectionNext: "Qué sigue",
        legalNameLabel: "Nombre legal",
        typeLabel: "Tipo de negocio",
        stageLabel: "Etapa",
        languageLabel: "Idioma principal",
        createdLabel: "Identidad creada el",
        onboardingComplete: "Configuración completa",
        noListing: "Ningún anuncio conectado todavía",
        listingPending: "Pendiente de verificación",
        listingVerified: "Verificado",
        nextItems: [
          { title: "Libro de negocio", body: "Un registro vivo de tu negocio a través del tiempo." },
          { title: "Mapa de salud del negocio", body: "Una vista honesta de cómo va tu negocio." },
          { title: "Próximo paso correcto", body: "Recomendaciones priorizadas, cuando estén listas." },
          { title: "Centro de aprendizaje", body: "Habilidades prácticas para hacer crecer tu negocio." },
        ],
        nextBadge: "Próximamente",
        editingComingSoon: "La edición llegará próximamente.",
      },
      common: {
        loading: "Cargando…",
        error: "Ocurrió un error.",
        retry: "Reintentar",
        cancel: "Cancelar",
      },
    };
  }

  return {
    preview: {
      heroEyebrow: "Leonix Business Concierge",
      heroTitle: "Building Better Businesses. Creating Better Lives.",
      heroLead:
        "Business Concierge will help you organize your business identity on Leonix and clearly understand what to do next — no sales pressure, no empty promises.",
      helpTitle: "What it will help with",
      helpItems: [
        "Clarify your business identity: who you are, what you offer, and where.",
        "Organize your verified information in one place.",
        "Identify important next steps, one at a time.",
        "Teach you practical skills, not create dependency.",
        "Prepare marketing support for when you're ready.",
        "Measure your progress honestly, with no invented numbers.",
      ],
      promiseTitle: "Our promise",
      promiseItems: [
        "Protect before profit.",
        "Teach before upselling.",
        "The smallest intervention that actually helps.",
        "We never fabricate evidence or results.",
        "You always keep final control.",
      ],
      journeyTitle: "The journey, step by step",
      journeySteps: ["Understand", "Organize", "Prioritize", "Act", "Learn", "Improve"],
      eligibilityTitle: "How to unlock full setup",
      eligibilityLead:
        "Verified Negocio advertisers on Leonix can unlock the complete Business Identity setup. If you already advertise as a business, you may already have access.",
      eligibilityCta: "See options to advertise as a business",
      ideaTitle: "Have a business idea?",
      ideaLead: "We're building tools for entrepreneurs still at the idea stage. They don't exist yet — we'll let you know when they're ready.",
      ideaBadge: "Coming soon",
    },
    access: {
      loading: "Loading your access status…",
      unavailableTitle: "We're preparing Business Concierge",
      unavailableBody: "This feature is still being prepared for your account. Please check back later.",
      ineligibleTitle: "We haven't found evidence of your business yet",
      ineligibleBody: "This isn't a final denial — we just can't automatically confirm you manage a business on Leonix yet.",
      ambiguousTitle: "We need to verify your business access",
      ambiguousBody: "We found business-related information but couldn't automatically confirm it. Our team can review it manually.",
      ambiguousCta: "Request manual review",
      eligibleTitle: "You can start setting up your business",
      eligibleBody: "Takes about 5-10 minutes. Your progress saves automatically at every step.",
      eligibleCta: "Start setup",
      signInRequired: "Sign in to continue.",
    },
    drafts: {
      resumeTitle: "Continue where you left off",
      multipleTitle: "You have multiple businesses in progress",
      step: "Step",
      of: "of",
      lastUpdated: "Last updated",
      resume: "Resume",
      delete: "Delete",
      deleteConfirmTitle: "Delete this draft?",
      deleteConfirmBody: "This cannot be undone.",
      deleteConfirmYes: "Yes, delete",
      deleteConfirmNo: "Cancel",
      startAnother: "Start another business",
      untitled: "Untitled business",
      expiresNote: "Inactive drafts are automatically removed after a while.",
    },
    wizard: {
      stepLabels: ["Basics", "Type & stage", "Location", "Contact", "Confirmation", "Existing listing", "Review"],
      back: "Back",
      next: "Next",
      saveState: { saving: "Saving…", saved: "Saved", failed: "Couldn't save — retry" },
      step1: {
        title: "Business basics",
        displayNameLabel: "Business name",
        displayNameHint: "The name you'll use on Leonix.",
        legalNameLabel: "Legal name (optional)",
        publicNameLabel: "Public name, if different (optional)",
        publicNameHint: "The legal name is the officially registered one; the public name is how customers know you, if different.",
        languageLabel: "Primary language",
      },
      step2: {
        title: "Business type and stage",
        typeLabel: "Business type",
        typeOptions: [
          { value: "retail", label: "Retail / storefront" },
          { value: "food", label: "Food & beverage" },
          { value: "services", label: "Services" },
          { value: "real_estate", label: "Real estate" },
          { value: "automotive", label: "Automotive" },
          { value: "other", label: "Other" },
        ],
        stageLabel: "Business stage",
        stageOptions: [
          { value: "idea", label: "Idea" },
          { value: "starting", label: "Starting" },
          { value: "active", label: "Active" },
          { value: "paused", label: "Paused" },
        ],
      },
      step3: {
        title: "Location or service area",
        kindLabel: "How do you describe your location?",
        kindPhysical: "Physical address",
        kindServiceArea: "Service area (text)",
        textLabel: "Description",
        textHintPhysical: "Example: 123 Main St, City",
        textHintServiceArea: "Example: Greater Leonix Metro area",
      },
      step4: {
        title: "Contact and preferred channel",
        typeLabel: "Contact type",
        typePhone: "Phone",
        typeEmail: "Email",
        typeWebsite: "Website",
        valueLabel: "Value",
        preferredLabel: "Is this your preferred communication channel?",
        channelLabel: "Preferred channel",
        channelWhatsapp: "WhatsApp",
        channelCall: "Call",
        channelEmail: "Email",
        primaryLabel: "Primary contact",
        addAnother: "Add another contact",
        removeLabel: "Remove contact",
        atLeastOne: "Add at least one contact to continue.",
      },
      step5: {
        title: "Ownership confirmation",
        confirmLabel: "I confirm I own or am authorized to represent this business, and the information is accurate to the best of my knowledge.",
        disclosure: "Leonix will use this information to build your Business Identity. This does not transfer legal ownership of the business.",
        settingUpForSomeoneElse: "I'm setting this up for someone else",
      },
      step6: {
        title: "Do you already have a Leonix listing?",
        skipLabel: "Skip for now",
        selectLabel: "Select a listing",
        sourceLabel: "Listing type",
        idLabel: "Listing ID or slug",
        verifying: "Verifying ownership…",
        verifiedOk: "Listing verified successfully.",
        verifiedPending: "We couldn't verify this listing yet — it will stay pending review.",
        unsupportedSource: "That listing type can't be linked yet.",
      },
      step7: {
        title: "Review and create",
        sectionBasics: "Basics",
        sectionTypeStage: "Type and stage",
        sectionContact: "Contact",
        sectionServiceArea: "Location",
        sectionOwnership: "Confirmation",
        sectionListing: "Linked listing",
        edit: "Edit",
        confirmedYes: "Confirmed",
        noListing: "None",
        submit: "Create Business Identity",
        submitting: "Creating…",
        duplicateAcknowledge: "I understand and want to continue anyway",
      },
      errors: { generic: "Something went wrong. Please try again.", validation: "Please check the highlighted fields.", network: "We couldn't reach the server. Please try again." },
    },
    duplicate: {
      exactTitle: "This business may already exist",
      probableTitle: "We found similar information",
      possibleTitle: "We found related information",
      exactBody: "A business with very similar information is already registered on Leonix.",
      probableBody: "A business with similar details is already registered on Leonix.",
      possibleBody: "A business with a similar name is already registered on Leonix.",
      ownBusinessBody: "You already have access to this business.",
      continueAnyway: "Continue anyway",
      openExisting: "Open my existing business",
      requestReview: "Request manual review",
      goBack: "Go back and correct",
    },
    completed: {
      sectionIdentity: "Business identity",
      sectionContact: "Contact",
      sectionServiceArea: "Service area",
      sectionListing: "Connected listing",
      sectionNext: "What comes next",
      legalNameLabel: "Legal name",
      typeLabel: "Business type",
      stageLabel: "Stage",
      languageLabel: "Primary language",
      createdLabel: "Identity created on",
      onboardingComplete: "Setup complete",
      noListing: "No listing connected yet",
      listingPending: "Pending verification",
      listingVerified: "Verified",
      nextItems: [
        { title: "Living Business Book", body: "A living record of your business over time." },
        { title: "Business Health Map", body: "An honest view of how your business is doing." },
        { title: "Next Right Move", body: "Prioritized recommendations, when ready." },
        { title: "Learning Center", body: "Practical skills to grow your business." },
      ],
      nextBadge: "Coming soon",
      editingComingSoon: "Editing is coming next.",
    },
    common: { loading: "Loading…", error: "Something went wrong.", retry: "Retry", cancel: "Cancel" },
  };
}

export type BusinessIdentityCopy = ReturnType<typeof businessIdentityCopy>;
