export type Lang = "es" | "en";

/**
 * Feature-local ES/EN copy for the Business Identity experience (Package BCO-3, expanded in Gate
 * BCO-3R-B for the 9-step global Identity flow). Follows the repository's existing convention
 * (dashboardShellCopy-style function returning a per-lang object literal), not a new i18n
 * framework. Spanish-first, plain, encouraging — no corporate or manipulative language.
 *
 * Controlled-option labels (broad business types, stages, operating models, sales relationships/
 * channels, contact labels, digital-profile platforms, authorization roles, countries, business
 * languages) are NOT duplicated here — they live in `constants.ts` / `countries.ts` /
 * `languages.ts` as the single source of truth and are rendered directly from there. This file
 * only holds step/field copy: titles, labels, help/"why we ask" text, button labels, and states.
 */
export function businessIdentityCopy(lang: Lang) {
  if (lang === "es") {
    return {
      preview: {
        heroEyebrow: "Leonix Business Concierge",
        heroTitle: "Construyendo mejores negocios. Creando mejores vidas.",
        heroLead:
          "Business Concierge te ayudará a organizar la identidad de tu negocio en Leonix y a entender con claridad qué hacer después — sin presión de venta y sin promesas vacías.",
        helpTitle: "En qué te va a ayudar",
        helpItems: [
          "Aclarar la identidad de tu negocio: quién eres, qué ofreces y dónde.",
          "Organizar tu información verificada en un solo lugar.",
          "Identificar los próximos pasos importantes, uno a la vez.",
          "Enseñarte habilidades prácticas, no crear dependencia.",
          "Preparar apoyo de marketing para cuando estés listo.",
          "Medir tu progreso con honestidad, sin inventar cifras.",
        ],
        promiseTitle: "Nuestra promesa",
        promiseItems: [
          "Proteger antes que vender.",
          "Enseñar antes que ofrecer más.",
          "La intervención más pequeña que realmente ayude.",
          "Nunca inventamos evidencia ni resultados.",
          "Tú siempre tienes el control final.",
        ],
        journeyTitle: "El camino, paso a paso",
        journeySteps: ["Entender", "Organizar", "Priorizar", "Actuar", "Aprender", "Mejorar"],
        eligibilityTitle: "Cómo desbloquear la configuración",
        eligibilityLead:
          "Los anunciantes Negocio verificados en Leonix pueden desbloquear la configuración completa de Business Identity. Si ya anuncias como negocio, es posible que ya tengas acceso.",
        eligibilityCta: "Ver opciones para anunciar como negocio",
        ideaTitle: "¿Tienes una idea de negocio?",
        ideaLead:
          "Estamos construyendo herramientas para quienes todavía están en la etapa de idea. Todavía no existen — te avisaremos cuando estén listas.",
        ideaBadge: "Próximamente",
      },
      access: {
        loading: "Cargando tu estado de acceso…",
        unavailableTitle: "Estamos preparando Business Concierge",
        unavailableBody: "Esta función todavía se está preparando para tu cuenta. Vuelve a intentarlo más tarde.",
        ineligibleTitle: "Todavía no encontramos evidencia de tu negocio",
        ineligibleBody:
          "No es un rechazo definitivo — simplemente todavía no podemos confirmar automáticamente que administras un negocio en Leonix.",
        ambiguousTitle: "Necesitamos verificar el acceso a tu negocio",
        ambiguousBody:
          "Encontramos información relacionada con un negocio, pero no pudimos confirmarla automáticamente. Nuestro equipo puede revisarlo manualmente.",
        ambiguousCta: "Solicitar revisión manual",
        eligibleTitle: "Puedes comenzar la configuración de tu negocio",
        eligibleBody: "Toma unos 8-12 minutos. Tu progreso se guarda automáticamente en cada paso.",
        eligibleCta: "Comenzar configuración",
        signInRequired: "Inicia sesión para continuar.",
      },
      drafts: {
        resumeTitle: "Continúa donde te quedaste",
        multipleTitle: "Tienes varios negocios en progreso",
        step: "Paso",
        of: "de",
        lastUpdated: "Última actualización",
        resume: "Continuar",
        delete: "Eliminar",
        deleteConfirmTitle: "¿Eliminar este borrador?",
        deleteConfirmBody: "Esta acción no se puede deshacer.",
        deleteConfirmYes: "Sí, eliminar",
        deleteConfirmNo: "Cancelar",
        startAnother: "Comenzar otro negocio",
        untitled: "Negocio sin nombre",
        expiresNote: "Los borradores sin actividad se eliminan automáticamente después de un tiempo.",
        migratedNoticeTitle: "Actualizamos tu borrador",
        migratedNoticeBody:
          "Agregamos nuevos pasos a la configuración desde tu última visita. Revisa el paso 3 (categoría y etapa) para confirmar que todo esté correcto — nada de tu información anterior se perdió.",
      },
      wizard: {
        stepLabels: [
          "Idioma",
          "Identidad del negocio",
          "Categoría y etapa",
          "Modelo de operación",
          "Ubicación",
          "Contacto y presencia digital",
          "Confirmación",
          "Anuncios existentes",
          "Revisión",
        ],
        back: "Atrás",
        next: "Siguiente",
        /** Gate BCO-3R-B.6 — short visible caption distinguishing this from the global site language control. */
        formLanguageLabel: "Formulario",
        saveState: { saving: "Guardando…", saved: "Guardado", failed: "No se pudo guardar — reintentar" },
        why: "Por qué lo preguntamos",
        requiredLabel: "Obligatorio",
        optionalLabel: "Opcional",
        requiredOptionalLegend: "Los campos obligatorios son necesarios para crear tu perfil. Los campos opcionales se pueden completar o actualizar después.",
        purpose: {
          title: "Vamos a crear el perfil principal de tu negocio en Leonix",
          body: "Esta información nos ayuda a mantener tus anuncios, contactos, ubicaciones y herramientas de negocio organizados en un solo lugar. También permitirá que las herramientas futuras de Leonix y la asistencia con inteligencia artificial te den apoyo más relevante según la información que tú hayas confirmado.\n\nTú decides qué información es pública. Podrás revisar y actualizar tus datos más adelante.\n\nCrear este perfil no publica un anuncio nuevo, no genera un cobro y no cambia la propiedad legal de tu negocio.",
          benefits: [
            "Un perfil de negocio confiable",
            "Menos preguntas repetidas",
            "Información de tu negocio consistente",
            "Anuncios autorizados conectados",
            "Mejores herramientas y orientación en el futuro",
            "Tú decides qué información es pública",
          ],
        },
        privacyShort: {
          title: "Tu información es para servirte mejor",
          body: "No vendemos tu información privada. No compartimos tu información privada con anunciantes. Solo mostramos públicamente la información que tú decides hacer pública.",
        },
        privacyFull: {
          title: "Tu información es para servirte mejor",
          body: "Leonix usa esta información para organizar tu perfil, mantener tus datos consistentes, conectar las herramientas que autorizas y ofrecerte apoyo más relevante.\n\nNo vendemos tu información privada.\nNo compartimos tu información privada con anunciantes.\nSolo mostramos públicamente la información que tú decides hacer pública.\n\nTrabajamos para proteger tus datos y limitar el acceso a las personas y sistemas autorizados. Algunos proveedores tecnológicos pueden procesar datos únicamente para operar el servicio, y podemos divulgar información cuando la ley lo requiera.",
        },
        step1: {
          title: "¿En qué idioma quieres configurar tu negocio?",
          lead: "Puedes cambiar de idioma en cualquier momento — no afecta el idioma real de tu negocio, solo cómo ves esta configuración.",
          esOption: "Español",
          enOption: "English",
          continueHint: "Selecciona un idioma para continuar.",
        },
        step2: {
          title: "Identidad del negocio",
          displayNameLabel: "Nombre del negocio (Obligatorio)",
          displayNameHint: "El nombre que usarás en Leonix.",
          legalNameLabel: "Nombre legal (opcional)",
          publicNameLabel: "Nombre público, si es diferente (opcional)",
          legalVsPublicHelp:
            "El nombre legal es el registrado oficialmente ante autoridades. El nombre público es como te conocen tus clientes, si es distinto del nombre que usas en Leonix.",
          businessPrimaryLanguageLabel: "Idioma principal del negocio",
          businessPrimaryLanguageHint: "El idioma en el que realmente operas — puede ser distinto del idioma de esta configuración.",
          additionalLanguagesLabel: "Otros idiomas que atiendes (opcional)",
          addLanguage: "Agregar idioma",
          removeLanguage: "Quitar",
          yearStartedLabel: "Año en que comenzó el negocio (opcional)",
          yearStartedHint: "Ejemplo: 2019.",
          whyWeAskText: "Usamos esto para mantener la información de tu negocio consistente en todo Leonix.",
          noPermanentRecordNote: "Nada se guarda de forma permanente hasta que completes y confirmes toda la configuración.",
        },
        step3: {
          title: "Categoría, tipo específico y etapa",
          broadTypeLabel: "Categoría del negocio (Obligatorio)",
          specificTypeLabel: "Tipo específico",
          specificTypeHint: "Busca o selecciona el que mejor describa tu negocio.",
          specificTypeOtherLabel: "Otro (describe tu tipo de negocio)",
          specificTypeOtherPlaceholder: "Ejemplo: Reparación de bicicletas",
          stageLabel: "Etapa del negocio (Obligatorio)",
          stageDescriptions: {
            planning_prelaunch: "Todavía estás planeando — aún no abres.",
            newly_opened: "Abriste hace poco tiempo.",
            operating: "Ya operas de forma regular.",
            growing: "Operas y estás creciendo activamente.",
            established_mature: "Llevas años operando de forma estable.",
            paused_restructuring: "Temporalmente en pausa o reorganizando el negocio.",
          } as Record<string, string>,
        },
        step4: {
          title: "Modelo de operación",
          operatingModelLabel: "¿Cómo opera tu negocio? (Obligatorio)",
          operatingModelHint: "Selecciona todas las que apliquen.",
          multipleLocationsFactLabel: "Tengo más de una ubicación física",
          salesRelationshipLabel: "¿A quién le vendes?",
          salesChannelLabel: "¿Por dónde vendes o atiendes clientes?",
          whyWeAskText: "Esto ayuda a Leonix a no recomendarte herramientas que no encajan con la forma real en que operas.",
        },
        step5: {
          title: "Ubicación y zona de servicio",
          countryLabel: "País (Obligatorio)",
          countryOtherNameLabel: "Nombre del país o territorio (si no aparece en la lista)",
          physicalTitle: "Dirección física",
          streetNumberLabel: "Número de calle",
          streetNameLabel: "Nombre de la calle",
          unitLabel: "Unidad / suite / piso (opcional)",
          neighborhoodLabel: "Colonia / barrio (opcional)",
          cityLabel: "Ciudad",
          stateProvinceLabel: "Estado / provincia / región",
          postalCodeLabel: "Código postal",
          addressVisibilityLabel: "¿Quién puede ver tu dirección exacta?",
          addressVisibilityOptions: {
            public_exact: "Pública — dirección exacta visible",
            city_only: "Solo ciudad — la dirección exacta queda privada",
            private: "Privada — nunca se muestra públicamente",
          } as Record<string, string>,
          mobileTitle: "Cobertura móvil",
          interactionModeLabel: "¿Cómo interactúas con tus clientes?",
          interactionModeOptions: { business_travels: "Yo voy con el cliente", customer_visits: "El cliente viene a mí", both: "Ambos" } as Record<string, string>,
          coverageTypeLabel: "Tipo de cobertura",
          coverageTypeOptions: {
            local_city: "Solo mi ciudad",
            custom_radius: "Radio personalizado",
            selected_cities: "Ciudades específicas",
            selected_regions: "Regiones específicas",
            nationwide: "Todo el país",
            international: "Internacional",
          } as Record<string, string>,
          radiusLabel: "Radio de servicio",
          radiusUnitOptions: { miles: "Millas", kilometers: "Kilómetros" } as Record<string, string>,
          citiesServedLabel: "Ciudades atendidas",
          regionsServedLabel: "Regiones atendidas",
          postalCodesServedLabel: "Códigos postales atendidos",
          addChipHint: "Escribe y presiona Enter para agregar",
          removeChip: "Quitar",
          customCoverageLabel: "Descripción de tu cobertura (opcional)",
          onlineTitle: "En línea / remoto",
          countriesServedLabel: "Países que atiendes",
          languagesServedLabel: "Idiomas en los que atiendes",
          timezoneLabel: "Zona horaria",
          regionalTitle: "Zona de servicio regional",
          hybridNote: "Como seleccionaste varios modelos de operación, completa cada sección aplicable.",
          multipleLocationsTitle: "Múltiples ubicaciones",
          multipleLocationsCheckbox: "Tengo más de una ubicación",
          multipleLocationsCountLabel: "Número aproximado de ubicaciones (opcional)",
          multipleLocationsNote: "Por ahora registramos tu ubicación principal. La administración completa de varias ubicaciones llegará en una fase futura.",
          coverage: {
            title: "¿Hasta dónde atiende tu negocio?",
            localSectionTitle: "Área local",
            baseCityLabel: "Ciudad base",
            baseStateProvinceLabel: "Estado / provincia / región",
            basePostalCodeLabel: "Código postal",
            inheritedLocationTemplate: "Usando tu ubicación principal: {value}",
            useInheritedLocation: "Usar esta ubicación",
            clearBaseLocation: "Borrar",
            radiusPresetLabel: "Radio de servicio",
            radiusCustomLabel: "Personalizado",
            radiusCustomValueLabel: "Número",
            radiusUnitLabel: "Unidad",
            nearbyNeighborhoodsLabel: "Colonias o zonas cercanas (opcional)",
            localNoteLabel: "Nota corta (opcional)",
            multiCitySectionTitle: "Varias ciudades",
            citiesStateProvinceLabel: "Estado / provincia (opcional, para acotar la búsqueda)",
            citiesServedLabel: "Ciudades atendidas",
            oneStateSectionTitle: "Un estado o provincia",
            stateProvinceLabel: "Estado / provincia / región",
            stateProvinceManualLabel: "Escribe el estado o provincia",
            excludedCitiesLabel: "Ciudades o zonas excluidas (opcional)",
            multiStateSectionTitle: "Varios estados o provincias",
            statesProvincesServedLabel: "Estados o provincias atendidos",
            selectAllStatesTemplate: "Seleccionar los {n} estados/provincias de {country}",
            excludedStatesLabel: "Estados o provincias excluidos (opcional)",
            nationwideSectionTitle: "Todo el país",
            nationwideConfirmLabel: "Atiendes clientes en todo este país.",
            excludedRegionsLabel: "Estados, provincias o regiones excluidos (opcional)",
            multiCountrySectionTitle: "Varios países",
            countriesServedLabel: "Países atendidos",
            addCountryPlaceholder: "Busca un país para agregar",
            regionShortcutsLegend: "Atajos por región",
            selectAllInRegionTemplate: "Seleccionar los {n} países de esta región",
            confirmLabel: "Confirmar selección",
            cancelLabel: "Cancelar",
            chooseSpecificLabel: "O elige países específicos",
            searchWithinRegionPlaceholder: "Buscar en esta región",
            countSelectedInRegionTemplate: "{n} países seleccionados en esta región",
            countSelectedTemplate: "{n} países seleccionados",
            excludedCountriesLabel: "Países excluidos (opcional)",
            worldwideSectionTitle: "Todo el mundo / en línea",
            worldwideConfirmLabel: "Confirmo que atiendo clientes en todo el mundo.",
            primaryTimeZoneLabel: "Zona horaria principal",
            additionalTimeZonesLabel: "Zonas horarias adicionales (opcional)",
            worldwideLanguagesLabel: "Idiomas en los que atiendes",
            worldwideExcludedCountriesLabel: "Países excluidos (opcional)",
            deliveryModelLabel: "¿Cómo entregas tu servicio?",
            deliveryModelOtherNoteLabel: "Describe brevemente",
            noResultsLabel: "Sin resultados",
            errorSummaryTitle: "Revisa estos campos de cobertura",
            summary: {
              localWithRadiusTemplate: "Área local: hasta {radius} {unit} desde {place}",
              localTemplate: "Área local: {place}",
              multiCityWithStateTemplate: "Atiende {n} ciudades en {state}",
              multiCityTemplate: "Atiende {n} ciudades",
              oneStateTemplate: "Atiende todo {state}",
              multiStateTemplate: "Atiende {n} estados o provincias",
              multiStateWithExclusionsTemplate: "Atiende {n} estados o provincias, excepto {exclusions}",
              nationwideTemplate: "Atiende todo {country}",
              nationwideWithExclusionsTemplate: "Atiende todo {country}, excepto {exclusions}",
              multiCountryTemplate: "Atiende {n} países",
              multiCountryRegionTemplate: "Atiende {n} países de {region}",
              worldwideTemplate: "Disponible en todo el mundo",
              worldwideWithLanguagesTemplate: "Disponible en todo el mundo, en {languages}",
              none: "—",
              milesUnit: "millas",
              kilometersUnit: "kilómetros",
              listJoiner: "y",
            },
          },
        },
        step6: {
          title: "Contacto y presencia digital",
          contactsSectionTitle: "Contactos",
          contactTypeLabel: "Tipo",
          contactValueLabel: "Valor",
          contactLabelLabel: "Etiqueta",
          contactVisibilityLabel: "Visibilidad",
          contactVisibilityOptions: { public: "Pública", private: "Privada" } as Record<string, string>,
          preferredChannelLabel: "¿Es tu canal preferido?",
          preferredChannelKindLabel: "Canal preferido",
          primaryLabel: "Contacto principal",
          addContact: "Agregar otro contacto",
          removeContact: "Eliminar contacto",
          atLeastOne: "Agrega al menos un contacto para continuar.",
          digitalProfilesSectionTitle: "Perfiles digitales",
          digitalProfilesHint: "Marca las plataformas donde ya tienes presencia y agrega el enlace o usuario.",
          handleOrUrlLabel: "Enlace o usuario",
          addProfile: "Agregar otro perfil",
          removeProfile: "Eliminar perfil",
          whyWeAskText: "Usamos estos enlaces para entender tu presencia actual y evitar pedirte la misma información dos veces. Seleccionar una plataforma no nos da acceso a tu cuenta privada.",
          capabilitiesLabel: "¿Qué puede recibir este número?",
          preferredMethodSectionTitle: "Método de respuesta preferido",
          preferredMethodHint: "Elige una sola forma en la que Leonix y tus clientes deben contactarte primero.",
          preferredMethodNoneOption: "Sin preferencia",
          preferredMethodIncompatible: "Agrega un contacto compatible con este método antes de seleccionarlo.",
          customLinksSectionTitle: "Otros enlaces de tu negocio",
          customLinksHint: "Agrega enlaces como reservaciones, menú, tienda en línea o portafolio.",
          customLinkTypeLabel: "Tipo de enlace",
          customLabelLabel: "Describe este enlace",
          customLabelPlaceholder: "Ejemplo: Catálogo de temporada",
          customLinkUrlLabel: "Enlace",
          addCustomLink: "Agregar otro enlace de negocio",
          removeCustomLink: "Eliminar enlace",
        },
        step7: {
          title: "Confirmación",
          roleLabel: "¿Eres dueño(a) del negocio o tienes permiso para administrarlo?",
          confirmLabel: "Confirmo que tengo permiso para crear y administrar este perfil, y que la información es correcta según mi conocimiento.",
          representativeRelationshipLabel: "¿Cuál es tu relación con el negocio?",
          representativeRelationshipPlaceholder: "Ejemplo: Gerente, socio, familiar autorizado",
          representativeContactEmailLabel: "Correo de contacto del dueño (opcional)",
          representativeNoteLabel: "Nota adicional (opcional)",
          manualReviewNote: "Las cuentas configuradas por un representante autorizado pasan por una revisión manual adicional.",
          noOwnershipTransferNote: "Esto no cambia la propiedad legal del negocio. Solo confirma que tienes permiso para administrar su información en Leonix.",
          noFakeInviteNote: "Esto no envía una invitación ni notifica al dueño automáticamente.",
        },
        step8: {
          title: "¿Ya tienes anuncios en Leonix?",
          lead: "Encontramos estos anuncios de Leonix conectados a tu cuenta.",
          loading: "Buscando tus anuncios…",
          none: "No encontramos anuncios conectados a tu cuenta.",
          error: "No pudimos buscar tus anuncios en este momento.",
          retry: "Reintentar",
          confirmCandidate: "Este anuncio es mío",
          leonixAdIdLabel: "ID de anuncio Leonix",
          statusLabel: "Estado",
          categoryLabel: "Categoría",
          noneOfTheseLabel: "Ninguno de estos es mío / no tengo anuncios",
          fallbackToggle: "¿No encuentras tu anuncio? Ingresa el ID manualmente",
          fallbackSourceLabel: "Tipo de anuncio",
          fallbackIdLabel: "ID o slug del anuncio",
          fallbackNote: "Esto es un respaldo — primero intentamos encontrar tus anuncios automáticamente.",
        },
        step9: {
          title: "Revisión y creación",
          sectionSetup: "Idioma de configuración",
          sectionIdentity: "Identidad del negocio",
          sectionCategoryStage: "Categoría y etapa",
          sectionOperatingModel: "Modelo de operación",
          sectionRelationships: "Relación con clientes",
          sectionChannels: "Canales de venta",
          sectionBusinessCountry: "País del negocio",
          sectionLocation: "Dirección física",
          sectionCoverage: "Zona de servicio",
          sectionContacts: "Contactos",
          sectionPreferredChannel: "Método de respuesta preferido",
          sectionDigitalProfiles: "Perfiles digitales",
          sectionCustomLinks: "Otros enlaces",
          sectionAuthorization: "Autorización",
          sectionListings: "Anuncios seleccionados",
          edit: "Editar",
          confirmedYes: "Confirmado",
          noneSelected: "Ninguno",
          listingConfirmed: "Confirmado",
          listingSkipped: "Omitido",
          listingNoneFound: "No se encontró ningún anuncio",
          submit: "Crear perfil de mi negocio",
          submitting: "Creando…",
          duplicateAcknowledge: "Entiendo y quiero continuar de todos modos",
          reverifying: "Verificando información…",
          finalExplanation: {
            title: "Al crear este perfil",
            items: [
              "Guardaremos esta información como el registro principal de tu negocio.",
              "Conectaremos únicamente los anuncios que confirmaste.",
              "Respetaremos las opciones de información pública y privada.",
              "Podrás actualizar tu información después.",
              "Las herramientas futuras de Leonix podrán usar información autorizada para darte apoyo más relevante.",
              "No publicaremos un anuncio nuevo.",
              "No te cobraremos por crear este perfil.",
              "No venderemos tu información privada ni la compartiremos con anunciantes.",
            ],
          },
        },
        errors: {
          generic: "Ocurrió un error. Intenta de nuevo.",
          validation: "Revisa los campos marcados.",
          network: "No pudimos conectar con el servidor. Intenta de nuevo.",
        },
      },
      duplicate: {
        exactTitle: "Es posible que este negocio ya exista",
        probableTitle: "Encontramos información similar",
        possibleTitle: "Encontramos información parecida",
        exactBody: "Un negocio con información muy similar ya está registrado en Leonix.",
        probableBody: "Un negocio con datos parecidos ya está registrado en Leonix.",
        possibleBody: "Un negocio con un nombre parecido ya está registrado en Leonix.",
        ownBusinessBody: "Ya tienes acceso a este negocio.",
        continueAnyway: "Continuar de todos modos",
        openExisting: "Abrir mi negocio existente",
        requestReview: "Solicitar revisión manual",
        goBack: "Volver y corregir",
      },
      completed: {
        sectionIdentity: "Identidad del negocio",
        sectionOperatingModel: "Modelo de operación",
        sectionBusinessCountry: "País del negocio",
        sectionLocation: "Dirección física",
        sectionCoverage: "Zona de servicio",
        sectionContact: "Contacto",
        sectionDigitalProfiles: "Perfiles digitales",
        sectionAuthorization: "Autorización",
        sectionListing: "Anuncios conectados",
        sectionNext: "Qué sigue",
        sectionDataUse: "Cómo Leonix usa esta información",
        legalNameLabel: "Nombre legal",
        legalNameOwnerOnlyNote: "Solo visible para el dueño autorizado.",
        typeLabel: "Tipo de negocio",
        stageLabel: "Etapa",
        languageLabel: "Idioma principal",
        businessLanguagesLabel: "Idiomas del negocio",
        yearStartedLabel: "Año de inicio",
        createdLabel: "Identidad creada el",
        onboardingComplete: "Configuración completa",
        noListing: "Ningún anuncio conectado todavía",
        listingPending: "Pendiente de verificación",
        listingVerified: "Verificado",
        dataUseItems: [
          "Un solo perfil de negocio confiable.",
          "Evita que te pidamos la misma información varias veces.",
          "Mantiene tus anuncios y materiales de negocio consistentes en Leonix.",
          "Conecta únicamente los anuncios que tú autorizaste.",
          "Prepara futuras Herramientas de Negocio, apoyo con inteligencia artificial y materiales creativos.",
          "Personaliza futura educación, orientación y recomendaciones para tu negocio.",
          "Protege tus campos privados — tú decides qué se hace público.",
          "Te permite revisar y corregir tu información en cualquier momento.",
          "Nunca vendemos tu información privada.",
          "Nunca compartimos tu información privada con anunciantes.",
          "Las funciones futuras con inteligencia artificial solo usan información autorizada y relevante para cada tarea específica.",
          "Las sugerencias de inteligencia artificial no se tratan automáticamente como hechos confirmados.",
          "Las acciones con consecuencias reales siempre requieren tu aprobación o la de un humano autorizado.",
        ],
        nextItems: [
          { title: "Libro de negocio", body: "Un registro vivo de tu negocio a través del tiempo." },
          { title: "Mapa de salud del negocio", body: "Una vista honesta de cómo va tu negocio." },
          { title: "Próximo paso correcto", body: "Recomendaciones priorizadas, cuando estén listas." },
          { title: "Centro de aprendizaje", body: "Habilidades prácticas para hacer crecer tu negocio." },
        ],
        nextBadge: "Próximamente",
        editingComingSoon: "La edición llegará próximamente.",
        helpDiscoveryTitle: "Ayuda a Leonix a entender tu negocio",
        helpDiscoveryBody: "La siguiente fase te permitirá contarnos más sobre tu negocio para recibir orientación más precisa. Todavía no está disponible.",
        helpDiscoveryCta: "Próxima fase — todavía no disponible",
        helpDiscoveryBadge: "Próxima fase",
      },
      common: {
        loading: "Cargando…",
        error: "Ocurrió un error.",
        retry: "Reintentar",
        cancel: "Cancelar",
      },
    };
  }

  return {
    preview: {
      heroEyebrow: "Leonix Business Concierge",
      heroTitle: "Building Better Businesses. Creating Better Lives.",
      heroLead:
        "Business Concierge will help you organize your business identity on Leonix and clearly understand what to do next — no sales pressure, no empty promises.",
      helpTitle: "What it will help with",
      helpItems: [
        "Clarify your business identity: who you are, what you offer, and where.",
        "Organize your verified information in one place.",
        "Identify important next steps, one at a time.",
        "Teach you practical skills, not create dependency.",
        "Prepare marketing support for when you're ready.",
        "Measure your progress honestly, with no invented numbers.",
      ],
      promiseTitle: "Our promise",
      promiseItems: [
        "Protect before profit.",
        "Teach before upselling.",
        "The smallest intervention that actually helps.",
        "We never fabricate evidence or results.",
        "You always keep final control.",
      ],
      journeyTitle: "The journey, step by step",
      journeySteps: ["Understand", "Organize", "Prioritize", "Act", "Learn", "Improve"],
      eligibilityTitle: "How to unlock full setup",
      eligibilityLead:
        "Verified Negocio advertisers on Leonix can unlock the complete Business Identity setup. If you already advertise as a business, you may already have access.",
      eligibilityCta: "See options to advertise as a business",
      ideaTitle: "Have a business idea?",
      ideaLead: "We're building tools for entrepreneurs still at the idea stage. They don't exist yet — we'll let you know when they're ready.",
      ideaBadge: "Coming soon",
    },
    access: {
      loading: "Loading your access status…",
      unavailableTitle: "We're preparing Business Concierge",
      unavailableBody: "This feature is still being prepared for your account. Please check back later.",
      ineligibleTitle: "We haven't found evidence of your business yet",
      ineligibleBody: "This isn't a final denial — we just can't automatically confirm you manage a business on Leonix yet.",
      ambiguousTitle: "We need to verify your business access",
      ambiguousBody: "We found business-related information but couldn't automatically confirm it. Our team can review it manually.",
      ambiguousCta: "Request manual review",
      eligibleTitle: "You can start setting up your business",
      eligibleBody: "Takes about 8-12 minutes. Your progress saves automatically at every step.",
      eligibleCta: "Start setup",
      signInRequired: "Sign in to continue.",
    },
    drafts: {
      resumeTitle: "Continue where you left off",
      multipleTitle: "You have multiple businesses in progress",
      step: "Step",
      of: "of",
      lastUpdated: "Last updated",
      resume: "Resume",
      delete: "Delete",
      deleteConfirmTitle: "Delete this draft?",
      deleteConfirmBody: "This cannot be undone.",
      deleteConfirmYes: "Yes, delete",
      deleteConfirmNo: "Cancel",
      startAnother: "Start another business",
      untitled: "Untitled business",
      expiresNote: "Inactive drafts are automatically removed after a while.",
      migratedNoticeTitle: "We updated your draft",
      migratedNoticeBody:
        "We added new setup steps since your last visit. Please review step 3 (category and stage) to confirm everything looks right — none of your earlier information was lost.",
    },
    wizard: {
      stepLabels: [
        "Language",
        "Business identity",
        "Category and stage",
        "Operating model",
        "Location",
        "Contact and digital presence",
        "Confirmation",
        "Existing listings",
        "Review",
      ],
      back: "Back",
      next: "Next",
      /** Gate BCO-3R-B.6 — short visible caption distinguishing this from the global site language control. */
      formLanguageLabel: "Form",
      saveState: { saving: "Saving…", saved: "Saved", failed: "Couldn't save — retry" },
      why: "Why we ask",
      requiredLabel: "Required",
      optionalLabel: "Optional",
      requiredOptionalLegend: "Required fields are needed to create your profile. Optional fields may be completed or updated later.",
      purpose: {
        title: "We'll create your business's primary profile in Leonix",
        body: "This information helps keep your listings, contacts, locations, and business tools organized in one place. It may also help future Leonix tools and AI-assisted features provide more relevant support using information you have confirmed.\n\nYou control what information is public. You can review and update your information later.\n\nCreating this profile does not publish a new advertisement, create a charge, or change legal ownership of your business.",
        benefits: [
          "One trusted business profile",
          "Fewer repeated questions",
          "Consistent business information",
          "Connected authorized listings",
          "Better future tools and guidance",
          "You decide what information is public",
        ],
      },
      privacyShort: {
        title: "Your information is used to serve you better",
        body: "We do not sell your private information. We do not share your private information with advertisers. We only display information publicly when you choose to make it public.",
      },
      privacyFull: {
        title: "Your information is used to serve you better",
        body: "Leonix uses this information to organize your profile, keep your business data consistent, connect the tools you authorize, and provide more relevant support.\n\nWe do not sell your private information.\nWe do not share your private information with advertisers.\nWe only display information publicly when you choose to make it public.\n\nWe work to protect your data and limit access to authorized people and systems. Certain technology providers may process data only to operate the service, and information may be disclosed when legally required.",
      },
      step1: {
        title: "What language do you want to use for setup?",
        lead: "You can change this at any time — it doesn't affect your business's real-world language, only how you see this setup.",
        esOption: "Español",
        enOption: "English",
        continueHint: "Select a language to continue.",
      },
      step2: {
        title: "Business identity",
        displayNameLabel: "Business name (Required)",
        displayNameHint: "The name you'll use on Leonix.",
        legalNameLabel: "Legal name (optional)",
        publicNameLabel: "Public name, if different (optional)",
        legalVsPublicHelp:
          "The legal name is the one officially registered with authorities. The public name is how customers know you, if different from the name you use on Leonix.",
        businessPrimaryLanguageLabel: "Business primary language",
        businessPrimaryLanguageHint: "The language you actually operate in — may differ from this setup's language.",
        additionalLanguagesLabel: "Other languages you serve (optional)",
        addLanguage: "Add language",
        removeLanguage: "Remove",
        yearStartedLabel: "Year the business started (optional)",
        yearStartedHint: "Example: 2019.",
        whyWeAskText: "We use this to keep your business information consistent throughout Leonix.",
        noPermanentRecordNote: "Nothing is permanently saved until you complete and confirm the entire setup.",
      },
      step3: {
        title: "Category, specific type, and stage",
        broadTypeLabel: "Business category (Required)",
        specificTypeLabel: "Specific type",
        specificTypeHint: "Search or select the one that best describes your business.",
        specificTypeOtherLabel: "Other (describe your business type)",
        specificTypeOtherPlaceholder: "Example: Bicycle repair",
        stageLabel: "Business stage (Required)",
        stageDescriptions: {
          planning_prelaunch: "You're still planning — not open yet.",
          newly_opened: "You opened recently.",
          operating: "You're operating on a regular basis.",
          growing: "You're operating and actively growing.",
          established_mature: "You've been operating steadily for years.",
          paused_restructuring: "Temporarily paused or reorganizing the business.",
        } as Record<string, string>,
      },
      step4: {
        title: "Operating model",
        operatingModelLabel: "How does your business operate? (Required)",
        operatingModelHint: "Select all that apply.",
        multipleLocationsFactLabel: "I have more than one physical location",
        salesRelationshipLabel: "Who do you sell to?",
        salesChannelLabel: "Where do you sell or serve customers?",
        whyWeAskText: "This helps Leonix avoid recommending tools that don't fit how your business actually works.",
      },
      step5: {
        title: "Location and service coverage",
        countryLabel: "Country (Required)",
        countryOtherNameLabel: "Country or territory name (if not in the list)",
        physicalTitle: "Physical address",
        streetNumberLabel: "Street number",
        streetNameLabel: "Street name",
        unitLabel: "Unit / suite / floor (optional)",
        neighborhoodLabel: "Neighborhood / district (optional)",
        cityLabel: "City",
        stateProvinceLabel: "State / province / region",
        postalCodeLabel: "Postal code",
        addressVisibilityLabel: "Who can see your exact address?",
        addressVisibilityOptions: {
          public_exact: "Public — exact address visible",
          city_only: "City only — exact address stays private",
          private: "Private — never shown publicly",
        } as Record<string, string>,
        mobileTitle: "Mobile coverage",
        interactionModeLabel: "How do you interact with customers?",
        interactionModeOptions: { business_travels: "I travel to the customer", customer_visits: "The customer comes to me", both: "Both" } as Record<string, string>,
        coverageTypeLabel: "Coverage type",
        coverageTypeOptions: {
          local_city: "Just my city",
          custom_radius: "Custom radius",
          selected_cities: "Specific cities",
          selected_regions: "Specific regions",
          nationwide: "Nationwide",
          international: "International",
        } as Record<string, string>,
        radiusLabel: "Service radius",
        radiusUnitOptions: { miles: "Miles", kilometers: "Kilometers" } as Record<string, string>,
        citiesServedLabel: "Cities served",
        regionsServedLabel: "Regions served",
        postalCodesServedLabel: "Postal codes served",
        addChipHint: "Type and press Enter to add",
        removeChip: "Remove",
        customCoverageLabel: "Describe your coverage (optional)",
        onlineTitle: "Online / remote",
        countriesServedLabel: "Countries you serve",
        languagesServedLabel: "Languages you serve in",
        timezoneLabel: "Time zone",
        regionalTitle: "Regional service area",
        hybridNote: "Since you selected multiple operating models, fill in every section that applies.",
        multipleLocationsTitle: "Multiple locations",
        multipleLocationsCheckbox: "I have more than one location",
        multipleLocationsCountLabel: "Approximate number of locations (optional)",
        multipleLocationsNote: "For now we record your primary location. Full multi-location management is coming in a future phase.",
        coverage: {
          title: "How far does your business serve?",
          localSectionTitle: "Local area",
          baseCityLabel: "Base city",
          baseStateProvinceLabel: "State / province / region",
          basePostalCodeLabel: "Postal code",
          inheritedLocationTemplate: "Using your primary location: {value}",
          useInheritedLocation: "Use this location",
          clearBaseLocation: "Clear",
          radiusPresetLabel: "Service radius",
          radiusCustomLabel: "Custom",
          radiusCustomValueLabel: "Number",
          radiusUnitLabel: "Unit",
          nearbyNeighborhoodsLabel: "Nearby neighborhoods (optional)",
          localNoteLabel: "Short note (optional)",
          multiCitySectionTitle: "Multiple cities",
          citiesStateProvinceLabel: "State / province (optional, narrows the search)",
          citiesServedLabel: "Cities served",
          oneStateSectionTitle: "One state or province",
          stateProvinceLabel: "State / province / region",
          stateProvinceManualLabel: "Type the state or province",
          excludedCitiesLabel: "Excluded cities or areas (optional)",
          multiStateSectionTitle: "Multiple states or provinces",
          statesProvincesServedLabel: "States or provinces served",
          selectAllStatesTemplate: "Select all {n} states/provinces in {country}",
          excludedStatesLabel: "Excluded states or provinces (optional)",
          nationwideSectionTitle: "Nationwide",
          nationwideConfirmLabel: "You serve customers throughout this country.",
          excludedRegionsLabel: "Excluded states, provinces, or regions (optional)",
          multiCountrySectionTitle: "Multiple countries",
          countriesServedLabel: "Countries served",
          addCountryPlaceholder: "Search a country to add",
          regionShortcutsLegend: "Region shortcuts",
          selectAllInRegionTemplate: "Select all {n} countries in this region",
          confirmLabel: "Confirm selection",
          cancelLabel: "Cancel",
          chooseSpecificLabel: "Or choose specific countries",
          searchWithinRegionPlaceholder: "Search within this region",
          countSelectedInRegionTemplate: "{n} countries selected in this region",
          countSelectedTemplate: "{n} countries selected",
          excludedCountriesLabel: "Excluded countries (optional)",
          worldwideSectionTitle: "Worldwide / online",
          worldwideConfirmLabel: "I confirm I serve customers worldwide.",
          primaryTimeZoneLabel: "Primary time zone",
          additionalTimeZonesLabel: "Additional time zones (optional)",
          worldwideLanguagesLabel: "Languages you serve in",
          worldwideExcludedCountriesLabel: "Excluded countries (optional)",
          deliveryModelLabel: "How do you deliver your service?",
          deliveryModelOtherNoteLabel: "Briefly describe",
          noResultsLabel: "No results",
          errorSummaryTitle: "Review these coverage fields",
          summary: {
            localWithRadiusTemplate: "Local area: within {radius} {unit} of {place}",
            localTemplate: "Local area: {place}",
            multiCityWithStateTemplate: "Serves {n} cities in {state}",
            multiCityTemplate: "Serves {n} cities",
            oneStateTemplate: "Serves all of {state}",
            multiStateTemplate: "Serves {n} states or provinces",
            multiStateWithExclusionsTemplate: "Serves {n} states or provinces, except {exclusions}",
            nationwideTemplate: "Serves all of {country}",
            nationwideWithExclusionsTemplate: "Serves all of {country}, except {exclusions}",
            multiCountryTemplate: "Serves {n} countries",
            multiCountryRegionTemplate: "Serves {n} {region} countries",
            worldwideTemplate: "Available worldwide",
            worldwideWithLanguagesTemplate: "Available worldwide, in {languages}",
            none: "—",
            milesUnit: "miles",
            kilometersUnit: "kilometers",
            listJoiner: "and",
          },
        },
      },
      step6: {
        title: "Contact and digital presence",
        contactsSectionTitle: "Contacts",
        contactTypeLabel: "Type",
        contactValueLabel: "Value",
        contactLabelLabel: "Label",
        contactVisibilityLabel: "Visibility",
        contactVisibilityOptions: { public: "Public", private: "Private" } as Record<string, string>,
        preferredChannelLabel: "Is this your preferred channel?",
        preferredChannelKindLabel: "Preferred channel",
        primaryLabel: "Primary contact",
        addContact: "Add another contact",
        removeContact: "Remove contact",
        atLeastOne: "Add at least one contact to continue.",
        digitalProfilesSectionTitle: "Digital profiles",
        digitalProfilesHint: "Check the platforms where you already have a presence and add the link or handle.",
        handleOrUrlLabel: "Link or handle",
        addProfile: "Add another profile",
        removeProfile: "Remove profile",
        whyWeAskText: "We use these links to understand your existing presence and avoid asking you to enter the same information twice. Selecting a platform does not give us access to your private account.",
        capabilitiesLabel: "What can this number receive?",
        preferredMethodSectionTitle: "Preferred response method",
        preferredMethodHint: "Choose the one way Leonix and your customers should reach you first.",
        preferredMethodNoneOption: "No preference",
        preferredMethodIncompatible: "Add a compatible contact before selecting this method.",
        customLinksSectionTitle: "Other business links",
        customLinksHint: "Add links like booking, menu, online store, or portfolio.",
        customLinkTypeLabel: "Link type",
        customLabelLabel: "Describe this link",
        customLabelPlaceholder: "Example: Seasonal catalog",
        customLinkUrlLabel: "Link",
        addCustomLink: "Add another business link",
        removeCustomLink: "Remove link",
      },
      step7: {
        title: "Confirmation",
        roleLabel: "Do you own this business or have permission to manage it?",
        confirmLabel: "I confirm that I have permission to create and manage this profile, and that the information is accurate to the best of my knowledge.",
        representativeRelationshipLabel: "What is your relationship to the business?",
        representativeRelationshipPlaceholder: "Example: Manager, partner, authorized family member",
        representativeContactEmailLabel: "Owner's contact email (optional)",
        representativeNoteLabel: "Additional note (optional)",
        manualReviewNote: "Accounts set up by an authorized representative go through an additional manual review.",
        noOwnershipTransferNote: "This does not change legal ownership of the business. It only confirms that you have permission to manage its information in Leonix.",
        noFakeInviteNote: "This does not send an invitation or automatically notify the owner.",
      },
      step8: {
        title: "Do you already have listings on Leonix?",
        lead: "We found these Leonix advertisements connected to your account.",
        loading: "Looking for your listings…",
        none: "We didn't find any listings connected to your account.",
        error: "We couldn't look up your listings right now.",
        retry: "Retry",
        confirmCandidate: "This listing is mine",
        leonixAdIdLabel: "Leonix Ad ID",
        statusLabel: "Status",
        categoryLabel: "Category",
        noneOfTheseLabel: "None of these are mine / I don't have listings",
        fallbackToggle: "Can't find your listing? Enter the ID manually",
        fallbackSourceLabel: "Listing type",
        fallbackIdLabel: "Listing ID or slug",
        fallbackNote: "This is a fallback — we first try to find your listings automatically.",
      },
      step9: {
        title: "Review and create",
        sectionSetup: "Setup language",
        sectionIdentity: "Business identity",
        sectionCategoryStage: "Category and stage",
        sectionOperatingModel: "Operating model",
        sectionRelationships: "Customer relationships",
        sectionChannels: "Sales channels",
        sectionBusinessCountry: "Business country",
        sectionLocation: "Physical address",
        sectionCoverage: "Service area",
        sectionContacts: "Contacts",
        sectionPreferredChannel: "Preferred response method",
        sectionDigitalProfiles: "Digital profiles",
        sectionCustomLinks: "Other links",
        sectionAuthorization: "Authorization",
        sectionListings: "Selected listings",
        edit: "Edit",
        confirmedYes: "Confirmed",
        noneSelected: "None",
        listingConfirmed: "Confirmed",
        listingSkipped: "Skipped",
        listingNoneFound: "No listing found",
        submit: "Create my business profile",
        submitting: "Creating…",
        duplicateAcknowledge: "I understand and want to continue anyway",
        reverifying: "Verifying information…",
        finalExplanation: {
          title: "When you create this profile",
          items: [
            "We'll save this information as the primary record of your business.",
            "We'll only connect the listings you confirmed.",
            "We'll respect your public/private information choices.",
            "You can update your information afterward.",
            "Future Leonix tools may use authorized information to give you more relevant support.",
            "We won't publish a new advertisement.",
            "We won't charge you for creating this profile.",
            "We won't sell your private information or share it with advertisers.",
          ],
        },
      },
      errors: { generic: "Something went wrong. Please try again.", validation: "Please check the highlighted fields.", network: "We couldn't reach the server. Please try again." },
    },
    duplicate: {
      exactTitle: "This business may already exist",
      probableTitle: "We found similar information",
      possibleTitle: "We found related information",
      exactBody: "A business with very similar information is already registered on Leonix.",
      probableBody: "A business with similar details is already registered on Leonix.",
      possibleBody: "A business with a similar name is already registered on Leonix.",
      ownBusinessBody: "You already have access to this business.",
      continueAnyway: "Continue anyway",
      openExisting: "Open my existing business",
      requestReview: "Request manual review",
      goBack: "Go back and correct",
    },
    completed: {
      sectionIdentity: "Business identity",
      sectionOperatingModel: "Operating model",
      sectionBusinessCountry: "Business country",
      sectionLocation: "Physical address",
      sectionCoverage: "Service area",
      sectionContact: "Contact",
      sectionDigitalProfiles: "Digital profiles",
      sectionAuthorization: "Authorization",
      sectionListing: "Connected listings",
      sectionNext: "What comes next",
      sectionDataUse: "How Leonix uses this information",
      legalNameLabel: "Legal name",
      legalNameOwnerOnlyNote: "Only visible to the authorized owner.",
      typeLabel: "Business type",
      stageLabel: "Stage",
      languageLabel: "Primary language",
      businessLanguagesLabel: "Business languages",
      yearStartedLabel: "Year started",
      createdLabel: "Identity created on",
      onboardingComplete: "Setup complete",
      noListing: "No listing connected yet",
      listingPending: "Pending verification",
      listingVerified: "Verified",
      dataUseItems: [
        "One trusted business profile.",
        "Avoids repeated questions.",
        "Keeps your ads and business materials consistent across Leonix.",
        "Connects only the listings you authorized.",
        "Prepares future Business Tools, AI-assisted support, and creative assets.",
        "Personalizes future education, guidance, and recommendations for your business.",
        "Protects your private fields — you decide what becomes public.",
        "Lets you review and correct your information at any time.",
        "We never sell your private information.",
        "We never share your private information with advertisers.",
        "Future AI-assisted features use only authorized, task-relevant information.",
        "AI suggestions are not automatically treated as confirmed facts.",
        "Actions with real consequences always require your approval or that of an authorized human.",
      ],
      nextItems: [
        { title: "Living Business Book", body: "A living record of your business over time." },
        { title: "Business Health Map", body: "An honest view of how your business is doing." },
        { title: "Next Right Move", body: "Prioritized recommendations, when ready." },
        { title: "Learning Center", body: "Practical skills to grow your business." },
      ],
      nextBadge: "Coming soon",
      editingComingSoon: "Editing is coming next.",
      helpDiscoveryTitle: "Help Leonix understand your business",
      helpDiscoveryBody: "The next phase will let you tell us more about your business so we can give more precise guidance. It isn't available yet.",
      helpDiscoveryCta: "Next phase — not available yet",
      helpDiscoveryBadge: "Next phase",
    },
    common: { loading: "Loading…", error: "Something went wrong.", retry: "Retry", cancel: "Cancel" },
  };
}

export type BusinessIdentityCopy = ReturnType<typeof businessIdentityCopy>;
