/**
 * Business Hub adapter — Executive Hub V3 (BIZ-HUB-INTEGRATION-01).
 *
 * GATE 1 finding: there is no real, queryable, cross-vertical "Business Hub" table or
 * service anywhere in this codebase today. `public.executives.business_hub_link` is a
 * plain text reference column (see supabase/migrations/20260810120000_executive_hub_executives.sql),
 * explicitly documented as "association only, no functional integration (locked system)".
 * The per-vertical classifieds tables (restaurantes_public_listings, servicios_public_listings,
 * autos_classifieds_listings, bienes-raices `listings`, comida_local_public_listings,
 * ofertas_locales) are a DIFFERENT product (classifieds) and are intentionally NOT treated
 * as a substitute "Business Hub" — conflating them would misrepresent what's connected.
 *
 * This file is a clean, inert seam: it defines the shape a future Business Hub lookup
 * service will return, and exposes functions with that exact signature that honestly report
 * "not available" today. When a real Business Hub service ships, only the body of
 * `searchBusinessHub` / `getBusinessHubByReference` needs to change — no caller in
 * Executive Hub (editor, actions, list) needs to change.
 *
 * NEVER return fabricated results from this module.
 */

export type BusinessHubSummary = {
  /** Future Business Hub record id. Not available until that service exists. */
  id: string;
  name: string;
  category: string;
  logoUrl: string | null;
  city: string;
  status: string;
  /** URL an admin can open to inspect the business (public page or admin detail). */
  previewUrl: string;
};

export type BusinessHubSearchResult = {
  /** False until a real Business Hub service is wired in. */
  available: boolean;
  results: BusinessHubSummary[];
  /** Human-readable reason shown in the UI — always truthful, never a fake "0 results" message. */
  reason: string;
};

/**
 * Multi-business architecture note (Gate 4): today's Supabase column persists exactly one
 * reference (`executives.business_hub_link`, a text field) — no schema change was made for
 * this build. A future one-to-many relationship would live in a join table (e.g.
 * `executive_businesses` keyed by `executive_slug` + `business_id`), not a new column here.
 * The editor UI documents this directly (disabled "+ Add another business" affordance).
 */

const NOT_IMPLEMENTED_REASON =
  "Business Hub directory service is not implemented yet — no real business records exist to search. This is not a \"0 results\" search failure; the service itself does not exist.";

/**
 * Search the real Business Hub directory. Intentionally always reports `available: false`
 * with zero results until a real Business Hub service is connected — never invents matches.
 */
export async function searchBusinessHub(_query: string): Promise<BusinessHubSearchResult> {
  return {
    available: false,
    results: [],
    reason: NOT_IMPLEMENTED_REASON,
  };
}

/**
 * Resolve a stored reference (id or manual link) to a full Business Hub summary.
 * Returns null honestly — there is no directory to resolve against yet.
 */
export async function getBusinessHubByReference(_reference: string): Promise<BusinessHubSummary | null> {
  return null;
}

/**
 * Future ownership / integration hooks (Gate 5 + Gate 7).
 * Architecture-only — documents the extension points other Leonix systems will use to
 * claim/reference an executive or a linked business. `executives.slug` is the stable key
 * every one of these can join against; none of this is implemented or wired up.
 */
export type ExecutiveOwnershipHooks = {
  /** CRM: which rep owns inbound leads generated by this executive's card. Not implemented. */
  leadOwner: { connected: false; note: string };
  /** Business Hub: which business record(s) this executive represents. Not implemented. */
  businessOwner: { connected: false; note: string };
  /** CRM: assigned sales rep for deals tied to this executive. Not implemented. */
  salesRep: { connected: false; note: string };
  /** CRM: account manager of record for this executive's book of business. Not implemented. */
  accountManager: { connected: false; note: string };
  /** Virtual Assistant: automated scheduling/reply ownership. Not implemented. */
  virtualAssistant: { connected: false; note: string };
  /** AI Concierge: automated lead qualification/routing for this executive. Not implemented. */
  aiConcierge: { connected: false; note: string };
  /** Connection Hub: networking/introductions graph ownership. Not implemented. */
  connectionHub: { connected: false; note: string };
};

export function describeExecutiveOwnershipHooks(slug: string): ExecutiveOwnershipHooks {
  const note = (system: string) =>
    `${system} can key off executives.slug ("${slug}") once that system ships — no Executive Hub schema change needed.`;
  return {
    leadOwner: { connected: false, note: note("CRM lead ownership") },
    businessOwner: { connected: false, note: note("Business Hub business ownership") },
    salesRep: { connected: false, note: note("CRM sales rep assignment") },
    accountManager: { connected: false, note: note("CRM account manager assignment") },
    virtualAssistant: { connected: false, note: note("Virtual Assistant") },
    aiConcierge: { connected: false, note: note("AI Concierge") },
    connectionHub: { connected: false, note: note("Connection Hub") },
  };
}
