import type { Lang } from "@/app/clasificados/config/clasificadosHub";

export const MASCOTAS_PERDIDOS_FORM_COPY = {
  es: {
    pageSubtitle: "Aviso gratuito. Revisa la vista previa antes de publicar.",
    sections: {
      main: "Tu aviso",
      media: "Fotos",
      petDetails: "Detalles de la mascota",
      lostDetails: "Cuándo y dónde se perdió",
      foundDetails: "Cuándo y dónde se encontró",
      adoptionDetails: "Detalles de adopción",
      objectDetails: "Detalles del objeto",
      reward: "Recompensa",
      location: "Ubicación",
      contact: "Contacto",
      social: "Redes sociales (opcional)",
    },
    fields: {
      noticeType: "Tipo de aviso",
      title: "Título",
      description: "Descripción",
      image: "Fotos (hasta 4)",
      petName: "Nombre",
      species: "Especie / tipo",
      breed: "Raza / mezcla",
      color: "Color",
      sex: "Sexo",
      ageApprox: "Edad aproximada",
      size: "Tamaño",
      identifyingMarks: "Señas particulares",
      hasCollar: "¿Tiene collar o arnés?",
      collarNote: "Descripción del collar/arnés",
      microchip: "¿Tiene microchip?",
      lastSeenDate: "Fecha en que se vio por última vez",
      foundDate: "Fecha en que se encontró",
      currentStatus: "Estado actual / dónde está la mascota ahora",
      claimInstructions: "Instrucciones para reclamarla",
      temperament: "Temperamento",
      vaccinated: "¿Vacunas al día?",
      spayedNeutered: "¿Esterilizado/a?",
      specialNeeds: "Necesidades especiales",
      adoptionDetails: "Detalles de la adopción",
      objectType: "Tipo / nombre del objeto",
      offersReward: "¿Ofreces recompensa?",
      rewardAmount: "Monto de la recompensa",
      safetyNote: "Precauciones / temperamento / cómo acercarse",
      city: "Ciudad",
      state: "Estado / Región",
      country: "País",
      zip: "Código postal / ZIP",
      lastSeenLocation: "Área aproximada",
      landmark: "Punto de referencia / intersección",
      phone: "Teléfono (llamadas)",
      smsPhone: "Mensajes de texto (SMS)",
      whatsapp: "WhatsApp",
      email: "Correo electrónico",
      facebook: "Facebook",
      instagram: "Instagram",
    },
    triState: { yes: "Sí", no: "No", unsure: "No sé" },
    imageHint: "Sube hasta 4 fotos. Solo JPG, PNG o WebP.",
    imageRemove: "Quitar",
    imageMain: "Principal",
    rewardAmountPlaceholder: "Ej. 500",
    rewardAmountHelper: "Solo el número — Leonix agrega el símbolo $ automáticamente.",
    lastSeenLocationHelper: "Ej. San José, CA 95116 — sin dirección exacta.",
    landmarkHelper: "Ej. King Rd & Story Rd",
    contactHelper: "Al menos un método de contacto es obligatorio.",
    previewCta: "Vista previa",
    gateFail: "Completa lo siguiente para continuar:",
  },
  en: {
    pageSubtitle: "Free notice. Review the preview before publishing.",
    sections: {
      main: "Your notice",
      media: "Photos",
      petDetails: "Pet details",
      lostDetails: "When and where it was lost",
      foundDetails: "When and where it was found",
      adoptionDetails: "Adoption details",
      objectDetails: "Item details",
      reward: "Reward",
      location: "Location",
      contact: "Contact",
      social: "Social media (optional)",
    },
    fields: {
      noticeType: "Notice type",
      title: "Title",
      description: "Description",
      image: "Photos (up to 4)",
      petName: "Name",
      species: "Species / type",
      breed: "Breed / mix",
      color: "Color",
      sex: "Sex",
      ageApprox: "Approximate age",
      size: "Size",
      identifyingMarks: "Identifying characteristics",
      hasCollar: "Has a collar or harness?",
      collarNote: "Collar/harness description",
      microchip: "Has a microchip?",
      lastSeenDate: "Date last seen",
      foundDate: "Date found",
      currentStatus: "Current status / where the pet is now",
      claimInstructions: "Instructions to claim",
      temperament: "Temperament",
      vaccinated: "Vaccinations up to date?",
      spayedNeutered: "Spayed/neutered?",
      specialNeeds: "Special needs",
      adoptionDetails: "Adoption details",
      objectType: "Item type / name",
      offersReward: "Offering a reward?",
      rewardAmount: "Reward amount",
      safetyNote: "Precautions / temperament / how to approach",
      city: "City",
      state: "State / Region",
      country: "Country",
      zip: "ZIP / Postal code",
      lastSeenLocation: "Approximate area",
      landmark: "Landmark / intersection",
      phone: "Phone (calls)",
      smsPhone: "Text messages (SMS)",
      whatsapp: "WhatsApp",
      email: "Email",
      facebook: "Facebook",
      instagram: "Instagram",
    },
    triState: { yes: "Yes", no: "No", unsure: "Not sure" },
    imageHint: "Upload up to 4 photos. JPG, PNG, or WebP only.",
    imageRemove: "Remove",
    imageMain: "Main",
    rewardAmountPlaceholder: "E.g. 500",
    rewardAmountHelper: "Numbers only — Leonix adds the $ automatically.",
    lastSeenLocationHelper: "E.g. San José, CA 95116 — no exact address.",
    landmarkHelper: "E.g. King Rd & Story Rd",
    contactHelper: "At least one contact method is required.",
    previewCta: "Preview",
    gateFail: "Complete the following to continue:",
  },
} as const;

export function mascotasPerdidosFormCopy(lang: Lang) {
  return MASCOTAS_PERDIDOS_FORM_COPY[lang];
}
