import type { DeepDetailGroupKey } from "./bienesRaicesNegocioFormState";

/** Spanish headings + field labels: shared by form (Step 8) and preview mapper. */
export const BR_DEEP_HEADINGS: Record<DeepDetailGroupKey, string> = {
  tipoYEstilo: "Tipo y estilo",
  construccion: "Construcción y materiales",
  interior: "Interior",
  exterior: "Exterior",
  estacionamiento: "Estacionamiento",
  loteTerreno: "Lote y terreno",
  utilidades: "Utilidades y energía",
  comunidadHoa: "Comunidad y HOA",
  financiera: "Información financiera",
  escuelasUbicacion: "Escuelas y ubicación",
  identificadores: "Identificadores del inmueble",
  observacionesAgente: "Observaciones del agente",
};

export const BR_DEEP_FIELD_LABELS: Record<DeepDetailGroupKey, Record<string, string>> = {
  tipoYEstilo: {
    tipoPropiedad: "Tipo de propiedad",
    subtipo: "Subtipo",
    estilo: "Estilo",
    estado: "Estado",
    uso: "Uso del inmueble",
  },
  construccion: {
    anioConstruccion: "Año de construcción",
    materialExterior: "Material exterior",
    tipoTecho: "Tipo de techo",
    fundacion: "Fundación",
    ventanas: "Ventanas",
    aislamiento: "Aislamiento",
    acabados: "Acabados",
  },
  interior: {
    pisos: "Pisos",
    calefaccion: "Calefacción",
    aireAcondicionado: "Aire acondicionado",
    chimenea: "Chimenea",
    electrodomesticos: "Electrodomésticos",
    distribucion: "Distribución",
    cuartosAdicionales: "Cuartos adicionales",
    oficina: "Oficina",
    sotano: "Sótano",
    closets: "Clósets",
    techos: "Techos",
  },
  exterior: {
    patio: "Patio",
    porch: "Porche",
    terraza: "Terraza",
    balcon: "Balcón",
    jardin: "Jardín",
    piscina: "Piscina / alberca",
    cocinaExterior: "Cocina exterior",
    cercado: "Cercado",
    vista: "Vista",
    iluminacion: "Iluminación exterior",
  },
  estacionamiento: {
    garaje: "Garaje",
    espacios: "Espacios",
    cubierto: "Cubierto / descubierto",
    accesoEv: "Carga eléctrica / EV",
    porton: "Portón",
    cochera: "Cochera",
    driveway: "Entrada / driveway",
  },
  loteTerreno: {
    tamano: "Tamaño del lote",
    dimensiones: "Dimensiones",
    topografia: "Topografía",
    esquina: "Esquina",
    usoSuelo: "Uso de suelo",
    zonificacion: "Zonificación",
  },
  utilidades: {
    agua: "Agua",
    alcantarillado: "Alcantarillado",
    electricidad: "Electricidad",
    gas: "Gas",
    internet: "Internet",
    panelesSolares: "Paneles solares",
    eficiencia: "Eficiencia energética",
    calentadorAgua: "Calentador de agua",
  },
  comunidadHoa: {
    hoa: "HOA",
    cuota: "Cuota",
    frecuencia: "Frecuencia",
    amenidades: "Amenidades",
    seguridad: "Seguridad",
    gated: "Comunidad cerrada",
  },
  financiera: {
    impuestosAnuales: "Impuestos anuales (aprox.)",
    precioPorPie: "Precio por pie cuadrado",
    ingresoActual: "Ingreso actual",
    gastosOperativos: "Gastos operativos",
    capRate: "Cap rate",
    sellerConcessions: "Concesiones del vendedor",
  },
  escuelasUbicacion: {
    distrito: "Distrito escolar",
    primaria: "Primaria",
    secundaria: "Secundaria",
    preparatoria: "Preparatoria",
    puntosCercanos: "Puntos cercanos",
    transporte: "Transporte",
    vecindario: "Vecindario",
    zona: "Zona",
  },
  identificadores: {
    mls: "MLS",
    parcela: "Número de parcela",
    codigoInterno: "Código interno",
    referenciaAnunciante: "Referencia del anunciante",
  },
  observacionesAgente: {
    observacionesPublicas: "Observaciones públicas",
    observacionesPrivadas: "Observaciones privadas (no se publican)",
    restricciones: "Restricciones",
    instruccionesShowing: "Instrucciones de visita",
  },
};
