/**
 * Program 6, Gate 6E — Creative archetype registry.
 * 10 archetypes with deterministic definitions.
 */
import type { ArchetypeDefinition, CreativeArchetypeKey } from "./types";

export const ARCHETYPES: Record<CreativeArchetypeKey, ArchetypeDefinition> = {
  AUTHORITY_TRADITIONAL_UPGRADED: {
    key: "AUTHORITY_TRADITIONAL_UPGRADED",
    label: "Authority — Traditional Upgraded",
    lane: "LANE_A_TRADITIONAL_UPGRADED",
    supportedFormats: ["FULL_PAGE", "HALF_HORIZONTAL", "HALF_VERTICAL", "QUARTER"],
    primaryPurpose: "Establish professional authority with upgraded typography and hierarchy while preserving familiar direct-response structure.",
    recommendedCategories: ["attorneys", "insurance", "immigration", "tax_accounting", "healthcare_professionals"],
    requiredSlots: ["logo", "headline", "services", "cta", "contact", "qr"],
    optionalSlots: ["portrait", "trust", "address", "disclaimer", "subheadline"],
    disallowedElements: ["fake_testimonial", "fake_award", "guarantee_without_basis"],
    visualHierarchy: "Business category immediately obvious → headline → portrait/authority → service bullets → CTA/contact/QR.",
    imageStrategy: "Recognizable portrait or professional environment. Real client photography only.",
    ctaStrategy: "Big phone/CTA. Direct-response structure preserved.",
    copyDensityBudget: "Moderate. Clear service bullets. No clutter.",
    sponsorBehavior: null,
    languageBehavior: "Spanish-first or bilingual. Preserve professional terminology.",
    complianceRiskTags: ["LEGAL", "MEDICAL", "INSURANCE", "IMMIGRATION", "TAX"],
  },
  PREMIUM_PHOTO_HERO: {
    key: "PREMIUM_PHOTO_HERO",
    label: "Premium Photo Hero",
    lane: "LANE_B_PREMIUM_CREATIVE",
    supportedFormats: ["FULL_PAGE", "FULL_BLEED", "HALF_HORIZONTAL", "SPREAD_BLEED"],
    primaryPurpose: "Campaign-level concept with hero photography, premium typography, emotional visual language.",
    recommendedCategories: ["restaurants", "beauty", "fitness", "real_estate", "home_services", "lifestyle"],
    requiredSlots: ["hero_image", "headline", "cta", "contact", "qr"],
    optionalSlots: ["logo", "subheadline", "benefits", "trust", "address", "disclaimer"],
    disallowedElements: ["stock_photo_as_client", "ai_image_as_authentic", "fake_review"],
    visualHierarchy: "Hero visual dominates → headline overlays or follows → supporting copy → CTA/contact.",
    imageStrategy: "Hero photography. Real client or licensed stock clearly distinguished.",
    ctaStrategy: "High-impact but disciplined. Single clear action.",
    copyDensityBudget: "Low-to-moderate. Let the visual breathe.",
    sponsorBehavior: null,
    languageBehavior: "Bilingual supported. Emotional language preserved across languages.",
    complianceRiskTags: ["NORMAL"],
  },
  OFFER_PROMO_BLAST: {
    key: "OFFER_PROMO_BLAST",
    label: "Offer / Promo Blast",
    lane: "LANE_A_TRADITIONAL_UPGRADED",
    supportedFormats: ["QUARTER", "HALF_HORIZONTAL", "HALF_VERTICAL", "FULL_PAGE"],
    primaryPurpose: "Time-limited offer, coupon, seasonal special with strong direct-response.",
    recommendedCategories: ["coupons", "specials", "seasonal_campaigns"],
    requiredSlots: ["offer", "headline", "cta", "qr", "disclaimer"],
    optionalSlots: ["logo", "hero_image", "benefits", "contact", "address"],
    disallowedElements: ["fake_expiration", "invented_price", "unverified_offer"],
    visualHierarchy: "Offer dominates → headline → benefits → CTA → QR → disclaimer.",
    imageStrategy: "Product or service photo. Offer visual prominence.",
    ctaStrategy: "Urgent, clear, with expiration truth.",
    copyDensityBudget: "Moderate. Offer clarity over density.",
    sponsorBehavior: null,
    languageBehavior: "Primary language + concise secondary CTA for quarter ads.",
    complianceRiskTags: ["NORMAL"],
  },
  MULTI_PANEL_SERVICE_GRID: {
    key: "MULTI_PANEL_SERVICE_GRID",
    label: "Multi-Panel Service Grid",
    lane: "LANE_A_TRADITIONAL_UPGRADED",
    supportedFormats: ["FULL_PAGE", "HALF_HORIZONTAL", "SPREAD_TRIM"],
    primaryPurpose: "Multiple strong service groups organized in a grid layout.",
    recommendedCategories: ["event_rentals", "party_services", "multi_service", "directories"],
    requiredSlots: ["logo", "headline", "services", "cta", "contact", "qr"],
    optionalSlots: ["hero_image", "secondary_image", "benefits", "trust", "address"],
    disallowedElements: ["cluttered_grid", "unreadable_service_text"],
    visualHierarchy: "Headline → service grid panels → CTA/contact/QR.",
    imageStrategy: "Service-specific images per panel if available.",
    ctaStrategy: "Organized contact paths for different service groups.",
    copyDensityBudget: "Higher density acceptable if organized in clear panels.",
    sponsorBehavior: null,
    languageBehavior: "Bilingual supported. Service names preserved.",
    complianceRiskTags: ["NORMAL"],
  },
  RECRUITMENT_HIRING: {
    key: "RECRUITMENT_HIRING",
    label: "Recruitment / Hiring",
    lane: "LANE_A_TRADITIONAL_UPGRADED",
    supportedFormats: ["QUARTER", "HALF_VERTICAL", "HALF_HORIZONTAL", "FULL_PAGE"],
    primaryPurpose: "Job postings, staffing, hiring with clear position and contact.",
    recommendedCategories: ["jobs", "staffing", "hospitality", "trades", "warehouse", "field_positions"],
    requiredSlots: ["headline", "services", "cta", "contact", "qr"],
    optionalSlots: ["logo", "hero_image", "benefits", "address", "disclaimer"],
    disallowedElements: ["fake_benefit", "discriminatory_language", "invented_salary"],
    visualHierarchy: "Position title → requirements → benefits → how to apply → QR/contact.",
    imageStrategy: "Work environment photo if available.",
    ctaStrategy: "Apply now with clear instructions.",
    copyDensityBudget: "Concise. Position clarity over density.",
    sponsorBehavior: null,
    languageBehavior: "Bilingual supported for workforce audiences.",
    complianceRiskTags: ["EMPLOYMENT"],
  },
  EVENT_VENUE_SHOWCASE: {
    key: "EVENT_VENUE_SHOWCASE",
    label: "Event / Venue Showcase",
    lane: "LANE_B_PREMIUM_CREATIVE",
    supportedFormats: ["FULL_PAGE", "FULL_BLEED", "HALF_HORIZONTAL", "SPREAD_BLEED"],
    primaryPurpose: "Banquet halls, quinceañeras, wedding vendors with premium visual showcase.",
    recommendedCategories: ["banquet_halls", "quinceaneras", "wedding_vendors", "entertainment", "venue_packages"],
    requiredSlots: ["hero_image", "headline", "services", "cta", "contact", "qr"],
    optionalSlots: ["logo", "secondary_image", "benefits", "trust", "address", "disclaimer"],
    disallowedElements: ["fake_event_photo", "invented_package_price"],
    visualHierarchy: "Venue hero visual → headline → package/services → CTA/contact.",
    imageStrategy: "Venue photography. Real venue images preferred.",
    ctaStrategy: "Book a tour / schedule consultation.",
    copyDensityBudget: "Moderate. Visual impact with organized package info.",
    sponsorBehavior: null,
    languageBehavior: "Bilingual supported. Celebration language culturally appropriate.",
    complianceRiskTags: ["NORMAL"],
  },
  SPONSORED_EDITORIAL: {
    key: "SPONSORED_EDITORIAL",
    label: "Sponsored Editorial / Leonix Te Explica",
    lane: "LANE_C_SPONSORED_EDITORIAL",
    supportedFormats: ["FULL_PAGE", "HALF_HORIZONTAL"],
    primaryPurpose: "Educational content (checklist, guide) with sponsor support. Sponsor does NOT control editorial truth.",
    recommendedCategories: ["leonix_te_explica", "educational_guide", "checklist", "financial_checkup", "home_preparation"],
    requiredSlots: ["headline", "leonix_brand", "sponsor", "disclaimer", "qr", "page_number"],
    optionalSlots: ["subheadline", "hero_image", "secondary_image", "cta", "contact"],
    disallowedElements: ["sponsor_controls_editorial", "fake_expert_quote", "medical_advice_without_disclaimer", "legal_advice_without_disclaimer"],
    visualHierarchy: "Leonix Te Explica label → title → intro → content blocks → sponsor disclosure → disclaimer → QR.",
    imageStrategy: "Editorial illustration or supporting visual. Not sponsor product shot.",
    ctaStrategy: "QR to full resource. Sponsor contact separate from editorial content.",
    copyDensityBudget: "Higher density for educational content. Organized in clear sections.",
    sponsorBehavior: "Sponsor supports useful Leonix content. Disclosure distinguishes 'Presentado con el apoyo de' from 'Contenido patrocinado'.",
    languageBehavior: "Spanish-first. May link to English digitally.",
    complianceRiskTags: ["LEGAL", "MEDICAL", "FINANCIAL", "SAFETY", "INSURANCE", "TAX", "HOUSING"],
  },
  BUSINESS_PROFILE_STORY: {
    key: "BUSINESS_PROFILE_STORY",
    label: "Business con Corazón — Profile Story",
    lane: "LANE_B_PREMIUM_CREATIVE",
    supportedFormats: ["FULL_PAGE", "HALF_HORIZONTAL"],
    primaryPurpose: "Founder story, community business spotlight with emotional storytelling.",
    recommendedCategories: ["community_business", "founder_story", "family_business"],
    requiredSlots: ["headline", "portrait", "leonix_brand", "qr"],
    optionalSlots: ["logo", "subheadline", "hero_image", "benefits", "trust", "cta", "contact", "address", "disclaimer"],
    disallowedElements: ["invented_biography", "fake_award", "unverified_origin_story"],
    visualHierarchy: "Portrait → headline/story → supporting content → CTA/QR.",
    imageStrategy: "Founder portrait + business environment.",
    ctaStrategy: "Visit/support/learn more.",
    copyDensityBudget: "Moderate. Story flow over density.",
    sponsorBehavior: null,
    languageBehavior: "Spanish-first. Story tone preserved.",
    complianceRiskTags: ["NORMAL"],
  },
  PREMIUM_INSTITUTIONAL: {
    key: "PREMIUM_INSTITUTIONAL",
    label: "Premium Institutional",
    lane: "LANE_B_PREMIUM_CREATIVE",
    supportedFormats: ["FULL_PAGE", "FULL_BLEED", "SPREAD_BLEED"],
    primaryPurpose: "Hospital, university, major law practice, financial institution — high-trust institutional presence.",
    recommendedCategories: ["hospital", "university", "major_law_practice", "financial_institution", "major_partner"],
    requiredSlots: ["logo", "headline", "trust", "cta", "contact", "qr", "disclaimer"],
    optionalSlots: ["hero_image", "subheadline", "benefits", "address", "leonix_brand"],
    disallowedElements: ["casual_tone", "discount_language", "fake_credential"],
    visualHierarchy: "Institutional logo → headline → trust/credibility → CTA/contact.",
    imageStrategy: "Institutional building or premium environment.",
    ctaStrategy: "Consultation/appointment. Professional tone.",
    copyDensityBudget: "Low-to-moderate. Institutional gravitas.",
    sponsorBehavior: null,
    languageBehavior: "Bilingual supported. Professional register.",
    complianceRiskTags: ["LEGAL", "MEDICAL", "FINANCIAL"],
  },
  LEGACY_DIRECTORY_BASIC: {
    key: "LEGACY_DIRECTORY_BASIC",
    label: "Legacy Directory Basic",
    lane: "LANE_A_TRADITIONAL_UPGRADED",
    supportedFormats: ["QUARTER", "HALF_VERTICAL", "HALF_HORIZONTAL"],
    primaryPurpose: "Conservative option for clients who want familiar local-magazine style with Leonix quality standards.",
    recommendedCategories: ["conservative_clients", "directory_listings"],
    requiredSlots: ["logo", "headline", "services", "cta", "contact"],
    optionalSlots: ["qr", "address", "disclaimer", "benefits"],
    disallowedElements: ["overly_modern_layout", "excessive_whitespace_if_client_prefers_density"],
    visualHierarchy: "Logo → headline → services → CTA/contact. Familiar structure.",
    imageStrategy: "Logo + optional product photo.",
    ctaStrategy: "Phone-forward. Familiar direct-response.",
    copyDensityBudget: "Moderate. Familiar density acceptable.",
    sponsorBehavior: null,
    languageBehavior: "Spanish-first.",
    complianceRiskTags: ["NORMAL"],
  },
};

export function getArchetype(key: CreativeArchetypeKey): ArchetypeDefinition {
  return ARCHETYPES[key];
}

export function getAllArchetypes(): readonly ArchetypeDefinition[] {
  return Object.values(ARCHETYPES);
}

export function getArchetypesByLane(lane: ArchetypeDefinition["lane"]): readonly ArchetypeDefinition[] {
  return Object.values(ARCHETYPES).filter((a) => a.lane === lane);
}
