export type AutosPublicLang = "es" | "en";

export const AUTOS_PUBLIC_BLUEPRINT_COPY = {
  es: {
    breadcrumb: "Clasificados",
    title: "Leonix Autos",
    tagline: "Encuentra tu próximo vehículo en NorCal — concesionarios y particulares en un solo lugar.",
    heroHeading: "Encuentra tu próximo auto",
    heroSubhead:
      "NorCal en un solo lugar: concesionarios y vendedores privados, con precios, millaje y ubicación claros.",
    heroSearchFieldLabel: "Marca, modelo o palabra clave",
    searchPlaceholder: "Ej. Civic 2021, Tacoma, BMW X3…",
    cityLabel: "Ciudad",
    cityPlaceholder: "Ej. San Jose",
    cityHelper: "Dónde quieres buscar",
    zipLabel: "ZIP",
    zipPlaceholder: "Ej. 95112",
    zipHelper: "Opcional · acota por código postal",
    nearLabel: "Cerca de",
    searchCta: "Buscar",
    quickDiscovery: "Explorar por estilo",
    quickChipsLabel: "Atajos de búsqueda",
    chipsShortcutHint: "Cada atajo abre resultados ya filtrados",
    chips: {
      sedan: "Sedán",
      suv: "SUV",
      truck: "Camioneta",
      coupe: "Coupé",
      luxury: "Lujo",
      ev: "Eléctrico / Híbrido",
      hatchback: "Hatchback",
      economical: "Económico",
      family: "Familiar",
    },
    featuredZoneTitle: "Inventario premium cerca de {city}, {state}",
    landingFeaturedTitle: "Autos destacados cerca de ti",
    landingFeaturedSubtitle: "Concesionarios y particulares — misma vitrina, distintos vendedores.",
    featuredBadge: "Destacado",
    freshTitle: "Inventario reciente",
    browseAll: "Explorar todos los autos",
    browseAllShort: "Ver todos los autos",
    primaryDiscoveryHint: "Abre el listado completo; ajusta filtros y orden en la siguiente pantalla.",
    heroSearchFooterHint:
      "Buscar te lleva a resultados con tu texto, ciudad y ZIP. Ver todos abre el inventario completo.",
    browseBodyStyleTitle: "Compra por tipo de carrocería",
    browseNeedTitle: "Compra según tu necesidad",
    featuredDealersTitle: "Concesionarios destacados",
    featuredDealersSubtitle: "Inventario en Leonix con ubicación y reseñas visibles para compradores.",
    recentAddedTitle: "Recién agregados",
    recentAddedSubtitle: "Listados recientes con precio, millaje y tipo de vendedor visibles.",
    cardViewDetails: "Ver detalles",
    bodyStyleBrowse: {
      sedans: "Sedanes",
      suvs: "SUVs",
      trucks: "Camionetas",
      coupes: "Cupés",
      minivans: "Minivans",
      hatchbacks: "Hatchbacks",
    },
    needBrowse: {
      firstCar: "Primer auto",
      lowMiles: "Bajo millaje",
      economical: "Económicos",
      family: "Familiares",
      work: "Para trabajo",
      luxury: "Lujo",
    },
    needBrowseHint: {
      firstCar: "Entradas accesibles para empezar",
      lowMiles: "Menor desgaste, más tranquilidad",
      economical: "Presupuesto inteligente",
      family: "Espacio y seguridad",
      work: "Capacidad de carga y uso diario",
      luxury: "Equipamiento y confort premium",
    },
    needBrowseApply: "Ver resultados con estos criterios",
    heroRadiusShort: "Radio (pronto)",
    publishBandTitle: "¿Eres concesionario o vendedor privado?",
    publishBandBody:
      "Publica tu auto en minutos y llega a compradores con anuncios premium: fotos claras, datos estructurados y presencia junto a inventario de confianza.",
    publishTrust1: "Presentación premium y datos completos",
    publishTrust2: "Visible para quien ya explora Autos en Leonix",
    publishTrust3: "Particulares y concesionarios en el mismo destino",
    publishNowCta: "Publicar ahora",
    exploreAllAutosCta: "Explorar todos los autos",
    dealerInventoryCta: "Ver inventario",
    langEs: "Español",
    langEn: "English",
    resultsTitle: "Autos en venta",
    resultsNear: "cerca de {city}, {state}",
    resultCount: "{n} resultados",
    sortLabel: "Ordenar",
    sortNewest: "Más reciente",
    sortPriceLow: "Precio: menor",
    sortPriceHigh: "Precio: mayor",
    sortMileage: "Menor millaje",
    filtersOpen: "Filtros",
    filtersTitle: "Filtros",
    filterApply: "Aplicar",
    filterReset: "Restablecer",
    filterPrice: "Precio (USD)",
    priceMin: "Mín.",
    priceMax: "Máx.",
    filterMake: "Marca",
    filterModel: "Modelo",
    filterYear: "Año",
    yearFrom: "Desde",
    yearTo: "Hasta",
    filterAny: "Cualquiera",
    conditionNew: "Nuevo",
    conditionUsed: "Usado",
    conditionCertified: "Certificado",
    filterCondition: "Condición",
    filterSeller: "Vendedor",
    sellerAll: "Todos",
    sellerDealer: "Concesionario",
    sellerPrivate: "Privado",
    filterBody: "Carrocería",
    filterTransmission: "Transmisión",
    filterDrivetrain: "Tracción",
    filterFuel: "Combustible",
    mileageMin: "Millaje mín.",
    mileageMax: "Millaje máx.",
    filterMileage: "Millaje (rango)",
    filterTitle: "Estado del título",
    filterRadius: "Radio (millas)",
    filterRadiusHint: "Próximamente: búsqueda por distancia desde el ZIP.",
    paginationPrev: "Anterior",
    paginationNext: "Siguiente",
    loadMore: "Cargar más",
    pageOf: "Página {page}",
    resultsClearAll: "Limpiar búsqueda",
    resultsUseLocation: "Usar mi ubicación",
    resultsLocationDenied: "Ubicación no disponible; usa ciudad o ZIP.",
    resultsLocationLoading: "Obteniendo ubicación…",
    resultsRecentSection: "Recientemente publicados",
    resultsMainSection: "Todos los resultados",
    resultsControlHint: "Ciudad canónica NorCal · ZIP de 5 dígitos",
    resultsQuickFilters: "Atajos rápidos",
    resultsQuickFiltersHint: "Aplican filtros reales sobre tu búsqueda actual (conservan ciudad/ZIP si ya los elegiste).",
    chipQuickPrivate: "Privado",
    chipQuickDealer: "Negocio",
    chipQuickLowMiles: "Bajo millaje",
    chipQuickEconomical: "Económico",
    filterGroupLocation: "Ubicación",
    filterGroupPrice: "Precio",
    filterGroupYear: "Año",
    filterGroupVehicle: "Vehículo",
    filterGroupSellerCondition: "Vendedor y condición",
    filterGroupMechanical: "Mecánica y millaje",
    filterGroupTitle: "Estado del título",
    resultsLaneFeaturedSubtitle:
      "Espacio visible para concesionarios con inventario promocionado — no reemplaza el listado completo ni oculta anuncios particulares.",
    resultsLaneRecentSubtitle: "Ordenados por antigüedad del listado en esta vista (más recientes primero cuando ordenas por «Más reciente»).",
    resultsLaneMainSubtitle: "Listado mixto: particulares y concesionarios con visibilidad equitativa dentro de tus filtros.",
    resultsResetShort: "Restablecer",
    resultsLocationHint: "Solo al tocar el botón. No rastreamos tu ubicación en segundo plano.",
    cardMonthly: "desde {amount}/mes est.",
    cardMi: "mi",
    sellerDealerFooter: "Concesionario",
    sellerPrivateFooter: "Privado",
    sellerLaneBadgeDealer: "Negocio",
    sellerLaneBadgePrivate: "Privado",
    alertCta: "Establecer alerta",
    postAd: "Publicar anuncio",
    viewListings: "Ver anuncios",
    hubNote: "También en Leonix",
  },
  en: {
    breadcrumb: "Classifieds",
    title: "Leonix Autos",
    tagline: "Find your next vehicle in NorCal — dealerships and private sellers in one premium destination.",
    heroHeading: "Find your next car",
    heroSubhead:
      "NorCal in one place — dealerships and private sellers, with clear price, mileage, and location.",
    heroSearchFieldLabel: "Make, model, or keyword",
    searchPlaceholder: "e.g. Civic 2021, Tacoma, BMW X3…",
    cityLabel: "City",
    cityPlaceholder: "e.g. San Jose",
    cityHelper: "Where you want to search",
    zipLabel: "ZIP",
    zipPlaceholder: "e.g. 95112",
    zipHelper: "Optional · narrows by postal code",
    nearLabel: "Near",
    searchCta: "Search",
    quickDiscovery: "Browse by style",
    quickChipsLabel: "Search shortcuts",
    chipsShortcutHint: "Each shortcut opens filtered results",
    chips: {
      sedan: "Sedan",
      suv: "SUV",
      truck: "Truck",
      coupe: "Coupe",
      luxury: "Luxury",
      ev: "Electric / Hybrid",
      hatchback: "Hatchback",
      economical: "Budget-friendly",
      family: "Family",
    },
    featuredZoneTitle: "Premium inventory near {city}, {state}",
    landingFeaturedTitle: "Featured vehicles near you",
    landingFeaturedSubtitle: "Dealerships and private sellers — one showcase, different sellers.",
    featuredBadge: "Featured",
    freshTitle: "Fresh inventory",
    browseAll: "Explore all vehicles",
    browseAllShort: "View all vehicles",
    primaryDiscoveryHint: "Open the full list; refine filters and sort on the next screen.",
    heroSearchFooterHint:
      "Search opens results with your keyword, city, and ZIP. View all opens the full inventory.",
    browseBodyStyleTitle: "Shop by body style",
    browseNeedTitle: "Shop by need",
    featuredDealersTitle: "Featured dealerships",
    featuredDealersSubtitle: "Inventory on Leonix with location and ratings visible to buyers.",
    recentAddedTitle: "Recently added",
    recentAddedSubtitle: "Fresh listings with price, mileage, and seller type visible.",
    cardViewDetails: "View details",
    bodyStyleBrowse: {
      sedans: "Sedans",
      suvs: "SUVs",
      trucks: "Trucks",
      coupes: "Coupes",
      minivans: "Minivans",
      hatchbacks: "Hatchbacks",
    },
    needBrowse: {
      firstCar: "First car",
      lowMiles: "Low mileage",
      economical: "Budget picks",
      family: "Family-friendly",
      work: "For work",
      luxury: "Luxury",
    },
    needBrowseHint: {
      firstCar: "Accessible entries to get started",
      lowMiles: "Less wear, more peace of mind",
      economical: "Smarter budget choices",
      family: "Space and safety",
      work: "Cargo and daily duty",
      luxury: "Premium comfort and features",
    },
    needBrowseApply: "See results with these criteria",
    heroRadiusShort: "Radius (soon)",
    publishBandTitle: "Dealership or private seller?",
    publishBandBody:
      "Post in minutes and reach buyers with premium ads — clear photos, structured details, and presence alongside trusted inventory.",
    publishTrust1: "Premium layout and complete vehicle details",
    publishTrust2: "Seen by shoppers already browsing Leonix Autos",
    publishTrust3: "Private sellers and dealerships in one destination",
    publishNowCta: "Publish now",
    exploreAllAutosCta: "Explore all vehicles",
    dealerInventoryCta: "View inventory",
    langEs: "Spanish",
    langEn: "English",
    resultsTitle: "Vehicles for sale",
    resultsNear: "near {city}, {state}",
    resultCount: "{n} results",
    sortLabel: "Sort",
    sortNewest: "Newest",
    sortPriceLow: "Price: low to high",
    sortPriceHigh: "Price: high to low",
    sortMileage: "Lowest mileage",
    filtersOpen: "Filters",
    filtersTitle: "Filters",
    filterApply: "Apply",
    filterReset: "Reset",
    filterPrice: "Price (USD)",
    priceMin: "Min",
    priceMax: "Max",
    filterMake: "Make",
    filterModel: "Model",
    filterYear: "Year",
    yearFrom: "From",
    yearTo: "To",
    filterAny: "Any",
    conditionNew: "New",
    conditionUsed: "Used",
    conditionCertified: "Certified",
    filterCondition: "Condition",
    filterSeller: "Seller",
    sellerAll: "All",
    sellerDealer: "Dealership",
    sellerPrivate: "Private",
    filterBody: "Body style",
    filterTransmission: "Transmission",
    filterDrivetrain: "Drivetrain",
    filterFuel: "Fuel",
    mileageMin: "Min mileage",
    mileageMax: "Max mileage",
    filterMileage: "Mileage range",
    filterTitle: "Title status",
    filterRadius: "Radius (miles)",
    filterRadiusHint: "Coming soon: search by distance.",
    paginationPrev: "Previous",
    paginationNext: "Next",
    loadMore: "Load more",
    pageOf: "Page {page}",
    resultsClearAll: "Clear search",
    resultsUseLocation: "Use my location",
    resultsLocationDenied: "Location unavailable; enter city or ZIP.",
    resultsLocationLoading: "Getting location…",
    resultsRecentSection: "Recently posted",
    resultsMainSection: "All results",
    resultsControlHint: "Canonical NorCal city · 5-digit ZIP",
    resultsQuickFilters: "Quick filters",
    resultsQuickFiltersHint: "Apply real filters on top of your current search (city/ZIP stay if you already set them).",
    chipQuickPrivate: "Private",
    chipQuickDealer: "Dealer",
    chipQuickLowMiles: "Low mileage",
    chipQuickEconomical: "Budget",
    filterGroupLocation: "Location",
    filterGroupPrice: "Price",
    filterGroupYear: "Year",
    filterGroupVehicle: "Vehicle",
    filterGroupSellerCondition: "Seller & condition",
    filterGroupMechanical: "Mechanical & mileage",
    filterGroupTitle: "Title status",
    resultsLaneFeaturedSubtitle:
      "Visible space for dealerships with promoted inventory — it does not replace the full feed or hide private listings.",
    resultsLaneRecentSubtitle: "Ordered by listing recency in this view (newest first when you sort by Newest).",
    resultsLaneMainSubtitle: "Mixed feed: private sellers and dealerships with fair visibility within your filters.",
    resultsResetShort: "Reset all",
    resultsLocationHint: "Only when you tap the button. We do not track your location in the background.",
    cardMonthly: "from {amount}/mo est.",
    cardMi: "mi",
    sellerDealerFooter: "Dealership",
    sellerPrivateFooter: "Private",
    sellerLaneBadgeDealer: "Dealer",
    sellerLaneBadgePrivate: "Private",
    alertCta: "Set alert",
    postAd: "Post a listing",
    viewListings: "View listings",
    hubNote: "Also on Leonix",
  },
} as const;

export type AutosPublicBlueprintCopy = (typeof AUTOS_PUBLIC_BLUEPRINT_COPY)[AutosPublicLang];
