export type AutosPublicLang = "es" | "en";

export const AUTOS_PUBLIC_BLUEPRINT_COPY = {
  es: {
    breadcrumb: "Clasificados",
    title: "Leonix Autos",
    tagline: "Encuentra tu próximo vehículo en NorCal — concesionarios y particulares en un solo lugar.",
    heroHeading: "Encuentra tu próximo auto",
    heroSubhead:
      "Compra y vende con confianza a través de concesionarios y vendedores particulares — inventario real, ubicación y millaje claros.",
    searchPlaceholder: "¿Qué auto estás buscando?",
    cityLabel: "Ciudad",
    cityPlaceholder: "Ej. San Jose",
    zipLabel: "ZIP",
    zipPlaceholder: "5 dígitos",
    nearLabel: "Cerca de",
    searchCta: "Buscar",
    quickDiscovery: "Explorar por estilo",
    quickChipsLabel: "Atajos por tipo de vehículo",
    chips: {
      sedan: "Sedán",
      suv: "SUV",
      truck: "Camioneta",
      coupe: "Coupé",
      luxury: "Lujo",
      ev: "Eléctrico / Híbrido",
      hatchback: "Hatchback",
      economical: "Económico",
      family: "Familiar",
    },
    featuredZoneTitle: "Destacado cerca de San Jose, CA",
    landingFeaturedTitle: "Autos destacados cerca de ti",
    featuredBadge: "Destacado",
    freshTitle: "Inventario reciente",
    browseAll: "Explorar todos los autos",
    browseAllShort: "Ver todos los autos",
    primaryDiscoveryHint: "Ver inventario completo con filtros y ordenamiento",
    browseBodyStyleTitle: "Compra por tipo de carrocería",
    browseNeedTitle: "Compra según tu necesidad",
    featuredDealersTitle: "Concesionarios destacados",
    recentAddedTitle: "Recién agregados",
    cardViewDetails: "Ver detalles",
    bodyStyleBrowse: {
      sedans: "Sedanes",
      suvs: "SUVs",
      trucks: "Camionetas",
      coupes: "Cupés",
      minivans: "Minivans",
      hatchbacks: "Hatchbacks",
    },
    needBrowse: {
      firstCar: "Primer auto",
      lowMiles: "Bajo millaje",
      economical: "Económicos",
      family: "Familiares",
      work: "Para trabajo",
      luxury: "Lujo",
    },
    needBrowseHint: {
      firstCar: "Entradas accesibles para empezar",
      lowMiles: "Menor desgaste, más tranquilidad",
      economical: "Presupuesto inteligente",
      family: "Espacio y seguridad",
      work: "Capacidad de carga y uso diario",
      luxury: "Equipamiento y confort premium",
    },
    heroRadiusShort: "Radio (pronto)",
    publishBandTitle: "¿Eres concesionario o vendedor privado?",
    publishBandBody:
      "Publica tu auto en minutos y llega a miles de compradores con anuncios premium en Leonix Clasificados.",
    publishNowCta: "Publicar ahora",
    exploreAllAutosCta: "Explorar todos los autos",
    dealerInventoryCta: "Ver inventario",
    langEs: "Español",
    langEn: "English",
    resultsTitle: "Autos en venta",
    resultsNear: "cerca de {city}, {state}",
    resultCount: "{n} resultados",
    sortLabel: "Ordenar",
    sortNewest: "Más reciente",
    sortPriceLow: "Precio: menor",
    sortPriceHigh: "Precio: mayor",
    sortMileage: "Menor millaje",
    filtersOpen: "Filtros",
    filtersTitle: "Filtros",
    filterApply: "Aplicar",
    filterReset: "Restablecer",
    filterPrice: "Precio (USD)",
    priceMin: "Mín.",
    priceMax: "Máx.",
    filterMake: "Marca",
    filterModel: "Modelo",
    filterYear: "Año",
    yearFrom: "Desde",
    yearTo: "Hasta",
    filterAny: "Cualquiera",
    conditionNew: "Nuevo",
    conditionUsed: "Usado",
    conditionCertified: "Certificado",
    filterCondition: "Condición",
    filterSeller: "Vendedor",
    sellerAll: "Todos",
    sellerDealer: "Concesionario",
    sellerPrivate: "Privado",
    filterBody: "Carrocería",
    filterTransmission: "Transmisión",
    filterDrivetrain: "Tracción",
    filterFuel: "Combustible",
    filterMileage: "Millaje máx.",
    filterTitle: "Estado del título",
    filterRadius: "Radio (millas)",
    filterRadiusHint: "Próximamente: búsqueda por distancia desde el ZIP.",
    paginationPrev: "Anterior",
    paginationNext: "Siguiente",
    loadMore: "Cargar más",
    pageOf: "Página {page}",
    cardMonthly: "desde {amount}/mes est.",
    cardMi: "mi",
    sellerDealerFooter: "Concesionario",
    sellerPrivateFooter: "Privado",
    alertCta: "Establecer alerta",
    postAd: "Publicar anuncio",
    viewListings: "Ver anuncios",
    hubNote: "También en Leonix",
  },
  en: {
    breadcrumb: "Classifieds",
    title: "Leonix Autos",
    tagline: "Find your next vehicle in NorCal — dealerships and private sellers in one premium destination.",
    heroHeading: "Find your next car",
    heroSubhead:
      "Buy and sell with confidence through dealerships and private sellers — real inventory with clear location and mileage.",
    searchPlaceholder: "What vehicle are you looking for?",
    cityLabel: "City",
    cityPlaceholder: "e.g. San Jose",
    zipLabel: "ZIP",
    zipPlaceholder: "5 digits",
    nearLabel: "Near",
    searchCta: "Search",
    quickDiscovery: "Browse by style",
    quickChipsLabel: "Quick shortcuts by vehicle type",
    chips: {
      sedan: "Sedan",
      suv: "SUV",
      truck: "Truck",
      coupe: "Coupe",
      luxury: "Luxury",
      ev: "Electric / Hybrid",
      hatchback: "Hatchback",
      economical: "Budget-friendly",
      family: "Family",
    },
    featuredZoneTitle: "Featured near San Jose, CA",
    landingFeaturedTitle: "Featured vehicles near you",
    featuredBadge: "Featured",
    freshTitle: "Fresh inventory",
    browseAll: "Explore all vehicles",
    browseAllShort: "View all vehicles",
    primaryDiscoveryHint: "Open the full inventory with filters and sorting",
    browseBodyStyleTitle: "Shop by body style",
    browseNeedTitle: "Shop by need",
    featuredDealersTitle: "Featured dealerships",
    recentAddedTitle: "Recently added",
    cardViewDetails: "View details",
    bodyStyleBrowse: {
      sedans: "Sedans",
      suvs: "SUVs",
      trucks: "Trucks",
      coupes: "Coupes",
      minivans: "Minivans",
      hatchbacks: "Hatchbacks",
    },
    needBrowse: {
      firstCar: "First car",
      lowMiles: "Low mileage",
      economical: "Budget picks",
      family: "Family-friendly",
      work: "For work",
      luxury: "Luxury",
    },
    needBrowseHint: {
      firstCar: "Accessible entries to get started",
      lowMiles: "Less wear, more peace of mind",
      economical: "Smarter budget choices",
      family: "Space and safety",
      work: "Cargo and daily duty",
      luxury: "Premium comfort and features",
    },
    heroRadiusShort: "Radius (soon)",
    publishBandTitle: "Dealership or private seller?",
    publishBandBody:
      "Post your vehicle in minutes and reach thousands of buyers with premium classified ads on Leonix.",
    publishNowCta: "Publish now",
    exploreAllAutosCta: "Explore all vehicles",
    dealerInventoryCta: "View inventory",
    langEs: "Spanish",
    langEn: "English",
    resultsTitle: "Vehicles for sale",
    resultsNear: "near {city}, {state}",
    resultCount: "{n} results",
    sortLabel: "Sort",
    sortNewest: "Newest",
    sortPriceLow: "Price: low to high",
    sortPriceHigh: "Price: high to low",
    sortMileage: "Lowest mileage",
    filtersOpen: "Filters",
    filtersTitle: "Filters",
    filterApply: "Apply",
    filterReset: "Reset",
    filterPrice: "Price (USD)",
    priceMin: "Min",
    priceMax: "Max",
    filterMake: "Make",
    filterModel: "Model",
    filterYear: "Year",
    yearFrom: "From",
    yearTo: "To",
    filterAny: "Any",
    conditionNew: "New",
    conditionUsed: "Used",
    conditionCertified: "Certified",
    filterCondition: "Condition",
    filterSeller: "Seller",
    sellerAll: "All",
    sellerDealer: "Dealership",
    sellerPrivate: "Private",
    filterBody: "Body style",
    filterTransmission: "Transmission",
    filterDrivetrain: "Drivetrain",
    filterFuel: "Fuel",
    filterMileage: "Max mileage",
    filterTitle: "Title status",
    filterRadius: "Radius (miles)",
    filterRadiusHint: "Coming soon: search by distance.",
    paginationPrev: "Previous",
    paginationNext: "Next",
    loadMore: "Load more",
    pageOf: "Page {page}",
    cardMonthly: "from {amount}/mo est.",
    cardMi: "mi",
    sellerDealerFooter: "Dealership",
    sellerPrivateFooter: "Private",
    alertCta: "Set alert",
    postAd: "Post a listing",
    viewListings: "View listings",
    hubNote: "Also on Leonix",
  },
} as const;

export type AutosPublicBlueprintCopy = (typeof AUTOS_PUBLIC_BLUEPRINT_COPY)[AutosPublicLang];
