/** Preset highlights: keys match `highlightPresets` in form state. */
export const BR_HIGHLIGHT_PRESET_DEFS: Array<{ key: string; label: string }> = [
  { key: "piscina", label: "Alberca / piscina" },
  { key: "cocinaRemodelada", label: "Cocina remodelada" },
  { key: "electrodomesticosLujo", label: "Electrodomésticos de lujo" },
  { key: "patio", label: "Patio" },
  { key: "balcon", label: "Balcón" },
  { key: "vista", label: "Vista" },
  { key: "comunidadCerrada", label: "Comunidad cerrada" },
  { key: "techosAltos", label: "Techos altos" },
  { key: "cuartoPrincipalGrande", label: "Recámara principal amplia" },
  { key: "walkInCloset", label: "Walk-in closet" },
  { key: "oficinaEnCasa", label: "Oficina en casa" },
  { key: "panelesSolares", label: "Paneles solares" },
  { key: "smartHome", label: "Smart home" },
  { key: "chimenea", label: "Chimenea" },
  { key: "lavanderia", label: "Lavandería" },
  { key: "estacionamientoTechado", label: "Estacionamiento techado" },
  { key: "accesoControlado", label: "Acceso controlado" },
  { key: "elevador", label: "Elevador" },
  { key: "terraza", label: "Terraza" },
  { key: "gimnasio", label: "Gimnasio" },
  { key: "amenidadesDesarrollo", label: "Amenidades del desarrollo" },
];
