import type { Lang } from "@/app/clasificados/config/clasificadosHub";

export const BUSCO_FORM_COPY = {
  es: {
    pageSubtitle: "Completa los datos de tu solicitud y revisa la vista previa antes de publicar.",
    sections: {
      main: "Tu solicitud",
      location: "Ubicación aproximada",
      budgetUrgency: "Presupuesto y urgencia",
      contact: "Contacto",
      socials: "Redes o enlace de contacto opcional",
      media: "Imagen de referencia",
    },
    fields: {
      type: "Tipo de búsqueda",
      typeOther: "¿Qué buscas?",
      title: "Título",
      description: "Descripción breve",
      city: "Ciudad",
      state: "Estado / Región",
      country: "País",
      zip: "Código postal",
      zone: "Zona / barrio / última ubicación",
      budget: "Presupuesto aproximado",
      urgency: "Urgencia",
      phone: "Teléfono para llamadas",
      whatsapp: "WhatsApp",
      smsPhone: "Mensaje de texto",
      email: "Correo electrónico",
      preferredContact: "Método preferido de contacto",
      facebook: "Facebook",
      instagram: "Instagram",
      tiktok: "TikTok",
      otherContactLabel: "Etiqueta del enlace",
      otherContactUrl: "URL del enlace",
      image: "Imagen de referencia",
    },
    urgencyOptions: {
      normal: "Normal",
      pronto: "Pronto",
      urgente: "Urgente",
    },
    preferredContactOptions: {
      telefono: "Teléfono",
      whatsapp: "WhatsApp",
      mensaje: "Mensaje",
      correo: "Correo",
    },
    locationPrivacyWarning: "No publiques tu dirección privada. Usa una ciudad, zona o punto de referencia.",
    imageHint: "Una imagen máximo. JPG, PNG o WebP.",
    imageHelperText: "Agrega una imagen si ayuda a identificar lo que buscas.",
    imageRemove: "Quitar imagen",
    previewCta: "Ver vista previa",
    gateFail: "Completa lo siguiente para continuar:",
    contactHint: "Indica al menos teléfono/WhatsApp o correo para que te puedan contactar.",
    socialsIntro: "Solo se mostrarán los enlaces que completes.",
    otherLinkHint: "Ej. Telegram, sitio web, Linktree",
  },
  en: {
    pageSubtitle: "Fill in your request details and review the preview before publishing.",
    sections: {
      main: "Your request",
      location: "Approximate location",
      budgetUrgency: "Budget and urgency",
      contact: "Contact",
      socials: "Optional social/contact link",
      media: "Reference image",
    },
    fields: {
      type: "Request type",
      typeOther: "What are you looking for?",
      title: "Title",
      description: "Short description",
      city: "City",
      state: "State / Region",
      country: "Country",
      zip: "ZIP / Postal code",
      zone: "Area / neighborhood / last known location",
      budget: "Approximate budget",
      urgency: "Urgency",
      phone: "Phone for calls",
      whatsapp: "WhatsApp",
      smsPhone: "Text message",
      email: "Email",
      preferredContact: "Preferred contact method",
      facebook: "Facebook",
      instagram: "Instagram",
      tiktok: "TikTok",
      otherContactLabel: "Link label",
      otherContactUrl: "Link URL",
      image: "Reference image",
    },
    urgencyOptions: {
      normal: "Normal",
      pronto: "Soon",
      urgente: "Urgent",
    },
    preferredContactOptions: {
      telefono: "Phone",
      whatsapp: "WhatsApp",
      mensaje: "Message",
      correo: "Email",
    },
    locationPrivacyWarning: "Do not post your private home address. Use a city, area, or nearby landmark.",
    imageHint: "One image max. JPG, PNG, or WebP.",
    imageHelperText: "Add an image if it helps identify what you are looking for.",
    imageRemove: "Remove image",
    previewCta: "View preview",
    gateFail: "Complete the following to continue:",
    contactHint: "Provide at least phone/WhatsApp or email so people can reach you.",
    socialsIntro: "Only filled links will be shown publicly.",
    otherLinkHint: "e.g. Telegram, website, Linktree",
  },
} as const;

export function buscoFormCopy(lang: Lang) {
  return BUSCO_FORM_COPY[lang];
}
