import type { Lang } from "@/app/clasificados/config/clasificadosHub";

export const BUSCO_FORM_COPY = {
  es: {
    pageSubtitle: "Completa los datos de tu solicitud y revisa la vista previa antes de publicar.",
    sections: {
      main: "Tu solicitud",
      media: "Imagen de referencia",
      location: "Ubicación aproximada",
      budgetUrgency: "Presupuesto y urgencia",
      details: "Detalles de tu búsqueda",
      contact: "Contacto",
      socials: "Redes o enlace de contacto opcional",
    },
    fields: {
      type: "Tipo de búsqueda",
      typeOther: "¿Qué buscas?",
      title: "Título",
      description: "Descripción breve",
      city: "Ciudad",
      state: "Estado / Región",
      country: "País",
      zip: "Código postal",
      zone: "Zona / barrio / última ubicación",
      budgetMode: "Presupuesto",
      budgetAmount: "Monto",
      urgency: "Urgencia",
      preferredCondition: "Condición preferida (opcional)",
      workType: "Tipo de trabajo",
      workSkills: "Habilidades / experiencia",
      workAvailability: "Disponibilidad",
      transportOrigin: "Origen aproximado",
      transportDestination: "Destino aproximado",
      volunteersCount: "Voluntarios necesarios (aprox.)",
      whenNeeded: "¿Cuándo?",
      phone: "Teléfono para llamadas",
      whatsapp: "WhatsApp",
      smsPhone: "Mensaje de texto",
      email: "Correo electrónico",
      facebook: "Facebook",
      instagram: "Instagram",
      tiktok: "TikTok",
      youtube: "YouTube",
      otherContactLabel: "Etiqueta del enlace",
      otherContactUrl: "URL del enlace",
      image: "Imagen de referencia",
    },
    locationPrivacyWarning: "No publiques tu dirección privada. Usa una ciudad, zona o punto de referencia.",
    imageHint: "Una imagen máximo. JPG, PNG o WebP.",
    imageHelperText: "Agrega una imagen si ayuda a identificar lo que buscas.",
    imageRemove: "Quitar imagen",
    previewCta: "Vista previa",
    gateFail: "Completa lo siguiente para continuar:",
    contactHint: "Indica al menos un teléfono, mensaje de texto, WhatsApp o correo para que te puedan contactar.",
    socialsIntro: "Solo se mostrarán los enlaces que completes.",
    otherLinkHint: "Ej. Telegram, sitio web, Linktree",
    workNote: "No es un anuncio de empleador — es tu solicitud de trabajo o trabajo extra.",
  },
  en: {
    pageSubtitle: "Fill in your request details and review the preview before publishing.",
    sections: {
      main: "Your request",
      media: "Reference image",
      location: "Approximate location",
      budgetUrgency: "Budget and urgency",
      details: "Details of your request",
      contact: "Contact",
      socials: "Optional social/contact link",
    },
    fields: {
      type: "Request type",
      typeOther: "What are you looking for?",
      title: "Title",
      description: "Short description",
      city: "City",
      state: "State / Region",
      country: "Country",
      zip: "ZIP / Postal code",
      zone: "Area / neighborhood / last known location",
      budgetMode: "Budget",
      budgetAmount: "Amount",
      urgency: "Urgency",
      preferredCondition: "Preferred condition (optional)",
      workType: "Type of work",
      workSkills: "Skills / experience",
      workAvailability: "Availability",
      transportOrigin: "Approximate origin",
      transportDestination: "Approximate destination",
      volunteersCount: "Volunteers needed (approx.)",
      whenNeeded: "When?",
      phone: "Phone for calls",
      whatsapp: "WhatsApp",
      smsPhone: "Text message",
      email: "Email",
      facebook: "Facebook",
      instagram: "Instagram",
      tiktok: "TikTok",
      youtube: "YouTube",
      otherContactLabel: "Link label",
      otherContactUrl: "Link URL",
      image: "Reference image",
    },
    locationPrivacyWarning: "Do not post your private home address. Use a city, area, or nearby landmark.",
    imageHint: "One image max. JPG, PNG, or WebP.",
    imageHelperText: "Add an image if it helps identify what you are looking for.",
    imageRemove: "Remove image",
    previewCta: "Preview",
    gateFail: "Complete the following to continue:",
    contactHint: "Provide at least a phone, text, WhatsApp, or email so people can reach you.",
    socialsIntro: "Only filled links will be shown publicly.",
    otherLinkHint: "e.g. Telegram, website, Linktree",
    workNote: "Not an employer job posting — this is your request for work or side work.",
  },
} as const;

export function buscoFormCopy(lang: Lang) {
  return BUSCO_FORM_COPY[lang];
}
