import type { ComidaLocalDraft } from "./comidaLocalTypes";

/** Safe empty draft — no fake URLs, cities, or contact data. */
export function createEmptyComidaLocalDraft(): ComidaLocalDraft {
  return {
    draftListingId: "",
    businessName: "",
    foodType: "",
    foodTypeCustom: "",
    businessType: "",
    businessTypeCustom: "",
    cityCanonical: "",
    cityDisplay: "",
    zoneNote: "",
    primaryContactChoice: "",
    phone: "",
    whatsapp: "",
    email: "",
    queVendes: "",
    instagramUrl: "",
    facebookUrl: "",
    tiktokUrl: "",
    locationNote: "",
    locationUrl: "",
    availabilityNote: "",
    weeklyHours: {},
    serviceOptions: [],
    serviceOptionOtherCustom: "",
    businessAddressLine: "",
    showAddressPublicly: false,
    paymentMethods: [],
    paymentOtherNote: "",
    priceLevel: "",
    languages: [],
    customLanguages: [],
    highlights: [],
    highlightsOtherCustom: "",
    additionalWebsites: [],
    mainPhoto: null,
    logoImage: null,
    galleryImages: [],
  };
}
