/** Spanish (default) strings — BR Negocio agente individual residencial publish + preview chrome. */
export const BR_COPY_ES = {
  stepLabels: [
    "Tipo de anuncio",
    "Información básica",
    "Fotos y medios",
    "Detalles esenciales",
    "Características destacadas",
    "Descripción",
    "Información profesional",
    "Contacto y enlaces",
    "Extras opcionales",
    "Vista previa",
  ],
  app: {
    kicker: "Leonix Clasificados · Negocio",
    title: "Publicar Bienes Raíces — Agente",
    subtitle:
      "Leonix es una vitrina premium: el listado oficial sigue en tu MLS o sitio web. Completa los pasos y revisa la vista previa fija antes de publicar.",
    navPasos: "Pasos",
    cambiarCanal: "Cambiar canal",
    verCategoria: "Ver categoría BR",
    pasoDe: "Paso",
    de: "de",
    anterior: "Anterior",
    siguiente: "Siguiente",
    vistaPreviaTitulo: "Vista previa",
    vistaPreviaBody:
      "Abre la vista previa con tus datos actuales. Puedes volver a editar sin perder el borrador en esta sesión.",
    verVistaPrevia: "Ver vista previa",
  },
  step01: {
    title: "Tipo de anuncio",
    sub: "Residencial en Leonix: una vitrina clara para compradores. Esta ruta es solo venta.",
    tipoPublicacion: "Tipo de publicación",
    tipoPublicacionHint: "Fijo en esta variante: solo venta residencial.",
    ventaResidencial: "Venta residencial",
    tipoPropiedad: "Tipo de propiedad",
    especificaTipo: "Especifica el tipo de propiedad",
    especificaTipoHint: "Se muestra en el anuncio como tipo de propiedad.",
    subtipo: "Subtipo (opcional)",
    subtipoHint: "Detalle según el tipo elegido (por ejemplo penthouse o planta baja). No es obligatorio.",
    detalleAdicional: "Detalle adicional (opcional)",
    detalleAdicionalHint: "Si quieres añadir una nota corta sobre el tipo o la distribución.",
  },
  step02: {
    title: "Información básica",
    sub: "Datos que verán primero los compradores en la vista previa.",
    titulo: "Título del anuncio",
    precio: "Precio",
    precioHint: "Usa números; en la vista previa se muestra en dólares.",
    estadoAnuncio: "Estado del anuncio",
    estadoAnuncioHint: "Indica si sigue disponible, pendiente, bajo contrato o vendido.",
    ciudad: "Ciudad",
    ciudadHint: "Lista oficial NorCal: escribe y elige una ciudad; al salir del campo se guarda el nombre canónico.",
    ciudadPlaceholder: "Ej. San Jose, Fremont…",
    area: "Área de la ciudad",
    areaHint: "La zona general donde se ubica la propiedad.",
    direccion: "Dirección",
    direccionHint: "Calle y número; puedes omitir número interior en el anuncio público.",
    listado: "Enlace o archivo del listado",
    listadoHint:
      "Así el comprador puede ver más detalles en tu publicación original sin llenar demasiado este anuncio.",
    pegarUrl: "Pegar URL",
    subirPdf: "Subir PDF o archivo",
    archivo: "Archivo:",
    adjunto: "adjunto",
    quitar: "Quitar",
    estados: { disponible: "Disponible", pendiente: "Pendiente", bajo_contrato: "Bajo contrato", vendido: "Vendido" },
  },
  step03: {
    title: "Fotos y medios",
    sub: "La imagen principal es la portada. Video, tour y folleto se usan en la vista previa cuando activas los botones correspondientes.",
    fotos: "Fotos",
    agregarFotos: "Agregar fotos",
    portada: "Imagen principal (portada)",
    portadaHint: "Elige cuál foto es la portada.",
    fotoN: (n: number) => `Foto ${n}`,
    moverIzq: "Mover izquierda",
    moverDer: "Mover derecha",
    eliminar: "Eliminar",
    archivoSubido: "Archivo subido",
    subirVideo: "Subir video",
    video: "Video (opcional)",
    videoHint:
      "Enlace público (YouTube, Vimeo, etc.) o archivo de video breve para la vista previa. No se sube a Mux hasta publicar.",
    tour: "Tour virtual / 3D (opcional)",
    tourHint:
      "Enlace a Matterport, tour 360, recorrido virtual o URL pública. También puedes subir un archivo compatible (p. ej. imagen/PDF de portada, video corto, HTML estático) para vista previa local.",
    folleto: "Folleto / documento (opcional)",
    folletoHint:
      "PDF, Word o imagen de folleto/plano. Se enlaza con «Ver folleto» en la vista previa. Tipos permitidos: PDF, DOC/DOCX, JPG/PNG.",
  },
  step04: {
    title: "Detalles esenciales",
    sub: "Sólo lo que ayuda al comprador a decidir.",
    recamaras: "Recámaras",
    banos: "Baños completos",
    mediosBanos: "Medios baños",
    mediosHint: "Opcional.",
    tamanoInterior: "Tamaño interior",
    tamanoInteriorHint: "Pies cuadrados aproximados.",
    tamanoLote: "Tamaño del lote",
    tamanoLoteHint: "Si aplica; si no, déjalo vacío.",
    estacionamientos: "Estacionamientos",
    ano: "Año de construcción",
    condicion: "Condición de la propiedad",
    condicionHint: "Estado general al momento de publicar.",
  },
  step05: {
    title: "Características destacadas",
    sub: "Marca lo que quieres mostrar en la vista previa.",
  },
  step06: {
    title: "Descripción",
    principal: "Descripción principal",
    notas: "Notas adicionales (opcional)",
    notasHint: "Mensaje corto o detalle interno; no es el cuerpo principal.",
  },
  step07: {
    title: "Información profesional",
    sub: "Cada campo corresponde a un espacio fijo en la vista previa.",
    agente: "Agente",
    fotoAgente: "Foto del agente",
    fotoAgenteHint: "Sube una imagen o pega una URL pública.",
    nombre: "Nombre completo",
    titulo: "Título",
    licencia: "Licencia o número profesional",
    licenciaHint: "Si aplica en tu estado.",
    mostrarMarca: "Mostrar oficina o marca en la tarjeta",
    mostrarMarcaHint: "Si está desactivado, la vista previa no muestra el bloque de marca aunque haya datos guardados.",
    oficina: "Oficina o marca",
    nombreMarca: "Nombre de oficina o marca",
    logo: "Logo de oficina o marca",
    logoHint: "Imagen o URL; se muestra arriba de tu foto en la vista previa.",
    licenciaMarca: "Licencia de broker u oficina (opcional)",
    sitioMarca: "Sitio web de oficina o marca (opcional)",
    sitioMarcaHint: "Enlace breve bajo el nombre de la marca en la tarjeta.",
    redes: "Redes sociales",
    redesSub: "Un enlace por red; cada icono en la vista previa usa solo su campo.",
    subirImagen: "Subir imagen",
    pegarUrlImagen: "Pegar URL de imagen",
    subirArchivo: "Subir archivo",
    pegarUrl: "Pegar URL",
    instagram: "Instagram",
    facebook: "Facebook",
    youtube: "YouTube",
    tiktok: "TikTok",
    x: "X / Twitter",
    otroSocial: "Otro enlace social (opcional)",
    areaServicio: "Área de servicio (opcional)",
    idiomas: "Idiomas (opcional)",
    idiomasPh: "Ej. inglés y español",
    segundoAgente: "Segundo agente",
    agente2Foto: "Foto del segundo agente",
    agente2FotoHint: "Sube una imagen o pega una URL pública.",
    agente2Nombre: "Nombre completo",
    agente2Titulo: "Título",
    agente2Licencia: "Licencia o número profesional",
    agente2Telefono: "Teléfono (opcional)",
    agente2Correo: "Correo (opcional)",
    agregarSegundoAgente: "Agregar segundo agente",
    ocultarSegundoAgente: "Ocultar",
    agregarBrokerAsesor: "Agregar broker / asesor",
    ocultarBrokerAsesor: "Ocultar",
    brokerSection: "Broker / asesor",
    brokerNombre: "Nombre",
    brokerTitulo: "Título o rol",
    brokerLicencia: "Licencia o número",
    brokerTelefono: "Teléfono",
    brokerEmail: "Correo electrónico",
    brokerSitioWeb: "Sitio web",
    brokerSitioWebHint: "Opcional",
    brokerInstagram: "Instagram",
    brokerFacebook: "Facebook",
    brokerYoutube: "YouTube",
    brokerTiktok: "TikTok",
    brokerX: "X / Twitter",
    brokerOtro: "Otro enlace",
  },
  step08: {
    title: "Contacto y enlaces",
    sub: "Los interruptores activan el botón; el destino concreto viene del campo correspondiente. Sin destino válido, el botón no aparece en la vista previa.",
    contactoBase: "Contacto base (tarjeta)",
    telefono: "Teléfono principal",
    telefonoHint: "Se muestra en la tarjeta y sirve de respaldo si un destino de llamada va vacío.",
    correo: "Correo electrónico principal",
    correoHint: "Se muestra en la tarjeta y sirve de respaldo para «Solicitar información».",
    destinos: "Destinos de los botones",
    destinosSub:
      "Cada botón usa solo su campo. Donde no indiques un valor, el mapa aplica respaldos (teléfono/correo principal, listado de información básica o archivos de la galería); está documentado en el código del mapa.",
    numLlamadas: "Número para llamadas",
    numLlamadasHint: "Si vacío: teléfono principal.",
    numWa: "Número para WhatsApp",
    numWaHint: "Si vacío: teléfono principal.",
    correoInfo: "Correo para solicitar información",
    correoInfoHint: "Si vacío: correo principal.",
    enlaceVisita: "Enlace para programar visita",
    enlaceVisitaHint: "Calendly u otro enlace https. Sin enlace, no hay botón.",
    enlaceWeb: "Enlace del sitio web",
    enlaceWebHint: "Botón «Ver sitio web». Si vacío: sitio de oficina o marca (paso anterior).",
    enlaceListado: "Enlace del MLS o listado completo",
    enlaceListadoHint: "Si vacío: listado de «Información básica».",
    enlaceMls: "Enlace MLS (destino propio)",
    enlaceMlsHint: "Si vacío: mismo destino que «listado completo» o listado básico.",
    enlaceTour: "Enlace del tour",
    enlaceTourHint: "Si vacío: tour de «Fotos y medios».",
    enlaceFolleto: "Enlace del folleto",
    enlaceFolletoHint: "Si vacío: folleto de «Fotos y medios».",
    interruptores: "Interruptores",
    interruptoresSub: "«Mostrar iconos de redes» requiere al menos un enlace en el paso de redes.",
    ctaSolicitar: "Solicitar información",
    ctaVisita: "Programar visita",
    ctaLlamar: "Llamar",
    ctaWa: "WhatsApp",
    ctaWeb: "Ver sitio web",
    ctaRedes: "Mostrar iconos de redes",
    ctaListado: "Ver listado completo",
    ctaMls: "Ver MLS",
    ctaTour: "Ver tour",
    ctaFolleto: "Ver folleto",
  },
  step09: {
    title: "Extras opcionales",
    sub: "Opcional; sólo aparece en la vista previa si hay datos.",
    openHouse: "Open house",
    fecha: "Fecha",
    horaInicio: "Hora inicio",
    horaFin: "Hora fin",
    notasOh: "Notas",
    agregarOpenHouse: "Agregar fecha de open house",
    eliminarFecha: "Quitar esta fecha",
    asesorFin: "Asesor financiero",
    nombreAsesor: "Nombre",
    telAsesor: "Teléfono",
    correoAsesor: "Correo del asesor",
  },
  previewUi: {
    meta: "Vista previa del anuncio",
    badge: "Vista previa · Negocio",
    volverEditar: "Volver a editar",
    galeria: "Galería",
    fotoPrincipal: "Foto principal",
    foto2: "Foto 2",
    foto3: "Foto 3",
    video: "Video",
    reproducirVideo: "Reproducir video",
    tourVirtual: "Tour virtual",
    planoFolleto: "Plano / folleto",
    tourPlano: "Tour / plano",
    abrirTour: "Abrir tour",
    abrirPlano: "Abrir plano / folleto",
    verTodasFotos: (n: number) => `Ver todas las fotos (${n})`,
    slotPrincipal: "Foto principal",
    slotPrincipalSub: "Agrega fotos en el formulario.",
    slot2: "Foto 2",
    opcional: "Opcional",
    slotVideoTitle: "Video",
    slotVideoSub: "Pega un enlace o sube un archivo.",
    slotTour: "Tour / plano",
    slotTourSub: "Enlace o archivo (tour o folleto).",
    verMapa: "Ver en mapa",
    fotoAgente: "Foto del agente",
    sitioWeb: "Sitio web",
    area: "Área:",
    idiomas: "Idiomas:",
    llamar: "Llamar ahora",
    whatsapp: "WhatsApp",
    solicitarInfo: "Solicitar información",
    programarVisita: "Programar visita",
    verSitioWeb: "Ver sitio web",
    verListado: "Ver listado completo",
    verMls: "Ver MLS",
    verTour: "Ver tour",
    verFolleto: "Ver folleto",
    brokerAsesor: "Broker / asesor",
    detallesPropiedad: "Detalles de la propiedad",
    caracteristicas: "Características destacadas",
    descripcion: "Descripción",
    notasAdicionales: "Notas adicionales",
    masInfo: "Más información",
    openHouse: "Open house",
    contactoFin: "Contacto de financiamiento",
    ubicacionAprox: "Ubicación aproximada",
    abrirMapa: "Abrir en mapa",
    emptySlotPdf: "archivo.pdf",
    licenciaAgente: "Licencia o número profesional:",
    licenciaMarca: "Licencia de oficina:",
    enlaceGenerico: "Enlace",
    notaVerTodasFotos: "En el anuncio publicado, este control abre la galería completa.",
    lightboxClose: "Cerrar",
    lightboxPrev: "Anterior",
    lightboxNext: "Siguiente",
    lightboxVideo: "Video",
    lightboxZoomHint: "Ctrl + rueda para ampliar",
    lightboxResetZoom: "Restablecer",
    lightboxOpenVideoTab: "Abrir video en una pestaña nueva",
    lightboxGalleryCount: (cur: number, total: number) => `Galería · ${cur} / ${total}`,
    footerDefault:
      "Leonix es una vitrina premium: el listado oficial puede estar en tu MLS o sitio web.",
  },
  previewFormat: {
    opLine: "Venta residencial",
    estados: {
      disponible: "Disponible",
      pendiente: "Pendiente",
      bajo_contrato: "Bajo contrato",
      vendido: "Vendido",
    },
    condicion: {
      excelente: "Excelente",
      buena: "Buena",
      regular: "Regular",
      necesita_reparacion: "Necesita reparación",
    },
    detalleTipo: "Tipo de propiedad",
    detalleRecamaras: "Recámaras",
    detalleBanos: "Baños",
    detalleMedios: "Medios baños",
    detalleInterior: "Tamaño interior",
    detalleLote: "Tamaño del lote",
    detalleEstac: "Estacionamientos",
    detalleAno: "Año de construcción",
    detalleCond: "Condición",
    qfRec: "Recámaras",
    qfBan: "Baños",
    qfInt: "Interior (ft²)",
    qfEst: "Estacionamientos",
    qfAno: "Año",
    qfLote: "Lote (ft²)",
  },
} as const;
