/**
 * CAT-STD-1A — Read-only category pipeline registry for rollout gates.
 * Documentation in code; do not use for runtime routing or filtering.
 */

export type CatStd1aRisk = "LOW" | "MEDIUM" | "HIGH";

export type CatStd1aPipelineEntry = {
  slug: string;
  displayName: string;
  aliasSlugs: string[];
  landingRoute: string;
  landingPageFile: string;
  landingClients: string[];
  resultsRoute: string;
  resultsAliasRoute: string;
  resultsPageFile: string;
  resultsClients: string[];
  listingCards: string[];
  emptyState: string;
  publishRoute: string;
  dataSources: string[];
  queryParamNotes: string;
  defaultPageSize: number | null;
  perPageParam: string | null;
  standardShellStatus: "full" | "partial" | "custom";
  risk: CatStd1aRisk;
};

/** Twelve marketplace pipelines under `/clasificados` (+ iglesias separate). */
export const CAT_STD_1A_PIPELINES: readonly CatStd1aPipelineEntry[] = [
  {
    slug: "en-venta",
    displayName: "En Venta / Varios",
    aliasSlugs: ["varios", "for-sale"],
    landingRoute: "/clasificados/en-venta",
    landingPageFile: "app/(site)/clasificados/en-venta/page.tsx",
    landingClients: ["EnVentaHubPageClient.tsx", "CategoryStandardLandingBlock"],
    resultsRoute: "/clasificados/en-venta/results",
    resultsAliasRoute: "(none — results only, no resultados re-export)",
    resultsPageFile: "app/(site)/clasificados/en-venta/results/page.tsx",
    resultsClients: ["EnVentaResultsClient.tsx", "EnVentaResultsChipsRow.tsx", "EnVentaResultsListingSections.tsx"],
    listingCards: ["EnVentaResultListingCard.tsx"],
    emptyState: "EnVentaResultsEmpty.tsx",
    publishRoute: "/clasificados/publicar/en-venta",
    dataSources: ["queryEnVentaBrowseListings (Supabase listings, cap 800)", "fetchEnVentaPublicListingsForBrowse (hub SSR)"],
    queryParamNotes: "EV_RESULTS_PARAM: lang,q,city,zip,evDept,evSub,cond,priceMin,priceMax,pickup,ship,delivery,seller,free,nego,meetup,sort,view,page,featured",
    defaultPageSize: 24,
    perPageParam: null,
    standardShellStatus: "partial",
    risk: "MEDIUM",
  },
  {
    slug: "rentas",
    displayName: "Rentas",
    aliasSlugs: [],
    landingRoute: "/clasificados/rentas",
    landingPageFile: "app/(site)/clasificados/rentas/page.tsx",
    landingClients: ["RentasLandingHub.tsx"],
    resultsRoute: "/clasificados/rentas/results",
    resultsAliasRoute: "/clasificados/rentas/resultados (re-export if present)",
    resultsPageFile: "app/(site)/clasificados/rentas/results/page.tsx",
    resultsClients: ["RentasResultsClient.tsx", "RentasResultsTopBar.tsx"],
    listingCards: ["Rentas result cards inline in RentasResultsClient"],
    emptyState: "Inline empty in RentasResultsClient",
    publishRoute: "/clasificados/publicar/rentas",
    dataSources: ["rentasListingPublicSelect (Supabase, cap 5000)", "fetchRentasPublicListingsForBrowse"],
    queryParamNotes: "RENTAS_QUERY_* via rentasBrowseContract — q,city,zip,tipo,rentMin/Max,page,sort,lat,lng,radiusKm,…",
    defaultPageSize: 6,
    perPageParam: null,
    standardShellStatus: "partial",
    risk: "HIGH",
  },
  {
    slug: "empleos",
    displayName: "Empleos",
    aliasSlugs: [],
    landingRoute: "/clasificados/empleos",
    landingPageFile: "app/(site)/clasificados/empleos/page.tsx",
    landingClients: ["EmpleosLandingServer.tsx", "EmpleosLandingPageClient.tsx"],
    resultsRoute: "/clasificados/empleos/results",
    resultsAliasRoute: "/clasificados/empleos/resultados",
    resultsPageFile: "app/(site)/clasificados/empleos/resultados/page.tsx (results/ re-exports)",
    resultsClients: ["EmpleosResultsView.tsx"],
    listingCards: ["EmpleosJobResultCard.tsx"],
    emptyState: "Inline empty + recovery in EmpleosResultsView",
    publishRoute: "/clasificados/publicar/empleos",
    dataSources: ["/api/clasificados/empleos/listings", "mergeEmpleosSeedWithLiveJobs"],
    queryParamNotes: "q,city,state,zip,category,jobType,modality,salaryMin/Max,experience,featured,recent,quickApply,sort,lane — no page param",
    defaultPageSize: null,
    perPageParam: null,
    standardShellStatus: "partial",
    risk: "HIGH",
  },
  {
    slug: "autos",
    displayName: "Autos",
    aliasSlugs: [],
    landingRoute: "/clasificados/autos",
    landingPageFile: "app/(site)/clasificados/autos/page.tsx",
    landingClients: ["AutosPublicLanding.tsx", "AutosLandingPage.tsx", "AutosHeroSearch.tsx"],
    resultsRoute: "/clasificados/autos/results",
    resultsAliasRoute: "/clasificados/autos/resultados",
    resultsPageFile: "app/(site)/clasificados/autos/resultados/page.tsx (results/ re-exports)",
    resultsClients: ["AutosPublicResultsShell.tsx", "AutosPublicFilterRail.tsx"],
    listingCards: ["AutosPublicFeaturedCard.tsx", "AutosPublicStandardCard.tsx"],
    emptyState: "Inline in AutosPublicResultsShell",
    publishRoute: "/clasificados/publicar/autos",
    dataSources: ["useAutosPublicListingsFetch (client)"],
    queryParamNotes: "AUTOS_BROWSE_URL_KEYS — radiusMiles scaffolded not applied in filters yet",
    defaultPageSize: 12,
    perPageParam: null,
    standardShellStatus: "partial",
    risk: "HIGH",
  },
  {
    slug: "bienes-raices",
    displayName: "Bienes Raíces",
    aliasSlugs: [],
    landingRoute: "/clasificados/bienes-raices",
    landingPageFile: "app/(site)/clasificados/bienes-raices/page.tsx",
    landingClients: ["BienesRaicesLandingHub.tsx", "BienesRaicesLandingView.tsx"],
    resultsRoute: "/clasificados/bienes-raices/results",
    resultsAliasRoute: "/clasificados/bienes-raices/resultados",
    resultsPageFile: "app/(site)/clasificados/bienes-raices/resultados/page.tsx",
    resultsClients: ["BienesRaicesResultsClient.tsx"],
    listingCards: ["BienesRaicesNegocioCard.tsx", "BienesRaicesNegocioFeaturedCard.tsx"],
    emptyState: "Inline in BienesRaicesResultsClient",
    publishRoute: "/clasificados/publicar/bienes-raices",
    dataSources: ["fetchBrPublishedListingsForBrowse", "brDemoListingPool merge"],
    queryParamNotes: "buildBrResultsUrl / brResultsFilters — operationType,city,propiedad,page,sort,…",
    defaultPageSize: 9,
    perPageParam: null,
    standardShellStatus: "partial",
    risk: "HIGH",
  },
  {
    slug: "servicios",
    displayName: "Servicios",
    aliasSlugs: [],
    landingRoute: "/clasificados/servicios",
    landingPageFile: "app/(site)/clasificados/servicios/page.tsx",
    landingClients: ["ServiciosLandingPage.tsx", "ServiciosHeroSearch.tsx"],
    resultsRoute: "/clasificados/servicios/results",
    resultsAliasRoute: "/clasificados/servicios/resultados",
    resultsPageFile: "app/(site)/clasificados/servicios/resultados/page.tsx (RSC server page)",
    resultsClients: ["ServiciosResultsPageShell.tsx (layout)", "ServiciosHorizontalResultCard.tsx"],
    listingCards: ["ServiciosHorizontalResultCard.tsx"],
    emptyState: "Inline in servicios resultados page/shell",
    publishRoute: "/clasificados/publicar/servicios",
    dataSources: ["listServiciosPublicListingsRaw", "serviciosPublicListingsServer"],
    queryParamNotes: "ServiciosResultsFilterQuery — q,city,group,seller,sort,verified,whatsapp,… (no page)",
    defaultPageSize: null,
    perPageParam: null,
    standardShellStatus: "partial",
    risk: "MEDIUM",
  },
  {
    slug: "restaurantes",
    displayName: "Restaurantes",
    aliasSlugs: [],
    landingRoute: "/clasificados/restaurantes",
    landingPageFile: "app/(site)/clasificados/restaurantes/page.tsx",
    landingClients: ["RestaurantesLandingPage.tsx"],
    resultsRoute: "/clasificados/restaurantes/results",
    resultsAliasRoute: "/clasificados/restaurantes/resultados",
    resultsPageFile: "app/(site)/clasificados/restaurantes/resultados/page.tsx",
    resultsClients: ["RestaurantesResultsShell.tsx"],
    listingCards: ["RestaurantePublishedListingCard.tsx"],
    emptyState: "Inline in RestaurantesResultsShell",
    publishRoute: "/clasificados/restaurantes/publicar",
    dataSources: ["restaurantesResultsInventoryServer", "restaurantesDiscoveryContract"],
    queryParamNotes: "q,city,zip,cuisine,service,sort — load-more via visible state (PAGE_SIZE 9)",
    defaultPageSize: 9,
    perPageParam: null,
    standardShellStatus: "partial",
    risk: "MEDIUM",
  },
  {
    slug: "comunidad",
    displayName: "Comunidad y Eventos",
    aliasSlugs: ["comunidad-y-eventos (label only)"],
    landingRoute: "/clasificados/comunidad",
    landingPageFile: "app/(site)/clasificados/comunidad/page.tsx",
    landingClients: ["CategoryStandardLandingPage (inline in page.tsx)"],
    resultsRoute: "/clasificados/comunidad/results",
    resultsAliasRoute: "/clasificados/comunidad/resultados",
    resultsPageFile: "app/(site)/clasificados/comunidad/resultados/page.tsx",
    resultsClients: ["CommunityListingsResultsClient.tsx"],
    listingCards: ["CommunityDiscoveryListingCard.tsx"],
    emptyState: "Inline in CommunityListingsResultsClient",
    publishRoute: "/clasificados/publicar/comunidad",
    dataSources: ["fetchPublishedCommunityCategoryListings (limit 160)"],
    queryParamNotes: "q,city,cost,mode,eventCost,eventType,dateFrom,dateTo,audience,registration,accessibility,level",
    defaultPageSize: null,
    perPageParam: null,
    standardShellStatus: "full",
    risk: "LOW",
  },
  {
    slug: "clases",
    displayName: "Clases",
    aliasSlugs: [],
    landingRoute: "/clasificados/clases",
    landingPageFile: "app/(site)/clasificados/clases/page.tsx",
    landingClients: ["CategoryStandardLandingPage (inline in page.tsx)"],
    resultsRoute: "/clasificados/clases/results",
    resultsAliasRoute: "/clasificados/clases/resultados",
    resultsPageFile: "app/(site)/clasificados/clases/resultados/page.tsx",
    resultsClients: ["CommunityListingsResultsClient.tsx (category=clases)"],
    listingCards: ["CommunityDiscoveryListingCard.tsx"],
    emptyState: "Inline in CommunityListingsResultsClient",
    publishRoute: "/clasificados/publicar/clases",
    dataSources: ["fetchPublishedCommunityCategoryListings (limit 160)"],
    queryParamNotes: "q,city,classType,level,cost,mode,audience,registration,accessibility",
    defaultPageSize: null,
    perPageParam: null,
    standardShellStatus: "full",
    risk: "LOW",
  },
  {
    slug: "busco",
    displayName: "Busco / Se busca",
    aliasSlugs: ["se-busca (label)"],
    landingRoute: "/clasificados/busco",
    landingPageFile: "app/(site)/clasificados/busco/page.tsx",
    landingClients: ["CategoryStandardLandingPage", "BuscoLandingRecentListings.tsx"],
    resultsRoute: "/clasificados/busco/results",
    resultsAliasRoute: "/clasificados/busco/resultados",
    resultsPageFile: "app/(site)/clasificados/busco/resultados/page.tsx",
    resultsClients: ["BuscoResultsClient.tsx"],
    listingCards: ["BuscoRequestCard.tsx"],
    emptyState: "COPY.emptyTitle/emptyBody in BuscoResultsClient",
    publishRoute: "/publicar/busco/quick",
    dataSources: ["fetchPublishedBuscoListings (client)"],
    queryParamNotes: "q,tipo,city,zone,budget,contact — no pagination",
    defaultPageSize: null,
    perPageParam: null,
    standardShellStatus: "full",
    risk: "LOW",
  },
  {
    slug: "mascotas-y-perdidos",
    displayName: "Mascotas y Perdidos",
    aliasSlugs: [],
    landingRoute: "/clasificados/mascotas-y-perdidos",
    landingPageFile: "app/(site)/clasificados/mascotas-y-perdidos/page.tsx",
    landingClients: ["CategoryStandardLandingPage", "MascotasPerdidosLandingRecentListings.tsx"],
    resultsRoute: "/clasificados/mascotas-y-perdidos/results",
    resultsAliasRoute: "/clasificados/mascotas-y-perdidos/resultados",
    resultsPageFile: "app/(site)/clasificados/mascotas-y-perdidos/resultados/page.tsx",
    resultsClients: ["MascotasPerdidosResultsClient.tsx"],
    listingCards: ["MascotasPerdidosNoticeCard.tsx"],
    emptyState: "COPY.emptyTitle/emptyBody in MascotasPerdidosResultsClient",
    publishRoute: "/clasificados/publicar/mascotas-y-perdidos",
    dataSources: ["fetchPublishedMascotasPerdidosListings (limit 160)"],
    queryParamNotes: "q,tipo,city — no pagination",
    defaultPageSize: null,
    perPageParam: null,
    standardShellStatus: "full",
    risk: "LOW",
  },
  {
    slug: "viajes",
    displayName: "Viajes",
    aliasSlugs: ["travel (legacy folder app/clasificados/travel)"],
    landingRoute: "/clasificados/viajes",
    landingPageFile: "app/(site)/clasificados/viajes/page.tsx",
    landingClients: ["ViajesLandingPage.tsx", "ViajesSearchBar.tsx"],
    resultsRoute: "/clasificados/viajes/results",
    resultsAliasRoute: "/clasificados/viajes/resultados",
    resultsPageFile: "app/(site)/clasificados/viajes/resultados/page.tsx",
    resultsClients: ["ViajesResultsShell.tsx"],
    listingCards: ["Viajes result rows in ViajesResultsShell"],
    emptyState: "Inline in ViajesResultsShell",
    publishRoute: "/clasificados/publicar/viajes",
    dataSources: ["fetchViajesPublicBrowseRowsMerged", "viajesStagedListingsDbServer"],
    queryParamNotes: "viajesBrowseContract — dest,q,from,t,budget,audience,sort,lang",
    defaultPageSize: null,
    perPageParam: null,
    standardShellStatus: "partial",
    risk: "MEDIUM",
  },
] as const;

export const CAT_STD_1A_IGLESIAS: CatStd1aPipelineEntry = {
  slug: "iglesias",
  displayName: "Iglesias",
  aliasSlugs: [],
  landingRoute: "/iglesias",
  landingPageFile: "app/(site)/iglesias/page.tsx",
  landingClients: ["IglesiasPageClient.tsx"],
  resultsRoute: "(none)",
  resultsAliasRoute: "(none)",
  resultsPageFile: "(none)",
  resultsClients: [],
  listingCards: [],
  emptyState: "N/A",
  publishRoute: "(site-section CMS — not clasificados publish)",
  dataSources: ["getSiteSectionPayload(iglesias_page)"],
  queryParamNotes: "lang via shell merge",
  defaultPageSize: null,
  perPageParam: null,
  standardShellStatus: "custom",
  risk: "LOW",
};
