/**
 * CAT-STD-1A — Read-only category pipeline registry for rollout gates.
 * Documentation in code; do not use for runtime routing or filtering.
 */

export type CatStd1aRisk = "LOW" | "MEDIUM" | "HIGH";

export type CatStd1aPipelineEntry = {
  slug: string;
  displayName: string;
  landingRoute: string;
  landingPageFile: string;
  landingClients: string[];
  resultsRoute: string;
  resultsAliasRoute: string;
  resultsPageFile: string;
  resultsClients: string[];
  listingCards: string[];
  publishRoute: string;
  dataSources: string[];
  queryParamNotes: string;
  standardShellStatus: "full" | "partial" | "custom";
  risk: CatStd1aRisk;
};

/** Twelve marketplace pipelines under `/clasificados` (+ iglesias separate). */
export const CAT_STD_1A_PIPELINES: readonly CatStd1aPipelineEntry[] = [
  {
    slug: "en-venta",
    displayName: "En Venta / Varios",
    landingRoute: "/clasificados/en-venta",
    landingPageFile: "app/(site)/clasificados/en-venta/page.tsx",
    landingClients: ["EnVentaHubPageClient.tsx"],
    resultsRoute: "/clasificados/en-venta/results",
    resultsAliasRoute: "/clasificados/en-venta/resultados (if linked)",
    resultsPageFile: "app/(site)/clasificados/en-venta/results/page.tsx",
    resultsClients: ["EnVentaResultsClient.tsx"],
    listingCards: ["EnVenta listing cards in results grid"],
    publishRoute: "/clasificados/publicar/en-venta",
    dataSources: ["fetchEnVentaPublicListingsForBrowse", "getMergedEnVentaHubLanding"],
    queryParamNotes: "lang; browse filters via en-venta results URL helpers",
    standardShellStatus: "partial",
    risk: "MEDIUM",
  },
  {
    slug: "rentas",
    displayName: "Rentas",
    landingRoute: "/clasificados/rentas",
    landingPageFile: "app/(site)/clasificados/rentas/page.tsx",
    landingClients: ["RentasLandingHub.tsx"],
    resultsRoute: "/clasificados/rentas/results",
    resultsAliasRoute: "/clasificados/rentas/resultados",
    resultsPageFile: "app/(site)/clasificados/rentas/results/page.tsx",
    resultsClients: ["RentasResultsClient.tsx", "RentasResultsTopBar.tsx"],
    listingCards: ["Rentas result cards in RentasResultsClient"],
    publishRoute: "/clasificados/publicar/rentas",
    dataSources: ["fetchRentasPublicListingsForBrowse"],
    queryParamNotes: "lang, q, city, zip, tipo, precio, beds, rent min/max, mascotas, page, sort — see rentasResultsQueryKeys.ts",
    standardShellStatus: "partial",
    risk: "HIGH",
  },
  {
    slug: "empleos",
    displayName: "Empleos",
    landingRoute: "/clasificados/empleos",
    landingPageFile: "app/(site)/clasificados/empleos/page.tsx",
    landingClients: ["EmpleosLandingServer.tsx", "EmpleosLandingPageClient.tsx"],
    resultsRoute: "/clasificados/empleos/results",
    resultsAliasRoute: "/clasificados/empleos/resultados",
    resultsPageFile: "app/(site)/clasificados/empleos/resultados/page.tsx (results/ re-exports)",
    resultsClients: ["EmpleosResultsView.tsx"],
    listingCards: ["EmpleosJobResultCard.tsx"],
    publishRoute: "/clasificados/publicar/empleos",
    dataSources: ["/api/clasificados/empleos/listings", "mergeEmpleosSeedWithLiveJobs"],
    queryParamNotes: "q, city, state, zip, category, jobType, modality, salaryMin/Max, experience, featured, recent, sort, lane, …",
    standardShellStatus: "partial",
    risk: "HIGH",
  },
  {
    slug: "autos",
    displayName: "Autos",
    landingRoute: "/clasificados/autos",
    landingPageFile: "app/(site)/clasificados/autos/page.tsx",
    landingClients: ["AutosPublicLanding.tsx", "AutosLandingPage.tsx", "AutosHeroSearch.tsx"],
    resultsRoute: "/clasificados/autos/results",
    resultsAliasRoute: "/clasificados/autos/resultados",
    resultsPageFile: "app/(site)/clasificados/autos/resultados/page.tsx (results/ re-exports)",
    resultsClients: ["AutosPublicResultsShell.tsx", "AutosPublicFilterRail.tsx"],
    listingCards: ["AutosPublicFeaturedCard.tsx", "AutosPublicStandardCard.tsx"],
    publishRoute: "/clasificados/publicar/autos",
    dataSources: ["useAutosPublicListingsFetch"],
    queryParamNotes: "AUTOS_BROWSE_URL_KEYS: lang, q, city, zip, make, model, price, bodyStyle, seller, sort, page, …",
    standardShellStatus: "partial",
    risk: "HIGH",
  },
  {
    slug: "bienes-raices",
    displayName: "Bienes Raíces",
    landingRoute: "/clasificados/bienes-raices",
    landingPageFile: "app/(site)/clasificados/bienes-raices/page.tsx",
    landingClients: ["BienesRaicesLandingHub.tsx", "BienesRaicesLandingView.tsx"],
    resultsRoute: "/clasificados/bienes-raices/results",
    resultsAliasRoute: "/clasificados/bienes-raices/resultados",
    resultsPageFile: "app/(site)/clasificados/bienes-raices/resultados/page.tsx",
    resultsClients: ["BienesRaicesResultsClient.tsx", "BienesRaicesNegocioCard.tsx"],
    listingCards: ["BienesRaicesNegocioCard.tsx", "BienesRaicesNegocioFeaturedCard.tsx"],
    publishRoute: "/clasificados/publicar/bienes-raices",
    dataSources: ["fetchBrPublishedListingsForBrowse", "brDemoListingPool merge"],
    queryParamNotes: "buildBrResultsUrl / brFilterContract keys (operationType, city, propiedad, …)",
    standardShellStatus: "partial",
    risk: "HIGH",
  },
  {
    slug: "servicios",
    displayName: "Servicios",
    landingRoute: "/clasificados/servicios",
    landingPageFile: "app/(site)/clasificados/servicios/page.tsx",
    landingClients: ["ServiciosLandingPage.tsx", "ServiciosHeroSearch.tsx"],
    resultsRoute: "/clasificados/servicios/results",
    resultsAliasRoute: "/clasificados/servicios/resultados",
    resultsPageFile: "app/(site)/clasificados/servicios/resultados/page.tsx (server page + filters)",
    resultsClients: ["ServiciosResultsPageShell.tsx", "ServiciosHorizontalResultCard.tsx"],
    listingCards: ["ServiciosHorizontalResultCard.tsx"],
    publishRoute: "/clasificados/publicar/servicios",
    dataSources: ["listServiciosPublicListingsRaw", "serviciosPublicListingsServer"],
    queryParamNotes: "ServiciosResultsFilterQuery — keyword, city, category, seller, lang",
    standardShellStatus: "partial",
    risk: "MEDIUM",
  },
  {
    slug: "restaurantes",
    displayName: "Restaurantes",
    landingRoute: "/clasificados/restaurantes",
    landingPageFile: "app/(site)/clasificados/restaurantes/page.tsx",
    landingClients: ["RestaurantesLandingPage.tsx"],
    resultsRoute: "/clasificados/restaurantes/results",
    resultsAliasRoute: "/clasificados/restaurantes/resultados",
    resultsPageFile: "app/(site)/clasificados/restaurantes/resultados/page.tsx",
    resultsClients: ["RestaurantesResultsShell.tsx", "RestaurantePublishedListingCard.tsx"],
    listingCards: ["RestaurantePublishedListingCard.tsx"],
    publishRoute: "/clasificados/restaurantes/publicar",
    dataSources: ["restaurantesResultsInventoryServer", "restaurantesDiscoveryContract"],
    queryParamNotes: "q, city, zip, cuisine, service, sort — restaurantesDiscoveryContract",
    standardShellStatus: "partial",
    risk: "MEDIUM",
  },
  {
    slug: "comunidad",
    displayName: "Comunidad y Eventos",
    landingRoute: "/clasificados/comunidad",
    landingPageFile: "app/(site)/clasificados/comunidad/page.tsx",
    landingClients: ["page.tsx (CategoryStandardLandingPage)"],
    resultsRoute: "/clasificados/comunidad/results",
    resultsAliasRoute: "/clasificados/comunidad/resultados",
    resultsPageFile: "app/(site)/clasificados/comunidad/resultados/page.tsx",
    resultsClients: ["CommunityListingsResultsClient.tsx", "CommunityDiscoveryListingCard.tsx"],
    listingCards: ["CommunityDiscoveryListingCard.tsx"],
    publishRoute: "/clasificados/publicar/comunidad",
    dataSources: ["fetchPublishedCommunityCategoryListings"],
    queryParamNotes: "lang, q, city, zip, category pills, event filters in client",
    standardShellStatus: "full",
    risk: "LOW",
  },
  {
    slug: "clases",
    displayName: "Clases",
    landingRoute: "/clasificados/clases",
    landingPageFile: "app/(site)/clasificados/clases/page.tsx",
    landingClients: ["page.tsx (CategoryStandardLandingPage)"],
    resultsRoute: "/clasificados/clases/results",
    resultsAliasRoute: "/clasificados/clases/resultados",
    resultsPageFile: "app/(site)/clasificados/clases/resultados/page.tsx",
    resultsClients: ["CommunityListingsResultsClient.tsx (category=clases)"],
    listingCards: ["CommunityDiscoveryListingCard.tsx"],
    publishRoute: "/clasificados/publicar/clases",
    dataSources: ["fetchPublishedCommunityCategoryListings"],
    queryParamNotes: "Same family as comunidad + clases taxonomy chips",
    standardShellStatus: "full",
    risk: "LOW",
  },
  {
    slug: "busco",
    displayName: "Busco / Se busca",
    landingRoute: "/clasificados/busco",
    landingPageFile: "app/(site)/clasificados/busco/page.tsx",
    landingClients: ["page.tsx (CategoryStandardLandingPage)", "BuscoLandingRecentListings.tsx"],
    resultsRoute: "/clasificados/busco/results",
    resultsAliasRoute: "/clasificados/busco/resultados",
    resultsPageFile: "app/(site)/clasificados/busco/resultados/page.tsx",
    resultsClients: ["BuscoResultsClient.tsx"],
    listingCards: ["Busco notice cards in results client"],
    publishRoute: "/publicar/busco/quick",
    dataSources: ["busco public listings fetch in client"],
    queryParamNotes: "lang, q, city, tipo, urgency — busco browse URLs",
    standardShellStatus: "full",
    risk: "LOW",
  },
  {
    slug: "mascotas-y-perdidos",
    displayName: "Mascotas y Perdidos",
    landingRoute: "/clasificados/mascotas-y-perdidos",
    landingPageFile: "app/(site)/clasificados/mascotas-y-perdidos/page.tsx",
    landingClients: ["page.tsx (CategoryStandardLandingPage)", "MascotasPerdidosLandingRecentListings.tsx"],
    resultsRoute: "/clasificados/mascotas-y-perdidos/results",
    resultsAliasRoute: "/clasificados/mascotas-y-perdidos/resultados",
    resultsPageFile: "app/(site)/clasificados/mascotas-y-perdidos/resultados/page.tsx",
    resultsClients: ["MascotasPerdidosResultsClient.tsx", "MascotasPerdidosNoticeCard.tsx"],
    listingCards: ["MascotasPerdidosNoticeCard.tsx"],
    publishRoute: "/clasificados/publicar/mascotas-y-perdidos",
    dataSources: ["mascotas public browse client fetch"],
    queryParamNotes: "lang, q, city, tipo aviso, status — mascotasPerdidosBrowseUrls",
    standardShellStatus: "full",
    risk: "LOW",
  },
  {
    slug: "viajes",
    displayName: "Viajes",
    landingRoute: "/clasificados/viajes",
    landingPageFile: "app/(site)/clasificados/viajes/page.tsx",
    landingClients: ["ViajesLandingPage.tsx", "ViajesSearchBar.tsx"],
    resultsRoute: "/clasificados/viajes/results",
    resultsAliasRoute: "/clasificados/viajes/resultados",
    resultsPageFile: "app/(site)/clasificados/viajes/resultados/page.tsx",
    resultsClients: ["ViajesResultsShell.tsx"],
    listingCards: ["Viajes business result rows in shell"],
    publishRoute: "/clasificados/publicar/viajes",
    dataSources: ["fetchViajesPublicBrowseRowsMerged", "viajesStagedListingsDbServer"],
    queryParamNotes: "buildViajesBrowseUrl state — destination, category, lang",
    standardShellStatus: "partial",
    risk: "MEDIUM",
  },
] as const;

export const CAT_STD_1A_IGLESIAS: CatStd1aPipelineEntry = {
  slug: "iglesias",
  displayName: "Iglesias",
  landingRoute: "/iglesias",
  landingPageFile: "app/(site)/iglesias/page.tsx",
  landingClients: ["IglesiasPageClient.tsx"],
  resultsRoute: "(none)",
  resultsAliasRoute: "(none)",
  resultsPageFile: "(none)",
  resultsClients: [],
  listingCards: [],
  publishRoute: "(site-section CMS — not clasificados publish)",
  dataSources: ["getSiteSectionPayload(iglesias_page)"],
  queryParamNotes: "lang via shell merge",
  standardShellStatus: "custom",
  risk: "LOW",
};
