-- RETIRED 2026-09-25.
--
-- This file formerly created a certification-only schema in the isolated "Leonix Certification"
-- Supabase project. That project has been deleted during the one-project consolidation.
--
-- Historical SQL is preserved in git history and the C9 closure documentation.
-- There is intentionally NO executable SQL in the current file.
-- DO NOT repoint or execute the old certification setup against Leonix Media.
