/**
 * URL query keys for `/clasificados/rentas/results`.
 * @see rentasBrowseContract.ts — canonical definitions and parsing.
 */
export {
  RENTAS_QUERY_AMUEBLADO,
  RENTAS_QUERY_BATHS_MIN,
  RENTAS_QUERY_BRANCH,
  RENTAS_QUERY_CITY,
  RENTAS_QUERY_DEPOSIT_MAX,
  RENTAS_QUERY_DEPOSIT_MIN,
  RENTAS_QUERY_LAT,
  RENTAS_QUERY_LEASE,
  RENTAS_QUERY_LNG,
  RENTAS_QUERY_MASCOTAS,
  RENTAS_QUERY_PAGE,
  RENTAS_QUERY_PARKING_MIN,
  RENTAS_QUERY_PRECIO,
  RENTAS_QUERY_PROPIEDAD,
  RENTAS_QUERY_Q,
  RENTAS_QUERY_RADIUS_KM,
  RENTAS_QUERY_RECS,
  RENTAS_QUERY_RENT_MAX,
  RENTAS_QUERY_RENT_MIN,
  RENTAS_QUERY_SORT,
  RENTAS_QUERY_SQFT_MAX,
  RENTAS_QUERY_SQFT_MIN,
  RENTAS_QUERY_STATE,
  RENTAS_QUERY_TIPO,
  RENTAS_QUERY_ZIP,
  RENTAS_RESULTS_PAGE_SIZE,
} from "./rentasBrowseContract";
