/**
 * TODAY-2 — Personalized DIY Concierge types. Mirrors the Gate BCO-5A/6A type conventions exactly.
 * This package never duplicates a business fact, a Health Map conclusion, or a lesson body into a
 * second permanent copy — every type here either points back at Health Map / Living Book /
 * Learning Center records (run/finding/lesson/checklist ids or durable keys) or holds a
 * deterministic action instance derived from them.
 */
import type { HealthDimensionKey } from "../healthMap/types";

export type DiyActionStatus =
  | "available"
  | "in_progress"
  | "awaiting_evidence"
  | "awaiting_owner_confirmation"
  | "completed"
  | "postponed"
  | "blocked"
  | "no_longer_applicable"
  | "cancelled";

export type DiyActionOwnerDecision =
  | "start"
  | "continue"
  | "mark_ready_for_review"
  | "confirm_completion"
  | "postpone"
  | "resume"
  | "decline"
  | "request_guidance"
  | "request_managed_service";

export type DiyEvidenceType =
  | "owner_attestation"
  | "url"
  | "text_note"
  | "checklist_confirmation"
  | "file_reference"
  | "business_fact_reference"
  | "listing_reference"
  | "staff_confirmation";

export type DiyEvidenceVisibility = "owner_and_staff" | "staff_only";

export type ApprovalRequestType =
  | "action_completion_confirmation"
  | "owner_correction_confirmation"
  | "concierge_guidance_request"
  | "managed_service_request"
  | "postponement_review"
  | "resume_decision"
  | "content_draft_approval";

export type ApprovalStatus = "pending" | "approved" | "declined" | "withdrawn" | "expired" | "superseded";

export type ServiceRequestType = "guide_me_concierge" | "let_leonix_handle_it";

export type ServiceRequestUrgency = "no_rush" | "soon" | "urgent";

export type ServiceRequestStatus = "pending" | "acknowledged" | "closed" | "cancelled";

/** Same dual-actor shape proven throughout Gate BCO-5A/6A — never a bare string. */
export type DiyConciergeActor =
  | { type: "staff"; rosterId: string; authUserId: string; email: string; role: string }
  | { type: "owner"; authUserId: string; email: string };

export type DiyAction = {
  id: string;
  businessId: string;
  actionKey: string;
  dimensionKey: HealthDimensionKey;
  sourceRunId: string | null;
  sourceFindingId: string | null;
  registryVersion: string;
  status: DiyActionStatus;
  ownerDecision: DiyActionOwnerDecision | null;
  reviewDate: string | null;
  reassessmentTrigger: string | null;
  completedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export type DiyActionEvent = {
  id: string;
  businessId: string;
  actionId: string;
  eventType: "created" | "status_changed" | "decision_recorded" | "evidence_linked" | "note_added";
  fromStatus: DiyActionStatus | null;
  toStatus: DiyActionStatus | null;
  decision: DiyActionOwnerDecision | null;
  note: string | null;
  actorType: "staff" | "owner";
  actorEmail: string;
  actorRole: string;
  createdAt: string;
};

export type DiyActionEvidence = {
  id: string;
  businessId: string;
  actionId: string;
  evidenceType: DiyEvidenceType;
  valueText: string | null;
  referenceId: string | null;
  ownerNote: string | null;
  visibility: DiyEvidenceVisibility;
  actorType: "staff" | "owner";
  actorEmail: string;
  createdAt: string;
};

export type OwnerApproval = {
  id: string;
  businessId: string;
  requestType: ApprovalRequestType;
  sourceRecordType: string;
  sourceRecordId: string;
  requestedDecision: string;
  status: ApprovalStatus;
  requestedAt: string;
  decidedAt: string | null;
  requestedByActorType: "staff" | "owner";
  requestedByEmail: string;
  decidedByActorType: "staff" | "owner" | null;
  decidedByEmail: string | null;
  ownerNote: string | null;
  staffNote: string | null;
  createdAt: string;
  updatedAt: string;
};

export type ServiceRequest = {
  id: string;
  businessId: string;
  sourceActionId: string | null;
  requestType: ServiceRequestType;
  requestedDeliverable: string;
  requestedOutcome: string | null;
  ownerNote: string | null;
  urgencyPreference: ServiceRequestUrgency;
  status: ServiceRequestStatus;
  entitlementSnapshot: Record<string, unknown>;
  requestedByEmail: string;
  acknowledgedByEmail: string | null;
  acknowledgedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

/** Deterministic, code-resident action template — never generated by AI. */
export type DiyActionTemplate = {
  actionKey: string;
  dimensionKey: HealthDimensionKey;
  /** Health Map dimension statuses / finding types that make this action applicable. */
  appliesToDimensionStatuses: readonly string[];
  conditionEs: string;
  conditionEn: string;
  whyItMattersEs: string;
  whyItMattersEn: string;
  consequenceEs: string;
  consequenceEn: string;
  isFree: boolean;
  estimatedCost: string | null;
  stepsEs: readonly string[];
  stepsEn: readonly string[];
  toolsEs: readonly string[];
  toolsEn: readonly string[];
  estimatedMinutes: number;
  requiredEvidenceTypes: readonly DiyEvidenceType[];
  ownerConfirmable: boolean;
  relatedLessonKey: string | null;
  relatedResourceKeys: readonly string[];
  reassessmentTriggerEs: string;
  reassessmentTriggerEn: string;
};

/** Fully resolved owner-facing action card — a template instantiated against live action state. */
export type DiyActionCard = {
  actionKey: string;
  businessId: string;
  dimensionKey: HealthDimensionKey;
  status: DiyActionStatus;
  ownerDecision: DiyActionOwnerDecision | null;
  reviewDate: string | null;
  sourceRunId: string | null;
  sourceFindingId: string | null;
  conditionEs: string;
  conditionEn: string;
  whyItMattersEs: string;
  whyItMattersEn: string;
  consequenceEs: string;
  consequenceEn: string;
  isFree: boolean;
  estimatedCost: string | null;
  stepsEs: readonly string[];
  stepsEn: readonly string[];
  toolsEs: readonly string[];
  toolsEn: readonly string[];
  estimatedMinutes: number;
  requiredEvidenceTypes: readonly DiyEvidenceType[];
  ownerConfirmable: boolean;
  relatedLessonKey: string | null;
  relatedResourceKeys: readonly string[];
  reassessmentTriggerEs: string;
  reassessmentTriggerEn: string;
  createdAt: string;
  updatedAt: string;
};

/** A truthful "cannot produce an action" state — never silently skipped. */
export type BlockedActionState = {
  dimensionKey: HealthDimensionKey;
  reason: "contradiction_blocked" | "insufficient_information" | "human_review_required" | "capacity_risk" | "not_evidenced";
};
