/**
 * Bienes Raíces — Shared filter option registry.
 *
 * Single source of truth for landing chips, results chips, and drawer options.
 * All three surfaces pull from this config to ensure label/value consistency.
 *
 * Visibility flags:
 * - landingFeatured: Shown on landing as intent tiles or shortcut chips
 * - resultsChip: Shown on results as fast filter chips
 * - drawerFull: Shown in drawer as full expanded menu
 *
 * Support status:
 * - supported: Data exists in listing rows and filter function handles it
 * - deferred: Data exists in application but not yet wired to filter function
 * - unavailable: Data not available in public listing results
 */

import type { Lang } from "@/app/clasificados/config/clasificadosHub";

// ─── Filter option types ───────────────────────────────────────────────────────

export type BrFilterVisibility = "landingFeatured" | "resultsChip" | "drawerFull";
export type BrFilterSupport = "supported" | "deferred" | "unavailable";

export interface BrFilterOption {
  /** Unique identifier for the option */
  id: string;
  /** Human-readable label (ES) */
  labelEs: string;
  /** Human-readable label (EN) */
  labelEn: string;
  /** URL query parameter key */
  queryKey: string;
  /** Value to set in URL when selected */
  queryValue: string;
  /** Application source field(s) */
  appSourceFields: string[];
  /** Where this option appears */
  visibility: BrFilterVisibility[];
  /** Current support status */
  support: BrFilterSupport;
  /** Section in drawer */
  drawerSection: BrDrawerSection;
  /** Optional hint/helper text */
  hintEs?: string;
  hintEn?: string;
}

export type BrDrawerSection =
  | "queBuscas"
  | "donde"
  | "presupuesto"
  | "tamano"
  | "caracteristicas"
  | "condicion"
  | "terreno"
  | "comercial"
  | "medios"
  | "quienPublica";

// ─── SECTION 1: ¿Qué buscas? ─────────────────────────────────────────────────────

const QUE_BUSCAS_OPTIONS: BrFilterOption[] = [
  {
    id: "operation_venta",
    labelEs: "Venta",
    labelEn: "Sale",
    queryKey: "operationType",
    queryValue: "venta",
    appSourceFields: ["publicationType", "tipoOperacion", "listing.operation"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "queBuscas",
  },
  {
    id: "operation_renta",
    labelEs: "Renta",
    labelEn: "Rent",
    queryKey: "operationType",
    queryValue: "renta",
    appSourceFields: ["publicationType", "tipoOperacion", "listing.operation"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "queBuscas",
  },
  {
    id: "type_residencial",
    labelEs: "Residencial",
    labelEn: "Residential",
    queryKey: "propertyType",
    queryValue: "residencial",
    appSourceFields: ["categoriaPropiedad", "publicationType"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "queBuscas",
  },
  {
    id: "type_comercial",
    labelEs: "Comercial",
    labelEn: "Commercial",
    queryKey: "propertyType",
    queryValue: "comercial",
    appSourceFields: ["categoriaPropiedad", "publicationType"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "queBuscas",
  },
  {
    id: "type_terreno",
    labelEs: "Terreno / lote",
    labelEn: "Land / lot",
    queryKey: "propertyType",
    queryValue: "terreno",
    appSourceFields: ["categoriaPropiedad", "publicationType"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "queBuscas",
  },
  {
    id: "subtype_casa",
    labelEs: "Casa",
    labelEn: "House",
    queryKey: "propertyType",
    queryValue: "casa",
    appSourceFields: ["residencial.tipoCodigo", "tipoPropiedad"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "queBuscas",
  },
  {
    id: "subtype_departamento",
    labelEs: "Departamento",
    labelEn: "Apartment",
    queryKey: "propertyType",
    queryValue: "departamento",
    appSourceFields: ["residencial.tipoCodigo", "tipoPropiedad"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "queBuscas",
  },
  {
    id: "subtype_condo",
    labelEs: "Condo",
    labelEn: "Condo",
    queryKey: "propertyType",
    queryValue: "condo",
    appSourceFields: ["residencial.tipoCodigo", "tipoPropiedad"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "queBuscas",
  },
  {
    id: "subtype_townhome",
    labelEs: "Townhome",
    labelEn: "Townhome",
    queryKey: "propertyType",
    queryValue: "townhome",
    appSourceFields: ["residencial.tipoCodigo", "tipoPropiedad"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "queBuscas",
  },
  {
    id: "subtype_oficina",
    labelEs: "Oficina",
    labelEn: "Office",
    queryKey: "propertyType",
    queryValue: "oficina",
    appSourceFields: ["comercial.tipoCodigo", "tipoPropiedad"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "queBuscas",
  },
  {
    id: "subtype_local",
    labelEs: "Local comercial",
    labelEn: "Commercial space",
    queryKey: "propertyType",
    queryValue: "local",
    appSourceFields: ["comercial.tipoCodigo", "tipoPropiedad"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "queBuscas",
  },
  {
    id: "subtype_bodega",
    labelEs: "Bodega",
    labelEn: "Warehouse",
    queryKey: "propertyType",
    queryValue: "bodega",
    appSourceFields: ["comercial.tipoCodigo", "tipoPropiedad"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "queBuscas",
  },
  {
    id: "subtype_multifamiliar",
    labelEs: "Multifamiliar",
    labelEn: "Multi-family",
    queryKey: "propertyType",
    queryValue: "multifamiliar",
    appSourceFields: ["publicationType", "tipoPropiedad"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "queBuscas",
  },
  {
    id: "subtype_proyecto_nuevo",
    labelEs: "Proyecto nuevo",
    labelEn: "New construction",
    queryKey: "propertyType",
    queryValue: "proyecto_nuevo",
    appSourceFields: ["publicationType", "tipoPropiedad"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "queBuscas",
  },
];

// ─── SECTION 2: ¿Dónde? ─────────────────────────────────────────────────────────

const DONDE_OPTIONS: BrFilterOption[] = [
  {
    id: "location_city",
    labelEs: "Ciudad o zona",
    labelEn: "City or area",
    queryKey: "city",
    queryValue: "", // Text input, not a preset value
    appSourceFields: ["ciudad", "ubicacionLinea", "colonia"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "donde",
    hintEs: "Ej: San José, Oakland, Downtown",
    hintEn: "Ex: San Jose, Oakland, Downtown",
  },
  {
    id: "location_colonia",
    labelEs: "Colonia / vecindario",
    labelEn: "Neighborhood",
    queryKey: "colonia",
    queryValue: "", // Text input
    appSourceFields: ["colonia", "gate12d.colonia"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "donde",
  },
  {
    id: "location_state",
    labelEs: "Estado",
    labelEn: "State",
    queryKey: "state",
    queryValue: "", // Select dropdown
    appSourceFields: ["estado", "gate12d.estado"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "donde",
  },
  {
    id: "location_zip",
    labelEs: "Código postal",
    labelEn: "ZIP code",
    queryKey: "zip",
    queryValue: "", // Text input
    appSourceFields: ["codigoPostal", "gate12d.codigoPostal"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "donde",
  },
  {
    id: "location_country",
    labelEs: "País",
    labelEn: "Country",
    queryKey: "country",
    queryValue: "", // Select dropdown
    appSourceFields: ["pais"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "donde",
  },
];

// ─── SECTION 3: ¿Presupuesto? ────────────────────────────────────────────────────

const PRESUPUESTO_OPTIONS: BrFilterOption[] = [
  {
    id: "price_min",
    labelEs: "Precio mínimo",
    labelEn: "Price minimum",
    queryKey: "priceMin",
    queryValue: "", // Number input
    appSourceFields: ["precio"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "presupuesto",
  },
  {
    id: "price_max",
    labelEs: "Precio máximo",
    labelEn: "Price maximum",
    queryKey: "priceMax",
    queryValue: "", // Number input
    appSourceFields: ["precio"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "presupuesto",
  },
  {
    id: "budget_sale_500k",
    labelEs: "Hasta $500k",
    labelEn: "Up to $500k",
    queryKey: "priceMax",
    queryValue: "500000",
    appSourceFields: ["precio"],
    visibility: ["landingFeatured", "resultsChip"],
    support: "supported",
    drawerSection: "presupuesto",
  },
  {
    id: "budget_sale_500k_800k",
    labelEs: "$500k–$800k",
    labelEn: "$500k–$800k",
    queryKey: "priceMin",
    queryValue: "500000", // Combined with priceMax in UI
    appSourceFields: ["precio"],
    visibility: ["landingFeatured", "resultsChip"],
    support: "supported",
    drawerSection: "presupuesto",
  },
  {
    id: "budget_sale_800k_1m",
    labelEs: "$800k–$1.2M",
    labelEn: "$800k–$1.2M",
    queryKey: "priceMin",
    queryValue: "800000",
    appSourceFields: ["precio"],
    visibility: ["landingFeatured", "resultsChip"],
    support: "supported",
    drawerSection: "presupuesto",
  },
  {
    id: "budget_sale_1m_plus",
    labelEs: "$1.2M+",
    labelEn: "$1.2M+",
    queryKey: "priceMin",
    queryValue: "1200000",
    appSourceFields: ["precio"],
    visibility: ["landingFeatured", "resultsChip"],
    support: "supported",
    drawerSection: "presupuesto",
  },
  {
    id: "budget_rent_2500",
    labelEs: "Rentas hasta $2,500",
    labelEn: "Rent up to $2,500",
    queryKey: "priceMax",
    queryValue: "2500",
    appSourceFields: ["precio"],
    visibility: ["landingFeatured", "resultsChip"],
    support: "supported",
    drawerSection: "presupuesto",
  },
  {
    id: "budget_rent_2500_4000",
    labelEs: "Rentas $2,500–$4,000",
    labelEn: "Rent $2,500–$4,000",
    queryKey: "priceMin",
    queryValue: "2500",
    appSourceFields: ["precio"],
    visibility: ["landingFeatured", "resultsChip"],
    support: "supported",
    drawerSection: "presupuesto",
  },
  {
    id: "budget_rent_4000_plus",
    labelEs: "Rentas $4,000+",
    labelEn: "Rent $4,000+",
    queryKey: "priceMin",
    queryValue: "4000",
    appSourceFields: ["precio"],
    visibility: ["landingFeatured", "resultsChip"],
    support: "supported",
    drawerSection: "presupuesto",
  },
];

// ─── SECTION 4: ¿Tamaño? ───────────────────────────────────────────────────────

const TAMANO_OPTIONS: BrFilterOption[] = [
  {
    id: "size_beds_1",
    labelEs: "1+ recámaras",
    labelEn: "1+ bedrooms",
    queryKey: "beds",
    queryValue: "1",
    appSourceFields: ["recamaras", "residencial.recamaras"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "tamano",
  },
  {
    id: "size_beds_2",
    labelEs: "2+ recámaras",
    labelEn: "2+ bedrooms",
    queryKey: "beds",
    queryValue: "2",
    appSourceFields: ["recamaras", "residencial.recamaras"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "tamano",
  },
  {
    id: "size_beds_3",
    labelEs: "3+ recámaras",
    labelEn: "3+ bedrooms",
    queryKey: "beds",
    queryValue: "3",
    appSourceFields: ["recamaras", "residencial.recamaras"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "tamano",
  },
  {
    id: "size_beds_4",
    labelEs: "4+ recámaras",
    labelEn: "4+ bedrooms",
    queryKey: "beds",
    queryValue: "4",
    appSourceFields: ["recamaras", "residencial.recamaras"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "tamano",
  },
  {
    id: "size_beds_5",
    labelEs: "5+ recámaras",
    labelEn: "5+ bedrooms",
    queryKey: "beds",
    queryValue: "5",
    appSourceFields: ["recamaras", "residencial.recamaras"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "tamano",
  },
  {
    id: "size_baths_1",
    labelEs: "1+ baños",
    labelEn: "1+ bathrooms",
    queryKey: "baths",
    queryValue: "1",
    appSourceFields: ["banos", "banosCompletos", "residencial.banos"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "tamano",
  },
  {
    id: "size_baths_2",
    labelEs: "2+ baños",
    labelEn: "2+ bathrooms",
    queryKey: "baths",
    queryValue: "2",
    appSourceFields: ["banos", "banosCompletos", "residencial.banos"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "tamano",
  },
  {
    id: "size_baths_3",
    labelEs: "3+ baños",
    labelEn: "3+ bathrooms",
    queryKey: "baths",
    queryValue: "3",
    appSourceFields: ["banos", "banosCompletos", "residencial.banos"],
    visibility: ["drawerFull"],
    support: "supported",
    drawerSection: "tamano",
  },
  {
    id: "size_half_baths_1",
    labelEs: "1+ medios baños",
    labelEn: "1+ half baths",
    queryKey: "halfBaths",
    queryValue: "1",
    appSourceFields: ["mediosBanos", "residencial.mediosBanos"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_sqft_500",
    labelEs: "500+ pies²",
    labelEn: "500+ sqft",
    queryKey: "sqftMin",
    queryValue: "500",
    appSourceFields: ["piesCuadrados", "interiorSqft", "residencial.interiorSqft", "comercial.interiorSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_sqft_1000",
    labelEs: "1,000+ pies²",
    labelEn: "1,000+ sqft",
    queryKey: "sqftMin",
    queryValue: "1000",
    appSourceFields: ["piesCuadrados", "interiorSqft", "residencial.interiorSqft", "comercial.interiorSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_sqft_1500",
    labelEs: "1,500+ pies²",
    labelEn: "1,500+ sqft",
    queryKey: "sqftMin",
    queryValue: "1500",
    appSourceFields: ["piesCuadrados", "interiorSqft", "residencial.interiorSqft", "comercial.interiorSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_sqft_2000",
    labelEs: "2,000+ pies²",
    labelEn: "2,000+ sqft",
    queryKey: "sqftMin",
    queryValue: "2000",
    appSourceFields: ["piesCuadrados", "interiorSqft", "residencial.interiorSqft", "comercial.interiorSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_sqft_3000",
    labelEs: "3,000+ pies²",
    labelEn: "3,000+ sqft",
    queryKey: "sqftMin",
    queryValue: "3000",
    appSourceFields: ["piesCuadrados", "interiorSqft", "residencial.interiorSqft", "comercial.interiorSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_sqft_5000",
    labelEs: "5,000+ pies²",
    labelEn: "5,000+ sqft",
    queryKey: "sqftMin",
    queryValue: "5000",
    appSourceFields: ["piesCuadrados", "interiorSqft", "residencial.interiorSqft", "comercial.interiorSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_lot_2500",
    labelEs: "Lote 2,500+ pies²",
    labelEn: "Lot 2,500+ sqft",
    queryKey: "lotSqftMin",
    queryValue: "2500",
    appSourceFields: ["tamanoLote", "loteSqft", "residencial.loteSqft", "terreno.loteSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_lot_5000",
    labelEs: "Lote 5,000+ pies²",
    labelEn: "Lot 5,000+ sqft",
    queryKey: "lotSqftMin",
    queryValue: "5000",
    appSourceFields: ["tamanoLote", "loteSqft", "residencial.loteSqft", "terreno.loteSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_lot_7500",
    labelEs: "Lote 7,500+ pies²",
    labelEn: "Lot 7,500+ sqft",
    queryKey: "lotSqftMin",
    queryValue: "7500",
    appSourceFields: ["tamanoLote", "loteSqft", "residencial.loteSqft", "terreno.loteSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_lot_10000",
    labelEs: "Lote 10,000+ pies²",
    labelEn: "Lot 10,000+ sqft",
    queryKey: "lotSqftMin",
    queryValue: "10000",
    appSourceFields: ["tamanoLote", "loteSqft", "residencial.loteSqft", "terreno.loteSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_lot_1_acre",
    labelEs: "Lote 1+ acre",
    labelEn: "Lot 1+ acre",
    queryKey: "lotAcresMin",
    queryValue: "1",
    appSourceFields: ["tamanoLote", "loteSqft", "residencial.loteSqft", "terreno.loteSqft"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_parking_1",
    labelEs: "1+ estacionamiento",
    labelEn: "1+ parking",
    queryKey: "parking",
    queryValue: "1",
    appSourceFields: ["estacionamientos", "estacionamiento", "residencial.estacionamiento", "comercial.estacionamiento"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_parking_2",
    labelEs: "2+ estacionamientos",
    labelEn: "2+ parking",
    queryKey: "parking",
    queryValue: "2",
    appSourceFields: ["estacionamientos", "estacionamiento", "residencial.estacionamiento", "comercial.estacionamiento"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_parking_3",
    labelEs: "3+ estacionamientos",
    labelEn: "3+ parking",
    queryKey: "parking",
    queryValue: "3",
    appSourceFields: ["estacionamientos", "estacionamiento", "residencial.estacionamiento", "comercial.estacionamiento"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_parking_4",
    labelEs: "4+ estacionamientos",
    labelEn: "4+ parking",
    queryKey: "parking",
    queryValue: "4",
    appSourceFields: ["estacionamientos", "estacionamiento", "residencial.estacionamiento", "comercial.estacionamiento"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_levels_1",
    labelEs: "1 nivel",
    labelEn: "1 story",
    queryKey: "levels",
    queryValue: "1",
    appSourceFields: ["niveles", "comercial.niveles"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_levels_2",
    labelEs: "2 niveles",
    labelEn: "2 stories",
    queryKey: "levels",
    queryValue: "2",
    appSourceFields: ["niveles", "comercial.niveles"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_levels_3",
    labelEs: "3+ niveles",
    labelEn: "3+ stories",
    queryKey: "levels",
    queryValue: "3",
    appSourceFields: ["niveles", "comercial.niveles"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_year_1950",
    labelEs: "Año 1950+",
    labelEn: "Built 1950+",
    queryKey: "yearBuiltMin",
    queryValue: "1950",
    appSourceFields: ["anioConstruccion", "residencial.ano"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_year_1980",
    labelEs: "Año 1980+",
    labelEn: "Built 1980+",
    queryKey: "yearBuiltMin",
    queryValue: "1980",
    appSourceFields: ["anioConstruccion", "residencial.ano"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_year_2000",
    labelEs: "Año 2000+",
    labelEn: "Built 2000+",
    queryKey: "yearBuiltMin",
    queryValue: "2000",
    appSourceFields: ["anioConstruccion", "residencial.ano"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_year_2010",
    labelEs: "Año 2010+",
    labelEn: "Built 2010+",
    queryKey: "yearBuiltMin",
    queryValue: "2010",
    appSourceFields: ["anioConstruccion", "residencial.ano"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
  {
    id: "size_year_2020",
    labelEs: "Año 2020+",
    labelEn: "Built 2020+",
    queryKey: "yearBuiltMin",
    queryValue: "2020",
    appSourceFields: ["anioConstruccion", "residencial.ano"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "tamano",
  },
];

// ─── SECTION 5: ¿Características? ─────────────────────────────────────────────

const CARACTERISTICAS_OPTIONS: BrFilterOption[] = [
  {
    id: "feature_pets",
    labelEs: "Mascotas permitidas",
    labelEn: "Pets allowed",
    queryKey: "pets",
    queryValue: "true",
    appSourceFields: ["petsAllowed", "Leonix:pets_allowed"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_furnished",
    labelEs: "Amueblado",
    labelEn: "Furnished",
    queryKey: "furnished",
    queryValue: "true",
    appSourceFields: ["amueblado", "Leonix:furnished"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_pool",
    labelEs: "Alberca / piscina",
    labelEn: "Pool",
    queryKey: "pool",
    queryValue: "true",
    appSourceFields: ["highlightPresets.piscina", "Leonix:pool", "residencial.highlightKeys"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_patio",
    labelEs: "Patio",
    labelEn: "Patio",
    queryKey: "patio",
    queryValue: "true",
    appSourceFields: ["highlightPresets.patio", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_balcon",
    labelEs: "Balcón",
    labelEn: "Balcony",
    queryKey: "balcony",
    queryValue: "true",
    appSourceFields: ["highlightPresets.balcon", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_vista",
    labelEs: "Vista",
    labelEn: "View",
    queryKey: "view",
    queryValue: "true",
    appSourceFields: ["highlightPresets.vista", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_gated",
    labelEs: "Comunidad cerrada",
    labelEn: "Gated community",
    queryKey: "gated",
    queryValue: "true",
    appSourceFields: ["highlightPresets.comunidadCerrada", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_home_office",
    labelEs: "Oficina en casa",
    labelEn: "Home office",
    queryKey: "homeOffice",
    queryValue: "true",
    appSourceFields: ["highlightPresets.oficinaEnCasa", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_solar",
    labelEs: "Paneles solares",
    labelEn: "Solar panels",
    queryKey: "solar",
    queryValue: "true",
    appSourceFields: ["highlightPresets.panelesSolares", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_fireplace",
    labelEs: "Chimenea",
    labelEn: "Fireplace",
    queryKey: "fireplace",
    queryValue: "true",
    appSourceFields: ["highlightPresets.chimenea", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_laundry",
    labelEs: "Lavandería",
    labelEn: "Laundry",
    queryKey: "laundry",
    queryValue: "true",
    appSourceFields: ["Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_covered_parking",
    labelEs: "Estacionamiento techado",
    labelEn: "Covered parking",
    queryKey: "coveredParking",
    queryValue: "true",
    appSourceFields: ["highlightPresets.estacionamientoTechado", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_access_control",
    labelEs: "Acceso controlado",
    labelEn: "Controlled access",
    queryKey: "accessControl",
    queryValue: "true",
    appSourceFields: ["highlightPresets.accesoControlado", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_elevator",
    labelEs: "Elevador",
    labelEn: "Elevator",
    queryKey: "elevator",
    queryValue: "true",
    appSourceFields: ["highlightPresets.elevador", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_terrace",
    labelEs: "Terraza",
    labelEn: "Terrace",
    queryKey: "terrace",
    queryValue: "true",
    appSourceFields: ["highlightPresets.terraza", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_gym",
    labelEs: "Gimnasio",
    labelEn: "Gym",
    queryKey: "gym",
    queryValue: "true",
    appSourceFields: ["highlightPresets.gimnasio", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_amenities",
    labelEs: "Amenidades del desarrollo",
    labelEn: "Development amenities",
    queryKey: "amenities",
    queryValue: "true",
    appSourceFields: ["highlightPresets.amenidadesDesarrollo", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_walk_in_closet",
    labelEs: "Walk-in closet",
    labelEn: "Walk-in closet",
    queryKey: "walkInCloset",
    queryValue: "true",
    appSourceFields: ["highlightPresets.walkInCloset", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_high_ceilings",
    labelEs: "Techos altos",
    labelEn: "High ceilings",
    queryKey: "highCeilings",
    queryValue: "true",
    appSourceFields: ["highlightPresets.techosAltos", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
  {
    id: "feature_smart_home",
    labelEs: "Smart home",
    labelEn: "Smart home",
    queryKey: "smartHome",
    queryValue: "true",
    appSourceFields: ["highlightPresets.smartHome", "Leonix:highlight_slugs"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "caracteristicas",
  },
];

// ─── SECTION 6: ¿Condición y disponibilidad? ───────────────────────────────────

const CONDICION_OPTIONS: BrFilterOption[] = [
  {
    id: "condition_excelente",
    labelEs: "Excelente",
    labelEn: "Excellent",
    queryKey: "condition",
    queryValue: "excelente",
    appSourceFields: ["condicion", "residencial.condicion", "comercial.condicion"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "condicion",
  },
  {
    id: "condition_buena",
    labelEs: "Buena",
    labelEn: "Good",
    queryKey: "condition",
    queryValue: "buena",
    appSourceFields: ["condicion", "residencial.condicion", "comercial.condicion"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "condicion",
  },
  {
    id: "condition_regular",
    labelEs: "Regular",
    labelEn: "Fair",
    queryKey: "condition",
    queryValue: "regular",
    appSourceFields: ["condicion", "residencial.condicion", "comercial.condicion"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "condicion",
  },
  {
    id: "condition_remodelar",
    labelEs: "Para remodelar",
    labelEn: "Fixer-upper",
    queryKey: "condition",
    queryValue: "necesita_reparacion",
    appSourceFields: ["condicion", "residencial.condicion", "comercial.condicion"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "condicion",
  },
  {
    id: "status_disponible",
    labelEs: "Disponible",
    labelEn: "Available",
    queryKey: "listingStatus",
    queryValue: "disponible",
    appSourceFields: ["estadoAnuncio", "listingStatus", "Leonix:br_listing_status"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "condicion",
  },
  {
    id: "status_pendiente",
    labelEs: "Pendiente",
    labelEn: "Pending",
    queryKey: "listingStatus",
    queryValue: "pendiente",
    appSourceFields: ["estadoAnuncio", "listingStatus", "Leonix:br_listing_status"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "condicion",
  },
  {
    id: "status_bajo_contrato",
    labelEs: "Bajo contrato",
    labelEn: "Under contract",
    queryKey: "listingStatus",
    queryValue: "bajo_contrato",
    appSourceFields: ["estadoAnuncio", "listingStatus", "Leonix:br_listing_status"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "condicion",
  },
  {
    id: "status_preconstruccion",
    labelEs: "Próximamente / preconstrucción",
    labelEn: "Coming soon / pre-construction",
    queryKey: "listingStatus",
    queryValue: "preconstruccion",
    appSourceFields: ["listingStatus", "publicationType"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "condicion",
  },
];

// ─── SECTION 7: ¿Terreno? ───────────────────────────────────────────────────────

const TERRENO_OPTIONS: BrFilterOption[] = [
  {
    id: "terrain_residential",
    labelEs: "Lote residencial",
    labelEn: "Residential lot",
    queryKey: "terrainType",
    queryValue: "residential",
    appSourceFields: ["terreno.tipoCodigo", "terreno.subtipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "terreno",
  },
  {
    id: "terrain_commercial",
    labelEs: "Lote comercial",
    labelEn: "Commercial lot",
    queryKey: "terrainType",
    queryValue: "commercial",
    appSourceFields: ["terreno.tipoCodigo", "terreno.subtipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "terreno",
  },
  {
    id: "terrain_agricultural",
    labelEs: "Rancho / agrícola",
    labelEn: "Ranch / agricultural",
    queryKey: "terrainType",
    queryValue: "agricultural",
    appSourceFields: ["terreno.tipoCodigo", "terreno.subtipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "terreno",
  },
  {
    id: "terrain_buildable",
    labelEs: "Listo para construir",
    labelEn: "Build-ready",
    queryKey: "buildReady",
    queryValue: "true",
    appSourceFields: ["terreno.listoConstruir"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "terreno",
  },
  {
    id: "terrain_fenced",
    labelEs: "Cercado",
    labelEn: "Fenced",
    queryKey: "fenced",
    queryValue: "true",
    appSourceFields: ["terreno.cercado"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "terreno",
  },
  {
    id: "terrain_access",
    labelEs: "Acceso",
    labelEn: "Access",
    queryKey: "terrainAccess",
    queryValue: "", // Select dropdown
    appSourceFields: ["terreno.acceso"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "terreno",
  },
  {
    id: "terrain_utilities",
    labelEs: "Servicios disponibles",
    labelEn: "Utilities available",
    queryKey: "utilities",
    queryValue: "true",
    appSourceFields: ["terreno.servicios"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "terreno",
  },
  {
    id: "terrain_topography",
    labelEs: "Topografía",
    labelEn: "Topography",
    queryKey: "topography",
    queryValue: "", // Select dropdown
    appSourceFields: ["terreno.topografia"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "terreno",
  },
];

// ─── SECTION 8: ¿Comercial / inversión? ─────────────────────────────────────────

const COMERCIAL_OPTIONS: BrFilterOption[] = [
  {
    id: "commercial_office",
    labelEs: "Oficina",
    labelEn: "Office",
    queryKey: "commercialType",
    queryValue: "office",
    appSourceFields: ["comercial.tipoCodigo", "comercial.subtipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "commercial_retail",
    labelEs: "Local",
    labelEn: "Retail",
    queryKey: "commercialType",
    queryValue: "retail",
    appSourceFields: ["comercial.tipoCodigo", "comercial.subtipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "commercial_warehouse",
    labelEs: "Bodega",
    labelEn: "Warehouse",
    queryKey: "commercialType",
    queryValue: "warehouse",
    appSourceFields: ["comercial.tipoCodigo", "comercial.subtipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "commercial_restaurant",
    labelEs: "Restaurante",
    labelEn: "Restaurant",
    queryKey: "commercialType",
    queryValue: "restaurant",
    appSourceFields: ["comercial.tipoCodigo", "comercial.subtipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "commercial_mixed",
    labelEs: "Mixto",
    labelEn: "Mixed-use",
    queryKey: "commercialType",
    queryValue: "mixed",
    appSourceFields: ["comercial.tipoCodigo", "comercial.subtipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "commercial_industrial",
    labelEs: "Industrial",
    labelEn: "Industrial",
    queryKey: "commercialType",
    queryValue: "industrial",
    appSourceFields: ["comercial.tipoCodigo", "comercial.subtipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "commercial_use",
    labelEs: "Uso",
    labelEn: "Use",
    queryKey: "commercialUse",
    queryValue: "", // Text input
    appSourceFields: ["comercial.uso"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "inv_units",
    labelEs: "Número de unidades",
    labelEn: "Number of units",
    queryKey: "invUnits",
    queryValue: "", // Number input
    appSourceFields: ["invNumUnidades"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "inv_current_rent",
    labelEs: "Renta actual",
    labelEn: "Current rent",
    queryKey: "invCurrentRent",
    queryValue: "", // Number input
    appSourceFields: ["invRentaActual"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "inv_occupancy",
    labelEs: "Ocupación",
    labelEn: "Occupancy",
    queryKey: "invOccupancy",
    queryValue: "", // Select dropdown
    appSourceFields: ["invOcupacion"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "inv_cap_rate",
    labelEs: "Cap rate",
    labelEn: "Cap rate",
    queryKey: "invCapRate",
    queryValue: "", // Number input
    appSourceFields: ["invCapRate"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "inv_estimated_income",
    labelEs: "Ingreso estimado",
    labelEn: "Estimated income",
    queryKey: "invIncome",
    queryValue: "", // Number input
    appSourceFields: ["invIngresoEstimado"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "commercial_load_access",
    labelEs: "Acceso de carga",
    labelEn: "Loading dock access",
    queryKey: "loadAccess",
    queryValue: "true",
    appSourceFields: ["comercial.accesoCarga"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
  {
    id: "commercial_zoning",
    labelEs: "Zonificación",
    labelEn: "Zoning",
    queryKey: "zoning",
    queryValue: "", // Text input
    appSourceFields: ["comercial.zonificacion", "terreno.usoZonificacion"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "comercial",
  },
];

// ─── SECTION 9: Medios ───────────────────────────────────────────────────────────

const MEDIOS_OPTIONS: BrFilterOption[] = [
  {
    id: "media_photos",
    labelEs: "Con fotos",
    labelEn: "Has photos",
    queryKey: "hasPhotos",
    queryValue: "true",
    appSourceFields: ["media.photoUrls", "media.photoDataUrls"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "medios",
  },
  {
    id: "media_video",
    labelEs: "Con video",
    labelEn: "Has video",
    queryKey: "hasVideo",
    queryValue: "true",
    appSourceFields: ["media.listingVideoSlots", "media.externalVideoUrls", "media.videoUrl"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "medios",
  },
  {
    id: "media_virtual_tour",
    labelEs: "Con tour virtual",
    labelEn: "Has virtual tour",
    queryKey: "hasVirtualTour",
    queryValue: "true",
    appSourceFields: ["media.virtualTourUrl", "gate12d.virtualTourUrl"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "medios",
  },
  {
    id: "media_floor_plan",
    labelEs: "Con plano / floor plan",
    labelEn: "Has floor plan",
    queryKey: "hasFloorPlan",
    queryValue: "true",
    appSourceFields: ["media.floorPlanUrls", "media.sitePlanUrl"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "medios",
  },
];

// ─── SECTION 10: ¿Quién publica? ─────────────────────────────────────────────────

const QUIEN_PUBLICA_OPTIONS: BrFilterOption[] = [
  {
    id: "seller_privado",
    labelEs: "Particular / Privado",
    labelEn: "Private owner",
    queryKey: "sellerType",
    queryValue: "privado",
    appSourceFields: ["sellerKind", "advertiserType"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "quienPublica",
  },
  {
    id: "seller_negocio",
    labelEs: "Negocio / Agente",
    labelEn: "Business / Agent",
    queryKey: "sellerType",
    queryValue: "negocio",
    appSourceFields: ["sellerKind", "advertiserType"],
    visibility: ["landingFeatured", "resultsChip", "drawerFull"],
    support: "supported",
    drawerSection: "quienPublica",
  },
  {
    id: "seller_equipo",
    labelEs: "Equipo",
    labelEn: "Team",
    queryKey: "advertiserType",
    queryValue: "equipo_agentes",
    appSourceFields: ["advertiserType", "identityEquipo"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "quienPublica",
  },
  {
    id: "seller_oficina",
    labelEs: "Oficina / brokerage",
    labelEn: "Office / brokerage",
    queryKey: "advertiserType",
    queryValue: "oficina_brokerage",
    appSourceFields: ["advertiserType", "identityOficina"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "quienPublica",
  },
  {
    id: "seller_constructor",
    labelEs: "Constructor / desarrollador",
    labelEn: "Builder / developer",
    queryKey: "advertiserType",
    queryValue: "constructor_desarrollador",
    appSourceFields: ["advertiserType", "identityConstructor"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "quienPublica",
  },
  {
    id: "contact_phone",
    labelEs: "Con teléfono",
    labelEn: "Has phone",
    queryKey: "hasPhone",
    queryValue: "true",
    appSourceFields: ["seller.telefono", "contactChannels"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "quienPublica",
  },
  {
    id: "contact_whatsapp",
    labelEs: "Con WhatsApp",
    labelEn: "Has WhatsApp",
    queryKey: "hasWhatsapp",
    queryValue: "true",
    appSourceFields: ["seller.whatsapp", "contactChannels"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "quienPublica",
  },
  {
    id: "contact_website",
    labelEs: "Con sitio web",
    labelEn: "Has website",
    queryKey: "hasWebsite",
    queryValue: "true",
    appSourceFields: ["identityAgente.sitioWeb", "identityEquipo.sitioWeb", "identityOficina.sitioWeb", "identityConstructor.sitioWeb"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "quienPublica",
  },
  {
    id: "trust_license",
    labelEs: "Licencia visible",
    labelEn: "License visible",
    queryKey: "showLicense",
    queryValue: "true",
    appSourceFields: ["identityAgente.licencia", "trust.mostrarLicencia"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "quienPublica",
  },
  {
    id: "trust_brokerage",
    labelEs: "Brokerage visible",
    labelEn: "Brokerage visible",
    queryKey: "showBrokerage",
    queryValue: "true",
    appSourceFields: ["identityAgente.brokerage", "trust.mostrarBrokerage"],
    visibility: ["drawerFull"],
    support: "deferred",
    drawerSection: "quienPublica",
  },
];

// ─── Combined registry ─────────────────────────────────────────────────────────

export const BR_FILTER_OPTIONS: readonly BrFilterOption[] = [
  ...QUE_BUSCAS_OPTIONS,
  ...DONDE_OPTIONS,
  ...PRESUPUESTO_OPTIONS,
  ...TAMANO_OPTIONS,
  ...CARACTERISTICAS_OPTIONS,
  ...CONDICION_OPTIONS,
  ...TERRENO_OPTIONS,
  ...COMERCIAL_OPTIONS,
  ...MEDIOS_OPTIONS,
  ...QUIEN_PUBLICA_OPTIONS,
] as const;

// ─── Helper functions ───────────────────────────────────────────────────────────

export function getBrFilterOptionById(id: string): BrFilterOption | undefined {
  return BR_FILTER_OPTIONS.find((opt) => opt.id === id);
}

export function getBrFilterOptionsBySection(section: BrDrawerSection): BrFilterOption[] {
  return BR_FILTER_OPTIONS.filter((opt) => opt.drawerSection === section);
}

export function getBrFilterOptionsByVisibility(visibility: BrFilterVisibility): BrFilterOption[] {
  return BR_FILTER_OPTIONS.filter((opt) => opt.visibility.includes(visibility));
}

export function getBrFilterOptionsBySupport(support: BrFilterSupport): BrFilterOption[] {
  return BR_FILTER_OPTIONS.filter((opt) => opt.support === support);
}

export function getBrFilterLabel(option: BrFilterOption, lang: Lang): string {
  return lang === "es" ? option.labelEs : option.labelEn;
}

export function getBrFilterHint(option: BrFilterOption, lang: Lang): string | undefined {
  return lang === "es" ? option.hintEs : option.hintEn;
}

export function getBrDrawerSectionLabel(section: BrDrawerSection, lang: Lang): string {
  const labels: Record<BrDrawerSection, { es: string; en: string }> = {
    queBuscas: { es: "¿Qué buscas?", en: "What are you looking for?" },
    donde: { es: "¿Dónde?", en: "Where?" },
    presupuesto: { es: "¿Presupuesto?", en: "Budget?" },
    tamano: { es: "¿Tamaño?", en: "Size?" },
    caracteristicas: { es: "¿Características?", en: "Features?" },
    condicion: { es: "¿Condición y disponibilidad?", en: "Condition & availability?" },
    terreno: { es: "¿Terreno?", en: "Land?" },
    comercial: { es: "¿Comercial / inversión?", en: "Commercial / investment?" },
    medios: { es: "Medios", en: "Media" },
    quienPublica: { es: "¿Quién publica?", en: "Who publishes?" },
  };
  return lang === "es" ? labels[section].es : labels[section].en;
}
