import type { ServiciosLang } from "../types/serviciosBusinessProfile";

export function getServiciosProfileLabels(lang: ServiciosLang) {
  if (lang === "en") {
    return {
      reviewsSuffix: (n: number) => `(${n} reviews)`,
      openNow: "Open now",
      closed: "Closed",
      requestQuote: "Request quote",
      whatsapp: "WhatsApp",
      callOffice: "Call office",
      call: "Call",
      email: "Email",
      message: "Message",
      viewDetails: "View details",
      attachPhoto: "Attach photo",
      send: "Send",
      about: "About us",
      services: "Our services",
      gallery: "Project gallery",
      trust: "Why choose us",
      reviews: "Customer reviews",
      serviceAreas: "Service areas",
      offerTitle: "Special offer",
      visitWebsite: "Visit website",
      featured: "Featured",
      reviewsSummary: (rating: number, count: number) => `${rating} (${count} reviews)`,
      galleryMore: "More photos",
      promoViewImage: "View image",
      promoViewPdf: "View PDF",
      videoTour: "Video",
      weeklyHours: "Weekly hours",
      physicalLocation: "Location",
      openInMaps: "Open in Maps",
      showMoreServices: "Show more services",
      showLessServices: "Show fewer",
    };
  }
  return {
    reviewsSuffix: (n: number) => `(${n} reseñas)`,
    openNow: "Abierto ahora",
    closed: "Cerrado",
    requestQuote: "Solicitar cotización",
    whatsapp: "WhatsApp",
    callOffice: "Llamar oficina",
    call: "Llamar",
    email: "Correo",
    message: "Mensaje",
    viewDetails: "Ver detalles",
    attachPhoto: "Adjuntar foto",
    send: "Enviar",
    about: "Sobre nosotros",
    services: "Nuestros servicios",
    gallery: "Galería de trabajos",
    trust: "¿Por qué elegirnos?",
    reviews: "Reseñas de clientes",
    serviceAreas: "Zonas de servicio",
    offerTitle: "Oferta especial",
    visitWebsite: "Visitar sitio web",
    featured: "Destacado",
    reviewsSummary: (rating: number, count: number) => `${rating} (${count} reseñas)`,
    galleryMore: "Más fotos",
    promoViewImage: "Ver imagen",
    promoViewPdf: "Ver PDF",
    videoTour: "Video",
    weeklyHours: "Horario de la semana",
    physicalLocation: "Ubicación",
    openInMaps: "Abrir en mapa",
    showMoreServices: "Ver más servicios",
    showLessServices: "Ver menos",
  };
}
